/**
 * Arricchimento editoriale dei rifugi principali: paragrafo descrittivo
 * aggiuntivo (desc) e storia documentata (hist), in 4 lingue.
 * Solo fatti verificabili da fonti ufficiali (CAI/SAC/FFCAM, siti dei rifugi).
 */
export const REFUGE_CONTENT = {
  'rifugio-capanna-regina-margherita': {
    desc: {
      it: 'Dormire qui significa passare la notte sul punto abitato più alto d’Europa: la capanna poggia sulla vetta della Punta Gnifetti e ospita, oltre agli alpinisti diretti ai Quattromila del Rosa, laboratori scientifici dove si studiano medicina d’alta quota, clima e fisiologia. L’accesso è riservato ad alpinisti con esperienza di ghiacciaio, in cordata dalla Capanna Gnifetti.',
      en: 'Sleeping here means spending the night at the highest inhabited point in Europe: the hut sits on the very summit of Punta Gnifetti and hosts, besides climbers bound for the Monte Rosa four-thousanders, scientific laboratories studying high-altitude medicine, climate and physiology. Access is for experienced glacier mountaineers only, roped up from the Gnifetti hut.',
      fr: 'Dormir ici, c’est passer la nuit au point habité le plus haut d’Europe : la cabane repose sur le sommet même de la Punta Gnifetti et accueille, outre les alpinistes en route vers les 4000 du Rose, des laboratoires scientifiques où l’on étudie médecine d’altitude, climat et physiologie. Accès réservé aux alpinistes aguerris, encordés depuis la cabane Gnifetti.',
      de: 'Hier zu schlafen heißt, die Nacht am höchsten bewohnten Punkt Europas zu verbringen: Die Hütte steht direkt auf dem Gipfel der Punta Gnifetti und beherbergt neben Alpinisten auf dem Weg zu den Monte-Rosa-Viertausendern auch Labore für Höhenmedizin, Klima- und Physiologieforschung. Der Zustieg ist erfahrenen Gletschergängern vorbehalten, angeseilt von der Gnifetti-Hütte.',
    },
    hist: {
      it: 'Inaugurata il 18 agosto 1893 per volontà del Club Alpino Italiano sulla vetta della Punta Gnifetti (4.554 m), fu battezzata in onore della regina Margherita di Savoia, che salì personalmente alla capanna pochi giorni dopo l’apertura pernottandovi — episodio rimasto celebre nella storia dell’alpinismo. Fin dall’origine fu concepita anche come osservatorio scientifico d’alta quota. L’edificio attuale, completamente ricostruito e inaugurato nel 1980, è gestito dal CAI di Varallo e continua la doppia vocazione alpinistica e scientifica.',
      en: 'Inaugurated on 18 August 1893 by the Italian Alpine Club on the summit of Punta Gnifetti (4,554 m), it was named in honour of Queen Margherita of Savoy, who personally climbed to the hut days after its opening and spent the night — an episode that became famous in mountaineering history. From the start it was also conceived as a high-altitude scientific observatory. The present building, completely rebuilt and inaugurated in 1980, is run by the CAI of Varallo and continues this twin alpine and scientific vocation.',
      fr: 'Inaugurée le 18 août 1893 par le Club Alpin Italien au sommet de la Punta Gnifetti (4 554 m), elle fut baptisée en l’honneur de la reine Marguerite de Savoie, qui monta elle-même à la cabane quelques jours après l’ouverture et y passa la nuit — épisode resté célèbre dans l’histoire de l’alpinisme. Dès l’origine, elle fut aussi conçue comme observatoire scientifique d’altitude. Le bâtiment actuel, entièrement reconstruit et inauguré en 1980, est géré par le CAI de Varallo et poursuit cette double vocation alpine et scientifique.',
      de: 'Am 18. August 1893 vom Italienischen Alpenverein auf dem Gipfel der Punta Gnifetti (4.554 m) eingeweiht, wurde sie zu Ehren von Königin Margherita von Savoyen benannt, die wenige Tage nach der Eröffnung selbst zur Hütte aufstieg und dort übernachtete — eine berühmte Episode der Alpingeschichte. Von Anfang an war sie auch als wissenschaftliches Höhenobservatorium gedacht. Der heutige, 1980 vollständig neu errichtete Bau wird vom CAI Varallo geführt und setzt die doppelte alpine und wissenschaftliche Berufung fort.',
    },
  },
  'rifugio-vittorio-emanuele-ii-nuovo': {
    desc: {
      it: 'È la base storica della via normale al Gran Paradiso, l’unico Quattromila interamente italiano: nelle notti d’estate il rifugio si anima alle tre del mattino di cordate in partenza. La sagoma a mezza botte in lamiera, pensata per resistere alle valanghe, è ormai un’icona della Valsavarenche; accanto sopravvive il vecchio rifugio in pietra.',
      en: 'This is the historic base for the normal route up the Gran Paradiso, the only entirely Italian four-thousander: on summer nights the hut comes alive at three in the morning with departing rope parties. Its half-barrel metal silhouette, designed to shed avalanches, has become an icon of the Valsavarenche; the old stone hut survives alongside.',
      fr: 'C’est la base historique de la voie normale du Grand-Paradis, le seul 4000 entièrement italien : les nuits d’été, le refuge s’anime à trois heures du matin au départ des cordées. Sa silhouette en demi-tonneau métallique, conçue pour résister aux avalanches, est devenue une icône de la Valsavarenche ; l’ancien refuge de pierre subsiste à côté.',
      de: 'Dies ist der historische Stützpunkt des Normalwegs auf den Gran Paradiso, den einzigen ganz italienischen Viertausender: In Sommernächten erwacht die Hütte um drei Uhr früh mit aufbrechenden Seilschaften. Die halbtonnenförmige Blechsilhouette, gebaut, um Lawinen standzuhalten, ist längst eine Ikone des Valsavarenche; daneben steht noch die alte Steinhütte.',
    },
    hist: {
      it: 'Il primo rifugio, voluto dal CAI di Torino e intitolato al re Vittorio Emanuele II — che in queste valli aveva le sue riserve di caccia — fu inaugurato nel 1884 ed è tra i più antichi rifugi italiani. L’edificio “nuovo”, la caratteristica mezza botte metallica, venne aperto nel 1961 per far fronte alla crescita dell’alpinismo sul Gran Paradiso. Resta di proprietà del CAI Torino.',
      en: 'The first hut, promoted by the CAI of Turin and named after King Vittorio Emanuele II — who kept his hunting reserves in these valleys — was inaugurated in 1884 and is among Italy’s oldest refuges. The “new” building, the distinctive metal half-barrel, opened in 1961 to cope with the growth of mountaineering on the Gran Paradiso. It remains the property of CAI Turin.',
      fr: 'Le premier refuge, voulu par le CAI de Turin et dédié au roi Victor-Emmanuel II — qui avait ses réserves de chasse dans ces vallées — fut inauguré en 1884 : c’est l’un des plus anciens refuges italiens. Le bâtiment « nouveau », le fameux demi-tonneau métallique, ouvrit en 1961 pour répondre à l’essor de l’alpinisme au Grand-Paradis. Il appartient toujours au CAI de Turin.',
      de: 'Die erste Hütte, vom CAI Turin errichtet und König Vittorio Emanuele II. gewidmet — der in diesen Tälern seine Jagdreviere hatte —, wurde 1884 eingeweiht und gehört zu den ältesten Hütten Italiens. Der „neue“ Bau, die markante Blech-Halbtonne, öffnete 1961, um dem wachsenden Bergsteigerstrom am Gran Paradiso zu begegnen. Sie gehört weiterhin dem CAI Turin.',
    },
  },
  'rifugio-federico-chabod': {
    desc: {
      it: 'Posato sui pascoli alti del vallone di Lavassey, è la partenza della via normale ovest al Gran Paradiso, che si ricongiunge a quella classica sotto la vetta: molte cordate salgono dal Chabod e scendono al Vittorio Emanuele, concatenando i due rifugi in un anello d’alta quota. Dalla terrazza, la parete nord-ovest del Gran Paradiso incombe con i suoi seracchi.',
      en: 'Set on the high pastures of the Lavassey valley, it is the start of the west normal route up the Gran Paradiso, which rejoins the classic route below the summit: many parties climb from the Chabod and descend to the Vittorio Emanuele, linking the two huts in a high-level loop. From the terrace, the north-west face of the Gran Paradiso looms with its seracs.',
      fr: 'Posé sur les hauts pâturages du vallon de Lavassey, c’est le départ de la voie normale ouest du Grand-Paradis, qui rejoint la voie classique sous le sommet : beaucoup de cordées montent du Chabod et descendent au Vittorio Emanuele, enchaînant les deux refuges en boucle d’altitude. De la terrasse, la face nord-ouest du Grand-Paradis domine avec ses séracs.',
      de: 'Auf den Hochweiden des Lavassey-Tals gelegen, ist sie der Ausgangspunkt des westlichen Normalwegs auf den Gran Paradiso, der unter dem Gipfel auf die klassische Route trifft: Viele Seilschaften steigen von der Chabod-Hütte auf und zur Vittorio-Emanuele-Hütte ab und verbinden beide zu einer Höhenrunde. Von der Terrasse drohen die Séracs der Nordwestwand des Gran Paradiso.',
    },
    hist: {
      it: 'Il rifugio, aperto negli anni Ottanta del Novecento, è dedicato a Federico Chabod (1901–1960), storico di fama europea, partigiano e primo presidente della Valle d’Aosta autonoma: una figura che unisce come poche la cultura e la montagna valdostane. La struttura è stata ampliata e ammodernata negli anni Duemila.',
      en: 'The hut, opened in the 1980s, is dedicated to Federico Chabod (1901–1960), a historian of European stature, partisan and first president of the autonomous Aosta Valley region: few figures so unite Valdostan culture and mountains. The building was enlarged and modernised in the 2000s.',
      fr: 'Le refuge, ouvert dans les années 1980, est dédié à Federico Chabod (1901-1960), historien de stature européenne, partisan et premier président de la Vallée d’Aoste autonome : peu de figures unissent autant la culture et la montagne valdôtaines. Le bâtiment a été agrandi et modernisé dans les années 2000.',
      de: 'Die in den 1980er-Jahren eröffnete Hütte ist Federico Chabod (1901–1960) gewidmet, Historiker von europäischem Rang, Partisan und erster Präsident der autonomen Region Aostatal: Kaum eine Gestalt verbindet Kultur und Berge des Aostatals so sehr. Der Bau wurde in den 2000er-Jahren erweitert und modernisiert.',
    },
  },
  'rifugio-quintino-sella-al-felik': {
    desc: {
      it: 'Arroccato sullo sperone roccioso del Felik, è il grande crocevia alpinistico fra Castore, Polluce e la traversata dei Lyskamm: all’alba le cordate si snodano sulla cresta nevosa del Naso del Lyskamm in uno spettacolo che da solo vale la salita. L’accesso escursionistico dal Colle di Bettaforca è lungo ma non difficile fino al rifugio, con tratti attrezzati finali.',
      en: 'Perched on the rocky Felik spur, this is the great mountaineering crossroads between Castor, Pollux and the Lyskamm traverse: at dawn rope parties wind up the snowy crest of the Lyskamm Nose in a spectacle worth the climb in itself. The hiking approach from the Bettaforca pass is long but not difficult, with equipped final sections.',
      fr: 'Perché sur l’éperon rocheux du Felik, c’est le grand carrefour alpin entre Castor, Pollux et la traversée des Lyskamm : à l’aube, les cordées serpentent sur la crête neigeuse du Nez du Lyskamm, spectacle qui vaut à lui seul la montée. L’accès pédestre depuis le col de Bettaforca est long mais sans grande difficulté, avec des sections équipées sur la fin.',
      de: 'Auf dem Felsporn des Felik thronend, ist sie das große alpinistische Kreuz zwischen Castor, Pollux und der Lyskamm-Überschreitung: Im Morgengrauen ziehen die Seilschaften über den Firngrat der Lyskamm-Nase — ein Schauspiel, das allein den Aufstieg lohnt. Der Wanderzustieg vom Bettaforca-Pass ist lang, aber bis zur Hütte nicht schwierig, mit versicherten Schlusspassagen.',
    },
    hist: {
      it: 'Il primo ricovero fu costruito nel 1885 dalla sezione di Biella del CAI e intitolato a Quintino Sella, statista biellese e fondatore del Club Alpino Italiano nel 1863. Ricostruito e ampliato più volte — l’ultima struttura principale risale alla fine del Novecento — resta di proprietà del CAI Biella ed è uno dei rifugi d’alta quota più frequentati del Rosa.',
      en: 'The first shelter was built in 1885 by the Biella section of the CAI and named after Quintino Sella, the Biellese statesman who founded the Italian Alpine Club in 1863. Rebuilt and enlarged several times — the latest main structure dates from the late 20th century — it remains the property of CAI Biella and is one of the busiest high huts of the Monte Rosa.',
      fr: 'Le premier abri fut construit en 1885 par la section de Biella du CAI et dédié à Quintino Sella, homme d’État biellais et fondateur du Club Alpin Italien en 1863. Reconstruit et agrandi à plusieurs reprises — la dernière structure principale date de la fin du XXe siècle — il appartient toujours au CAI de Biella et compte parmi les refuges d’altitude les plus fréquentés du Rose.',
      de: 'Die erste Schutzhütte wurde 1885 von der CAI-Sektion Biella gebaut und nach Quintino Sella benannt, dem Staatsmann aus Biella, der 1863 den Italienischen Alpenverein gründete. Mehrfach neu gebaut und erweitert — der heutige Hauptbau stammt vom Ende des 20. Jahrhunderts — gehört sie weiter dem CAI Biella und ist eine der meistbesuchten Höhenhütten des Monte Rosa.',
    },
  },
  'monte-rosa-hutte': {
    desc: {
      it: 'Il “cristallo di rocca” ai piedi del versante svizzero del Rosa è una meta in sé: l’involucro sfaccettato in alluminio brilla sopra il ghiacciaio del Gorner ed è visibile perfino dal Gornergrat. L’avvicinamento da Rotenboden attraversa il ghiacciaio su percorso attrezzato e segnalato: da affrontare solo con condizioni buone e passo sicuro.',
      en: 'The “rock crystal” at the foot of Monte Rosa’s Swiss side is a destination in itself: its faceted aluminium shell glitters above the Gorner glacier and can be seen even from the Gornergrat. The approach from Rotenboden crosses the glacier on an equipped, marked route: to be tackled only in good conditions and with a sure step.',
      fr: 'Le « cristal de roche » au pied du versant suisse du Rose est une destination en soi : son enveloppe d’aluminium à facettes scintille au-dessus du glacier du Gorner et se voit jusque du Gornergrat. L’approche depuis Rotenboden traverse le glacier sur un itinéraire équipé et balisé : à entreprendre seulement par bonnes conditions et d’un pas sûr.',
      de: 'Der „Bergkristall“ am Fuß der Schweizer Seite des Monte Rosa ist ein Ziel für sich: Die facettierte Aluminiumhülle glitzert über dem Gornergletscher und ist selbst vom Gornergrat zu sehen. Der Zustieg von Rotenboden quert den Gletscher auf gesicherter, markierter Route — nur bei guten Verhältnissen und mit sicherem Tritt.',
    },
    hist: {
      it: 'La prima capanna Bétemps fu costruita nel 1895 dal Club Alpino Svizzero. L’edificio attuale, progettato con il Politecnico federale di Zurigo e inaugurato nel 2009, è un manifesto di architettura alpina sostenibile: la “montagna di cristallo” in alluminio copre con il fotovoltaico circa il 90% del proprio fabbisogno energetico. È gestita dalla sezione Monte Rosa del SAC.',
      en: 'The first Bétemps hut was built in 1895 by the Swiss Alpine Club. The current building, designed with ETH Zurich and inaugurated in 2009, is a manifesto of sustainable alpine architecture: the aluminium “crystal mountain” covers about 90% of its energy needs with photovoltaics. It is run by the Monte Rosa section of the SAC.',
      fr: 'La première cabane Bétemps fut construite en 1895 par le Club Alpin Suisse. Le bâtiment actuel, conçu avec l’École polytechnique de Zurich et inauguré en 2009, est un manifeste d’architecture alpine durable : la « montagne de cristal » en aluminium couvre environ 90 % de ses besoins énergétiques grâce au photovoltaïque. Elle est gérée par la section Monte Rosa du CAS.',
      de: 'Die erste Bétemps-Hütte wurde 1895 vom Schweizer Alpen-Club gebaut. Der heutige Bau, mit der ETH Zürich entworfen und 2009 eingeweiht, ist ein Manifest nachhaltiger Alpinarchitektur: Der „Bergkristall“ aus Aluminium deckt rund 90 % seines Energiebedarfs mit Photovoltaik. Geführt wird er von der Sektion Monte Rosa des SAC.',
    },
  },
  'refuge-du-gouter': {
    desc: {
      it: 'Sospeso sull’Aiguille du Goûter lungo la via normale francese al Monte Bianco, è il rifugio-chiave per la vetta: si dorme qui per partire nel cuore della notte verso il Dôme du Goûter e la cresta delle Bosses. La salita dal Nid d’Aigle attraversa il famigerato Grand Couloir, esposto alla caduta sassi: passaggio da affrontare presto e senza soste. Prenotazione obbligatoria con largo anticipo.',
      en: 'Suspended on the Aiguille du Goûter along the French normal route up Mont Blanc, this is the key hut for the summit: you sleep here to set out in the middle of the night for the Dôme du Goûter and the Bosses ridge. The approach from the Nid d’Aigle crosses the notorious Grand Couloir, exposed to rockfall: a passage to take early and without stopping. Booking essential far in advance.',
      fr: 'Suspendu à l’Aiguille du Goûter sur la voie normale française du Mont-Blanc, c’est le refuge clé pour le sommet : on y dort pour partir en pleine nuit vers le Dôme du Goûter et l’arête des Bosses. La montée depuis le Nid d’Aigle traverse le fameux Grand Couloir, exposé aux chutes de pierres : passage à franchir tôt et sans s’arrêter. Réservation indispensable longtemps à l’avance.',
      de: 'An der Aiguille du Goûter über dem französischen Normalweg auf den Mont Blanc schwebend, ist dies die Schlüsselhütte für den Gipfel: Man schläft hier, um mitten in der Nacht zum Dôme du Goûter und zum Bosses-Grat aufzubrechen. Der Zustieg vom Nid d’Aigle quert das berüchtigte Grand Couloir mit Steinschlaggefahr: früh und ohne Halt passieren. Reservierung lange im Voraus zwingend.',
    },
    hist: {
      it: 'L’attuale rifugio, inaugurato nel 2013 dalla Federazione francese dei club alpini (FFCAM), ha sostituito la storica struttura del 1962: un ovoide futuristico in legno e acciaio inox progettato per resistere a venti estremi e funzionare con energia solare e fusione della neve. È fra i rifugi tecnologicamente più avanzati delle Alpi.',
      en: 'The current refuge, inaugurated in 2013 by the French federation of alpine clubs (FFCAM), replaced the historic 1962 structure: a futuristic ovoid of timber and stainless steel designed to withstand extreme winds and to run on solar power and snow-melting. It is among the most technologically advanced huts in the Alps.',
      fr: 'Le refuge actuel, inauguré en 2013 par la FFCAM, a remplacé la structure historique de 1962 : un ovoïde futuriste de bois et d’inox conçu pour résister aux vents extrêmes et fonctionner à l’énergie solaire et à la fonte de neige. C’est l’un des refuges les plus avancés technologiquement des Alpes.',
      de: 'Die heutige Hütte, 2013 vom französischen Alpenclub-Verband (FFCAM) eingeweiht, ersetzte den historischen Bau von 1962: ein futuristisches Ovoid aus Holz und Edelstahl, gebaut für extreme Winde, betrieben mit Solarenergie und Schneeschmelze. Sie zählt zu den technologisch fortschrittlichsten Hütten der Alpen.',
    },
  },
  'hospice-du-grand-saint-bernard': {
    desc: {
      it: 'Non un semplice rifugio ma un luogo dello spirito: da quasi mille anni i canonici accolgono chiunque bussi alla porta dell’ospizio, d’estate come nel lungo inverno a 2.470 metri, quando il colle è raggiungibile solo con sci o racchette. Si visitano la chiesa barocca, la cripta, il museo e il celebre allevamento dei cani San Bernardo, oggi curato dalla Fondation Barry.',
      en: 'Not merely a refuge but a place of the spirit: for nearly a thousand years the canons have welcomed whoever knocks at the hospice door, in summer as in the long winter at 2,470 metres, when the pass can be reached only on skis or snowshoes. You can visit the baroque church, the crypt, the museum and the famous St Bernard dog kennels, today run by the Barry Foundation.',
      fr: 'Plus qu’un refuge, un lieu de l’esprit : depuis près de mille ans, les chanoines accueillent quiconque frappe à la porte de l’hospice, l’été comme durant le long hiver à 2 470 mètres, quand le col n’est accessible qu’à ski ou en raquettes. On y visite l’église baroque, la crypte, le musée et le célèbre élevage des chiens saint-bernard, aujourd’hui confié à la Fondation Barry.',
      de: 'Kein bloßes Refugium, sondern ein Ort des Geistes: Seit fast tausend Jahren empfangen die Chorherren jeden, der an die Tür des Hospizes klopft — im Sommer wie im langen Winter auf 2.470 Metern, wenn der Pass nur mit Ski oder Schneeschuhen erreichbar ist. Zu besichtigen sind Barockkirche, Krypta, Museum und die berühmte Bernhardiner-Zucht, heute von der Fondation Barry betreut.',
    },
    hist: {
      it: 'Fondato attorno al 1050 da San Bernardo di Mentone per proteggere i pellegrini della via Francigena dai pericoli del valico e dai briganti, l’ospizio è abitato ininterrottamente da allora: è una delle istituzioni di accoglienza più antiche d’Europa. Dai suoi corridoi passarono pellegrini, eserciti — Napoleone nel maggio 1800 con quarantamila uomini — e generazioni di viaggiatori salvati dai canonici e dai loro cani, allevati al colle dal Seicento.',
      en: 'Founded around 1050 by St Bernard of Menthon to protect Via Francigena pilgrims from the dangers of the pass and from brigands, the hospice has been inhabited without interruption ever since: one of Europe’s oldest institutions of hospitality. Its corridors have seen pilgrims, armies — Napoleon in May 1800 with forty thousand men — and generations of travellers rescued by the canons and their dogs, bred at the pass since the 17th century.',
      fr: 'Fondé vers 1050 par saint Bernard de Menthon pour protéger les pèlerins de la via Francigena des dangers du col et des brigands, l’hospice est habité sans interruption depuis : l’une des plus anciennes institutions d’accueil d’Europe. Dans ses couloirs passèrent pèlerins, armées — Napoléon en mai 1800 avec quarante mille hommes — et des générations de voyageurs sauvés par les chanoines et leurs chiens, élevés au col depuis le XVIIe siècle.',
      de: 'Um 1050 vom heiligen Bernhard von Menthon gegründet, um die Pilger der Via Francigena vor den Gefahren des Passes und vor Räubern zu schützen, ist das Hospiz seither ununterbrochen bewohnt: eine der ältesten Herbergsinstitutionen Europas. Durch seine Flure zogen Pilger, Armeen — Napoleon im Mai 1800 mit vierzigtausend Mann — und Generationen von Reisenden, gerettet von den Chorherren und ihren seit dem 17. Jahrhundert am Pass gezüchteten Hunden.',
    },
  },
  'rifugio-vittorio-sella': {
    desc: {
      it: 'La posizione, al centro dell’anfiteatro pascolivo del Lauson, ne fa il miglior osservatorio di fauna del Parco: stambecchi e camosci pascolano ogni sera a pochi metri dalle finestre, e i sentieri verso il Col Lauson, i laghi del Lauson e l’Herbetet partono dalla porta. È tappa dell’anello del Gran Paradiso e meta classica della gita di giornata da Valnontey per la mulattiera reale.',
      en: 'Its position at the centre of the Lauson pasture amphitheatre makes it the Park’s best wildlife observatory: ibex and chamois graze every evening a few metres from the windows, and the trails to the Col Lauson, the Lauson lakes and the Herbetet start at the door. It is a stage on the Gran Paradiso loop and a classic day trip from Valnontey via the royal mule track.',
      fr: 'Sa position au centre de l’amphithéâtre pastoral du Lauson en fait le meilleur observatoire de faune du Parc : bouquetins et chamois paissent chaque soir à quelques mètres des fenêtres, et les sentiers vers le col Lauson, les lacs du Lauson et l’Herbetet partent de la porte. C’est une étape de la boucle du Grand-Paradis et la classique sortie à la journée depuis Valnontey par la muletière royale.',
      de: 'Die Lage im Zentrum des Weide-Amphitheaters von Lauson macht sie zum besten Wildbeobachtungsposten des Parks: Steinböcke und Gämsen weiden jeden Abend wenige Meter vor den Fenstern, und die Wege zum Col Lauson, zu den Lauson-Seen und zum Herbetet beginnen an der Tür. Etappe der Gran-Paradiso-Runde und klassisches Tagesziel von Valnontey über den königlichen Saumpfad.',
    },
    hist: {
      it: 'Gli edifici nascono come casotto e scuderie delle cacce reali di Vittorio Emanuele II, costruiti a metà Ottocento lungo la rete di mulattiere volute dal re. Passati al Club Alpino Italiano dopo la nascita del Parco (1922), furono trasformati in rifugio dalla sezione di Biella e intitolati a Vittorio Sella (1859–1943), il biellese che con le sue fotografie di montagna — dal Caucaso al K2 — portò le Alpi e il mondo d’alta quota nelle case di tutti.',
      en: 'The buildings began as a lodge and stables for the royal hunts of Vittorio Emanuele II, built in the mid-1800s along the king’s network of mule tracks. Passed to the Italian Alpine Club after the Park’s creation (1922), they were converted into a refuge by the Biella section and named after Vittorio Sella (1859–1943), the Biellese whose mountain photographs — from the Caucasus to K2 — brought the Alps and the high world into everyone’s homes.',
      fr: 'Les bâtiments naquirent comme pavillon et écuries des chasses royales de Victor-Emmanuel II, construits au milieu du XIXe siècle le long du réseau de muletières voulu par le roi. Passés au Club Alpin Italien après la création du Parc (1922), ils furent transformés en refuge par la section de Biella et dédiés à Vittorio Sella (1859-1943), le Biellais dont les photographies de montagne — du Caucase au K2 — firent entrer les Alpes et la haute altitude dans toutes les maisons.',
      de: 'Die Gebäude entstanden Mitte des 19. Jahrhunderts als Jagdhaus und Stallungen der königlichen Jagden Vittorio Emanueles II. entlang des königlichen Saumpfadnetzes. Nach der Gründung des Parks (1922) an den Italienischen Alpenverein übergegangen, wurden sie von der Sektion Biella zur Hütte umgebaut und Vittorio Sella (1859–1943) gewidmet, dessen Bergfotografien — vom Kaukasus bis zum K2 — die Alpen und die Welt der Höhe in alle Häuser brachten.',
    },
  },
  'rifugio-elisabetta-soldini': {
    desc: {
      it: 'Ultimo avamposto italiano del TMB prima del Col de la Seigne, il rifugio guarda dall’alto la piana del Lac Combal e il fronte morenico del ghiacciaio del Miage. La terrazza al tramonto, quando le Pyramides Calcaires si accendono, è uno dei momenti che i trekker del Tour ricordano più volentieri. Base ideale anche per esplorare la Val Veny e il lago del Miage.',
      en: 'The TMB’s last Italian outpost before the Col de la Seigne, the hut looks down on the Lac Combal plain and the moraine front of the Miage glacier. The terrace at sunset, when the Pyramides Calcaires catch fire, is one of the moments TMB trekkers remember most fondly. An ideal base, too, for exploring Val Veny and the Miage lake.',
      fr: 'Dernier avant-poste italien du TMB avant le col de la Seigne, le refuge domine la plaine du lac Combal et le front morainique du glacier du Miage. La terrasse au couchant, quand s’embrasent les Pyramides Calcaires, est l’un des moments que les trekkeurs du Tour gardent le plus volontiers en mémoire. Base idéale aussi pour explorer le Val Veny et le lac du Miage.',
      de: 'Als letzter italienischer Vorposten des TMB vor dem Col de la Seigne blickt die Hütte auf die Ebene des Lac Combal und die Moränenfront des Miage-Gletschers hinab. Die Terrasse bei Sonnenuntergang, wenn die Pyramides Calcaires Feuer fangen, gehört zu den liebsten Erinnerungen der TMB-Trekker. Auch ideale Basis für Val Veny und den Miage-See.',
    },
    hist: {
      it: 'Il rifugio sorge sugli edifici dell’alpe e della caserma della Lex Blanche, riadattati nel secondo dopoguerra: fu inaugurato nel 1949 dal CAI e intitolato a Elisabetta Soldini Montanaro per volontà della famiglia, che ne sostenne la realizzazione. Ampliato negli anni, è oggi gestito dal CAI e rappresenta una delle tappe-simbolo del versante italiano del Tour du Mont Blanc.',
      en: 'The refuge stands on the buildings of the Lex Blanche alp and barracks, adapted after WWII: it was inaugurated in 1949 by the CAI and named after Elisabetta Soldini Montanaro at the wish of her family, who supported its creation. Enlarged over the years, it is now CAI-run and one of the symbolic stages of the Italian side of the Tour du Mont Blanc.',
      fr: 'Le refuge s’élève sur les bâtiments de l’alpage et de la caserne de la Lex Blanche, réaménagés après la Seconde Guerre : il fut inauguré en 1949 par le CAI et dédié à Elisabetta Soldini Montanaro à la demande de sa famille, qui soutint sa création. Agrandi au fil des ans, il est géré par le CAI et reste l’une des étapes symboles du versant italien du Tour du Mont-Blanc.',
      de: 'Die Hütte steht auf den Gebäuden der Alp und Kaserne von Lex Blanche, nach dem Zweiten Weltkrieg umgebaut: 1949 vom CAI eingeweiht und auf Wunsch der Familie, die den Bau unterstützte, Elisabetta Soldini Montanaro gewidmet. Über die Jahre erweitert, wird sie heute vom CAI geführt und ist eine der Symbol-Etappen der italienischen Seite der Tour du Mont Blanc.',
    },
  },
  'rifugio-deffeyes': {
    desc: {
      it: 'La conca che ospita il rifugio è un piccolo mondo glaciale: laghi di scioglimento, rocce levigate e la fronte del ghiacciaio del Rutor a portata di passeggiata. Oltre alla tappa del Tour del Rutor, dal rifugio partono gli itinerari per la Testa del Rutor e il giro dei laghi; le cascate lungo la salita da La Thuile sono fra le più imponenti delle Alpi occidentali.',
      en: 'The basin holding the hut is a small glacial world: meltwater lakes, polished rock and the snout of the Rutor glacier within strolling distance. Besides the Tour du Rutor stage, routes leave the hut for the Testa del Rutor and the lakes circuit; the waterfalls on the climb from La Thuile are among the mightiest in the western Alps.',
      fr: 'La combe qui abrite le refuge est un petit monde glaciaire : lacs de fonte, roches polies et front du glacier du Rutor à portée de promenade. Outre l’étape du Tour du Rutor, du refuge partent les itinéraires de la Testa del Rutor et le tour des lacs ; les cascades de la montée depuis La Thuile comptent parmi les plus imposantes des Alpes occidentales.',
      de: 'Der Kessel der Hütte ist eine kleine Gletscherwelt: Schmelzseen, geschliffene Felsen und die Zunge des Rutor-Gletschers in Spazierweite. Neben der Etappe der Rutor-Runde starten hier die Routen zur Testa del Rutor und zur Seenrunde; die Wasserfälle des Anstiegs von La Thuile gehören zu den mächtigsten der Westalpen.',
    },
    hist: {
      it: 'Il rifugio del CAI di Aosta è dedicato ad Albert Deffeyes (1913–1953), alpinista e uomo politico valdostano fra i protagonisti della rinascita autonomista del dopoguerra, scomparso prematuramente. La struttura, più volte ampliata, è da decenni il punto d’appoggio per l’esplorazione del gruppo del Rutor e dei suoi ghiacciai.',
      en: 'The CAI Aosta hut is dedicated to Albert Deffeyes (1913–1953), a Valdostan mountaineer and politician, a protagonist of the post-war autonomist rebirth, who died young. The building, enlarged several times, has for decades been the base for exploring the Rutor group and its glaciers.',
      fr: 'Le refuge du CAI d’Aoste est dédié à Albert Deffeyes (1913-1953), alpiniste et homme politique valdôtain, protagoniste de la renaissance autonomiste d’après-guerre, disparu prématurément. Le bâtiment, plusieurs fois agrandi, est depuis des décennies le point d’appui pour explorer le massif du Rutor et ses glaciers.',
      de: 'Die Hütte des CAI Aosta ist Albert Deffeyes (1913–1953) gewidmet, Bergsteiger und Politiker des Aostatals, Mitgestalter des autonomistischen Wiederaufbruchs der Nachkriegszeit, früh verstorben. Der mehrfach erweiterte Bau ist seit Jahrzehnten der Stützpunkt zur Erkundung der Rutor-Gruppe und ihrer Gletscher.',
    },
  },
  'rifugio-bertone': {
    desc: {
      it: 'A meno di due ore da Courmayeur, è il balcone più accessibile sul versante sud del Monte Bianco e la prima tappa classica del TMB italiano. La terrazza guarda il Dente del Gigante e le Grandes Jorasses; mezz’ora sopra il rifugio, la cresta erbosa del Mont de la Saxe regala uno dei punti panoramici più celebri delle Alpi, ideale al tramonto.',
      en: 'Less than two hours from Courmayeur, this is the most accessible balcony on Mont Blanc’s southern side and the classic first stage of the Italian TMB. The terrace faces the Dent du Géant and the Grandes Jorasses; half an hour above the hut, the grassy crest of Mont de la Saxe offers one of the most celebrated viewpoints in the Alps, ideal at sunset.',
      fr: 'À moins de deux heures de Courmayeur, c’est le balcon le plus accessible du versant sud du Mont-Blanc et la première étape classique du TMB italien. La terrasse fait face à la Dent du Géant et aux Grandes Jorasses ; une demi-heure au-dessus du refuge, la crête herbeuse du Mont de la Saxe offre l’un des belvédères les plus célèbres des Alpes, idéal au couchant.',
      de: 'Weniger als zwei Stunden von Courmayeur ist dies der zugänglichste Balkon der Südseite des Mont Blanc und die klassische erste Etappe des italienischen TMB. Die Terrasse blickt auf Dent du Géant und Grandes Jorasses; eine halbe Stunde über der Hütte bietet der Grasgrat des Mont de la Saxe einen der berühmtesten Aussichtspunkte der Alpen — ideal bei Sonnenuntergang.',
    },
    hist: {
      it: 'Ricavato da un alpeggio del Mont de la Saxe, il rifugio è dedicato a Giorgio Bertone, guida alpina di Courmayeur fra le più forti della sua generazione, protagonista di grandi salite sul Bianco negli anni Sessanta e Settanta e scomparso in montagna nel 1977. La gestione familiare ne ha fatto una delle tappe più amate del Tour du Mont Blanc.',
      en: 'Converted from an alp on the Mont de la Saxe, the hut is dedicated to Giorgio Bertone, a Courmayeur mountain guide among the strongest of his generation, protagonist of great climbs on Mont Blanc in the 1960s and 70s, who died in the mountains in 1977. Family management has made it one of the best-loved stops on the Tour du Mont Blanc.',
      fr: 'Aménagé dans un alpage du Mont de la Saxe, le refuge est dédié à Giorgio Bertone, guide de Courmayeur parmi les plus forts de sa génération, auteur de grandes ascensions au Mont-Blanc dans les années 1960-70, disparu en montagne en 1977. Sa gestion familiale en a fait l’une des étapes les plus aimées du Tour du Mont-Blanc.',
      de: 'Aus einer Alp am Mont de la Saxe entstanden, ist die Hütte Giorgio Bertone gewidmet, einem Bergführer aus Courmayeur, der zu den stärksten seiner Generation zählte, großen Touren am Mont Blanc der 1960er und 70er prägte und 1977 in den Bergen blieb. Die familiäre Führung machte sie zu einer der beliebtesten Stationen der Tour du Mont Blanc.',
    },
  },
  'rifugio-elena': {
    desc: {
      it: 'La posizione, di fronte alla lingua del ghiacciaio di Pré de Bar, è fra le più scenografiche dell’intera Val Ferret: dal terrazzo si segue con lo sguardo la salita al Gran Col Ferret da una parte e il Mont Dolent — la montagna dei tre confini — dall’altra. È l’ultimo posto tappa italiano del TMB in senso antiorario e base per la gita facile da Arnouva.',
      en: 'Its position facing the tongue of the Pré de Bar glacier is among the most scenic in the whole Val Ferret: from the terrace your eye follows the climb to the Grand Col Ferret on one side and Mont Dolent — the mountain of three borders — on the other. It is the TMB’s last Italian overnight stop anticlockwise and the base for the easy walk up from Arnouva.',
      fr: 'Sa position face à la langue du glacier de Pré de Bar est parmi les plus spectaculaires de tout le Val Ferret : de la terrasse, le regard suit la montée au Grand col Ferret d’un côté et le Mont Dolent — la montagne des trois frontières — de l’autre. C’est la dernière halte italienne du TMB dans le sens antihoraire et la base de la balade facile depuis Arnouva.',
      de: 'Die Lage gegenüber der Zunge des Pré-de-Bar-Gletschers gehört zu den szenischsten des ganzen Val Ferret: Von der Terrasse folgt der Blick dem Anstieg zum Grand Col Ferret auf der einen und dem Mont Dolent — dem Berg der drei Grenzen — auf der anderen Seite. Letzte italienische Übernachtungsstation des TMB gegen den Uhrzeigersinn und Basis für den leichten Spaziergang von Arnouva.',
    },
    hist: {
      it: 'Un ricovero a Pré de Bar esisteva già a inizio Novecento, ma valanghe e guerre ne segnarono più volte la storia: l’edificio attuale, moderno e ampio, è stato ricostruito e inaugurato negli anni Novanta poco sopra il sito storico. Il nome ricorda la tradizione sabauda della famiglia reale, legata a queste montagne di confine.',
      en: 'A shelter at Pré de Bar existed by the early 1900s, but avalanches and wars repeatedly marked its history: the present building, modern and spacious, was rebuilt and inaugurated in the 1990s just above the historic site. The name recalls the Savoy tradition of the royal family, tied to these border mountains.',
      fr: 'Un abri existait à Pré de Bar dès le début du XXe siècle, mais avalanches et guerres en marquèrent plusieurs fois l’histoire : le bâtiment actuel, moderne et spacieux, fut reconstruit et inauguré dans les années 1990 juste au-dessus du site historique. Le nom rappelle la tradition savoyarde de la famille royale, liée à ces montagnes frontalières.',
      de: 'Eine Unterkunft am Pré de Bar gab es schon Anfang des 20. Jahrhunderts, doch Lawinen und Kriege prägten ihre Geschichte mehrfach: Der heutige, moderne und großzügige Bau wurde in den 1990er-Jahren knapp über dem historischen Standort neu errichtet. Der Name erinnert an die savoyische Tradition des Königshauses, das diesen Grenzbergen verbunden war.',
    },
  },
  'rifugio-frassati': {
    desc: {
      it: 'Moderno e accogliente, presidia l’alto vallone del Gran San Bernardo sul percorso dell’Alta Via 1: è l’appoggio per il Col Malatrà, il passaggio chiave che guarda il massiccio del Monte Bianco, e per le cime di confine della comba di Merdeux. D’estate il rifugio è animato da una vivace attività culturale ispirata alla figura del suo dedicatario.',
      en: 'Modern and welcoming, it guards the upper Great St Bernard valley on the Alta Via 1: the support point for the Col Malatrà, the key passage facing the Mont Blanc massif, and for the border summits of the Merdeux combe. In summer the hut hosts lively cultural activities inspired by the figure it is named after.',
      fr: 'Moderne et accueillant, il garde le haut vallon du Grand-Saint-Bernard sur la Haute Route n° 1 : point d’appui pour le col Malatrà, passage clé face au massif du Mont-Blanc, et pour les sommets frontaliers de la combe de Merdeux. L’été, le refuge vit d’une animation culturelle inspirée de la figure de son dédicataire.',
      de: 'Modern und einladend bewacht sie das obere Tal des Grossen Sankt Bernhard am Höhenweg 1: Stützpunkt für den Col Malatrà, die Schlüsselpassage mit Blick auf das Mont-Blanc-Massiv, und für die Grenzgipfel der Merdeux-Mulde. Im Sommer belebt ein kulturelles Programm die Hütte, inspiriert von ihrem Namensgeber.',
    },
    hist: {
      it: 'Il rifugio è dedicato a Pier Giorgio Frassati (1901–1925), il giovane torinese appassionato di montagna proclamato beato nel 1990, simbolo di un alpinismo vissuto come amicizia e fede: sua la frase “verso l’alto” che accompagna il rifugio. Costruito dalle sezioni giovanili e dal CAI, è gestito con spirito di accoglienza che ne riflette l’intitolazione.',
      en: 'The hut is dedicated to Pier Giorgio Frassati (1901–1925), the young Turinese mountain lover beatified in 1990, a symbol of mountaineering lived as friendship and faith: his phrase “verso l’alto” — towards the heights — accompanies the hut. Built with the CAI and its youth sections, it is run with a spirit of welcome reflecting its name.',
      fr: 'Le refuge est dédié à Pier Giorgio Frassati (1901-1925), le jeune Turinois passionné de montagne béatifié en 1990, symbole d’un alpinisme vécu comme amitié et foi : sa devise « verso l’alto » — vers le haut — accompagne le refuge. Construit avec le CAI et ses sections jeunes, il est tenu dans un esprit d’accueil fidèle à son nom.',
      de: 'Die Hütte ist Pier Giorgio Frassati (1901–1925) gewidmet, dem jungen Turiner Bergfreund, 1990 seliggesprochen, Symbol eines als Freundschaft und Glaube gelebten Alpinismus: Sein Wort „verso l’alto“ — empor — begleitet die Hütte. Mit dem CAI und seinen Jugendsektionen erbaut, wird sie in einem Geist der Gastfreundschaft geführt, der dem Namen entspricht.',
    },
  },
  'rifugio-prarayer': {
    desc: {
      it: 'Si raggiunge solo a piedi, con la passeggiata pianeggiante lungo il lago di Place Moulin: mezz’ora di camminata sopra acque turchesi che è già parte dell’esperienza. La conca di Prarayer, chiusa dalla Dent d’Hérens e dalle Grandes Murailles, è il cuore escursionistico dell’alta Valpelline: di qui passano l’Alta Via 1, il Tour del Cervino e le salite ai bivacchi e ai colli di confine.',
      en: 'It can be reached only on foot, by the level walk along the Place Moulin reservoir: half an hour above turquoise water that is already part of the experience. The Prarayer basin, closed by the Dent d’Hérens and the Grandes Murailles, is the hiking heart of the upper Valpelline: through here pass the Alta Via 1, the Tour of the Matterhorn and the routes to the border bivouacs and cols.',
      fr: 'On n’y accède qu’à pied, par la promenade plate le long du lac de Place Moulin : une demi-heure au-dessus d’eaux turquoise qui fait déjà partie de l’expérience. Le bassin de Prarayer, fermé par la Dent d’Hérens et les Grandes Murailles, est le cœur pédestre de la haute Valpelline : ici passent la Haute Route n° 1, le Tour du Cervin et les montées vers les bivouacs et cols frontaliers.',
      de: 'Erreichbar nur zu Fuß, über den ebenen Weg am Place-Moulin-Stausee entlang: eine halbe Stunde über türkisfarbenem Wasser, die schon Teil des Erlebnisses ist. Der Kessel von Prarayer, abgeschlossen von Dent d’Hérens und Grandes Murailles, ist das Wanderherz der oberen Valpelline: Hier verlaufen Höhenweg 1, Matterhorn-Tour und die Anstiege zu den Grenzbiwaks und -pässen.',
    },
    hist: {
      it: 'Prarayer era l’ultimo insediamento dell’alta Valpelline sulla storica via del Col Collon verso il Vallese: le sue case ospitavano viandanti e contrabbandieri ben prima che, con la costruzione della diga di Place Moulin negli anni Sessanta, la conca diventasse raggiungibile solo a piedi. Gli edifici dell’antico villaggio sono stati trasformati nell’attuale rifugio, che ne conserva le mura in pietra.',
      en: 'Prarayer was the last settlement of the upper Valpelline on the historic Col Collon route to Valais: its houses sheltered wayfarers and smugglers long before the construction of the Place Moulin dam in the 1960s left the basin reachable only on foot. The buildings of the old village were converted into today’s refuge, which preserves their stone walls.',
      fr: 'Prarayer était le dernier hameau de la haute Valpelline sur l’historique voie du col Collon vers le Valais : ses maisons abritaient voyageurs et contrebandiers bien avant que la construction du barrage de Place Moulin, dans les années 1960, ne rende le bassin accessible qu’à pied. Les bâtiments de l’ancien village ont été transformés en l’actuel refuge, qui en conserve les murs de pierre.',
      de: 'Prarayer war die letzte Siedlung der oberen Valpelline an der historischen Route über den Col Collon ins Wallis: Ihre Häuser beherbergten Reisende und Schmuggler, lange bevor der Bau der Place-Moulin-Staumauer in den 1960er-Jahren den Talkessel nur noch zu Fuß erreichbar machte. Die Gebäude des alten Dorfes wurden zur heutigen Hütte umgebaut, die ihre Steinmauern bewahrt.',
    },
  },
  'rifugio-duca-degli-abruzzi': {
    desc: {
      it: 'All’Oriondé il Cervino non è più un fondale ma una presenza: la piramide della Gran Becca incombe verticale sopra il rifugio, e in un’ora e mezza si sale alla Croce Carrel, ai piedi della cresta del Leone. È la meta ideale per chi vuole respirare l’alta montagna del Cervino senza essere alpinista, con tramonti che restano impressi.',
      en: 'At the Oriondé the Matterhorn is no longer a backdrop but a presence: the pyramid of the Gran Becca looms vertical above the hut, and in an hour and a half you can climb to the Carrel Cross at the foot of the Lion ridge. The ideal destination for breathing the Matterhorn’s high mountain world without being a climber, with unforgettable sunsets.',
      fr: 'À l’Oriondé, le Cervin n’est plus un décor mais une présence : la pyramide de la Gran Becca surplombe le refuge à la verticale, et en une heure et demie on monte à la Croix Carrel, au pied de l’arête du Lion. Destination idéale pour respirer la haute montagne du Cervin sans être alpiniste, avec des couchers de soleil inoubliables.',
      de: 'Am Oriondé ist das Matterhorn keine Kulisse mehr, sondern Gegenwart: Die Pyramide der Gran Becca ragt senkrecht über der Hütte auf, und in anderthalb Stunden steigt man zum Carrel-Kreuz am Fuß des Löwengrats. Das ideale Ziel, um die Hochgebirgswelt des Matterhorns zu atmen, ohne Alpinist zu sein — mit unvergesslichen Sonnenuntergängen.',
    },
    hist: {
      it: 'Il rifugio porta il nome di Luigi Amedeo di Savoia, Duca degli Abruzzi (1873–1933), il grande alpinista ed esploratore che dal Breuil partì giovanissimo per le sue prime salite al Cervino prima delle spedizioni al Polo, in Alaska e al K2. La struttura, ai piedi della via italiana alla Gran Becca, è storicamente legata alle guide del Cervino, che vi accompagnano gli aspiranti alla Capanna Carrel.',
      en: 'The refuge bears the name of Luigi Amedeo of Savoy, Duke of the Abruzzi (1873–1933), the great climber and explorer who as a very young man set out from the Breuil for his first Matterhorn climbs before his expeditions to the Pole, Alaska and K2. Standing at the foot of the Italian route up the Gran Becca, it is historically tied to the Matterhorn guides, who accompany aspirants from here to the Carrel hut.',
      fr: 'Le refuge porte le nom de Louis-Amédée de Savoie, duc des Abruzzes (1873-1933), grand alpiniste et explorateur qui, tout jeune, partit du Breuil pour ses premières ascensions du Cervin avant ses expéditions au Pôle, en Alaska et au K2. Au pied de la voie italienne de la Gran Becca, il est historiquement lié aux guides du Cervin, qui y accompagnent les aspirants vers la cabane Carrel.',
      de: 'Die Hütte trägt den Namen von Luigi Amedeo von Savoyen, Herzog der Abruzzen (1873–1933), dem großen Bergsteiger und Forscher, der als junger Mann vom Breuil zu seinen ersten Matterhorn-Besteigungen aufbrach, bevor er zum Pol, nach Alaska und zum K2 zog. Am Fuß des italienischen Wegs auf die Gran Becca ist sie historisch mit den Matterhorn-Führern verbunden, die Aspiranten von hier zur Carrel-Hütte begleiten.',
    },
  },
  'rifugio-mario-bezzi': {
    desc: {
      it: 'In fondo alla Valgrisenche, dove la valle si fa stretta e selvaggia, il Bezzi è la porta dei ghiacciai di Gliairetta e dell’Ormelune: meta in sé per la bella mulattiera lungo la Dora, ma anche tappa dell’Alta Via 2 e base per scialpinismo di primavera. La cucina casalinga è rinomata fra i frequentatori della valle.',
      en: 'At the head of the Valgrisenche, where the valley turns narrow and wild, the Bezzi is the gateway to the Gliairetta and Ormelune glaciers: a destination in itself for the fine mule track along the Dora, but also an Alta Via 2 stage and a spring ski-touring base. Its home cooking is renowned among the valley’s regulars.',
      fr: 'Au fond de la Valgrisenche, là où la vallée devient étroite et sauvage, le Bezzi est la porte des glaciers de Gliairetta et de l’Ormelune : but en soi pour la belle muletière le long de la Doire, mais aussi étape de la Haute Route n° 2 et base de ski de randonnée au printemps. Sa cuisine maison est réputée parmi les habitués de la vallée.',
      de: 'Am Talschluss des Valgrisenche, wo das Tal eng und wild wird, ist die Bezzi-Hütte das Tor zu den Gletschern von Gliairetta und Ormelune: ein Ziel für sich dank des schönen Saumpfads entlang der Dora, zugleich Etappe des Höhenwegs 2 und Frühjahrs-Skitourenbasis. Die Hausmannskost ist unter den Stammgästen des Tals berühmt.',
    },
    hist: {
      it: 'Il rifugio, sorto fra le due guerre e più volte ampliato, è intitolato a Mario Bezzi, alpinista milanese legato a queste montagne. La sua posizione all’alpe Vaudet ne ha fatto per generazioni il punto d’appoggio naturale per le traversate verso la Val di Rhêmes e per le cime di confine con la Tarentaise.',
      en: 'The hut, built between the wars and enlarged several times, is named after Mario Bezzi, a Milanese mountaineer devoted to these mountains. Its position at the Vaudet alp has made it for generations the natural support point for crossings to the Rhêmes valley and for the border summits with the Tarentaise.',
      fr: 'Le refuge, né entre les deux guerres et plusieurs fois agrandi, est dédié à Mario Bezzi, alpiniste milanais attaché à ces montagnes. Sa position à l’alpage de Vaudet en a fait, pour des générations, le point d’appui naturel des traversées vers le val de Rhêmes et des sommets frontaliers de la Tarentaise.',
      de: 'Die zwischen den Kriegen erbaute und mehrfach erweiterte Hütte ist Mario Bezzi gewidmet, einem Mailänder Bergsteiger, der diesen Bergen verbunden war. Ihre Lage an der Alp Vaudet machte sie über Generationen zum natürlichen Stützpunkt für Übergänge ins Rhêmes-Tal und zu den Grenzgipfeln der Tarentaise.',
    },
  },
  'rifugio-gian-federico-benevolo': {
    desc: {
      it: 'L’alta Val di Rhêmes che circonda il rifugio è dominata dalla parete calcarea della Granta Parey, la montagna-simbolo della valle: i sentieri verso i laghi Goletta, il ghiacciaio di Lavassey e i colli di confine con la Francia partono tutti da qui. Tappa amata anche dagli scialpinisti in primavera.',
      en: 'The upper Rhêmes valley around the hut is dominated by the limestone wall of the Granta Parey, the valley’s symbol mountain: the trails to the Goletta lakes, the Lavassey glacier and the border cols with France all start here. A favourite stop for ski tourers in spring as well.',
      fr: 'Le haut val de Rhêmes qui entoure le refuge est dominé par la paroi calcaire de la Granta Parey, montagne symbole de la vallée : les sentiers vers les lacs de la Goletta, le glacier de Lavassey et les cols frontaliers avec la France partent tous d’ici. Étape aimée aussi des skieurs-alpinistes au printemps.',
      de: 'Das obere Rhêmes-Tal um die Hütte wird von der Kalkwand der Granta Parey beherrscht, dem Symbolberg des Tals: Die Wege zu den Goletta-Seen, zum Lavassey-Gletscher und zu den Grenzpässen nach Frankreich beginnen alle hier. Im Frühjahr auch bei Skitourengehern beliebt.',
    },
    hist: {
      it: 'Il rifugio ricorda Gian Federico Benevolo, giovane alpinista cui la struttura fu dedicata dalla famiglia. Nato come piccolo ricovero e progressivamente ampliato fino all’aspetto attuale, è da decenni il presidio escursionistico e alpinistico dell’alta Val di Rhêmes, dentro i confini del Parco e della sua area protetta.',
      en: 'The hut remembers Gian Federico Benevolo, a young mountaineer to whom it was dedicated by his family. Born as a small shelter and progressively enlarged to its present form, it has for decades been the hiking and climbing outpost of the upper Rhêmes valley, within the Park’s protected area.',
      fr: 'Le refuge rappelle Gian Federico Benevolo, jeune alpiniste auquel la famille dédia la structure. Né comme petit abri puis progressivement agrandi jusqu’à son aspect actuel, il est depuis des décennies le poste pédestre et alpin du haut val de Rhêmes, dans l’aire protégée du Parc.',
      de: 'Die Hütte erinnert an Gian Federico Benevolo, einen jungen Bergsteiger, dem die Familie den Bau widmete. Als kleine Schutzhütte entstanden und schrittweise zur heutigen Gestalt erweitert, ist sie seit Jahrzehnten der Wander- und Bergstützpunkt des oberen Rhêmes-Tals im Schutzgebiet des Parks.',
    },
  },
  'rifugio-coda': {
    desc: {
      it: 'In bilico sullo spartiacque fra Valle d’Aosta e Biellese, il Coda guarda da una parte la pianura padana — nelle giornate limpide si vedono le risaie e, lontano, gli Appennini — e dall’altra il Monte Rosa. È tappa dell’Alta Via 1 e meta storica delle sezioni biellesi; il tramonto sulla pianura, con il mare di nebbie sotto, è il suo marchio di fabbrica.',
      en: 'Balanced on the watershed between the Aosta Valley and the Biella hills, the Coda looks one way over the Po plain — on clear days you can see the rice paddies and, far off, the Apennines — and the other way at Monte Rosa. An Alta Via 1 stage and a historic destination of the Biella CAI; sunset over the plain, with a sea of mists below, is its trademark.',
      fr: 'En équilibre sur la ligne de partage entre Vallée d’Aoste et Biellais, le Coda regarde d’un côté la plaine du Pô — par temps clair, on voit les rizières et, au loin, les Apennins — et de l’autre le Mont Rose. Étape de la Haute Route n° 1 et but historique des sections biellaises ; le coucher de soleil sur la plaine, mer de brumes en contrebas, est sa signature.',
      de: 'Auf der Wasserscheide zwischen Aostatal und Biella balancierend, blickt die Coda-Hütte auf der einen Seite über die Poebene — an klaren Tagen sieht man Reisfelder und fern den Apennin — und auf der anderen zum Monte Rosa. Etappe des Höhenwegs 1 und historisches Ziel der Bieller Sektionen; der Sonnenuntergang über der Ebene mit dem Nebelmeer darunter ist ihr Markenzeichen.',
    },
    hist: {
      it: 'Il rifugio della sezione CAI di Biella è dedicato ai fratelli Delfo e Agostino Coda, figure dell’alpinismo biellese di inizio Novecento. Inaugurato negli anni Venti sul crinale del Mont Mars e più volte rinnovato, da un secolo è il punto d’incontro fra gli escursionisti valdostani e quelli piemontesi.',
      en: 'The CAI Biella hut is dedicated to the brothers Delfo and Agostino Coda, figures of early-20th-century Biellese mountaineering. Opened in the 1920s on the Mont Mars crest and renewed several times, for a century it has been the meeting point of Valdostan and Piedmontese hikers.',
      fr: 'Le refuge de la section CAI de Biella est dédié aux frères Delfo et Agostino Coda, figures de l’alpinisme biellais du début du XXe siècle. Inauguré dans les années 1920 sur la crête du Mont Mars et plusieurs fois rénové, il est depuis un siècle le point de rencontre des randonneurs valdôtains et piémontais.',
      de: 'Die Hütte der CAI-Sektion Biella ist den Brüdern Delfo und Agostino Coda gewidmet, Gestalten des Bieller Alpinismus des frühen 20. Jahrhunderts. In den 1920er-Jahren auf dem Grat des Mont Mars eröffnet und mehrfach erneuert, ist sie seit einem Jahrhundert der Treffpunkt der Wanderer aus Aostatal und Piemont.',
    },
  },
  'bivacco-giusto-gervasutti-al-freboudze': {
    desc: {
      it: 'Il tubo futuristico incastonato sulla morena del Freboudze è diventato un’icona fotografica delle Alpi: un modulo hi-tech con vetrata panoramica che inquadra le Grandes Jorasses come uno schermo. L’accesso è ripido e per escursionisti esperti; il bivacco, sempre aperto, è base per le vie sul versante orientale delle Jorasses.',
      en: 'The futuristic tube set on the Freboudze moraine has become a photographic icon of the Alps: a hi-tech module whose panoramic window frames the Grandes Jorasses like a screen. The approach is steep, for experienced hikers; the bivouac, always open, serves the routes on the east side of the Jorasses.',
      fr: 'Le tube futuriste posé sur la moraine du Freboudze est devenu une icône photographique des Alpes : un module high-tech dont la baie panoramique cadre les Grandes Jorasses comme un écran. L’accès est raide, pour randonneurs aguerris ; le bivouac, toujours ouvert, dessert les voies du versant est des Jorasses.',
      de: 'Die futuristische Röhre auf der Freboudze-Moräne ist zur Foto-Ikone der Alpen geworden: ein Hightech-Modul, dessen Panoramafenster die Grandes Jorasses wie ein Bildschirm rahmt. Der Zustieg ist steil, für erfahrene Berggänger; das stets offene Biwak dient den Routen der Ostseite der Jorasses.',
    },
    hist: {
      it: 'Il modulo attuale, installato nel 2011 su progetto LEAPfactory, ha sostituito il vecchio bivacco in legno e lamiera dedicato a Giusto Gervasutti (1909–1946), il “Fortissimo” dell’alpinismo italiano fra le due guerre, caduto sul Monte Bianco. La sua forma a tubo, costruita per resistere alle valanghe e trasportata in elicottero, ha fatto scuola nell’architettura dei bivacchi alpini.',
      en: 'The current module, installed in 2011 to a LEAPfactory design, replaced the old wood-and-metal bivouac dedicated to Giusto Gervasutti (1909–1946), the “Fortissimo” of interwar Italian climbing, who died on Mont Blanc. Its tube form, built to withstand avalanches and flown in by helicopter, set a precedent in alpine bivouac architecture.',
      fr: 'Le module actuel, installé en 2011 sur un projet LEAPfactory, a remplacé l’ancien bivouac de bois et tôle dédié à Giusto Gervasutti (1909-1946), le « Fortissimo » de l’alpinisme italien de l’entre-deux-guerres, disparu au Mont-Blanc. Sa forme de tube, conçue pour résister aux avalanches et héliportée, a fait école dans l’architecture des bivouacs alpins.',
      de: 'Das heutige Modul, 2011 nach einem Entwurf von LEAPfactory installiert, ersetzte das alte Holz-Blech-Biwak, das Giusto Gervasutti (1909–1946) gewidmet war, dem „Fortissimo“ des italienischen Alpinismus der Zwischenkriegszeit, der am Mont Blanc fiel. Die Röhrenform, lawinensicher gebaut und per Helikopter eingeflogen, wurde stilbildend für die Architektur alpiner Biwaks.',
    },
  },
  'rifugio-champillon': {
    desc: {
      it: 'Poco sotto il Col Champillon, sul tracciato del Tour des Combins, il rifugio domina la conca di By e il solco della Valpelline: la terrazza guarda dritto il Grand Combin. È meta apprezzata anche per gite in giornata da Ollomont e per osservare l’avifauna alpina al tramonto, quando il vallone si svuota.',
      en: 'Just below the Col Champillon, on the Tour des Combins route, the hut overlooks the By basin and the trench of the Valpelline: the terrace looks straight at the Grand Combin. It is also a popular day-trip from Ollomont and a fine spot for alpine birdlife at dusk, when the valley empties.',
      fr: 'Juste sous le col Champillon, sur le tracé du Tour des Combins, le refuge domine la combe de By et le sillon de la Valpelline : la terrasse regarde droit le Grand Combin. But apprécié aussi à la journée depuis Ollomont, et bel observatoire de l’avifaune alpine au crépuscule, quand le vallon se vide.',
      de: 'Knapp unter dem Col Champillon, an der Route der Tour des Combins, überblickt die Hütte den By-Kessel und die Furche der Valpelline: Die Terrasse schaut direkt auf den Grand Combin. Beliebt auch als Tagesziel von Ollomont und schöner Beobachtungspunkt für die alpine Vogelwelt in der Dämmerung, wenn sich das Tal leert.',
    },
    hist: {
      it: 'Il rifugio è intitolato ad Adolphe Letey, guida e figura della comunità di Ollomont, e nasce dal recupero degli alpeggi di Champillon: una storia recente che si innesta su secoli di alpicoltura nella conca di By, dove un tempo si lavorava anche il rame delle miniere di Ollomont.',
      en: 'The hut is named after Adolphe Letey, a guide and figure of the Ollomont community, and was created by restoring the Champillon alps: a recent story grafted onto centuries of alpine farming in the By basin, where the copper of the Ollomont mines was once worked too.',
      fr: 'Le refuge porte le nom d’Adolphe Letey, guide et figure de la communauté d’Ollomont, et naît de la réhabilitation des alpages de Champillon : une histoire récente greffée sur des siècles d’alpiculture dans la combe de By, où l’on travaillait jadis aussi le cuivre des mines d’Ollomont.',
      de: 'Die Hütte trägt den Namen von Adolphe Letey, Bergführer und Persönlichkeit der Gemeinde Ollomont, und entstand aus der Sanierung der Almen von Champillon: eine junge Geschichte auf Jahrhunderten von Almwirtschaft im By-Kessel, wo einst auch das Kupfer der Gruben von Ollomont verarbeitet wurde.',
    },
  },
  'rifugio-nacamuli-al-col-collon': {
    desc: {
      it: 'Aggrappato ai pendii sopra la comba d’Oren, è l’ultimo presidio italiano sulla storica via del Col Collon verso Arolla: base per la traversata glaciale del Tour del Cervino, per le cime della Becca d’Oren e per gli scialpinisti della primavera. La vista sul lago di Place Moulin, mille metri più in basso, è di quelle che non si dimenticano.',
      en: 'Clinging to the slopes above the Oren combe, it is the last Italian outpost on the historic Col Collon route to Arolla: the base for the Tour of the Matterhorn’s glacier crossing, for the Becca d’Oren summits and for spring ski tourers. The view of the Place Moulin reservoir, a thousand metres below, is the unforgettable kind.',
      fr: 'Accroché aux pentes au-dessus de la combe d’Oren, c’est le dernier poste italien sur l’historique voie du col Collon vers Arolla : base de la traversée glaciaire du Tour du Cervin, des sommets de la Becca d’Oren et des skieurs-alpinistes du printemps. La vue sur le lac de Place Moulin, mille mètres plus bas, est de celles qu’on n’oublie pas.',
      de: 'An die Hänge über der Oren-Mulde geklammert, ist sie der letzte italienische Stützpunkt an der historischen Route über den Col Collon nach Arolla: Basis für die Gletscherquerung der Matterhorn-Tour, die Gipfel der Becca d’Oren und Frühjahrs-Skitourengeher. Der Blick auf den Place-Moulin-See, tausend Meter tiefer, gehört zu den unvergesslichen.',
    },
    hist: {
      it: 'Il rifugio, costruito negli anni Trenta e rinnovato nel tempo, ricorda Aldo Nacamuli, alpinista cui fu dedicato dalla famiglia. Sorge lungo uno dei valichi più antichi delle Alpi occidentali: dal Col Collon passavano già nel Medioevo uomini e merci fra la Valpelline e il Vallese, e i ritrovamenti sul ghiacciaio ne testimoniano la lunghissima frequentazione.',
      en: 'The hut, built in the 1930s and renewed over time, remembers Aldo Nacamuli, a mountaineer to whom it was dedicated by his family. It stands on one of the oldest crossings of the western Alps: people and goods were already moving over the Col Collon between the Valpelline and Valais in the Middle Ages, and finds on the glacier testify to its very long use.',
      fr: 'Le refuge, construit dans les années 1930 et rénové au fil du temps, rappelle Aldo Nacamuli, alpiniste auquel sa famille le dédia. Il s’élève sur l’un des plus anciens passages des Alpes occidentales : dès le Moyen Âge, hommes et marchandises franchissaient le col Collon entre Valpelline et Valais, comme en témoignent les objets retrouvés sur le glacier.',
      de: 'Die in den 1930er-Jahren erbaute und mehrfach erneuerte Hütte erinnert an Aldo Nacamuli, einen Bergsteiger, dem die Familie sie widmete. Sie steht an einem der ältesten Übergänge der Westalpen: Schon im Mittelalter zogen Menschen und Waren über den Col Collon zwischen Valpelline und Wallis, wie Funde auf dem Gletscher belegen.',
    },
  },
  'rifugio-crete-seche': {
    desc: {
      it: 'Il vallone di Crête Sèche, severo e poco frequentato, è uno degli angoli più autentici della Valpelline: dal rifugio si sale alla Fenêtre de Durand sul Tour des Combins, ai laghi glaciali del vallone e alle cime di confine con il Vallese. Ambiente ideale per chi cerca silenzio e fauna.',
      en: 'The stern, little-visited Crête Sèche valley is one of the most authentic corners of the Valpelline: from the hut you climb to the Fenêtre de Durand on the Tour des Combins, to the valley’s glacial lakes and to the border summits with Valais. Ideal country for those seeking silence and wildlife.',
      fr: 'Le vallon de Crête Sèche, sévère et peu fréquenté, est l’un des coins les plus authentiques de la Valpelline : du refuge, on monte à la Fenêtre de Durand sur le Tour des Combins, aux lacs glaciaires du vallon et aux sommets frontaliers du Valais. Cadre idéal pour qui cherche silence et faune.',
      de: 'Das strenge, wenig besuchte Crête-Sèche-Tal ist einer der authentischsten Winkel der Valpelline: Von der Hütte steigt man zur Fenêtre de Durand an der Tour des Combins, zu den Gletscherseen des Tals und zu den Grenzgipfeln des Wallis. Ideal für alle, die Stille und Wildtiere suchen.',
    },
    hist: {
      it: 'Nato come ricovero per alpinisti diretti alle cime della testata — Mont Gelé, Becca Crétaz e le punte di confine — il rifugio è stato rinnovato e ampliato nel tempo, mantenendo il carattere di presidio semplice e familiare del vallone. La Fenêtre de Durand, poco sopra, è da secoli passaggio di pastori e contrabbandieri fra Valpelline e Val de Bagnes.',
      en: 'Born as a shelter for climbers bound for the head summits — Mont Gelé, Becca Crétaz and the border points — the hut has been renewed and enlarged over time while keeping its character as the valley’s simple, family-run outpost. The Fenêtre de Durand just above has for centuries been the shepherds’ and smugglers’ passage between the Valpelline and the Val de Bagnes.',
      fr: 'Né comme abri pour les alpinistes des sommets du fond — Mont Gelé, Becca Crétaz et pointes frontalières — le refuge a été rénové et agrandi au fil du temps, en gardant son caractère de poste simple et familial du vallon. La Fenêtre de Durand, juste au-dessus, est depuis des siècles le passage des bergers et contrebandiers entre Valpelline et val de Bagnes.',
      de: 'Als Unterkunft für Bergsteiger zu den Gipfeln des Talschlusses — Mont Gelé, Becca Crétaz und den Grenzspitzen — entstanden, wurde die Hütte über die Zeit erneuert und erweitert und bewahrt ihren Charakter als einfacher, familiärer Stützpunkt des Tals. Die Fenêtre de Durand gleich darüber ist seit Jahrhunderten der Übergang von Hirten und Schmugglern zwischen Valpelline und Val de Bagnes.',
    },
  },
  'rifugio-guide-d-ayas': {
    desc: {
      it: 'A 3.388 metri sul plateau roccioso di Lambronecca, sopra il ghiacciaio di Verra, è il rifugio d’alta quota del versante di Ayas: base per Castore, Polluce, la traversata dei Lyskamm e il Breithorn. La salita escursionistica termina al Mezzalama; il tratto finale corre su pietraie e nevai ed è consigliato ad alpinisti o escursionisti molto esperti.',
      en: 'At 3,388 metres on the rocky Lambronecca shoulder above the Verra glacier, this is the high hut of the Ayas side: the base for Castor, Pollux, the Lyskamm traverse and the Breithorn. The hiking approach ends at the Mezzalama; the final stretch runs over scree and snowfields and is best left to mountaineers or very experienced hikers.',
      fr: 'À 3 388 mètres sur l’épaule rocheuse de Lambronecca, au-dessus du glacier de Verra, c’est le refuge d’altitude du versant d’Ayas : base pour Castor, Pollux, la traversée des Lyskamm et le Breithorn. L’approche pédestre s’arrête au Mezzalama ; la section finale court sur pierriers et névés, réservée aux alpinistes ou randonneurs très aguerris.',
      de: 'Auf 3.388 Metern auf der Felsschulter von Lambronecca über dem Verra-Gletscher ist dies die Höhenhütte der Ayas-Seite: Basis für Castor, Pollux, die Lyskamm-Überschreitung und das Breithorn. Der Wanderzustieg endet an der Mezzalama-Hütte; das letzte Stück verläuft über Schutt und Firn und gehört Alpinisten oder sehr erfahrenen Geherinnen.',
    },
    hist: {
      it: 'Costruito dalla Società Guide di Ayas e inaugurato alla fine del Novecento per affiancare lo storico rifugio Mezzalama (1936), porta in quota la tradizione delle guide della valle, attive da generazioni sui Quattromila del Rosa. La gestione diretta delle guide ne fa anche una scuola d’alta montagna a cielo aperto.',
      en: 'Built by the Ayas Guides Society and inaugurated at the end of the 20th century to complement the historic Mezzalama hut (1936), it carries the valley guides’ tradition to altitude — guides active for generations on the Monte Rosa four-thousanders. Run directly by the guides, it doubles as an open-air high-mountain school.',
      fr: 'Construit par la Société des Guides d’Ayas et inauguré à la fin du XXe siècle pour épauler l’historique refuge Mezzalama (1936), il porte en altitude la tradition des guides de la vallée, actives depuis des générations sur les 4000 du Rose. Géré directement par les guides, c’est aussi une école de haute montagne à ciel ouvert.',
      de: 'Von der Bergführergesellschaft von Ayas erbaut und Ende des 20. Jahrhunderts eröffnet, um die historische Mezzalama-Hütte (1936) zu ergänzen, trägt sie die Tradition der Talführer in die Höhe — seit Generationen auf den Viertausendern des Monte Rosa aktiv. Direkt von den Führern geführt, ist sie zugleich eine Hochgebirgsschule unter freiem Himmel.',
    },
  },
  'refuge-des-grands-mulets': {
    desc: {
      it: 'Arroccato su un isolotto roccioso che emerge dai ghiacciai dei Bossons e di Taconnaz, è uno dei luoghi più scenografici del massiccio: di notte le luci di Chamonix brillano duemila metri più in basso. Oggi è frequentato soprattutto in primavera dagli scialpinisti diretti al Monte Bianco per l’itinerario storico.',
      en: 'Perched on a rocky islet rising from the Bossons and Taconnaz glaciers, it is one of the most scenic spots in the massif: at night the lights of Chamonix glitter two thousand metres below. Today it is busiest in spring with ski mountaineers bound for Mont Blanc by the historic route.',
      fr: 'Perché sur un îlot rocheux émergeant des glaciers des Bossons et de Taconnaz, c’est l’un des sites les plus spectaculaires du massif : la nuit, les lumières de Chamonix scintillent deux mille mètres plus bas. Il vit surtout au printemps, avec les skieurs-alpinistes en route vers le Mont-Blanc par l’itinéraire historique.',
      de: 'Auf einer Felsinsel zwischen den Gletschern von Bossons und Taconnaz gelegen, ist sie einer der spektakulärsten Orte des Massivs: Nachts glitzern die Lichter von Chamonix zweitausend Meter tiefer. Heute ist sie vor allem im Frühjahr belebt, wenn Skibergsteiger auf der historischen Route zum Mont Blanc ziehen.',
    },
    hist: {
      it: 'I Grands Mulets sono legati alla nascita stessa dell’alpinismo: su questa via passò la prima ascensione del Monte Bianco (1786) e qui fu costruito nel 1853 il primo ricovero, fra i più antichi delle Alpi. Il rifugio attuale della FFCAM, su pilastri sopra la roccia, continua una storia di accoglienza lunga oltre un secolo e mezzo.',
      en: 'The Grands Mulets are tied to the very birth of mountaineering: the first ascent of Mont Blanc (1786) passed this way, and the first shelter — among the oldest in the Alps — was built here in 1853. The current FFCAM hut, on pillars above the rock, continues a story of hospitality more than a century and a half long.',
      fr: 'Les Grands Mulets sont liés à la naissance même de l’alpinisme : la première ascension du Mont-Blanc (1786) passa par ici, et le premier abri — parmi les plus anciens des Alpes — y fut construit en 1853. Le refuge actuel de la FFCAM, sur pilotis au-dessus du rocher, poursuit une histoire d’accueil de plus d’un siècle et demi.',
      de: 'Die Grands Mulets sind mit der Geburt des Alpinismus selbst verbunden: Über diesen Weg führte die Erstbesteigung des Mont Blanc (1786), und 1853 entstand hier eine der ältesten Schutzhütten der Alpen. Die heutige FFCAM-Hütte auf Stelzen über dem Fels setzt eine über anderthalb Jahrhunderte lange Geschichte der Gastfreundschaft fort.',
    },
  },
};
