/* Lotto descrizioni 2 — 4 sentieri con geografia coerente, prosa editoriale
 * 4 lingue fondata solo sui dati reali del Catasto. Nessun dato inventato. */
const fs = require('fs');
const path = require('path');
const FILE = path.join(__dirname, '..', 'src', 'data', 'trails-skeleton.json');
const FITNESS = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };
function caiDuration(km, gain, loss) {
  const h = km / 4 + Math.max(gain, 0) / 400 + Math.max(loss, 0) / 600;
  return Math.max(0.5, Math.round(h * 2) / 2);
}

const DESC = {
  '12-s9': {
    it: "Da Estoul (1884 m), conca di alpeggi e piste sopra Brusson, questo itinerario escursionistico (E) sale verso i laghi d'alta quota della Val d'Ayas: il Lago Battaglia, il valico del Col de Bringuez e infine il Lago Lungo a 2660 m. Con 7,3 km e circa 800 metri di dislivello, è una giornata di cammino tra praterie, pascoli e specchi d'acqua di origine glaciale, in un anfiteatro aperto verso le cime che separano l'Ayas dalla Valle del Lys. Periodo ideale l'estate, quando i laghi riflettono il cielo e la fioritura colora i prati; portate scorta d'acqua e protezione dal sole, perché gran parte del percorso è in ambiente aperto.",
    en: "From Estoul (1884 m), a basin of alpine pastures and ski runs above Brusson, this hiking route (E) climbs towards the high-altitude lakes of the Ayas valley: Lago Battaglia, the Col de Bringuez pass and finally Lago Lungo at 2660 m. With 7.3 km and about 800 metres of ascent, it is a day's walk among meadows, pastures and glacier-born sheets of water, in an amphitheatre opening towards the peaks that divide the Ayas from the Lys valley. Summer is the ideal season, when the lakes mirror the sky and the blooms colour the meadows; carry water and sun protection, as much of the route is in open terrain.",
    fr: "Depuis Estoul (1884 m), cuvette d'alpages et de pistes au-dessus de Brusson, cet itinéraire de randonnée (E) monte vers les lacs d'altitude du val d'Ayas : le Lac Battaglia, le Col de Bringuez et enfin le Lago Lungo à 2660 m. Avec 7,3 km et environ 800 mètres de dénivelé, c'est une journée de marche entre prairies, pâturages et plans d'eau d'origine glaciaire, dans un amphithéâtre ouvert vers les cimes séparant l'Ayas de la vallée du Lys. La saison idéale est l'été, quand les lacs reflètent le ciel ; emportez de l'eau et une protection solaire, car le parcours est en grande partie à découvert.",
    de: "Von Estoul (1884 m), einem Becken aus Almen und Skipisten oberhalb von Brusson, steigt diese Wanderung (E) zu den Hochgebirgsseen des Ayas-Tals auf: zum Lago Battaglia, zum Pass Col de Bringuez und schließlich zum Lago Lungo auf 2660 m. Mit 7,3 km und rund 800 Höhenmetern ist es eine Tageswanderung zwischen Matten, Weiden und glazialen Gewässern, in einem zu den Gipfeln zwischen Ayas und Lystal offenen Amphitheater. Ideal ist der Sommer, wenn die Seen den Himmel spiegeln; nimm Wasser und Sonnenschutz mit, da der Weg großteils im offenen Gelände verläuft.",
  },
  '19-s10': {
    it: "La Becca di Nona (3144 m) è la montagna che domina direttamente Aosta: la si vede dalla città e, dalla sua vetta, si abbraccia tutta la conca del capoluogo con la corona di quattromila sullo sfondo. Questo itinerario (E) parte dalla conca di Comboé (2118 m), antico alpeggio incassato tra le pendici, e risale oltre mille metri di dislivello fino in cima, attraverso praterie d'altitudine, pietraie e gli ultimi tratti più ripidi che precedono la sommità. È una salita esigente nonostante la classificazione escursionistica: richiede allenamento, passo sicuro e una giornata stabile. La ricompensa è uno dei panorami più completi sulla Valle d'Aosta, dal Monte Bianco al Cervino al Gran Paradiso.",
    en: "Becca di Nona (3144 m) is the mountain that directly overlooks Aosta: it is seen from the city, and from its summit the whole basin of the regional capital opens up, with the crown of four-thousanders behind. This route (E) starts from the Comboé basin (2118 m), an old alpine pasture set among the slopes, and climbs more than a thousand metres to the top, through high meadows, scree and the steeper final sections before the summit. It is a demanding ascent despite the hiking grade: it calls for fitness, a sure foot and a settled day. The reward is one of the most complete panoramas over the Aosta Valley, from Mont Blanc to the Matterhorn and Gran Paradiso.",
    fr: "La Becca di Nona (3144 m) est la montagne qui domine directement Aoste : on la voit depuis la ville et, de son sommet, on embrasse toute la cuvette du chef-lieu, avec la couronne de quatre mille en toile de fond. Cet itinéraire (E) part de la cuvette de Comboé (2118 m), ancien alpage encaissé dans les pentes, et grimpe plus de mille mètres jusqu'au sommet, à travers prairies d'altitude, pierriers et les derniers passages plus raides. C'est une montée exigeante malgré la cotation randonnée : elle demande de l'entraînement, un pied sûr et une journée stable. La récompense est l'un des panoramas les plus complets sur la Vallée d'Aoste, du Mont-Blanc au Cervin et au Grand-Paradis.",
    de: "Die Becca di Nona (3144 m) ist der Berg, der direkt über Aosta aufragt: Man sieht ihn von der Stadt, und von seinem Gipfel öffnet sich das ganze Becken des Hauptorts mit dem Kranz der Viertausender im Hintergrund. Diese Route (E) startet im Becken von Comboé (2118 m), einer alten, in die Hänge eingebetteten Alm, und steigt über tausend Höhenmeter zum Gipfel auf, durch Hochmatten, Geröll und die steileren Schlusspassagen. Es ist ein anspruchsvoller Aufstieg trotz der Wandereinstufung: Er erfordert Training, Trittsicherheit und einen stabilen Tag. Der Lohn ist eines der vollständigsten Panoramen über das Aostatal, vom Mont Blanc bis zum Matterhorn und Gran Paradiso.",
  },
  '66-s1': {
    it: "Da Oveillan (886 m), nei pressi del fondovalle della Valgrisenche, questo itinerario (E) compie una lunga risalita di quasi 1400 metri di dislivello fino all'alpe di Tsa de Metz (2267 m). La Valgrisenche è una delle valli laterali più selvagge e meno frequentate della Valle d'Aosta, chiusa in alto dai ghiacciai del Rutor e della Grande Sassière: salire da quasi mille metri di quota fino agli alpeggi significa attraversare l'intera fascia boschiva, dai castagni e latifoglie del basso versante alle conifere e infine ai pascoli aperti. È un percorso impegnativo per il dislivello, adatto a chi cerca quiete e un contatto autentico con l'ambiente d'alpe. Periodo consigliato l'estate.",
    en: "From Oveillan (886 m), near the valley floor of the Valgrisenche, this route (E) makes a long climb of nearly 1400 metres to the Tsa de Metz alp (2267 m). The Valgrisenche is one of the wildest and least frequented side-valleys of the Aosta Valley, closed at its head by the glaciers of the Rutor and the Grande Sassière: climbing from barely a thousand metres up to the alpine pastures means crossing the whole forest belt, from the chestnuts and broadleaves of the lower slope to the conifers and finally the open pastures. It is a demanding route for its height gain, suited to those seeking quiet and genuine contact with the alpine-pasture environment. Summer is the recommended season.",
    fr: "Depuis Oveillan (886 m), près du fond de la Valgrisenche, cet itinéraire (E) effectue une longue montée de près de 1400 mètres jusqu'à l'alpage de Tsa de Metz (2267 m). La Valgrisenche est l'une des vallées latérales les plus sauvages et les moins fréquentées de la Vallée d'Aoste, fermée en amont par les glaciers du Rutor et de la Grande Sassière : monter d'à peine mille mètres jusqu'aux alpages, c'est traverser toute la ceinture forestière, des châtaigniers et feuillus du bas versant aux conifères puis aux pâturages ouverts. C'est un parcours exigeant par son dénivelé, pour qui cherche la quiétude et un contact authentique avec le milieu d'alpage. Saison conseillée l'été.",
    de: "Von Oveillan (886 m), nahe dem Talboden des Valgrisenche, vollzieht diese Route (E) einen langen Anstieg von fast 1400 Höhenmetern zur Alm Tsa de Metz (2267 m). Das Valgrisenche ist eines der wildesten und am wenigsten besuchten Seitentäler des Aostatals, am Talschluss von den Gletschern des Rutor und der Grande Sassière abgeschlossen: von knapp tausend Metern bis zu den Almen aufzusteigen heißt, den gesamten Waldgürtel zu durchqueren, von Kastanien und Laubbäumen des unteren Hangs bis zu Nadelwäldern und schließlich offenen Weiden. Eine wegen der Höhenmeter anspruchsvolle Route für alle, die Stille und echten Kontakt mit der Almlandschaft suchen. Empfohlene Jahreszeit: Sommer.",
  },
  '45-s13': {
    it: "Da Praz (1761 m), nel comune di Ollomont in Valpelline, il sentiero (E) sale alla Becca d'Aver (2469 m), cima panoramica affacciata su una delle valli più tranquille e autentiche della regione. Con 4,4 km e circa 800 metri di dislivello, la salita attraversa pascoli e praterie d'alpeggio fino alla sommità, da cui lo sguardo spazia sui contrafforti del Grand Combin e sulle montagne di confine verso la Svizzera. La Valpelline, percorsa storicamente dai valichi verso il Vallese, conserva un carattere rurale e silenzioso: la Becca d'Aver ne è un belvedere ideale, raggiungibile in mezza giornata da escursionisti con un minimo di allenamento. Periodo migliore l'estate e l'inizio autunno.",
    en: "From Praz (1761 m), in the municipality of Ollomont in the Valpelline, the path (E) climbs to Becca d'Aver (2469 m), a panoramic summit overlooking one of the quietest and most authentic valleys in the region. With 4.4 km and about 800 metres of ascent, the climb crosses pastures and alpine meadows to the top, from which the view ranges over the buttresses of the Grand Combin and the border mountains towards Switzerland. The Valpelline, historically crossed by passes towards the Valais, keeps a rural and silent character: Becca d'Aver is an ideal viewpoint over it, reachable in half a day by hikers with a minimum of fitness. The best season is summer and early autumn.",
    fr: "Depuis Praz (1761 m), dans la commune d'Ollomont en Valpelline, le sentier (E) monte à la Becca d'Aver (2469 m), sommet panoramique dominant l'une des vallées les plus tranquilles et authentiques de la région. Avec 4,4 km et environ 800 mètres de dénivelé, la montée traverse pâturages et prairies d'alpage jusqu'au sommet, d'où le regard parcourt les contreforts du Grand-Combin et les montagnes frontalières vers la Suisse. La Valpelline, historiquement parcourue par les cols vers le Valais, garde un caractère rural et silencieux : la Becca d'Aver en est un belvédère idéal, accessible en une demi-journée à des randonneurs un minimum entraînés. La meilleure saison est l'été et le début de l'automne.",
    de: "Von Praz (1761 m), in der Gemeinde Ollomont im Valpelline, steigt der Weg (E) zur Becca d'Aver (2469 m) auf, einem Aussichtsgipfel über einem der ruhigsten und ursprünglichsten Täler der Region. Mit 4,4 km und rund 800 Höhenmetern quert der Anstieg Weiden und Almmatten bis zum Gipfel, von dem der Blick über die Ausläufer des Grand Combin und die Grenzberge zur Schweiz schweift. Das Valpelline, historisch von den Pässen zum Wallis durchzogen, bewahrt einen ländlichen, stillen Charakter: Die Becca d'Aver ist ein idealer Aussichtspunkt darüber, in einem halben Tag von einigermaßen trainierten Wanderern erreichbar. Beste Jahreszeit: Sommer und Frühherbst.",
  },
};

const json = JSON.parse(fs.readFileSync(FILE, 'utf8'));
const arr = Array.isArray(json) ? json : json.trails;
let done = 0;
for (const [slug, d] of Object.entries(DESC)) {
  const t = arr.find((x) => x.slug === slug);
  if (!t) { console.log('MISS', slug); continue; }
  t.description_it = d.it; t.description_en = d.en;
  t.description_fr = d.fr; t.description_de = d.de;
  t.name_en = t.name_en || t.name_it;
  t.name_fr = t.name_fr || t.name_it;
  t.name_de = t.name_de || t.name_it;
  if (t.duration_hours == null)
    t.duration_hours = caiDuration(t.distance_km || 0, t.elevation_gain_m || 0, t.elevation_loss_m || 0);
  if (t.fitness_level == null) t.fitness_level = FITNESS[t.difficulty] ?? 2;
  if (t.mobile_coverage == null) t.mobile_coverage = 'partial';
  t.enriched = true;
  console.log(slug, 'OK', [d.it, d.en, d.fr, d.de].map((s) => s.length).join('/'));
  done++;
}
fs.writeFileSync(FILE, JSON.stringify(json, null, 2) + '\n');
console.log('TOTALE:', done);
