/* Lotto descrizioni 3 — 4 sentieri, prosa editoriale 4 lingue su dati
 * verificabili (comune, toponimi, quote, dislivello, difficoltà). No invenzioni. */
const fs = require('fs');
const path = require('path');
const FILE = path.join(__dirname, '..', 'src', 'data', 'trails-skeleton.json');
const FITNESS = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };
const cai = (km, g, l) => Math.max(0.5, Math.round((km / 4 + Math.max(g, 0) / 400 + Math.max(l, 0) / 600) * 2) / 2);

const DESC = {
  '17-s4': {
    it: "Da Covarey (1211 m), sui monti di Charvensod che fanno da balcone alla conca di Aosta, questo itinerario escursionistico (E) sale al Col de la Croix (2286 m) con poco più di mille metri di dislivello in circa 8 chilometri. Il sentiero abbandona presto i boschi di conifere del versante per aprirsi sui pascoli d'alta quota fino al valico, uno dei passaggi che mettono in comunicazione i valloni meridionali della valle centrale. Dal colle lo sguardo spazia sulla città di Aosta e, verso nord, sulla catena di confine con i suoi quattromila. È una salita continua, da affrontare in estate con buona scorta d'acqua: gran parte del tracciato è in ambiente aperto e assolato.",
    en: "From Covarey (1211 m), on the mountains of Charvensod that form a balcony over the Aosta basin, this hiking route (E) climbs to the Col de la Croix (2286 m) with just over a thousand metres of ascent in about 8 kilometres. The path soon leaves the conifer woods of the slope to open onto high pastures up to the pass, one of the crossings linking the southern side-valleys of the central valley. From the col the view ranges over the city of Aosta and, to the north, the border chain with its four-thousanders. It is a continuous climb, best done in summer with plenty of water: much of the route is in open, sunny terrain.",
    fr: "Depuis Covarey (1211 m), sur les montagnes de Charvensod qui forment un balcon sur la cuvette d'Aoste, cet itinéraire de randonnée (E) monte au Col de la Croix (2286 m) avec un peu plus de mille mètres de dénivelé en environ 8 kilomètres. Le sentier quitte vite les bois de conifères pour s'ouvrir sur les pâturages d'altitude jusqu'au col, l'un des passages reliant les vallons méridionaux de la vallée centrale. Du col, le regard parcourt la ville d'Aoste et, vers le nord, la chaîne frontalière et ses quatre mille. C'est une montée continue, à faire en été avec une bonne réserve d'eau : le parcours est en grande partie à découvert.",
    de: "Von Covarey (1211 m), auf den Bergen von Charvensod, die einen Balkon über dem Becken von Aosta bilden, steigt diese Wanderung (E) mit gut tausend Höhenmetern auf rund 8 Kilometern zum Col de la Croix (2286 m) auf. Der Weg verlässt bald die Nadelwälder und öffnet sich auf Hochweiden bis zum Pass, einem der Übergänge zwischen den südlichen Seitentälern des zentralen Tals. Vom Pass schweift der Blick über die Stadt Aosta und nach Norden zur Grenzkette mit ihren Viertausendern. Ein durchgehender Anstieg, im Sommer mit ausreichend Wasser anzugehen: Der Weg verläuft großteils im offenen, sonnigen Gelände.",
  },
  '18-s46': {
    it: "Da Chardonney (1450 m), frazione di Champorcher, questo itinerario per Escursionisti Esperti (EE) raggiunge il Lago Vercoche e prosegue fino al Col Laris (2588 m), con oltre 1100 metri di dislivello in circa 6,7 chilometri. La salita attraversa boschi e alpeggi fino al bacino del Vercoche, specchio d'acqua incastonato tra le praterie d'alta quota della valle di Champorcher, e poi guadagna il valico tra pietraie e creste. È una giornata di cammino impegnativa per il dislivello e il terreno alto: richiede allenamento, passo sicuro e una giornata stabile. Champorcher, all'estremità sud-orientale della Valle d'Aosta, conserva un ambiente raccolto e poco affollato, dominato in alto dai contrafforti del Mont Glacier.",
    en: "From Chardonney (1450 m), a hamlet of Champorcher, this Expert Hikers (EE) route reaches Lake Vercoche and continues to the Col Laris (2588 m), with over 1100 metres of ascent in about 6.7 kilometres. The climb crosses woods and alpine pastures to the Vercoche basin, a sheet of water set among the high meadows of the Champorcher valley, then gains the pass over scree and ridges. It is a demanding day for its height gain and high terrain: it calls for fitness, a sure foot and a settled day. Champorcher, at the south-eastern end of the Aosta Valley, keeps an intimate, uncrowded setting, dominated above by the buttresses of Mont Glacier.",
    fr: "Depuis Chardonney (1450 m), hameau de Champorcher, cet itinéraire pour Randonneurs Experts (EE) atteint le lac Vercoche et continue jusqu'au Col Laris (2588 m), avec plus de 1100 mètres de dénivelé en environ 6,7 kilomètres. La montée traverse bois et alpages jusqu'au bassin du Vercoche, plan d'eau niché parmi les prairies d'altitude du val de Champorcher, puis gagne le col entre pierriers et crêtes. C'est une journée exigeante par son dénivelé et son terrain d'altitude : elle demande de l'entraînement, un pied sûr et une journée stable. Champorcher, à l'extrémité sud-est de la Vallée d'Aoste, garde un cadre intime et peu fréquenté, dominé en haut par les contreforts du Mont Glacier.",
    de: "Von Chardonney (1450 m), einem Ortsteil von Champorcher, erreicht diese Route für Erfahrene Wanderer (EE) den Vercoche-See und führt weiter zum Col Laris (2588 m), mit über 1100 Höhenmetern auf rund 6,7 Kilometern. Der Anstieg quert Wälder und Almen bis zum Vercoche-Becken, einem Gewässer inmitten der Hochmatten des Champorcher-Tals, und gewinnt dann über Geröll und Grate den Pass. Ein wegen Höhenmetern und Hochgelände anspruchsvoller Tag: Er erfordert Training, Trittsicherheit und stabiles Wetter. Champorcher, am südöstlichen Ende des Aostatals, bewahrt eine intime, wenig besuchte Umgebung, oben überragt von den Ausläufern des Mont Glacier.",
  },
  '18-s38': {
    it: "Da Chardonney (1450 m), nel comune di Champorcher, questo itinerario escursionistico (E) sale al Rifugio Dondena (2196 m) con circa 770 metri di dislivello in poco più di 6 chilometri. È una salita progressiva e regolare attraverso boschi e alpeggi fino all'ampia conca di Dondena, storico pianoro d'alta quota punteggiato di baite e base di partenza per i colli e le cime della testata di Champorcher. La pendenza contenuta e il fondo per lo più agevole ne fanno una meta adatta anche a escursionisti con allenamento moderato e una buona introduzione all'ambiente d'alta quota. Periodo consigliato dall'estate all'inizio autunno; verificare sempre l'apertura stagionale del rifugio.",
    en: "From Chardonney (1450 m), in the municipality of Champorcher, this hiking route (E) climbs to the Dondena refuge (2196 m) with about 770 metres of ascent in just over 6 kilometres. It is a progressive, steady climb through woods and alpine pastures to the broad Dondena basin, a historic high-altitude plateau dotted with huts and a base for the cols and peaks at the head of Champorcher. The moderate gradient and mostly easy surface make it a goal suited even to hikers of moderate fitness, and a good introduction to the high-mountain environment. Recommended from summer to early autumn; always check the refuge's seasonal opening.",
    fr: "Depuis Chardonney (1450 m), dans la commune de Champorcher, cet itinéraire de randonnée (E) monte au refuge Dondena (2196 m) avec environ 770 mètres de dénivelé en un peu plus de 6 kilomètres. C'est une montée progressive et régulière à travers bois et alpages jusqu'à la vaste cuvette de Dondena, plateau d'altitude historique parsemé de chalets et base pour les cols et sommets de la tête de Champorcher. La pente modérée et le terrain en grande partie facile en font un but accessible même aux randonneurs moyennement entraînés et une bonne introduction au milieu de haute montagne. Conseillé de l'été au début de l'automne ; vérifier toujours l'ouverture saisonnière du refuge.",
    de: "Von Chardonney (1450 m), in der Gemeinde Champorcher, steigt diese Wanderung (E) mit rund 770 Höhenmetern auf gut 6 Kilometern zur Dondena-Hütte (2196 m) auf. Es ist ein gleichmäßiger Anstieg durch Wälder und Almen bis zum weiten Becken von Dondena, einem historischen Hochplateau voller Hütten und Ausgangspunkt für die Pässe und Gipfel am Talschluss von Champorcher. Die mäßige Steigung und der überwiegend einfache Untergrund machen es auch für mäßig trainierte Wanderer zu einem geeigneten Ziel und einer guten Einführung in die hochalpine Umgebung. Empfohlen von Sommer bis Frühherbst; stets die saisonale Öffnung der Hütte prüfen.",
  },
  '18-s35': {
    it: "Dal parcheggio di Dondena (2103 m), nell'alta valle di Champorcher, questo itinerario escursionistico (E) raggiunge il Col Pontonnet (2897 m) con circa 800 metri di dislivello in 7,7 chilometri, partendo già in piena fascia alpina. Si cammina nell'ampia conca di Dondena tra pascoli e pietraie, salendo verso il valico che si affaccia oltre i tremila metri sulle valli vicine. È un percorso d'alta quota, ben oltre il limite del bosco fin dalla partenza: nonostante la classificazione escursionistica richiede allenamento per lo sviluppo e attenzione al meteo, che in quota cambia rapidamente. Dal colle il panorama abbraccia la testata di Champorcher e le creste che la separano dal Piemonte. Periodo consigliato l'estate.",
    en: "From the Dondena car park (2103 m), in the upper Champorcher valley, this hiking route (E) reaches the Col Pontonnet (2897 m) with about 800 metres of ascent over 7.7 kilometres, starting already in the full alpine belt. You walk through the broad Dondena basin among pastures and scree, climbing towards the pass that looks out above three thousand metres over the neighbouring valleys. It is a high-altitude route, well beyond the treeline from the start: despite the hiking grade it calls for fitness for its length and attention to weather, which changes quickly at altitude. From the col the panorama embraces the head of Champorcher and the ridges separating it from Piedmont. Summer is the recommended season.",
    fr: "Depuis le parking de Dondena (2103 m), dans le haut val de Champorcher, cet itinéraire de randonnée (E) atteint le Col Pontonnet (2897 m) avec environ 800 mètres de dénivelé sur 7,7 kilomètres, en partant déjà en pleine zone alpine. On marche dans la vaste cuvette de Dondena parmi pâturages et pierriers, montant vers le col qui domine au-delà de trois mille mètres les vallées voisines. C'est un parcours d'altitude, bien au-dessus de la limite des arbres dès le départ : malgré la cotation randonnée, il demande de l'entraînement pour son développement et de l'attention à la météo, qui change vite en altitude. Du col, le panorama embrasse la tête de Champorcher et les crêtes qui la séparent du Piémont. Saison conseillée l'été.",
    de: "Vom Parkplatz Dondena (2103 m), im oberen Champorcher-Tal, erreicht diese Wanderung (E) den Col Pontonnet (2897 m) mit rund 800 Höhenmetern auf 7,7 Kilometern und startet bereits in der vollen alpinen Stufe. Man geht durch das weite Becken von Dondena zwischen Weiden und Geröll und steigt zum Pass auf, der über dreitausend Meter auf die Nachbartäler blickt. Es ist eine Höhenroute, von Beginn an weit über der Baumgrenze: Trotz der Wandereinstufung erfordert sie Training wegen der Länge und Aufmerksamkeit fürs Wetter, das in der Höhe rasch umschlägt. Vom Pass umfasst das Panorama den Talschluss von Champorcher und die Grate zum Piemont. Empfohlene Jahreszeit: Sommer.",
  },
};

const json = JSON.parse(fs.readFileSync(FILE, 'utf8'));
const arr = Array.isArray(json) ? json : json.trails;
let done = 0;
for (const [slug, d] of Object.entries(DESC)) {
  const t = arr.find((x) => x.slug === slug);
  if (!t) { console.log('MISS', slug); continue; }
  t.description_it = d.it; t.description_en = d.en; t.description_fr = d.fr; t.description_de = d.de;
  t.name_en = t.name_en || t.name_it; t.name_fr = t.name_fr || t.name_it; t.name_de = t.name_de || t.name_it;
  if (t.duration_hours == null) t.duration_hours = cai(t.distance_km || 0, t.elevation_gain_m || 0, t.elevation_loss_m || 0);
  if (t.fitness_level == null) t.fitness_level = FITNESS[t.difficulty] ?? 2;
  if (t.mobile_coverage == null) t.mobile_coverage = 'partial';
  t.enriched = true;
  console.log(slug, 'OK', [d.it, d.en, d.fr, d.de].map((s) => s.length).join('/'));
  done++;
}
fs.writeFileSync(FILE, JSON.stringify(json, null, 2) + '\n');
console.log('TOTALE:', done);
