import fs from 'fs';

const en = JSON.parse(fs.readFileSync('src/messages/en.json', 'utf8'));

const fr = {
  Site: {
    name: 'Sentieri VdA',
    tagline: "Les sentiers de la Vallée d'Aoste, racontés comme ils le méritent.",
  },
  Nav: {
    trails: 'Sentiers',
    alteVie: 'Hautes Routes',
    tours: 'Tours',
    refuges: 'Refuges',
    floraFauna: 'Flore & Faune',
    parks: 'Parcs',
    blog: 'Journal',
    about: 'À propos',
  },
  Home: {
    heroEyebrow: "Vallée d'Aoste · Alpes occidentales",
    heroTitle: 'Marcher entre les géants.',
    heroSubtitle:
      "Guide éditorial des sentiers valdôtains : cartes interactives, profils altimétriques et fiches détaillées — des Hautes Routes aux tours du Mont-Blanc, Cervin et Grand Paradiso.",
    heroCtaPrimary: 'Explorer les sentiers',
    heroCtaSecondary: 'Les Hautes Routes',
    featuredEyebrow: 'À la une',
    featuredTitle: 'Étapes à faire au moins une fois',
    exploreMapTitle: 'Toute la région, sur une carte',
    exploreMapDescription:
      'Filtrez par difficulté, durée, dénivelé. Téléchargez le GPX. Partez.',
    statTrails: 'Sentiers documentés',
    statAlteVie: 'Étapes des Hautes Routes',
    statTotalKm: 'Kilomètres de sentier',
    statTours: 'Grands massifs',
    statStagesSuffix: ' étapes',
    statToursSuffix: ' Tours',
    allTrails: 'Tous les sentiers',
    choosePathEyebrow: 'Choisissez votre itinéraire',
    choosePathTitle: 'Par où voulez-vous commencer ?',
    exploreCta: 'Explorer',
    mapAv1: 'Haute Route 1',
    mapAv2: 'Haute Route 2',
    pathAv1Title: 'Haute Route 1',
    pathAv1Sub: '17 étapes · Donnas → Courmayeur',
    pathTmbTitle: 'Tour du Mont-Blanc',
    pathTmbSub: 'Côté italien · Val Ferret',
    pathGpTitle: 'Grand Paradiso',
    pathGpSub: 'Parc national · Bouquetins',
    pathDayTitle: "Une journée",
    pathDaySub: 'Toutes les vallées · Tous niveaux',
  },
  Trails: {
    title: "Sentiers de la Vallée d'Aoste",
    heroEyebrow: 'Cartes · GPX · Fiches complètes',
    heroSubtitle:
      '{count} sentiers vérifiés sur sources officielles — Hautes Routes, tours et randonnées à la journée.',
    filterDifficulty: 'Difficulté',
    filterLength: 'Longueur',
    filterDuration: 'Durée',
    filterElevation: 'Dénivelé',
    filterValley: 'Vallée',
    filterRoute: 'Itinéraire',
    all: 'Tous',
    noResults: 'Aucun sentier trouvé',
    routeTags: {
      'alta-via-1': 'Haute Route 1',
      'alta-via-2': 'Haute Route 2',
      'tour-mont-blanc': 'Tour du Mont-Blanc',
      'tour-monte-rosa': 'Tour du Monte Rosa',
      'tour-cervino': 'Tour du Cervin',
      'tour-gran-paradiso': 'Tour du Grand Paradiso',
      'tour-rutor': 'Tour du Rutor',
      'tour-gran-combin': 'Tour du Grand Combin',
    },
    details: {
      distance: 'Distance',
      elevationGain: 'Montée',
      elevationLoss: 'Descente',
      duration: 'Durée',
      difficulty: 'Difficulté',
      start: 'Départ',
      end: 'Arrivée',
      season: 'Meilleure saison',
      downloadGpx: 'Télécharger GPX',
      altimetricProfile: 'Profil altimétrique',
      description: 'Description',
      flora: 'Flore le long du sentier',
      fauna: 'Faune à observer',
      refugesNearby: 'Refuges & bivouacs',
      source: 'Source des données',
      waypoints: 'Points clés',
      geology: 'Géologie & paysage',
      geologyEyebrow: 'Sciences de la Terre',
      transport: 'Accès',
      parking: 'Parking',
      warnings: 'Avertissements',
      nearbyPeaks: 'Sommets proches',
      culturalNotes: 'Histoire & culture',
      waterSources: "Points d'eau",
      fitnessLevel: 'Condition physique',
      caloriesEstimate: '~{n} kcal estimées',
      kmFromStart: '{n} km depuis le départ',
    },
  },
  Difficulty: {
    T: 'Touristique',
    E: 'Randonnée',
    EE: 'Randonneurs expérimentés',
    EEA: 'Expérimentés avec équipement',
    A: 'Alpinisme',
  },
  Footer: {
    explore: 'Explorer',
    info: 'Infos',
    credits:
      "Données sentiers © Région Autonome Vallée d'Aoste — Catasto Sentieri (open data). © OpenStreetMap contributors. © MapTiler.",
    disclaimer:
      'Les informations sont indicatives. Vérifiez la météo et l\'enneigement avant de partir. La sécurité relève du randonneur.',
    newsletter: 'Newsletter',
    newsletterPlaceholder: 'votre@email.com',
    newsletterCta: "S'inscrire",
    rights: 'Tous droits réservés.',
  },
  AlteVie: {
    meta: {
      title: 'Les Hautes Routes',
      description:
        "Haute Route 1 des Géants et Haute Route 2 Naturaliste : itinéraires officiels multi-étapes de la Vallée d'Aoste avec données, étapes et cartes.",
    },
    heroEyebrow: "Itinéraires officiels — Région Autonome Vallée d'Aoste",
    heroTitle: 'Les Hautes Routes',
    heroSubtitle:
      "Les Hautes Routes sont les grands itinéraires à étapes officiels de la Vallée d'Aoste : parcours balisés régionaux d'est en ouest, reliant villages walser, refuges historiques et cols au-dessus de 2 700 m. Contrairement aux Tours — boucles autour d'un massif — elles racontent toute la géographie valdôtaine en une traversée. Nées dans les années 1970, elles restent parmi les treks alpins les plus complets d'Europe.",
    mapTitle: 'Carte du parcours',
    mapHint:
      'Tracés GPX officiels Région VdA · zoom et boussole pour explorer',
    stagesTitle: 'Toutes les étapes',
    viewStage: 'Ouvrir',
    compareTitle: 'Deux traversées, deux caractères',
    compareSubtitle:
      "L'AV1 traverse les trois grands massifs au versant nord ; l'AV2 suit le versant sud avec un focus naturaliste et la faune du Parc Gran Paradiso.",
    selectRoute: 'Choisir la route',
    officialGuide: 'Guide lovevda.it',
    stageLabel: 'Étape',
    fromTo: 'De → à',
    outsideRegion: 'Hors région',
    av1: {
      name: 'Haute Route 1 — des Géants',
      route: 'Donnas → Courmayeur (est → ouest)',
      statKm: '130 km',
      statGain: '8 500 m+',
      statStages: '17 étapes',
      statDays: '12–14 jours',
      difficultyLabel: 'Difficulté',
      difficulty: 'E / EE',
      seasonLabel: 'Saison',
      season: 'juillet – septembre',
      description:
        "La Haute Route 1 traverse toute la Vallée d'Aoste, touchant Monte Rosa, Cervin et Mont-Blanc en dix-sept étapes, des vignobles de Donnas (322 m) aux crêtes au-dessus de Courmayeur. Traversée alpine la plus complète de la région : pâturages walser, lacs glaciaires, refuges historiques et panoramas du Gran Paradiso au Mont-Blanc.",
      badge: '17 étapes disponibles sur ce site',
      ctaStages: 'Voir toutes les étapes',
      ctaPdf: 'Télécharger le guide PDF',
    },
    av2: {
      name: 'Haute Route 2 — Naturaliste',
      route: "Courmayeur → Donnas (versant sud, rive droite)",
      statKm: '~168 km',
      statGain: '~12 000 m+',
      statStages: '14 étapes',
      statDays: '12–14 jours',
      difficultyLabel: 'Difficulté',
      difficulty: 'E / EE',
      seasonLabel: 'Saison',
      season: 'juillet – septembre',
      description:
        "La Haute Route naturaliste traverse le versant sud — Val Veny, La Thuile, Valgrisenche, Rhêmes, Valsavarenche, Cogne et Champorcher — avec une faune remarquable dans les parcs Gran Paradiso et Mont Avic. Première section du Tor des Géants.",
      sources: 'Sources : lovevda.it, Catasto Sentieri VdA, Wikipedia',
      badge: '14 étapes disponibles sur ce site',
      cta: 'Voir toutes les étapes AV2',
    },
    legalNote:
      "Les Hautes Routes 1 et 2 sont des itinéraires officiels de la Région Autonome Vallée d'Aoste. Les Tours (TMB, Tour Monte Rosa, etc.) sont des parcours distincts dans la <tourLink>section Tours</tourLink>.",
  },
  Tour: {
    meta: {
      title: 'Les Tours',
      description:
        "Tour du Mont-Blanc, Monte Rosa, Cervin, Grand Paradiso, Rutor et Grand Combin : boucles autour des grands massifs de la Vallée d'Aoste.",
    },
    heroEyebrow: 'Boucles autour des grands massifs',
    heroTitle: 'Les Tours',
    heroSubtitle:
      "Les Tours sont des boucles autour d'un massif, souvent transfrontalières. Contrairement aux Hautes Routes — qui traversent la Vallée d'Aoste d'est en ouest — les Tours suivent la ceinture d'un groupe montagneux. Le Tour du Mont-Blanc (TMB) est le plus célèbre au monde.",
    labels: {
      distance: 'Distance',
      vdaSide: 'Tronçon valdôtain',
      places: 'Lieux VdA',
      difficulty: 'Difficulté',
      season: 'Saison',
    },
    badgeAvailable: 'Étapes italiennes disponibles',
    badgeSoon: 'Bientôt',
    badgeStages: '{count} étapes VdA disponibles',
    comingSoonCta: 'Fiche en préparation',
    selectTour: 'Choisir un tour',
    exploreStages: 'Voir les étapes',
    backToTours: 'Tous les tours',
    mapTitle: 'Carte du tour',
    mapHint: 'Tracés GPX officiels · zoom et boussole pour explorer',
    stagesTitle: 'Toutes les étapes',
    viewStage: 'Ouvrir',
    stageLabel: 'Étape',
    outsideRegion: 'Hors région',
    tmb: {
      name: 'Tour du Mont-Blanc (TMB)',
      distance: '170 km total (IT + FR + CH)',
      vdaSide: '~50 km, 3–4 étapes',
      places:
        'Courmayeur, Rif. Bertone (2 011 m), Rif. Bonatti (2 025 m), Rif. Elena (2 062 m), La Fouly (CH)',
      difficulty: 'E',
      season: 'juillet – septembre',
      description:
        "Itinéraire le plus célèbre des Alpes : dix jours, trois pays, vues constantes sur le versant sud du Mont-Blanc. Le tronçon italien en Val Ferret — de Courmayeur au Rifugio Bonatti — est considéré comme le plus spectaculaire de la boucle.",
      cta: 'Voir les étapes italiennes',
    },
    monteRosa: {
      name: 'Tour du Monte Rosa',
      distance: '~170 km (IT VdA + Piémont + CH)',
      vdaSide: '~40 km',
      places: 'Gressoney-la-Trinité, Champoluc, Brusson',
      difficulty: 'E / EE',
      season: 'juillet – septembre',
      description:
        "Boucle autour du second massif alpin par l'altitude, vallées walser, glaciers du Lys et cols au-dessus de 2 700 m. Moins fréquenté que le TMB mais tout aussi grandiose.",
      cta: 'Voir les étapes VdA',
    },
    cervino: {
      name: 'Tour du Cervin',
      distance: '~150 km, 8–10 jours',
      vdaSide: 'Boucle Zermatt (CH) ↔ Breuil-Cervinia (IT)',
      places: 'Valtournenche, Breuil-Cervinia, Plateau Rosa',
      difficulty: 'E / EE',
      season: 'juillet – septembre',
      description:
        "Tourne autour de la pyramide la plus iconique des Alpes, alternant vallées italiennes et suisses. Côté valdôtain : Plateau Rosa et vues frontales sur le Cervin.",
      cta: 'Voir les étapes VdA',
    },
    granParadiso: {
      name: 'Tour du Grand Paradiso',
      distance: '~120 km, 7–9 jours',
      difficulty: 'E',
      season: 'juin – septembre',
      description:
        "Boucle entièrement dans le Parc National du Grand Paradiso : Cogne, Valsavarenche et Val d'Orco (Piémont). Faune exceptionnelle — bouquetins quasi garantis.",
      cta: 'Voir les étapes VdA',
    },
    rutor: {
      name: 'Tour du Rutor',
      distance: '~55 km, 4–5 jours',
      vdaSide: 'La Thuile — Arvier — Morgex',
      difficulty: 'E / EE',
      season: 'juillet – septembre',
      description:
        "Tour moins connu mais idéal pour observer un glacier actif. Boucle autour du Rutor, au-dessus de La Thuile : alpages tranquilles, lacs glaciaires et vue sur le Mont-Blanc occidental.",
      cta: 'Voir les étapes VdA',
    },
    granCombin: {
      name: 'Tour du Grand Combin',
      distance: '~100 km, 6–8 jours',
      vdaSide: 'Valpelline (IT) + Valais (CH)',
      difficulty: 'EE',
      season: 'juillet – septembre',
      description:
        "Massif moins connu du grand public mais glaciologiquement spectaculaire : boucle transfrontalière avec cols au-dessus de 2 700 m et vues sur le Combin de Grafeneire.",
      cta: 'Voir les étapes VdA',
    },
  },
  FloraFauna: {
    heroEyebrow: 'Biodiversité alpine',
    heroTitle: 'Flore & faune',
    heroSubtitle:
      '{fauna} animaux et {flora} plantes indigènes, organisés par classe et habitat. Fiches naturalistes, cartes de répartition et sources fiables.',
    heroNote:
      'Photos Wikimedia Commons · CC · Observez toujours à distance sans déranger.',
  },
  About: {
    heroEyebrow: 'À propos',
    heroTitle: 'Un passionné, une région.',
    heroSubtitle:
      "Projet indépendant sur les sentiers valdôtains : données vérifiées, descriptions originales, zéro invention.",
    contact: 'Contact',
  },
  Refuges: {
    meta: {
      title: "Refuges & bivouacs de la Vallée d'Aoste",
      description:
        "Catalogue complet des refuges et bivouacs des Hautes Routes et tours : altitude, histoire, cuisine, tarifs et réservation.",
    },
    heroEyebrow: "Haute altitude · Vallée d'Aoste",
    heroTitle: 'Refuges & bivouacs',
    heroSubtitle:
      '25 refuges sur les Hautes Routes et les tours : fiches complètes avec photos, histoire, cuisine, tarifs et réservation.',
    heroNote:
      'Tarifs et dates indicatifs — vérifiez toujours le site officiel du refuge avant de partir.',
    search: 'Rechercher refuge ou vallée…',
    tabAll: 'Tous',
    tabRefuges: 'Refuges',
    tabBivouacs: 'Bivouacs',
    elevation: 'Altitude',
    valley: 'Vallée',
    beds: 'Lits',
    openPeriod: 'Ouverture',
    manager: 'Gestion',
    viewProfile: 'Fiche complète',
    noResults: 'Aucun refuge trouvé',
    book: 'Réserver / site officiel',
    call: 'Appeler',
    website: 'Site web',
    backToCatalog: 'Retour au catalogue',
    rifugio: 'Refuge',
    bivacco: 'Bivouac',
    history: 'Histoire',
    food: 'À manger',
    costs: 'Tarifs indicatifs',
    onTrails: 'Étapes liées',
    source: 'Source',
    contactsTitle: 'Contact & réservation',
    contactsSubtitle:
      'Coordonnées officielles — vérifiez ouvertures et tarifs sur le site avant de partir.',
    officialWebsite: 'Site officiel',
    instagram: 'Instagram',
    facebook: 'Facebook',
    email: 'E-mail',
    noSocial: 'Aucun profil social public vérifié pour cette structure.',
  },
};

const de = {
  Site: {
    name: 'Sentieri VdA',
    tagline: 'Die Wanderwege des Aostatales, erzählt wie sie es verdienen.',
  },
  Nav: {
    trails: 'Wanderwege',
    alteVie: 'Hochrouten',
    tours: 'Touren',
    refuges: 'Hütten',
    floraFauna: 'Flora & Fauna',
    parks: 'Parks',
    blog: 'Journal',
    about: 'Über uns',
  },
  Home: {
    heroEyebrow: 'Aostatal · Westalpen',
    heroTitle: 'Zwischen Giganten wandern.',
    heroSubtitle:
      'Editorialer Führer zu den Wegen im Aostatal: interaktive Karten, Höhenprofile und kuratierte Routen — von den Hochrouten bis zu Touren um Mont Blanc, Matterhorn und Gran Paradiso.',
    heroCtaPrimary: 'Wege entdecken',
    heroCtaSecondary: 'Die Hochrouten',
    featuredEyebrow: 'Empfohlen',
    featuredTitle: 'Etappen, die man mindestens einmal machen sollte',
    exploreMapTitle: 'Die ganze Region auf einer Karte',
    exploreMapDescription:
      'Filtern nach Schwierigkeit, Dauer, Höhenmeter. GPX herunterladen. Los geht’s.',
    statTrails: 'Dokumentierte Wege',
    statAlteVie: 'Hochrouten-Etappen',
    statTotalKm: 'Wegkilometer',
    statTours: 'Große Massive',
    statStagesSuffix: ' Etappen',
    statToursSuffix: ' Touren',
    allTrails: 'Alle Wege',
    choosePathEyebrow: 'Wählen Sie Ihre Route',
    choosePathTitle: 'Wo möchten Sie starten?',
    exploreCta: 'Entdecken',
    mapAv1: 'Hochroute 1',
    mapAv2: 'Hochroute 2',
    pathAv1Title: 'Hochroute 1',
    pathAv1Sub: '17 Etappen · Donnas → Courmayeur',
    pathTmbTitle: 'Tour du Mont Blanc',
    pathTmbSub: 'Italienische Seite · Val Ferret',
    pathGpTitle: 'Gran Paradiso',
    pathGpSub: 'Nationalpark · Steinböcke',
    pathDayTitle: 'Tagestouren',
    pathDaySub: 'Alle Täler · Alle Schwierigkeiten',
  },
  Trails: {
    title: 'Wanderwege im Aostatal',
    heroEyebrow: 'Karten · GPX · Vollständige Wegseiten',
    heroSubtitle:
      '{count} Wege aus offiziellen Quellen — Hochrouten, Touren und Tageswanderungen.',
    filterDifficulty: 'Schwierigkeit',
    filterLength: 'Länge',
    filterDuration: 'Dauer',
    filterElevation: 'Höhenmeter',
    filterValley: 'Tal',
    filterRoute: 'Route',
    all: 'Alle',
    noResults: 'Keine Wege gefunden',
    routeTags: {
      'alta-via-1': 'Hochroute 1',
      'alta-via-2': 'Hochroute 2',
      'tour-mont-blanc': 'Tour du Mont Blanc',
      'tour-monte-rosa': 'Monte-Rosa-Tour',
      'tour-cervino': 'Matterhorn-Tour',
      'tour-gran-paradiso': 'Gran-Paradiso-Tour',
      'tour-rutor': 'Rutor-Tour',
      'tour-gran-combin': 'Grand-Combin-Tour',
    },
    details: {
      distance: 'Distanz',
      elevationGain: 'Aufstieg',
      elevationLoss: 'Abstieg',
      duration: 'Dauer',
      difficulty: 'Schwierigkeit',
      start: 'Start',
      end: 'Ziel',
      season: 'Beste Saison',
      downloadGpx: 'GPX herunterladen',
      altimetricProfile: 'Höhenprofil',
      description: 'Beschreibung',
      flora: 'Flora entlang des Weges',
      fauna: 'Beobachtbare Fauna',
      refugesNearby: 'Hütten & Biwaks',
      source: 'Datenquelle',
      waypoints: 'Wichtige Punkte',
      geology: 'Geologie & Landschaft',
      geologyEyebrow: 'Geowissenschaften',
      transport: 'Anreise',
      parking: 'Parkplatz',
      warnings: 'Hinweise',
      nearbyPeaks: 'Nahe Gipfel',
      culturalNotes: 'Geschichte & Kultur',
      waterSources: 'Wasserstellen',
      fitnessLevel: 'Kondition',
      caloriesEstimate: '~{n} kcal geschätzt',
      kmFromStart: '{n} km vom Start',
    },
  },
  Difficulty: {
    T: 'Touristisch',
    E: 'Wanderer',
    EE: 'Erfahrene Wanderer',
    EEA: 'Erfahrene mit Ausrüstung',
    A: 'Alpin',
  },
  Footer: {
    explore: 'Entdecken',
    info: 'Info',
    credits:
      'Wegdaten © Autonome Region Aostatal — Catasto Sentieri (Open Data). © OpenStreetMap contributors. © MapTiler.',
    disclaimer:
      'Informationen dienen der Orientierung. Wetter und Schneeverhältnisse prüfen. Sicherheit liegt beim Wanderer.',
    newsletter: 'Newsletter abonnieren',
    newsletterPlaceholder: 'ihre@email.de',
    newsletterCta: 'Abonnieren',
    rights: 'Alle Rechte vorbehalten.',
  },
  AlteVie: {
    meta: {
      title: 'Die Hochrouten',
      description:
        'Hochroute 1 der Giganten und Hochroute 2 Naturalistica: offizielle Mehrtagesrouten im Aostatal mit Etappendaten und Karten.',
    },
    heroEyebrow: 'Offizielle Routen — Autonome Region Aostatal',
    heroTitle: 'Die Hochrouten',
    heroSubtitle:
      'Die Hochrouten sind die offiziellen Mehrtageswege im Aostatal: markierte Regionalrouten von Ost nach West, die Walserdörfer, historische Hütten und Pässe über 2.700 m verbinden. Im Gegensatz zu Touren — Schleifen um ein Massiv — erzählen die Hochrouten die gesamte Geographie des Aostatals in einer Querung.',
    mapTitle: 'Vollständige Routenkarte',
    mapHint:
      'Offizielle GPX-Tracks der Region VdA · Zoom und Kompass zum Erkunden',
    stagesTitle: 'Alle Etappen',
    viewStage: 'Öffnen',
    compareTitle: 'Zwei Querungen, zwei Charaktere',
    compareSubtitle:
      'AV1 durchquert die drei großen Massive am Nordhang; AV2 folgt der Südseite mit naturwissenschaftlichem Fokus und Gran-Paradiso-Fauna.',
    selectRoute: 'Route wählen',
    officialGuide: 'lovevda.it Guide',
    stageLabel: 'Etappe',
    fromTo: 'Von → nach',
    outsideRegion: 'Außerhalb der Region',
    av1: {
      name: 'Hochroute 1 — der Giganten',
      route: 'Donnas → Courmayeur (Ost → West)',
      statKm: '130 km',
      statGain: '8.500 m+',
      statStages: '17 Etappen',
      statDays: '12–14 Tage',
      difficultyLabel: 'Schwierigkeit',
      difficulty: 'E / EE',
      seasonLabel: 'Saison',
      season: 'Juli – September',
      description:
        'Die Hochroute 1 durchquert das gesamte Aostatal und berührt Monte Rosa, Matterhorn und Mont Blanc in siebzehn Etappen — von den Weinbergen in Donnas (322 m) zu den Graten über Courmayeur.',
      badge: '17 Etappen auf dieser Website',
      ctaStages: 'Alle Etappen ansehen',
      ctaPdf: 'PDF-Guide herunterladen',
    },
    av2: {
      name: 'Hochroute 2 — Naturalistica',
      route: 'Courmayeur → Donnas (Südhang, orographisch rechts)',
      statKm: '~168 km',
      statGain: '~12.000 m+',
      statStages: '14 Etappen',
      statDays: '12–14 Tage',
      difficultyLabel: 'Schwierigkeit',
      difficulty: 'E / EE',
      seasonLabel: 'Saison',
      season: 'Juli – September',
      description:
        'Die Naturalistica-Hochroute durchquert den Südhang — Val Veny, La Thuile, Valgrisenche, Rhêmes, Valsavarenche, Cogne und Champorcher — mit bemerkenswerter Fauna in den Parks Gran Paradiso und Mont Avic.',
      sources: 'Quellen: lovevda.it, Catasto Sentieri VdA, Wikipedia',
      badge: '14 Etappen auf dieser Website',
      cta: 'Alle AV2-Etappen ansehen',
    },
    legalNote:
      'Hochroute 1 und 2 sind offizielle Routen der Autonomen Region Aostatal. Touren (TMB, Monte-Rosa-Tour usw.) sind separate Routen in der <tourLink>Touren-Sektion</tourLink>.',
  },
  Tour: {
    meta: {
      title: 'Die Touren',
      description:
        'Tour du Mont Blanc, Monte Rosa, Matterhorn, Gran Paradiso, Rutor und Grand Combin: Wanderschleifen um die großen Massive des Aostatals.',
    },
    heroEyebrow: 'Schleifen um große Massive',
    heroTitle: 'Die Touren',
    heroSubtitle:
      'Touren sind Wanderschleifen um ein Massiv, oft grenzüberschreitend. Im Gegensatz zu Hochrouten — die das Aostatal von Ost nach West durchqueren — folgen Touren dem Kamm einer Berggruppe. Die Tour du Mont Blanc (TMB) ist weltweit am bekanntesten.',
    labels: {
      distance: 'Distanz',
      vdaSide: 'Aostatal-Abschnitt',
      places: 'Orte im Aostatal',
      difficulty: 'Schwierigkeit',
      season: 'Saison',
    },
    badgeAvailable: 'Italienische Etappen verfügbar',
    badgeSoon: 'Demnächst',
    badgeStages: '{count} VdA-Etappen verfügbar',
    comingSoonCta: 'Profil in Vorbereitung',
    selectTour: 'Tour wählen',
    exploreStages: 'Etappen ansehen',
    backToTours: 'Alle Touren',
    mapTitle: 'Tourkarte',
    mapHint: 'Offizielle GPX-Tracks · Zoom und Kompass zum Erkunden',
    stagesTitle: 'Alle Etappen',
    viewStage: 'Öffnen',
    stageLabel: 'Etappe',
    outsideRegion: 'Außerhalb der Region',
    tmb: {
      name: 'Tour du Mont Blanc (TMB)',
      distance: '170 km gesamt (IT + FR + CH)',
      vdaSide: '~50 km, 3–4 Etappen',
      places:
        'Courmayeur, Rif. Bertone (2.011 m), Rif. Bonatti (2.025 m), Rif. Elena (2.062 m), La Fouly (CH)',
      difficulty: 'E',
      season: 'Juli – September',
      description:
        'Die berühmteste Route der Alpen: zehn volle Tage, drei Länder, ständige Blicke auf die Südwand des Mont Blanc. Der italienische Abschnitt im Val Ferret gilt als spektakulärster der gesamten Schleife.',
      cta: 'Italienische Etappen ansehen',
    },
    monteRosa: {
      name: 'Monte-Rosa-Tour',
      distance: '~170 km (IT Aostatal + Piemont + CH)',
      vdaSide: '~40 km',
      places: 'Gressoney-la-Trinité, Champoluc, Brusson',
      difficulty: 'E / EE',
      season: 'Juli – September',
      description:
        'Schleife um das zweithöchste Massiv der Alpen, Walser-Täler, Lys-Gletscher und Pässe über 2.700 m. Weniger überlaufen als die TMB, aber ebenso grandios.',
      cta: 'VdA-Etappen ansehen',
    },
    cervino: {
      name: 'Matterhorn-Tour',
      distance: '~150 km, 8–10 Tage',
      vdaSide: 'Schleife Zermatt (CH) ↔ Breuil-Cervinia (IT)',
      places: 'Valtournenche, Breuil-Cervinia, Plateau Rosa',
      difficulty: 'E / EE',
      season: 'Juli – September',
      description:
        'Umkreist die ikonischste Pyramide der Alpen, wechselt italienische und schweizer Täler. Valdostanische Seite: Plateau Rosa und frontale Matterhorn-Blicke.',
      cta: 'VdA-Etappen ansehen',
    },
    granParadiso: {
      name: 'Gran-Paradiso-Tour',
      distance: '~120 km, 7–9 Tage',
      difficulty: 'E',
      season: 'Juni – September',
      description:
        'Schleife ganz im Gran-Paradiso-Nationalpark: Cogne, Valsavarenche und Val dell’Orco (Piemont). Außergewöhnliche Fauna — Steinböcke fast garantiert.',
      cta: 'VdA-Etappen ansehen',
    },
    rutor: {
      name: 'Rutor-Tour',
      distance: '~55 km, 4–5 Tage',
      vdaSide: 'La Thuile — Arvier — Morgex',
      difficulty: 'E / EE',
      season: 'Juli – September',
      description:
        'Weniger bekannte Tour, ideal um einen aktiven Gletscher zu beobachten. Schleife um den Rutor oberhalb La Thuile: ruhige Almen, Gletscherseen und Blick auf den westlichen Mont Blanc.',
      cta: 'VdA-Etappen ansehen',
    },
    granCombin: {
      name: 'Grand-Combin-Tour',
      distance: '~100 km, 6–8 Tage',
      vdaSide: 'Valpelline (IT) + Wallis (CH)',
      difficulty: 'EE',
      season: 'Juli – September',
      description:
        'Weniger bekanntes, aber glazial spektakuläres Massiv: grenzüberschreitende Schleife mit Pässen über 2.700 m und Blick auf den Combin de Grafeneire.',
      cta: 'VdA-Etappen ansehen',
    },
  },
  FloraFauna: {
    heroEyebrow: 'Alpine Biodiversität',
    heroTitle: 'Flora & Fauna',
    heroSubtitle:
      '{fauna} Tiere und {flora} heimische Pflanzen, nach Klasse und Lebensraum geordnet. Profile mit Naturhinweisen, Verbreitungskarten und Quellen.',
    heroNote:
      'Wikimedia-Commons-Fotos · CC · Beobachten Sie immer aus der Ferne ohne Tiere zu stören.',
  },
  About: {
    heroEyebrow: 'Über uns',
    heroTitle: 'Ein Enthusiast, eine Region.',
    heroSubtitle:
      'Unabhängiges Aostatal-Wegprojekt: verifizierte Daten, originelle Beschreibungen, keine erfundenen Fakten.',
    contact: 'Kontakt',
  },
  Refuges: {
    meta: {
      title: 'Hütten & Biwaks im Aostatal',
      description:
        'Vollständiger Katalog der Hütten und Biwaks an Hochroute 1, Hochroute 2 und Touren: Höhe, Geschichte, Verpflegung, Preise und Buchung.',
    },
    heroEyebrow: 'Hochalpine · Aostatal',
    heroTitle: 'Hütten & Biwaks',
    heroSubtitle:
      '25 Hütten an Hochrouten und Touren: vollständige Profile mit Fotos, Geschichte, Küche, Preisen und Buchungslinks.',
    heroNote:
      'Preise und Öffnungsdaten sind Richtwerte — prüfen Sie immer die offizielle Hüttenwebsite vor der Tour.',
    search: 'Hütte oder Tal suchen…',
    tabAll: 'Alle',
    tabRefuges: 'Hütten',
    tabBivouacs: 'Biwaks',
    elevation: 'Höhe',
    valley: 'Tal',
    beds: 'Betten',
    openPeriod: 'Geöffnet',
    manager: 'Betreiber',
    viewProfile: 'Vollständiges Profil',
    noResults: 'Keine Hütten gefunden',
    book: 'Buchen / offizielle Seite',
    call: 'Anrufen',
    website: 'Website',
    backToCatalog: 'Zurück zum Katalog',
    rifugio: 'Hütte',
    bivacco: 'Biwak',
    history: 'Geschichte',
    food: 'Verpflegung',
    costs: 'Richtpreise',
    onTrails: 'Verknüpfte Etappen',
    source: 'Quelle',
    contactsTitle: 'Kontakt & Buchung',
    contactsSubtitle:
      'Offizielle Betreiberdaten — Öffnungszeiten und Preise vor der Tour auf der Website prüfen.',
    officialWebsite: 'Offizielle Website',
    instagram: 'Instagram',
    facebook: 'Facebook',
    email: 'E-Mail',
    noSocial: 'Kein verifiziertes öffentliches Social-Media-Profil für diese Hütte.',
  },
};

fs.writeFileSync('src/messages/fr.json', JSON.stringify(fr, null, 2));
fs.writeFileSync('src/messages/de.json', JSON.stringify(de, null, 2));
console.log('Generated fr.json and de.json');
