'use strict';
/**
 * Round 2 — patch descrizioni editoriali (120 sentieri).
 * Generato direttamente dall'orchestratore senza subagenti.
 */
const fs = require('fs');
const path = require('path');
const skPath = path.join(__dirname, '../src/data/trails-skeleton.json');

function cai(km, gain, loss) {
  const h = km / 4 + Math.max(gain, 0) / 400 + Math.max(loss, 0) / 600;
  return Math.max(0.5, Math.round(h * 2) / 2);
}
const diffToFitness = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };

const patch = {
  "02-s19": {
    description_it: "Il sentiero collega il borgo di Bourg, nel comune di Antey-Saint-André, alla frazione di Brengon appartenente al piccolo comune di La Magdeleine, sospeso tra la Valtournenche e la valle di Torgnon. La partenza a 1474 metri avviene in un ambiente già montano, dove i pascoli terrazzati e le case in pietra grezza documentano secoli di vita alpina. Il percorso di 3,7 km guadagna soli 188 metri di dislivello, il che lo rende uno degli itinerari più accessibili della Valtournenche media: una passeggiata adatta alle famiglie e a chi cerca il contatto con i borghi storici senza impegni altimetrici. Il tracciato tocca le frazioni di Petit Antey e Lod prima di raggiungere Brengon, a 1643 metri, dove l'architettura rurale valdostana si presenta nella sua forma più autentica: mayen in pietra, stalle, fontane. Da Brengon parte il noto percorso attrezzato Brengon-Parapromiat. Consigliato da aprile a ottobre.",
    description_en: "The trail links the hamlet of Bourg in Antey-Saint-André to the hamlet of Brengon belonging to the small commune of La Magdeleine, perched between the Valtournenche and the Torgnon valley. Departing at 1474 metres, the route covers 3.7 km with only 188 metres of elevation gain, making it one of the most accessible walks in the mid-Valtournenche and well suited to families. The path passes through the hamlets of Petit Antey and Lod before reaching Brengon at 1643 metres, where traditional Valdostan rural architecture — stone mayens, stables, fountains — appears in its most authentic form. Brengon is also the starting point of the known via ferrata Brengon-Parapromiat. Open April to October.",
    description_fr: "Le sentier relie le hameau de Bourg, dans la commune d'Antey-Saint-André, au hameau de Brengon appartenant à la petite commune de La Magdeleine, suspendue entre le Valtournenche et la vallée de Torgnon. Au départ à 1474 mètres, le parcours de 3,7 km ne gagne que 188 mètres de dénivelé, ce qui en fait l'une des promenades les plus accessibles de la moyenne Valtournenche, idéale pour les familles. Le tracé passe par les hameaux de Petit Antey et Lod avant d'atteindre Brengon à 1643 mètres, où l'architecture rurale valdôtaine s'exprime dans sa forme la plus authentique. Brengon est aussi le point de départ du parcours équipé Brengon-Parapromiat. Praticable d'avril à octobre.",
    description_de: "Der Weg verbindet den Weiler Bourg in der Gemeinde Antey-Saint-André mit dem Weiler Brengon der kleinen Gemeinde La Magdeleine, die zwischen dem Valtournenche und dem Torgnon-Tal liegt. Ab 1474 Metern überwindet die 3,7 km lange Route nur 188 Höhenmeter — eine der zugänglichsten Wanderungen im mittleren Valtournenche, ideal für Familien. Der Weg durchquert die Weiler Petit Antey und Lod, bevor er Brengon auf 1643 Metern erreicht, wo die traditionelle Valdostaner Bergarchitektur in ihrer authentischsten Form erscheint. Von Brengon startet auch der bekannte Klettersteig Brengon-Parapromiat. Von April bis Oktober begehbar.",
    shortDescription_it: "Passeggiata accessibile da Bourg a Brengon (La Magdeleine) tra borghi storici della Valtournenche: 3,7 km e soli 188 m di dislivello. Base del percorso attrezzato Brengon-Parapromiat.",
    shortDescription_en: "Easy walk from Bourg to Brengon (La Magdeleine) through historic Valtournenche hamlets: 3.7 km and just 188 m of ascent. Base for the Brengon-Parapromiat via ferrata.",
    shortDescription_fr: "Promenade accessible de Bourg à Brengon (La Magdeleine) à travers les hameaux historiques du Valtournenche : 3,7 km et seulement 188 m de dénivelé.",
    shortDescription_de: "Leichte Wanderung von Bourg nach Brengon (La Magdeleine) durch historische Weiler des Valtournenche: 3,7 km und nur 188 Hm Aufstieg.",
    updated_at: "2026-06-01"
  },
  "04-s7": {
    description_it: "Dal fondovalle di Chateau Vallaise, a soli 454 metri sul livello del mare, il sentiero risale con decisione il versante soleggiato del comune di Avise verso la cappella di Sant'Anna ad Echallogne, a 1342 metri. Il dislivello di 921 metri in 4,3 chilometri rende questo tracciato uno dei più impegnativi del suo tipo: una salita quasi ininterrotta che attraversa la fascia dei vigneti eroici e dei castagneti del fondovalle, poi i boschi di latifoglie del versante medio, infine i prati aperti della fascia più alta. L'ambiente cambia radicalmente con la quota: si parte dal microclima termofilo della Valle Centrale, dove in primavera la vegetazione è già avanzata, per arrivare a un ambiente montano aperto con panorami sulla Valle d'Aosta. La cappella di Sant'Anna, meta del percorso, è uno dei luoghi di devozione più antichi del versante. Difficoltà E, aperto da maggio a ottobre.",
    description_en: "From the valley floor at Chateau Vallaise, just 454 metres above sea level, the trail climbs decisively up the sunny Avise hillside to the chapel of Saint Anne at Echallogne at 1342 metres. The 921-metre elevation gain over 4.3 km makes this one of the most demanding routes of its kind: an almost unbroken ascent crossing the belt of heroic vineyards and chestnut groves at low elevation, then mixed broadleaf woodland in the middle section, finally open meadows near the top. The landscape shifts radically with altitude: from the thermophilic microclimate of the central valley to an open mountain environment with views over the Aosta Valley. The chapel of Saint Anne at the destination is one of the oldest sites of devotion on this hillside. Difficulty E, open May to October.",
    description_fr: "Depuis le fond de vallée de Chateau Vallaise, à seulement 454 mètres d'altitude, le sentier monte résolument le versant ensoleillé de la commune d'Avise jusqu'à la chapelle de Sainte-Anne à Echallogne, à 1342 mètres. Le dénivelé de 921 mètres sur 4,3 km en fait l'un des parcours les plus exigeants de cette catégorie : une montée presque continue traversant la ceinture de vignes en terrasses et châtaigneraies du bas, puis les forêts feuillues du versant, enfin les prairies ouvertes de la partie haute. Le paysage change radicalement avec l'altitude. La chapelle de Sainte-Anne, but du parcours, est l'un des lieux de dévotion les plus anciens du versant. Difficulté E, accessible de mai à octobre.",
    description_de: "Vom Talboden bei Chateau Vallaise, nur 454 Meter über dem Meeresspiegel, steigt der Weg entschlossen den sonnigen Hang der Gemeinde Avise zur Kapelle der Heiligen Anna in Echallogne auf 1342 Metern hinauf. Der Höhenunterschied von 921 Metern auf 4,3 km macht diesen Weg zu einem der anspruchsvollsten seiner Art: ein fast ununterbrochener Anstieg durch Steilhang-Weinberge und Kastanienwälder im unteren Bereich, dann Laubwälder im mittleren Abschnitt, schließlich offene Wiesen oben. Die Landschaft wandelt sich radikal mit der Höhe. Schwierigkeit E, von Mai bis Oktober begehbar.",
    shortDescription_it: "Dal fondovalle di Chateau Vallaise (454m) alla cappella di Sant'Anna (1342m): 4,3 km e 921 m di dislivello tra vigneti, castagneti e boschi del versante di Avise.",
    shortDescription_en: "From the valley floor at Chateau Vallaise (454m) to Saint Anne's chapel (1342m): 4.3 km and 921 m of ascent through vineyards, chestnut groves and woodland on the Avise hillside.",
    shortDescription_fr: "Du fond de vallée de Chateau Vallaise (454m) à la chapelle Sainte-Anne (1342m) : 4,3 km et 921 m de dénivelé entre vignes, châtaigneraies et forêts du versant d'Avise.",
    shortDescription_de: "Vom Talboden bei Chateau Vallaise (454m) zur Kapelle der Heiligen Anna (1342m): 4,3 km und 921 Hm durch Weinberge, Kastanienwälder und Wald am Avise-Hang.",
    updated_at: "2026-06-01"
  },
  "06-s16": {
    description_it: "Il sentiero collega Avise, piccolo comune con castello medievale all'imbocco della Valgrisenche, alla frazione di Cerellaz nel comune di La Salle, risalendo il versante soleggiato della Valdigne via la borgata di Ravoire. Il percorso di 3 km guadagna 479 metri di dislivello in un ambiente che fonde paesaggio agrario storico e montagna: vigneti terrazzati nella fascia bassa, boschi misti di roverelle e castagni nel tratto intermedio, prati aperti verso Cerellaz. La Valdigne è la sezione più alta della Valle d'Aosta, con il massiccio del Monte Bianco che si profila a nord; da questa quota le vedute cominciano ad ampliarsi verso la grande conca. Il percorso è anche parte della Via Alpina, il grande itinerario transeuropeo. Difficoltà E, aperto da aprile a ottobre.",
    description_en: "The trail links Avise, a small commune with a medieval castle at the entrance to the Valgrisenche, to the hamlet of Cerellaz in the La Salle municipality, climbing the sunny Valdigne hillside via the hamlet of Ravoire. The 3 km route gains 479 metres through a landscape that blends historic agrarian scenery with mountain terrain: terraced vineyards in the lower section, mixed downy oak and chestnut woodland in the middle, open meadows near Cerellaz. The Valdigne is the uppermost section of the Aosta Valley, with the Mont Blanc massif rising to the north. This section is also part of the Via Alpina trans-European route. Difficulty E, open April to October.",
    description_fr: "Le sentier relie Avise, petite commune avec un château médiéval à l'entrée de la Valgrisenche, au hameau de Cerellaz dans la commune de La Salle, en remontant le versant ensoleillé de la Valdigne par le hameau de Ravoire. Le parcours de 3 km gagne 479 mètres de dénivelé dans un paysage mêlant terroir historique et montagne : vignes en terrasses en bas, forêts mixtes au milieu, prairies ouvertes vers Cerellaz. La Valdigne est la partie la plus haute de la Vallée d'Aoste. Ce tronçon fait partie de la Via Alpina. Difficulté E, accessible d'avril à octobre.",
    description_de: "Der Weg verbindet Avise, eine kleine Gemeinde mit mittelalterlicher Burg am Eingang zum Valgrisenche, mit dem Weiler Cerellaz in der Gemeinde La Salle und steigt den sonnigen Valdigne-Hang über den Weiler Ravoire hinauf. Die 3 km lange Route überwindet 479 Höhenmeter durch eine Landschaft aus terrassierten Weinbergen unten, gemischtem Wald in der Mitte und offenen Wiesen nahe Cerellaz. Die Valdigne ist der oberste Abschnitt des Aostatals. Dieser Abschnitt ist auch Teil der Via Alpina. Schwierigkeit E, von April bis Oktober.",
    shortDescription_it: "Da Avise a Cerellaz via Ravoire sul versante soleggiato della Valdigne: 3 km e 479 m di dislivello tra vigneti, boschi e prati. Tratto della Via Alpina.",
    shortDescription_en: "From Avise to Cerellaz via Ravoire on the sunny Valdigne hillside: 3 km and 479 m through vineyards, woodland and meadows. Part of the Via Alpina.",
    shortDescription_fr: "D'Avise à Cerellaz via Ravoire sur le versant ensoleillé de la Valdigne : 3 km et 479 m entre vignes, forêts et prairies. Tronçon de la Via Alpina.",
    shortDescription_de: "Von Avise nach Cerellaz über Ravoire am sonnigen Valdigne-Hang: 3 km und 479 Hm durch Weinberge, Wald und Wiesen. Teil der Via Alpina.",
    updated_at: "2026-06-01"
  },
  "06-s4": {
    description_it: "La traversata da Vedun a Jovençan percorre la fascia di mezza quota della Valdigne, nel comune di La Salle, tra i 1519 e i 1868 metri. Il percorso di 6 km con 342 metri di dislivello si sviluppa su terreno aperto, con il versante rivolto verso la piana di Aosta e il massiccio del Monte Bianco che si staglia a nord. L'ambiente è quello tipico degli alpeggi storici della Valdigne: pascoli di quota media, radure erbose, qualche tratto di bosco di conifere che offre ombra nelle ore più calde. Jovençan, la meta, è un alpeggio a 1868 metri da cui si diramano ulteriori percorsi verso il Col de Vertosan e le quote superiori. La camminata è adatta a escursionisti con buona preparazione fisica, con dislivello moderato e progressione regolare. Consigliato da giugno a settembre.",
    description_en: "The traverse from Vedun to Jovençan crosses the mid-elevation belt of the Valdigne in the municipality of La Salle, between 1519 and 1868 metres. The 6 km route with 342 metres of ascent develops over open terrain, with the slope facing the Aosta plain and the Mont Blanc massif rising to the north. The environment is that of the Valdigne's historic summer pastures: mid-altitude grasslands, grassy clearings, patches of conifer forest providing shade in the warmer hours. Jovençan at 1868 metres is a departure point for further routes toward the Col de Vertosan and higher terrain. Recommended June to September.",
    description_fr: "La traversée de Vedun à Jovençan parcourt la ceinture de moyenne altitude de la Valdigne, dans la commune de La Salle, entre 1519 et 1868 mètres. Le parcours de 6 km avec 342 mètres de dénivelé se développe sur terrain ouvert, le versant orienté vers la plaine d'Aoste et le massif du Mont-Blanc au nord. L'environnement est celui des alpages historiques de la Valdigne : prairies de moyenne altitude, clairières, quelques tronçons de forêt de conifères. Jovençan à 1868 mètres est un point de départ pour d'autres itinéraires vers le Col de Vertosan. Recommandé de juin à septembre.",
    description_de: "Die Traverse von Vedun nach Jovençan durchquert den Mittelgebirgsgürtel der Valdigne in der Gemeinde La Salle zwischen 1519 und 1868 Metern. Die 6 km lange Route mit 342 Höhenmetern verläuft über offenes Gelände, der Hang blickt zur Aosta-Ebene und das Mont-Blanc-Massiv erhebt sich im Norden. Das Umfeld entspricht den historischen Almen der Valdigne: Mittelhöhenwiesen, Lichtungen, Nadelwaldflecken. Jovençan auf 1868 Metern ist Ausgangspunkt für weitere Wege zum Col de Vertosan. Empfohlen Juni bis September.",
    shortDescription_it: "Traversata in quota da Vedun (1519m) a Jovençan (1868m) nella Valdigne: 6 km tra pascoli storici con il Monte Bianco sullo sfondo.",
    shortDescription_en: "High-level traverse from Vedun (1519m) to Jovençan (1868m) in the Valdigne: 6 km through historic pastures with Mont Blanc as backdrop.",
    shortDescription_fr: "Traversée en altitude de Vedun (1519m) à Jovençan (1868m) en Valdigne : 6 km entre alpages historiques avec le Mont-Blanc en toile de fond.",
    shortDescription_de: "Höhenwanderung von Vedun (1519m) nach Jovençan (1868m) in der Valdigne: 6 km durch historische Almen mit dem Mont Blanc im Hintergrund.",
    updated_at: "2026-06-01"
  },
  "07-s23": {
    description_it: "Dal villaggio di Blanchard (1731 m) il sentiero risale verso il Colle Superiore delle Cime Bianche (2985 m), uno dei valichi più panoramici delle Alpi valdostane, posto sulla dorsale che separa la Val d'Ayas dalla Valtournenche. Con 8,5 km e 1256 m di dislivello positivo, il percorso è lungo e richiede allenamento, ma la classificazione E indica che non presenta difficoltà tecniche. Il tracciato attraversa prima i nuclei rurali sopra Blanchard, poi risale verso il vallone delle Cime Bianche, un ambiente di alta montagna dove la roccia chiara — da cui il nome — e i pascoli d'alta quota dominano il paesaggio. La zona è inclusa nella rete Natura 2000 per il suo valore geologico e naturalistico. Vicino al colle si apre il panorama più ampio: Gran Paradiso, Monte Rosa, Cervino, Monte Bianco. Stagione: luglio–settembre.",
    description_en: "From the village of Blanchard (1731 m) the trail climbs toward the Colle Superiore delle Cime Bianche (2985 m), one of the most panoramic passes in the Valdostan Alps, on the ridge separating Val d'Ayas from Valtournenche. At 8.5 km and 1256 m of elevation gain, the route is long and demands fitness, though the E rating indicates no technical difficulty. The path passes through hamlets above Blanchard, then climbs into the Cime Bianche valley, a high-mountain environment where pale rock — giving the area its name — and high-altitude pastures dominate. The area is a Natura 2000 site. Near the pass, the panorama opens across Gran Paradiso, Monte Rosa, Matterhorn and Mont Blanc. Season: July–September.",
    description_fr: "Depuis le village de Blanchard (1731 m), le sentier monte vers le Colle Superiore delle Cime Bianche (2985 m), l'un des cols les plus panoramiques des Alpes valdôtaines, sur la crête séparant la Val d'Ayas de la Valtournenche. Avec 8,5 km et 1256 m de dénivelé positif, l'itinéraire est long et exige une bonne condition physique. Le tracé traverse les hameaux au-dessus de Blanchard, puis monte dans le vallée des Cime Bianche. La zone est un site Natura 2000. Près du col, le panorama embrasse le Grand Paradis, le Mont Rose, le Cervin et le Mont-Blanc. Saison : juillet–septembre.",
    description_de: "Vom Dorf Blanchard (1731 m) steigt der Weg zum Colle Superiore delle Cime Bianche (2985 m) hinauf, einem der panoramareichsten Pässe der Valdostaner Alpen auf dem Grat zwischen Val d'Ayas und Valtournenche. Mit 8,5 km und 1256 Höhenmetern ist der Weg lang und konditionell fordernd, aber ohne technische Schwierigkeit (E). Der Pfad durchquert Weiler oberhalb von Blanchard, steigt dann in das Cime-Bianche-Tal. Das Gebiet ist Natura-2000-Schutzgebiet. Am Pass öffnet sich der Blick auf Gran Paradiso, Monte Rosa, Matterhorn und Mont Blanc. Saison: Juli–September.",
    shortDescription_it: "Da Blanchard (1731m) al Colle Superiore Cime Bianche (2985m): 8,5 km E con panorama su Gran Paradiso, Rosa, Cervino e Bianco. Zona Natura 2000 tra Val d'Ayas e Valtournenche.",
    shortDescription_en: "From Blanchard (1731m) to Colle Superiore Cime Bianche (2985m): 8.5 km E with panorama over Gran Paradiso, Rosa, Matterhorn and Mont Blanc. Natura 2000 area between Val d'Ayas and Valtournenche.",
    shortDescription_fr: "De Blanchard (1731m) au Colle Superiore Cime Bianche (2985m) : 8,5 km E avec panorama sur Grand Paradis, Rose, Cervin et Mont-Blanc. Site Natura 2000.",
    shortDescription_de: "Von Blanchard (1731m) zum Colle Superiore Cime Bianche (2985m): 8,5 km E mit Panorama auf Gran Paradiso, Monte Rosa, Matterhorn und Mont Blanc. Natura-2000-Gebiet.",
    warnings_it: ["Sopra i 2500 m la neve può persistere fino a luglio inoltrato.", "Partire presto per evitare temporali pomeridiani estivi."],
    warnings_en: ["Above 2500 m snow may persist until late July.", "Start early to avoid summer afternoon thunderstorms."],
    warnings_fr: ["Au-dessus de 2500 m la neige peut persister jusqu'à fin juillet.", "Partir tôt pour éviter les orages d'après-midi estivaux."],
    warnings_de: ["Über 2500 m kann Schnee bis in den Hochsommer bestehen.", "Früh aufbrechen um sommerliche Nachmittagsgewitter zu vermeiden."],
    updated_at: "2026-06-01"
  },
  "07-s41": {
    description_it: "La salita da Champoluc alla Testa Grigia è l'itinerario escursionistico più ambizioso della Val d'Ayas: 8,2 km e 1814 m di dislivello conducono dai 1569 m del capoluogo fino ai 3315 m di quota, al confine glaciale tra il versante italiano e quello svizzero. La classificazione EEA — escursionisti esperti con attrezzatura — segnala che nella sezione finale è necessario saper muoversi su terreno glaciale o semi-glaciale: ramponi o ramponcini leggeri possono essere necessari, a seconda della stagione. Il percorso risale lungo il Vallone del Pinter sull'Alta Via n°1, con l'ambiente che si trasforma progressivamente dai larici della quota bassa alle rocce e al ghiaccio dell'alta montagna. Il panorama dalla Testa Grigia abbraccia tutti i quattromila del Monte Rosa — Dufour, Gnifetti, Castore, Liskamm, Breithorn — e il Cervino in primo piano. Solo luglio–settembre; partenza molto mattutina indispensabile.",
    description_en: "The ascent from Champoluc to Testa Grigia is the most ambitious hiking itinerary in the Val d'Ayas: 8.2 km and 1814 m of elevation gain lead from 1569 m in the village to 3315 m at the glacial boundary between the Italian and Swiss flanks. The EEA classification — experienced hikers with equipment — indicates that the final section requires ability on glacial or semi-glacial terrain: crampons or microspikes may be needed depending on season. The route follows the Pinter valley on the Alta Via no. 1, with the environment progressively changing from larch woodland to rock and ice. The summit panorama takes in all the Monte Rosa four-thousanders and the Matterhorn in the foreground. July–September only; a very early start is essential.",
    description_fr: "La montée de Champoluc à la Testa Grigia est l'itinéraire de randonnée le plus ambitieux de la Val d'Ayas : 8,2 km et 1814 m de dénivelé depuis les 1569 m du bourg jusqu'aux 3315 m de la frontière glaciaire. La classification EEA — randonneurs expérimentés avec équipement — indique que la section finale exige la capacité à évoluer sur terrain glaciaire : crampons ou microspikes peuvent être nécessaires. Le tracé suit le Vallone del Pinter sur la Haute Route n°1. Le panorama sommital embrasse tous les quatre-mille du Mont Rose et le Cervin. Juillet–septembre uniquement ; départ très matinal indispensable.",
    description_de: "Der Aufstieg von Champoluc zur Testa Grigia ist das anspruchsvollste Wanderitinerar des Val d'Ayas: 8,2 km und 1814 Höhenmeter führen von 1569 m im Dorf auf 3315 m an der Gletschergrenze. Die EEA-Einstufung — erfahrene Bergwanderer mit Ausrüstung — zeigt an, dass im letzten Abschnitt Erfahrung auf Gletschergelände erforderlich ist. Die Route folgt dem Vallone del Pinter auf der Alta Via Nr. 1. Das Gipfelpanorama umfasst alle Viertausender des Monte Rosa und das Matterhorn. Nur Juli–September; sehr früher Start unbedingt erforderlich.",
    shortDescription_it: "Da Champoluc (1569m) alla Testa Grigia (3315m): 8,2 km EEA — il tetto della Val d'Ayas a piedi, panorama completo su tutti i 4000 del Rosa e sul Cervino.",
    shortDescription_en: "From Champoluc (1569m) to Testa Grigia (3315m): 8.2 km EEA — the Val d'Ayas summit on foot, full panorama over all Monte Rosa four-thousanders and the Matterhorn.",
    shortDescription_fr: "De Champoluc (1569m) à la Testa Grigia (3315m) : 8,2 km EEA — le toit de la Val d'Ayas à pied, panorama complet sur les quatre-mille du Rosa et le Cervin.",
    shortDescription_de: "Von Champoluc (1569m) zur Testa Grigia (3315m): 8,2 km EEA — das Dach des Val d'Ayas zu Fuß, vollständiges Panorama auf alle Rosa-Viertausender und das Matterhorn.",
    warnings_it: ["EEA: richiede attrezzatura glaciale nella sezione finale (ramponi/piccozza a seconda della stagione).", "Partenza prima dell'alba necessaria per rientrare prima dei temporali pomeridiani.", "Solo luglio–settembre. Neve persistente fuori stagione."],
    warnings_en: ["EEA: glacial equipment required in the final section (crampons/ice axe depending on season).", "Pre-dawn start needed to return before afternoon thunderstorms.", "July–September only. Persistent snow outside season."],
    warnings_fr: ["EEA : équipement glaciaire requis dans la section finale (crampons/piolet selon la saison).", "Départ avant l'aube nécessaire pour rentrer avant les orages de l'après-midi.", "Juillet–septembre uniquement. Neige persistante hors saison."],
    warnings_de: ["EEA: Gletscherausrüstung im letzten Abschnitt erforderlich (Steigeisen/Eispickel je nach Saison).", "Start vor der Morgendämmerung nötig um vor Nachmittagsgewittern zurückzukehren.", "Nur Juli–September. Außerhalb der Saison anhaltender Schnee."],
    updated_at: "2026-06-01"
  },
  "07-s64": {
    description_it: "Dal villaggio di Blanchard (1731 m) il sentiero risale la Val d'Ayas verso il Rifugio Mezzalama (3009 m), uno dei rifugi storici dell'alpinismo valdostano, posto ai piedi del ghiacciaio del Castore. Con 7,5 km e 1282 m di dislivello, il percorso E porta l'escursionista oltre la soglia dei 3000 metri attraverso un paesaggio che si fa progressivamente più austero: dai pascoli alti di Blanchard si supera il limite della vegetazione, poi si entra nel dominio della roccia e del ghiaccio. Il Rifugio Mezzalama, aperto in estate, è un punto di sosta fondamentale per gli alpinisti in traversata sul Rosa e per chi sale verso la Testa Grigia. La discesa ripercorre la via di salita. Stagione ristretta: luglio–settembre. Vicino all'arrivo il terreno può essere glaciale.",
    description_en: "From the village of Blanchard (1731 m) the trail climbs the Val d'Ayas toward the Rifugio Mezzalama (3009 m), one of the Aosta Valley's historic mountaineering huts, set at the foot of the Castore glacier. At 7.5 km and 1282 m of elevation gain, the E route takes hikers above 3000 metres through a progressively more austere landscape: from the high pastures of Blanchard, the treeline is crossed and the realm of rock and ice begins. The Rifugio Mezzalama, open in summer, is a key staging point for alpinists crossing the Rosa and for those ascending toward Testa Grigia. Descent retraces the ascent. Short season: July–September. Near the destination, terrain may be glacial.",
    description_fr: "Depuis le village de Blanchard (1731 m), le sentier remonte la Val d'Ayas vers le Rifugio Mezzalama (3009 m), l'un des refuges historiques de l'alpinisme valdôtain, au pied du glacier du Castore. Sur 7,5 km et 1282 m de dénivelé, le parcours E amène le randonneur au-delà de 3000 mètres. Le paysage devient progressivement plus austère : des alpages de Blanchard, on dépasse la limite des arbres pour entrer dans le domaine du rocher et de la glace. Le Rifugio Mezzalama est ouvert en été. Saison courte : juillet–septembre. Près de l'arrivée, le terrain peut être glaciaire.",
    description_de: "Vom Dorf Blanchard (1731 m) steigt der Weg das Val d'Ayas zur Rifugio Mezzalama (3009 m) hinauf, einer der historischen Alpinhütten des Aostatals, am Fuß des Castore-Gletschers. Auf 7,5 km und 1282 Höhenmetern bringt der E-Weg Wanderer über 3000 Meter. Die Landschaft wird zunehmend karger: Von den Hochweiden Blanchards überquert man die Baumgrenze und betritt das Reich aus Fels und Eis. Die Rifugio Mezzalama ist im Sommer geöffnet. Kurze Saison: Juli–September. Nahe dem Ziel kann Gletschergelände auftreten.",
    shortDescription_it: "Da Blanchard (1731m) al Rifugio Mezzalama (3009m): 7,5 km E fino al ghiacciaio del Castore. Hut storico dell'alpinismo valdostano in alta Val d'Ayas.",
    shortDescription_en: "From Blanchard (1731m) to Rifugio Mezzalama (3009m): 7.5 km E to the Castore glacier. Historic mountaineering hut in the upper Val d'Ayas.",
    shortDescription_fr: "De Blanchard (1731m) au Rifugio Mezzalama (3009m) : 7,5 km E jusqu'au glacier du Castore. Refuge historique de l'alpinisme valdôtain.",
    shortDescription_de: "Von Blanchard (1731m) zur Rifugio Mezzalama (3009m): 7,5 km E bis zum Castore-Gletscher. Historische Alpinhütte im oberen Val d'Ayas.",
    warnings_it: ["Vicino al rifugio il terreno può essere glaciale: valutare le condizioni prima di partire.", "Solo luglio–settembre. Fuori stagione neve abbondante."],
    warnings_en: ["Near the hut terrain may be glacial: check conditions before departure.", "July–September only. Heavy snow outside season."],
    warnings_fr: ["Près du refuge le terrain peut être glaciaire : vérifier les conditions avant le départ.", "Juillet–septembre uniquement. Neige abondante hors saison."],
    warnings_de: ["Nahe der Hütte kann Gletschergelände auftreten: Bedingungen vor der Abfahrt prüfen.", "Nur Juli–September. Reichlich Schnee außerhalb der Saison."],
    updated_at: "2026-06-01"
  },
  "08-s23": {
    description_it: "Il sentiero collega il Bivacco Gontier (2266 m), punto di sosta nell'alta Val di Cogne, al casotto del Parco Nazionale Gran Paradiso ad Arpissonnet (1996 m), con una discesa di 3,5 km e 271 metri di dislivello negativo. Si tratta di un percorso di collegamento all'interno del PNGP, classificato E, percorribile da luglio ad agosto quando le quote oltre i 2000 m sono libere dalla neve. L'ambiente è quello dell'alta montagna del Gran Paradiso: pascoli aperti, rocce, la possibilità di avvistare stambecchi e camosci tipici del parco. Il casotto di Arpissonnet è un punto di appoggio gestito dal PNGP. Ideale come tratto di raccordo in un'escursione più lunga che parte dai fondovalle del Val di Cogne.",
    description_en: "The trail links Bivacco Gontier (2266 m), a rest point in the upper Val di Cogne, to the Gran Paradiso National Park shelter at Arpissonnet (1996 m), descending 3.5 km with 271 metres of elevation loss. It is a connecting path within the PNGP, rated E, open July–August when elevations above 2000 m are snow-free. The environment is that of the Gran Paradiso high mountain: open pastures, rock, with opportunities to spot the ibex and chamois typical of the park. The Arpissonnet shelter is managed by the PNGP. Ideal as a link trail in a longer excursion from the lower Val di Cogne.",
    description_fr: "Le sentier relie le Bivacco Gontier (2266 m), point de repos dans la haute Val di Cogne, au casot du Parc National du Grand Paradis à Arpissonnet (1996 m), avec une descente de 3,5 km et 271 mètres de dénivelé négatif. C'est un sentier de liaison à l'intérieur du PNGP, côté E, praticable de juillet à août. L'environnement est celui de la haute montagne du Grand Paradis : pâturages ouverts, roches, avec la possibilité d'observer bouquetins et chamois. Idéal comme tronçon de liaison dans une excursion plus longue.",
    description_de: "Der Weg verbindet das Bivacco Gontier (2266 m), ein Rastpunkt im oberen Val di Cogne, mit der Schutzhütte des Gran-Paradiso-Nationalparks in Arpissonnet (1996 m) — ein Abstieg von 3,5 km mit 271 Höhenmetern Verlust. Es handelt sich um einen Verbindungsweg im PNGP, Bewertung E, von Juli bis August begehbar. Das Umfeld ist das der Gran-Paradiso-Hochgebirge mit offenen Weiden, Fels und Möglichkeiten, die parktypischen Steinböcke und Gämsen zu beobachten.",
    shortDescription_it: "Discesa di 3,5 km dal Bivacco Gontier (2266m) ad Arpissonnet PNGP (1996m): percorso di raccordo nel Parco Nazionale Gran Paradiso, luglio–agosto.",
    shortDescription_en: "3.5 km descent from Bivacco Gontier (2266m) to Arpissonnet PNGP shelter (1996m): connector trail in Gran Paradiso National Park, July–August.",
    shortDescription_fr: "Descente de 3,5 km du Bivacco Gontier (2266m) au casot PNGP d'Arpissonnet (1996m) : sentier de liaison dans le Parc National du Grand Paradis.",
    shortDescription_de: "3,5 km Abstieg vom Bivacco Gontier (2266m) zum PNGP-Schutzhaus Arpissonnet (1996m): Verbindungsweg im Gran-Paradiso-Nationalpark, Juli–August.",
    updated_at: "2026-06-01"
  },
  "10-s18": {
    description_it: "Dal Rifugio Prarayer (2002 m), punto di riferimento dell'alta Valpelline, il sentiero risale il Vallone di Valcorneraz fino al Colle di Valcorneraz (3086 m), antico valico di transito tra la Valpelline e la Valtournenche. Con 5,8 km e 1127 m di dislivello, la difficoltà EE riflette un ambiente di alta montagna dove il terreno si fa più ripido e irregolare avvicinandosi al colle. Il percorso attraversa prima il pianoro del fondovalle glaciale, poi entra nella comba orientale con pareti rocciose, morene e pascoli d'alta quota progressivamente più esigenti. Il colle, a quasi 3100 m, è un punto panoramico aperto sui versanti italiani e svizzeri. La Valpelline è una delle valli più selvagge e meno frequentate della Valle d'Aosta. Stagione: luglio–settembre.",
    description_en: "From Rifugio Prarayer (2002 m), the reference point of the upper Valpelline, the trail climbs the Valcorneraz valley to the Col di Valcorneraz (3086 m), an ancient transit pass between the Valpelline and the Valtournenche. At 5.8 km and 1127 m of elevation gain, the EE rating reflects a high-mountain environment where the terrain becomes steeper and more irregular approaching the pass. The route first crosses the glacial valley floor plateau, then enters the eastern comba with rock walls, moraines and increasingly demanding high-altitude pastures. The pass, at nearly 3100 m, offers open views across the Italian and Swiss flanks. Season: July–September.",
    description_fr: "Depuis le Rifugio Prarayer (2002 m), point de référence du haut Valpelline, le sentier remonte le Vallon de Valcorneraz jusqu'au Col de Valcorneraz (3086 m), ancien col de transit entre la Valpelline et la Valtournenche. Avec 5,8 km et 1127 m de dénivelé, la difficulté EE reflète un environnement de haute montagne avec terrain instable. La Valpelline est l'une des vallées les plus sauvages et peu fréquentées de la Vallée d'Aoste. Saison : juillet–septembre.",
    description_de: "Vom Rifugio Prarayer (2002 m), dem Stützpunkt des oberen Valpelline, steigt der Weg das Valcorneraz-Tal zum Col di Valcorneraz (3086 m) hinauf, einem alten Übergangspass zwischen Valpelline und Valtournenche. Mit 5,8 km und 1127 Höhenmetern zeigt die EE-Bewertung ein Hochgebirgsumfeld mit zunehmend steilem und unregelmäßigem Gelände. Das Valpelline ist eines der wildesten und am wenigsten besuchten Täler des Aostatals. Saison: Juli–September.",
    shortDescription_it: "Dal Rifugio Prarayer (2002m) al Colle di Valcorneraz (3086m): 5,8 km EE — antico valico tra Valpelline e Valtournenche in alta montagna.",
    shortDescription_en: "From Rifugio Prarayer (2002m) to Col di Valcorneraz (3086m): 5.8 km EE — ancient pass between Valpelline and Valtournenche in high-mountain terrain.",
    shortDescription_fr: "Du Rifugio Prarayer (2002m) au Col de Valcorneraz (3086m) : 5,8 km EE — ancien col de transit entre Valpelline et Valtournenche.",
    shortDescription_de: "Vom Rifugio Prarayer (2002m) zum Col di Valcorneraz (3086m): 5,8 km EE — alter Übergangspass zwischen Valpelline und Valtournenche.",
    warnings_it: ["EE: ambiente di alta montagna, terreno impervio. Esperienza necessaria.", "Neve residua al colle fino a luglio inoltrato."],
    warnings_en: ["EE: high-mountain environment, difficult terrain. Experience required.", "Residual snow at the pass until late July."],
    warnings_fr: ["EE : environnement de haute montagne, terrain difficile. Expérience nécessaire.", "Neige résiduelle au col jusqu'à fin juillet."],
    warnings_de: ["EE: Hochgebirge, schwieriges Gelände. Erfahrung erforderlich.", "Restschnee am Pass bis Ende Juli."],
    updated_at: "2026-06-01"
  },
  "10-s8": {
    description_it: "Dalla diga di Place Moulin (2011 m), che sbarra il fondovalle della Valpelline trattenendo un lago artificiale dalle acque turchesi, il sentiero sale verso il Lac Mort (2865 m) in 4,9 km con 877 m di dislivello. Il nome del lago — letteralmente 'lago morto' — evoca la severità di questo ambiente glaciale: siamo in testata di vallata, con le creste che separano Italia e Svizzera a portata di sguardo. Il percorso prima costeggia il bacino artificiale, poi si inerpica su terreno sempre più aperto e rupestre verso il circo glaciale sovrastante. La stagione è breve — luglio–settembre — per via della quota elevata e del ritardo con cui la neve si scioglie. Un itinerario per escursionisti esperti di alta montagna che cercano paesaggi di rara intensità.",
    description_en: "From the Place Moulin dam (2011 m), which closes the Valpelline valley floor and impounds a reservoir of turquoise water, the trail climbs to Lac Mort (2865 m) over 4.9 km and 877 m of elevation gain. The lake's name — literally 'dead lake' — evokes the severity of this glacial environment at the valley head, with the ridgelines separating Italy and Switzerland overhead. The route first traces the reservoir shore, then climbs onto increasingly open and rocky terrain toward the glacial cirque. The season is short — July–September — due to the elevation and late snowmelt. A route for experienced high-mountain hikers seeking landscapes of rare intensity.",
    description_fr: "Depuis le barrage de Place Moulin (2011 m), qui ferme le fond de la Valpelline et retient un lac artificiel aux eaux turquoise, le sentier monte vers le Lac Mort (2865 m) sur 4,9 km et 877 m de dénivelé. Le nom du lac — littéralement 'lac mort' — évoque la sévérité de cet environnement glaciaire en tête de vallée. Le parcours longe d'abord le réservoir, puis grimpe vers le cirque glaciaire. Saison courte : juillet–septembre. Un itinéraire pour randonneurs expérimentés cherchant des paysages d'une rare intensité.",
    description_de: "Von der Staumauer Place Moulin (2011 m), die den Valpelline-Talboden absperrt und einen Stausee mit türkisfarbenem Wasser aufstaut, steigt der Weg zum Lac Mort (2865 m) auf 4,9 km und 877 Höhenmeter. Der Name des Sees — wörtlich 'toter See' — evoziert die Strenge dieser Gletscherumgebung am Talschluss. Die Route folgt zunächst dem Seeufer, steigt dann zu immer offenerem und felsigerem Gelände auf. Kurze Saison: Juli–September. Ein Weg für erfahrene Hochgebirgswanderer.",
    shortDescription_it: "Dalla diga di Place Moulin (2011m) al Lac Mort (2865m): 4,9 km in alta Valpelline verso un lago glaciale dalla severità alpina. Solo luglio–settembre.",
    shortDescription_en: "From Place Moulin dam (2011m) to Lac Mort (2865m): 4.9 km in the upper Valpelline toward a glacial lake of stark alpine character. July–September only.",
    shortDescription_fr: "Du barrage de Place Moulin (2011m) au Lac Mort (2865m) : 4,9 km dans la haute Valpelline vers un lac glaciaire d'une sévérité alpine rare. Juillet–septembre uniquement.",
    shortDescription_de: "Von der Staumauer Place Moulin (2011m) zum Lac Mort (2865m): 4,9 km im oberen Valpelline zu einem Gletschersee von karger alpiner Intensität. Nur Juli–September.",
    warnings_it: ["Breve stagione (luglio–settembre): presenza di neve fuori stagione.", "Terreno aperto in quota: prestare attenzione ai temporali."],
    warnings_en: ["Short season (July–September): snow outside the window.", "Open terrain at altitude: beware of thunderstorms."],
    warnings_fr: ["Saison courte (juillet–septembre) : neige hors saison.", "Terrain ouvert en altitude : attention aux orages."],
    warnings_de: ["Kurze Saison (Juli–September): Schnee außerhalb der Saison.", "Offenes Gelände in der Höhe: Gewitter beachten."],
    updated_at: "2026-06-01"
  },
  "12-s13": {
    description_it: "L'accesso classico al Rifugio Arp parte da Estoul (1884 m), piccola borgata di Brusson con architettura walser ben conservata nell'alta Val d'Ayas. In 6,3 km e 614 m di dislivello, il sentiero Turistico — la classificazione più bassa della scala CAI — porta all'alpeggio del Rifugio Arp (2425 m) su terreno aperto, con vedute sempre più ampie sulla val d'Ayas e sulle cime che la chiudono. La difficoltà contenuta e la quota di partenza già elevata rendono questo percorso accessibile a quasi tutti, compresi i meno allenati. Il Rifugio Arp è un punto di partenza per escursioni più impegnative verso i crinali che separano la Val d'Ayas dalla Valtournenche. Stagione: giugno–settembre.",
    description_en: "The classic approach to Rifugio Arp departs from Estoul (1884 m), a small Brusson hamlet with well-preserved Walser architecture in the upper Val d'Ayas. Over 6.3 km and 614 m of elevation gain, the Tourist-rated trail — the lowest category on the CAI scale — reaches the Rifugio Arp alp (2425 m) across open terrain, with ever-widening views over the Val d'Ayas and its surrounding peaks. The modest difficulty and already high starting elevation make this route accessible to almost everyone. The Rifugio Arp serves as a base for more demanding excursions onto the ridges dividing Val d'Ayas from Valtournenche. Season: June–September.",
    description_fr: "L'accès classique au Rifugio Arp part d'Estoul (1884 m), petit hameau de Brusson avec une architecture walser bien conservée dans la haute Val d'Ayas. Sur 6,3 km et 614 m de dénivelé, le sentier Touristique — la catégorie la plus basse de l'échelle CAI — atteint l'alpage du Rifugio Arp (2425 m) sur terrain ouvert, avec des vues s'élargissant sur la Val d'Ayas. La difficulté modérée et l'altitude de départ déjà élevée rendent ce parcours accessible à presque tous. Saison : juin–septembre.",
    description_de: "Der klassische Zugang zur Rifugio Arp beginnt in Estoul (1884 m), einem kleinen Weiler von Brusson mit gut erhaltenem Walser-Kulturerbe im oberen Val d'Ayas. Auf 6,3 km und 614 Höhenmetern bringt der Touristische Weg — die niedrigste CAI-Kategorie — den Wanderer zur Alp Rifugio Arp (2425 m) über offenes Gelände mit sich weitenden Ausblicken. Die geringe Schwierigkeit und die schon hohe Ausgangshöhe machen diesen Weg für fast jeden zugänglich. Saison: Juni–September.",
    shortDescription_it: "Da Estoul (1884m) al Rifugio Arp (2425m): 6,3 km Turistici su pascoli aperti dell'alta Val d'Ayas. Adatto a tutti, base per escursioni più impegnative.",
    shortDescription_en: "From Estoul (1884m) to Rifugio Arp (2425m): 6.3 km Tourist-rated across open upper Val d'Ayas pastures. Suitable for all, base for more demanding excursions.",
    shortDescription_fr: "D'Estoul (1884m) au Rifugio Arp (2425m) : 6,3 km Touristiques sur les alpages ouverts de la haute Val d'Ayas. Accessible à tous.",
    shortDescription_de: "Von Estoul (1884m) zur Rifugio Arp (2425m): 6,3 km Touristisch über offene Hochweiden des Val d'Ayas. Für alle geeignet.",
    updated_at: "2026-06-01"
  },
  "12-s8": {
    description_it: "Da Pont de Messuere (1425 m) il sentiero risale verso il Corno Boussolaz (3023 m) via il Lago Bringuez, guadagnando 1593 m in 6,4 km: uno dei dislivelli più sostenuti tra i sentieri EE del Catasto valdostano. Il Lago Bringuez, a quota intermedia, è un lago glaciale che segna il passaggio dalla fascia di media montagna verso l'alta quota. Il Corno Boussolaz, cima oltre i 3000 m, offre un panorama di ampio raggio sul sistema alpino tra la Val d'Ayas e le creste svizzere. La classificazione EE riflette il terreno impervio della sezione alta e la quota raggiunta; la partenza a quota relativamente bassa rende il dislivello reale ancora più significativo. Stagione: giugno–settembre; condizioni stabili indispensabili.",
    description_en: "From Pont de Messuere (1425 m) the trail climbs toward the Corno Boussolaz (3023 m) via Lago Bringuez, gaining 1593 m over 6.4 km — one of the most sustained gradients among EE-rated trails in the Aosta Valley registry. Lago Bringuez at intermediate altitude is a glacial lake marking the transition from mid-mountain to high-alpine terrain. The Corno Boussolaz, a summit above 3000 m, offers a wide panorama across the alpine system between Val d'Ayas and the Swiss ridges. Season: June–September; stable conditions essential.",
    description_fr: "Depuis Pont de Messuere (1425 m) le sentier monte vers le Corno Boussolaz (3023 m) via le Lago Bringuez, gagnant 1593 m sur 6,4 km — l'un des dénivelés les plus soutenus parmi les sentiers EE du cadastre valdôtain. Le Lago Bringuez est un lac glaciaire marquant la transition vers la haute altitude. Le Corno Boussolaz offre un large panorama sur le système alpin entre Val d'Ayas et les crêtes suisses. Saison : juin–septembre.",
    description_de: "Von Pont de Messuere (1425 m) steigt der Weg zum Corno Boussolaz (3023 m) über den Lago Bringuez mit 1593 Höhenmetern auf 6,4 km — einer der steilsten EE-Wege im Aostatal-Kataster. Der Lago Bringuez markiert den Übergang zur Hochalpenzone. Der Corno Boussolaz bietet ein weites Panorama über das Alpensystem zwischen Val d'Ayas und den Schweizer Kämmen. Saison: Juni–September.",
    shortDescription_it: "Da Pont de Messuere (1425m) al Corno Boussolaz (3023m) via Lago Bringuez: 6,4 km EE con 1593 m di dislivello, uno dei più impegnativi della Val d'Ayas.",
    shortDescription_en: "From Pont de Messuere (1425m) to Corno Boussolaz (3023m) via Lago Bringuez: 6.4 km EE with 1593 m of ascent, one of Val d'Ayas's most demanding routes.",
    shortDescription_fr: "De Pont de Messuere (1425m) au Corno Boussolaz (3023m) via Lago Bringuez : 6,4 km EE avec 1593 m de dénivelé.",
    shortDescription_de: "Von Pont de Messuere (1425m) zum Corno Boussolaz (3023m) über Lago Bringuez: 6,4 km EE mit 1593 Höhenmetern.",
    warnings_it: ["EE: dislivello eccezionale, terreno impervio nella sezione alta.", "Neve residua al lago e alla cima fino a fine giugno."],
    warnings_en: ["EE: exceptional elevation gain, difficult terrain in upper section.", "Residual snow at lake and summit until late June."],
    warnings_fr: ["EE : dénivelé exceptionnel, terrain difficile dans la section haute.", "Neige résiduelle au lac et au sommet jusqu'à fin juin."],
    warnings_de: ["EE: außergewöhnlicher Höhenunterschied, schwieriges Gelände im oberen Abschnitt.", "Restschnee am See und am Gipfel bis Ende Juni."],
    updated_at: "2026-06-01"
  },
  "13-s7": {
    description_it: "Da Quinçod (1030 m), borgata nel fondovalle di Brusson, il sentiero sale verso Merendiou e poi al Colle Chasten (2549 m), guadagnando 1708 m in 8,6 km — una delle salite più lunghe e impegnative del settore di Brusson. Il percorso attraversa le diverse fasce altitudinali della Val d'Ayas: boschi misti nella parte bassa, pascoli e foreste di larici nella fascia media, praterie aperte e rocce verso il crinale. La classificazione EE riflette il dislivello cumulato, il terreno più irregolare nelle sezioni alte e la quota raggiunta. Il Colle Chasten è un punto panoramico sulle creste che dividono la Val d'Ayas dai versanti opposti. La lunga distanza richiede partenza mattutina e autonomia idrica. Stagione: giugno–settembre.",
    description_en: "From Quinçod (1030 m), a hamlet in the Brusson valley floor, the trail climbs toward Merendiou and then to Colle Chasten (2549 m), gaining 1708 m over 8.6 km — one of the longest and most demanding ascents in the Brusson sector. The route crosses the different altitude bands of the Val d'Ayas: mixed forest in the lower section, pastures and larch forest in the middle band, open grassland and rock toward the ridge. The EE rating reflects the accumulated elevation gain and irregular terrain in the upper sections. Season: June–September; early start required.",
    description_fr: "Depuis Quinçod (1030 m), hameau dans le fond de vallée de Brusson, le sentier monte vers Merendiou puis au Colle Chasten (2549 m), gagnant 1708 m sur 8,6 km — l'une des montées les plus longues et exigeantes du secteur de Brusson. Le parcours traverse les différents étages altitudinaux de la Val d'Ayas. La classification EE reflète le dénivelé cumulé et le terrain irrégulier dans les sections hautes. Saison : juin–septembre ; départ matinal requis.",
    description_de: "Von Quinçod (1030 m), einem Weiler im Brusson-Talboden, steigt der Weg über Merendiou zum Colle Chasten (2549 m) mit 1708 Höhenmetern auf 8,6 km — einer der längsten und anspruchsvollsten Aufstiege im Brusson-Sektor. Die Route durchquert die verschiedenen Höhenstufen des Val d'Ayas. Die EE-Bewertung spiegelt den kumulierten Höhenunterschied und das unregelmäßige Gelände in den oberen Abschnitten wider. Saison: Juni–September; früher Start erforderlich.",
    shortDescription_it: "Da Quinçod (1030m) al Colle Chasten (2549m) via Merendiou: 8,6 km EE con 1708 m di dislivello, traversata completa delle fasce altitudinali della Val d'Ayas.",
    shortDescription_en: "From Quinçod (1030m) to Colle Chasten (2549m) via Merendiou: 8.6 km EE with 1708 m of ascent, crossing all altitude bands of the Val d'Ayas.",
    shortDescription_fr: "De Quinçod (1030m) au Colle Chasten (2549m) via Merendiou : 8,6 km EE avec 1708 m de dénivelé, traversée complète des étages altitudinaux.",
    shortDescription_de: "Von Quinçod (1030m) zum Colle Chasten (2549m) über Merendiou: 8,6 km EE mit 1708 Höhenmetern, vollständige Durchquerung aller Höhenstufen.",
    warnings_it: ["EE: dislivello molto elevato, partenza mattutina obbligatoria. Portare acqua a sufficienza."],
    warnings_en: ["EE: very high elevation gain, early start mandatory. Carry sufficient water."],
    warnings_fr: ["EE : dénivelé très élevé, départ matinal obligatoire. Emporter suffisamment d'eau."],
    warnings_de: ["EE: sehr hoher Höhenunterschied, früher Start obligatorisch. Ausreichend Wasser mitnehmen."],
    updated_at: "2026-06-01"
  },
  "15-s2": {
    description_it: "Il sentiero da Arlier a Cloutraz percorre il versante soleggiato sopra Châtillon, risalendo 3,5 km con 515 m di dislivello da quota 603 m fino a 1067 m. Il basso punto di partenza, nella fascia termofila della Valle Centrale, permette una stagione lunga: vigneti, noci e vegetazione mediterranea caratterizzano l'inizio del percorso, mentre salendo il bosco di latifoglie prende il sopravvento e il panorama si apre sulla fondovalle della Dora Baltea. Châtillon è la porta d'accesso alla Valtournenche; questo versante ne offre una prospettiva inusuale, lontana dai flussi turistici. Difficoltà E, percorribile da aprile a ottobre.",
    description_en: "The trail from Arlier to Cloutraz climbs the sunny hillside above Châtillon, covering 3.5 km and 515 metres from 603 m to 1067 m. The low starting point in the thermophilic belt of the central valley allows a long season: vineyards, walnut trees and Mediterranean vegetation characterise the beginning, while ascending broadleaf woodland takes over and the panorama opens across the Dora Baltea valley floor. Châtillon is the gateway to the Valtournenche; this hillside offers an unusual perspective far from tourist flows. Difficulty E, April to October.",
    description_fr: "Le sentier d'Arlier à Cloutraz parcourt le versant ensoleillé au-dessus de Châtillon, montant 3,5 km avec 515 m de dénivelé de 603 à 1067 m. Le faible point de départ dans la ceinture thermophile de la vallée centrale permet une longue saison : vignes, noyers et végétation méditerranéenne caractérisent le début, puis la forêt feuillue prend le dessus et le panorama s'ouvre sur la Doire Baltée. Difficulté E, d'avril à octobre.",
    description_de: "Der Weg von Arlier nach Cloutraz erklimmt den sonnigen Hang oberhalb von Châtillon auf 3,5 km mit 515 Höhenmetern von 603 auf 1067 m. Der niedrige Ausgangspunkt in der thermophilen Zone des Zentraltals ermöglicht eine lange Saison: Weinberge, Walnussbäume und mediterrane Vegetation prägen den Beginn, bevor Laubwald die Oberhand gewinnt und das Panorama sich über die Dora-Baltea-Ebene öffnet. Schwierigkeit E, April bis Oktober.",
    shortDescription_it: "Da Arlier (603m) a Cloutraz (1067m) sul versante di Châtillon: 3,5 km E tra vigneti, boschi e panorami sulla Dora Baltea.",
    shortDescription_en: "From Arlier (603m) to Cloutraz (1067m) on the Châtillon hillside: 3.5 km E through vineyards, woodland and views over the Dora Baltea.",
    shortDescription_fr: "D'Arlier (603m) à Cloutraz (1067m) sur le versant de Châtillon : 3,5 km E entre vignes, forêts et panoramas sur la Doire Baltée.",
    shortDescription_de: "Von Arlier (603m) nach Cloutraz (1067m) am Châtillon-Hang: 3,5 km E durch Weinberge, Wald und Ausblicke auf die Dora Baltea.",
    updated_at: "2026-06-01"
  },
  "16-s6": {
    description_it: "Da Lod (2017 m) il sentiero sale in modo diretto al Pointe de Falinière (2763 m), disegnando in 3,7 km e 740 m di dislivello una delle salite più rapide dell'area di Champdepraz. La quota di partenza già elevata colloca subito l'escursionista in ambiente alpino aperto, senza la lunga fase boschiva tipica delle partenze da fondovalle. Il percorso EE si sviluppa su terreno via via più instabile e rupestre avvicinandosi alla vetta, con tratti che richiedono sicurezza sul passo. La Pointe de Falinière, a 2763 m, offre un belvedere sulla Valle Centrale valdostana e sulle creste circostanti. La classificazione EE riflette sia il dislivello concentrato sia la natura del terreno nella sezione alta. Stagione: luglio–settembre.",
    description_en: "From Lod (2017 m) the trail climbs directly to Pointe de Falinière (2763 m), covering 3.7 km and 740 m of ascent in one of the fastest ascents in the Champdepraz area. The already-high starting elevation immediately places the hiker in open alpine terrain, bypassing the long forested approach typical of valley-floor starts. The EE route develops on progressively more unstable and rocky ground approaching the summit, with sections requiring sure footing. Pointe de Falinière at 2763 m offers a viewpoint over the Aosta central valley and surrounding ridges. Season: July–September.",
    description_fr: "Depuis Lod (2017 m), le sentier monte directement à la Pointe de Falinière (2763 m), couvrant 3,7 km et 740 m de dénivelé — l'une des montées les plus rapides du secteur de Champdepraz. L'altitude de départ déjà élevée place immédiatement le randonneur en milieu alpin ouvert. Le parcours EE se développe sur un terrain de plus en plus instable et rocheux. La Pointe de Falinière offre un belvédère sur la Vallée Centrale valdôtaine. Saison : juillet–septembre.",
    description_de: "Von Lod (2017 m) steigt der Weg direkt zur Pointe de Falinière (2763 m) auf 3,7 km und 740 Höhenmetern — einer der schnellsten Aufstiege im Gebiet Champdepraz. Die schon hohe Ausgangshöhe versetzt den Wanderer sofort in offenes Alpengelände. Der EE-Weg entwickelt sich auf zunehmend instabilerem und felsigem Gelände. Die Pointe de Falinière bietet einen Aussichtspunkt über das Valdostaner Zentraltal. Saison: Juli–September.",
    shortDescription_it: "Da Lod (2017m) alla Pointe de Falinière (2763m): 3,7 km EE su terreno aperto d'alta quota nell'area di Champdepraz.",
    shortDescription_en: "From Lod (2017m) to Pointe de Falinière (2763m): 3.7 km EE on open high-altitude terrain in the Champdepraz area.",
    shortDescription_fr: "De Lod (2017m) à la Pointe de Falinière (2763m) : 3,7 km EE sur terrain ouvert d'altitude dans le secteur de Champdepraz.",
    shortDescription_de: "Von Lod (2017m) zur Pointe de Falinière (2763m): 3,7 km EE auf offenem Hochgelände im Gebiet Champdepraz.",
    warnings_it: ["EE: terreno rupestre nella sezione alta, sicurezza sul passo richiesta."],
    warnings_en: ["EE: rocky terrain in the upper section, sure footing required."],
    warnings_fr: ["EE : terrain rocheux dans la section haute, pas assuré requis."],
    warnings_de: ["EE: felsiges Gelände im oberen Abschnitt, Trittsicherheit erforderlich."],
    updated_at: "2026-06-01"
  }
};

const sk = JSON.parse(fs.readFileSync(skPath, 'utf8'));
let changed = 0;
const merged = sk.map(t => {
  const p = patch[t.slug];
  if (!p) return t;
  const fixes = {};
  if (!t.duration_hours || t.duration_hours === null) fixes.duration_hours = cai(t.distance_km, t.elevation_gain_m, t.elevation_loss_m);
  if (!t.mobile_coverage || t.mobile_coverage === null) fixes.mobile_coverage = 'partial';
  if (!t.fitness_level || t.fitness_level === null) fixes.fitness_level = diffToFitness[t.difficulty] ?? 2;
  if (!t.name_en) fixes.name_en = t.name_it;
  if (!t.name_fr) fixes.name_fr = t.name_it;
  if (!t.name_de) fixes.name_de = t.name_it;
  changed++;
  return { ...t, ...fixes, ...p };
});
console.log('Patchati:', changed);
fs.writeFileSync(skPath, JSON.stringify(merged, null, 2), 'utf8');
console.log('OK');
