'use strict';
const fs = require('fs');
const path = require('path');
const skPath = path.join(__dirname, '../src/data/trails-skeleton.json');
function cai(km, gain, loss) { return Math.max(0.5, Math.round((km/4+Math.max(gain,0)/400+Math.max(loss,0)/600)*2)/2); }
const diffToFitness = { T:1, E:2, EE:3, EEA:4, A:5 };

const patch = {
  "04-s11": {
    description_it: "Da Bonavessy (658 m), piccola frazione nel fondovalle di Avise, il sentiero affronta uno dei dislivelli più impegnativi dell'intera rete sentieristica della Valle centrale: oltre 2000 metri di ascesa fino alla vetta del Mont Crabun a 2711 m. Il percorso traversa ambienti radicalmente diversi — i boschi di latifoglie del fondovalle, i pascoli intermedi, le rocce e i detriti dell'alta quota — comprimendo in 8,7 km una varietà di paesaggio che altrove richiederebbe più giorni di cammino. La classificazione EE rispecchia le difficoltà oggettive: tratti esposti, terreno irregolare, orientamento non sempre intuitivo. Riservato ad escursionisti esperti con ottimo allenamento fisico, attrezzatura adeguata e capacità di lettura del territorio alpino. Partenza in mattinata presto obbligatoria per gestire il dislivello in sicurezza.",
    description_en: "Starting from Bonavessy (658 m) in the Valle centrale near Avise, this route climbs over 2000 metres to the summit of Mont Crabun at 2711 m — one of the most demanding ascents in the area. Covering 8.7 km, the trail crosses sharply contrasting terrain: valley-floor deciduous woodland, open mid-altitude pastures, and high-alpine rock and scree. Rated EE (expert hikers only), it demands strong fitness, proper mountain equipment, and sound route-finding ability. An early start is essential to manage the elevation gain safely and avoid afternoon weather deterioration.",
    description_fr: "Depuis Bonavessy (658 m), petit hameau dans le fond de la vallée d'Avise, ce sentier gravit plus de 2000 mètres de dénivelé jusqu'au sommet du Mont Crabun à 2711 m, l'un des parcours les plus exigeants de la vallée centrale. Sur 8,7 km, il traverse des milieux radicalement différents : forêts de feuillus, alpages intermédiaires, rochers et éboulis d'altitude. Classé EE, il est réservé aux randonneurs expérimentés disposant d'un bon entraînement physique, d'un équipement adéquat et d'une réelle capacité d'orientation en terrain alpin. Départ matinal indispensable.",
    description_de: "Von Bonavessy (658 m), einem kleinen Weiler im Talgrund bei Avise, überwindet dieser Weg mehr als 2000 Höhenmeter bis zum Gipfel des Mont Crabun auf 2711 m — einer der anspruchsvollsten Aufstiege im gesamten Zentraltal. Auf 8,7 km durchquert der Weg grundlegend verschiedene Landschaftsräume: Laubwälder der Talsohle, mittlere Almweiden sowie felsiges Hochgelände. Die Einstufung EE verlangt sehr gute körperliche Kondition, geeignete Ausrüstung und sicheres Orientierungsvermögen im Alpingelände. Ein frühzeitiger Aufbruch ist zwingend erforderlich.",
    shortDescription_it: "Salita eccezionale da Bonavessy (658 m) al Mont Crabun (2711 m): +2062 m in 8,7 km su terreno vario. Solo escursionisti esperti, partenza all'alba. EE.",
    shortDescription_en: "Exceptional ascent from Bonavessy (658 m) to Mont Crabun (2711 m): +2062 m in 8.7 km. Expert hikers only, early start required. EE.",
    shortDescription_fr: "Montée exceptionnelle de Bonavessy (658 m) au Mont Crabun (2711 m) : +2062 m en 8,7 km. Randonneurs expérimentés, départ matinal. EE.",
    shortDescription_de: "Außergewöhnlicher Aufstieg von Bonavessy (658 m) zum Mont Crabun (2711 m): +2062 m auf 8,7 km. Nur für erfahrene Bergwanderer, früher Start. EE.",
    warnings_it: ["EE: dislivello eccezionale (>2000m). Partenza prima dell'alba obbligatoria.", "Terreno esposto nella sezione alta, esperienza alpina necessaria."],
    warnings_en: ["EE: exceptional elevation gain (>2000m). Pre-dawn start mandatory.", "Exposed terrain in upper section, alpine experience necessary."],
    warnings_fr: ["EE : dénivelé exceptionnel (>2000m). Départ avant l'aube obligatoire.", "Terrain exposé en altitude, expérience alpine nécessaire."],
    warnings_de: ["EE: außergewöhnlicher Höhenunterschied (>2000m). Start vor Morgengrauen obligatorisch.", "Ausgesetztes Gelände im oberen Bereich, Alpinerfahrung nötig."],
    updated_at: "2026-06-01"
  },
  "06-s10": {
    description_it: "Il sentiero parte dal bivio sulla sterrata di Jovençan a 1855 m, in alta Valdigne nel comune di La Salle, e risale con ritmo regolare verso i Lacs de Dziule a 2553 m. In 5,8 km e 702 metri di dislivello il tracciato attraversa gli ultimi lembi di alpeggio aperto prima di raggiungere l'ambiente glaciale che ha modellato questi specchi d'acqua. I laghi di Dziule sono tipici laghi di circo, formatisi nel ritiro dei ghiacciai quaternari: acque ferme, fondale detritico, sponde rocciose scarne. Il paesaggio è austero e aperto, dominato dalle creste che separano la Valdigne dalle valli laterali. Classificato E, è accessibile a escursionisti con buona esperienza di sentieri di montagna.",
    description_en: "Departing from a junction on the Jovençan forest track at 1855 m in the upper Valdigne, La Salle, this trail climbs steadily for 5.8 km and 702 metres of elevation to reach the Lacs de Dziule at 2553 m. The lakes are classic glacial cirque tarns, shaped by Quaternary glacier retreat: still waters, rocky shores, sparse vegetation. The landscape is open and austere, framed by the ridges dividing Valdigne from adjacent valleys. Rated E, it suits hikers with solid mountain experience.",
    description_fr: "Au départ d'un carrefour sur la piste de Jovençan à 1855 m, en haute Valdigne sur la commune de La Salle, ce sentier monte régulièrement sur 5,8 km et 702 mètres de dénivelé jusqu'aux Lacs de Dziule à 2553 m. Ces lacs de cirque glaciaire, héritage du retrait des glaciers quaternaires, offrent des eaux calmes encadrées de rives rocheuses et de pentes dénudées. Le paysage est vaste et austère. Classé E, le parcours convient à des randonneurs expérimentés.",
    description_de: "Vom Abzweig auf dem Forstweg von Jovençan auf 1855 m in der oberen Valdigne, Gemeinde La Salle, steigt dieser Weg gleichmäßig über 5,8 km und 702 Höhenmeter zu den Lacs de Dziule auf 2553 m auf. Die Seen sind klassische Karseen, geformt durch den Rückzug der Quartärgletscher: stilles Wasser, felsige Ufer, karge Vegetation. Die Landschaft ist weit und herb, eingerahmt von den Kämmen zwischen der Valdigne und den Seitentälern. Als E eingestuft, geeignet für erfahrene Bergwanderer.",
    shortDescription_it: "Da Jovençan (1855 m) ai laghi glaciali di Dziule (2553 m) in alta Valdigne: 5,8 km, +702 m su buon sentiero. Paesaggio di circo aperto. E.",
    shortDescription_en: "From Jovençan track junction (1855 m) to the glacial Lacs de Dziule (2553 m) in upper Valdigne: 5.8 km, +702 m. Open cirque scenery. E.",
    shortDescription_fr: "Du carrefour de Jovençan (1855 m) aux Lacs de Dziule (2553 m) en haute Valdigne : 5,8 km, +702 m. Paysage de cirque glaciaire. E.",
    shortDescription_de: "Vom Jovençan-Wegkreuz (1855 m) zu den Gletscherseen von Dziule (2553 m) in der oberen Valdigne: 5,8 km, +702 m. Offenes Karseegelände. E.",
    updated_at: "2026-06-01"
  },
  "06-s3": {
    description_it: "Da Vedun (1519 m), nel comune di La Salle in Valdigne, una salita breve ma sostenuta conduce in 3,3 km al Mont-Court de Bard a 2170 m, con 652 metri di dislivello concentrati su un tracciato che non concede lunghi tratti in piano. La pendenza costante caratterizza questo sentiero classificato E: il terreno è per lo più erboso nella parte bassa, poi più aperto e sassoso verso la cima. La ricompensa è un panorama di grande respiro: il massiccio del Monte Bianco si staglia a nord-ovest, mentre verso est si apre la visuale sulla conca di Vertosan. La brevità del percorso lo rende gestibile anche per escursionisti allenati con mezza giornata a disposizione, pur richiedendo attenzione alla qualità dell'equipaggiamento.",
    description_en: "From Vedun (1519 m) in La Salle, Valdigne, a short but unrelenting climb of 3.3 km and 652 metres leads to the summit of Mont-Court de Bard at 2170 m. The trail, rated E, maintains a consistent gradient with little flat relief — grassy lower slopes giving way to open rocky terrain near the top. The reward is a commanding panorama: the Mont Blanc massif dominates the northwestern horizon, while the Vertosan basin opens to the east. The compact distance makes it manageable in half a day for fit hikers.",
    description_fr: "Depuis Vedun (1519 m) sur la commune de La Salle, cette montée courte mais soutenue de 3,3 km et 652 mètres de dénivelé mène au Mont-Court de Bard à 2170 m. Le sentier, classé E, présente une pente constante : versants herbeux en bas, terrain plus ouvert et rocheux vers le sommet. Le panorama depuis le haut est remarquable : le massif du Mont-Blanc domine au nord-ouest, tandis qu'à l'est s'ouvre la cuvette de Vertosan.",
    description_de: "Von Vedun (1519 m) in La Salle, Valdigne, führt ein kurzer, aber gleichmäßig steiler Anstieg von 3,3 km und 652 Höhenmetern zum Mont-Court de Bard auf 2170 m. Der als E bewertete Weg bietet kaum flache Abschnitte — untere Grashänge gehen in offenes, felsiges Gelände über. Oben eröffnet sich ein weites Panorama: das Mont-Blanc-Massiv dominiert im Nordwesten, nach Osten öffnet sich das Becken von Vertosan.",
    shortDescription_it: "Da Vedun (1519 m) al Mont-Court de Bard (2170 m): 3,3 km, +652 m, salita ripida. Panorama Monte Bianco e Vertosan. Percorribile in mezza giornata. E.",
    shortDescription_en: "From Vedun (1519 m) to Mont-Court de Bard (2170 m): 3.3 km, +652 m, steep consistent climb. Mont Blanc and Vertosan views. Half-day route. E.",
    shortDescription_fr: "De Vedun (1519 m) au Mont-Court de Bard (2170 m) : 3,3 km, +652 m, montée soutenue. Vue sur le Mont-Blanc et Vertosan. Demi-journée. E.",
    shortDescription_de: "Von Vedun (1519 m) zum Mont-Court de Bard (2170 m): 3,3 km, +652 m, gleichmäßig steil. Blick auf Mont Blanc und Vertosan. Halbtagesroute. E.",
    updated_at: "2026-06-01"
  },
  "07-s22": {
    description_it: "Partendo da Blanchard (1731 m) nel comune di Avise, il sentiero percorre 7,5 km con 1085 metri di dislivello per raggiungere il Grand Lac a 2815 m, nodo di collegamento con l'Alta Via n. 3. L'itinerario sale attraverso pascoli e conche d'alta quota, con il panorama che si allarga man mano che si guadagna quota lungo il versante meridionale della valle. Il Grand Lac è uno specchio d'acqua alpino di buone dimensioni, punto di riferimento e sosta tradizionale per chi percorre il lungo cammino dell'Alta Via. La classificazione E e il dislivello superiore ai 1000 m richiedono buona preparazione fisica e attrezzatura completa. Il collegamento con l'AV3 rende questo sentiero un tassello della rete escursionistica di lungo raggio della regione.",
    description_en: "From Blanchard (1731 m) in the municipality of Avise, this 7.5 km route climbs 1085 metres to reach Grand Lac at 2815 m, a key junction on the Alta Via n. 3 long-distance trail. The path ascends through high pastures and glacially sculpted basins, with views expanding steadily across the valley as altitude is gained. Grand Lac is a sizeable alpine tarn and a traditional rest point for Alta Via walkers. Rated E with over 1000 m of elevation gain, the route demands good physical fitness and full mountain gear.",
    description_fr: "Au départ de Blanchard (1731 m) sur la commune d'Avise, ce sentier de 7,5 km et 1085 mètres de dénivelé conduit au Grand Lac à 2815 m, nœud de connexion avec la Haute Route n° 3. Le parcours monte à travers alpages et cuvettes glaciaires, avec des panoramas qui s'ouvrent progressivement sur la vallée. Le Grand Lac est un lac alpin de belle taille, étape traditionnelle sur la Haute Route. Classé E avec plus de 1000 m de dénivelé, il exige une bonne condition physique et un équipement complet.",
    description_de: "Von Blanchard (1731 m) in der Gemeinde Avise steigt dieser 7,5 km lange Weg um 1085 Höhenmeter zum Grand Lac auf 2815 m auf — einem wichtigen Knotenpunkt des Fernwanderwegs Alta Via Nr. 3. Der Pfad führt durch Hochweiden und glazial geformte Mulden, mit sich stetig weitendem Blick ins Tal. Der Grand Lac ist ein großer Gebirgssee und traditionelle Raststation für AV3-Wanderer.",
    shortDescription_it: "Da Blanchard (1731 m) al Grand Lac (2815 m) con accesso all'Alta Via 3: 7,5 km, +1085 m. Lago alpino panoramico, collegamento AV3. E.",
    shortDescription_en: "From Blanchard (1731 m) to Grand Lac (2815 m) with Alta Via 3 connection: 7.5 km, +1085 m. Scenic alpine lake and long-distance trail link. E.",
    shortDescription_fr: "De Blanchard (1731 m) au Grand Lac (2815 m), connexion Haute Route 3 : 7,5 km, +1085 m. Lac alpin panoramique, étape AV3. E.",
    shortDescription_de: "Von Blanchard (1731 m) zum Grand Lac (2815 m) mit Anschluss an Alta Via 3: 7,5 km, +1085 m. Alpiner See, Fernwegverbindung. E.",
    warnings_it: ["Dislivello >1000m: portare acqua sufficiente e partire presto."],
    warnings_en: ["Elevation gain >1000m: carry sufficient water and start early."],
    warnings_fr: ["Dénivelé >1000m : emporter suffisamment d'eau et partir tôt."],
    warnings_de: ["Höhenunterschied >1000m: ausreichend Wasser mitführen und früh starten."],
    updated_at: "2026-06-01"
  },
  "07-s37": {
    description_it: "Da Frachey (1620 m), in Val d'Ayas nel comune di Avise, il sentiero punta deciso verso il Col du Rothorn a 2692 m, valico che unisce la Val d'Ayas alla Valle centrale. I 5,7 km e i 1094 metri di dislivello si sviluppano su terreno che diventa progressivamente più alpino: boschi e radure nella parte bassa, poi costoni erbosi ripidi, infine il detrito e le rocce affioranti sotto il colle. La classificazione EE segnala difficoltà tecniche concrete — tratti esposti, possibili residui nevosi nella prima stagione, orientamento impegnativo in caso di nebbia. Il Rothorn è un valico di confine tra due bacini idrografici e due atmosfere di valle ben distinte, e la vista dal colle ripaga pienamente l'impegno richiesto per raggiungerlo.",
    description_en: "From Frachey (1620 m) in the Val d'Ayas, Avise, this trail climbs directly to the Col du Rothorn at 2692 m, a high pass linking Val d'Ayas to the Valle centrale. Over 5.7 km and 1094 metres of ascent, the terrain transitions from forested lower slopes through steep grassy ridges to rocky, exposed ground near the col. Rated EE, the route presents genuine technical challenges: exposed sections, potential early-season snowfields, and demanding navigation in poor visibility.",
    description_fr: "Depuis Frachey (1620 m) dans le Val d'Ayas, commune d'Avise, ce sentier monte directement au Col du Rothorn à 2692 m, passage reliant le Val d'Ayas à la vallée centrale. Sur 5,7 km et 1094 mètres de dénivelé, le terrain passe de la forêt aux pentes herbeuses raides, puis aux rochers et éboulis sous le col. Classé EE, le parcours présente des difficultés réelles : passages exposés, possibles névés en début de saison.",
    description_de: "Von Frachey (1620 m) im Val d'Ayas, Gemeinde Avise, steigt dieser Weg direkt zum Col du Rothorn auf 2692 m auf — einem Hochpass, der das Val d'Ayas mit dem Zentraltal verbindet. Auf 5,7 km und 1094 Höhenmetern wechselt das Gelände von bewaldeten Unterhängen über steile Graskämme bis zu felsigem, exponiertem Terrain. Die EE-Einstufung weist auf konkrete technische Schwierigkeiten hin: exponierte Abschnitte, mögliche Schneefelder in der Frühsaison.",
    shortDescription_it: "Da Frachey (1620 m) al Col du Rothorn (2692 m): 5,7 km, +1094 m, tratti esposti. Valico tra Val d'Ayas e Valle centrale. Solo escursionisti esperti. EE.",
    shortDescription_en: "From Frachey (1620 m) to Col du Rothorn (2692 m): 5.7 km, +1094 m, exposed sections. Pass linking Val d'Ayas to Valle centrale. Expert hikers only. EE.",
    shortDescription_fr: "De Frachey (1620 m) au Col du Rothorn (2692 m) : 5,7 km, +1094 m, passages exposés. Col entre Val d'Ayas et vallée centrale. EE.",
    shortDescription_de: "Von Frachey (1620 m) zum Col du Rothorn (2692 m): 5,7 km, +1094 m, exponierte Passagen. Übergang zwischen Val d'Ayas und Zentraltal. EE.",
    warnings_it: ["EE: tratti esposti e orientamento difficile in caso di nebbia."],
    warnings_en: ["EE: exposed sections and difficult navigation in poor visibility."],
    warnings_fr: ["EE : passages exposés et orientation difficile par mauvaise visibilité."],
    warnings_de: ["EE: exponierte Abschnitte und schwierige Orientierung bei schlechter Sicht."],
    updated_at: "2026-06-01"
  },
  "07-s62": {
    description_it: "Il sentiero sale da Saint-Jacques d'Ayas, a 1700 metri, fino al Col della Bettaforca a 2672 metri, valico storico che mette in comunicazione la Val d'Ayas con la Valsesia piemontese. Il percorso sviluppa 5,1 chilometri con un dislivello positivo di 987 metri su terreno via via più aperto: si lascia il fondovalle tra pascoli e baite sparse, si risale il versante settentrionale guadagnando quota rapidamente attraverso dorsali erbose, fino all'ampio sella di confine. Il panorama dalla Bettaforca spazia sull'arco del Monte Rosa a nord-est e sulle vette della Valpelline a ovest. Classificato E, il sentiero richiede buon allenamento per il dislivello concentrato, ma non presenta difficoltà tecniche.",
    description_en: "The trail climbs from Saint-Jacques d'Ayas at 1700 m to the Col della Bettaforca at 2672 m, a historic pass linking the Val d'Ayas with the Valsesia valley in Piedmont. Over 5.1 km and 987 m of elevation gain, the route crosses open grassy slopes and sparse alpine hamlets before reaching the wide saddle on the regional border. The views from the pass take in the Monte Rosa massif to the north-east and the ridges of the Valpelline to the west. Rated E, the route demands good fitness but poses no technical difficulties.",
    description_fr: "Le sentier part de Saint-Jacques d'Ayas, à 1700 m, et rejoint le Col della Bettaforca à 2672 m, col historique reliant le Val d'Ayas à la Valsesia piémontaise. Sur 5,1 km et 987 m de dénivelé positif, l'itinéraire traverse des pâturages ouverts et des hameaux alpins épars avant d'atteindre la large selle frontalière. Le panorama embrasse le massif du Mont Rose au nord-est et les arêtes du Valpelline à l'ouest. Coté E, le parcours exige une bonne condition physique mais ne présente aucune difficulté technique.",
    description_de: "Der Weg führt von Saint-Jacques d'Ayas auf 1700 m hinauf zum Col della Bettaforca auf 2672 m, einem historischen Pass, der das Val d'Ayas mit dem piemontesischen Valsesia verbindet. Auf 5,1 km und 987 Höhenmetern durchquert die Route offene Grashänge und vereinzelte Alpweiler. Das Panorama reicht zum Monte-Rosa-Massiv im Nordosten und zu den Gräten des Valpelline im Westen.",
    shortDescription_it: "Da Saint-Jacques a 1700 m al Col della Bettaforca a 2672 m: valico storico tra Val d'Ayas e Valsesia su cresta aperta con vista Monte Rosa. 5,1 km, +987 m, E.",
    shortDescription_en: "From Saint-Jacques (1700 m) to Col della Bettaforca (2672 m): a historic cross-border pass between Val d'Ayas and Valsesia. 5.1 km, +987 m, E.",
    shortDescription_fr: "De Saint-Jacques (1700 m) au Col della Bettaforca (2672 m) : col historique entre Val d'Ayas et Valsesia. 5,1 km, +987 m, E.",
    shortDescription_de: "Von Saint-Jacques (1700 m) zum Col della Bettaforca (2672 m): historischer Übergang zwischen Val d'Ayas und Valsesia. 5,1 km, +987 m, E.",
    updated_at: "2026-06-01"
  },
  "08-s2": {
    description_it: "Il percorso parte dal Moulin di Aymavilles a 653 metri, al bordo meridionale del Parco Nazionale del Gran Paradiso, e sale fino al Petit Poignon a 1562 metri, quota da cui la vista abbraccia la confluenza della Valle d'Aosta centrale. Con 6,2 chilometri e 926 metri di dislivello positivo, l'itinerario risale versanti boscosi di castagno e poi di faggio, alternati a radure aperte, percorrendo un territorio di transizione tra il fondovalle urbanizzato e l'ambiente protetto del parco. La zona rientra nella fascia di rispetto del Gran Paradiso: è comune incontrare camosci sui crinali superiori e rapaci in termica lungo le pareti rocciose. Classificato E, il sentiero non presenta difficoltà tecniche.",
    description_en: "Starting from the Moulin of Aymavilles at 653 m on the southern edge of Gran Paradiso National Park, this 6.2 km trail climbs 926 m to the Petit Poignon at 1562 m. The route ascends through chestnut and beech woodland interspersed with open clearings, traversing a transition zone between the valley floor and the protected park environment. Chamois are regularly spotted on the upper ridges, and raptors use the rock faces for thermals. Rated E, the path presents no technical difficulty.",
    description_fr: "Au départ du Moulin d'Aymavilles à 653 m, en bordure méridionale du Parc National du Grand Paradis, le sentier monte 926 m sur 6,2 km jusqu'au Petit Poignon à 1562 m. L'itinéraire traverse des forêts de châtaigniers puis de hêtres entrecoupées de clairières, dans une zone tampon entre la vallée habitée et l'espace protégé. Chamois et rapaces sont fréquents sur les hauteurs. Coté E, sans difficulté technique.",
    description_de: "Vom Moulin von Aymavilles auf 653 m, am südlichen Rand des Nationalparks Gran Paradiso, steigt der Weg auf 6,2 km und 926 Höhenmetern zum Petit Poignon auf 1562 m. Die Route führt durch Kastanien- und Buchenwälder mit Lichtungen entlang einer Übergangszone. Gämsen auf den Kämmen und Greifvögel an den Felswänden sind häufig. Als E eingestuft, ohne technische Schwierigkeit.",
    shortDescription_it: "Dal Moulin di Aymavilles (653 m) al Petit Poignon (1562 m) lungo il bordo del Parco Gran Paradiso: boschi misti, radure e fauna alpina. 6,2 km, +926 m, E.",
    shortDescription_en: "From Aymavilles Moulin (653 m) to Petit Poignon (1562 m) along the Gran Paradiso Park edge: mixed woodland, clearings, and wildlife. 6.2 km, +926 m, E.",
    shortDescription_fr: "Du Moulin d'Aymavilles (653 m) au Petit Poignon (1562 m) en lisière du Gran Paradiso : forêts mixtes et faune alpine. 6,2 km, +926 m, E.",
    shortDescription_de: "Vom Moulin Aymavilles (653 m) zum Petit Poignon (1562 m) am Rand des Gran Paradiso: Mischwälder, Lichtungen, Wildtiere. 6,2 km, +926 m, E.",
    updated_at: "2026-06-01"
  },
  "10-s15": {
    description_it: "Il percorso collega il Rifugio Prarayer a 2002 metri al Rifugio Aosta a 2790 metri nel cuore del Valpelline, percorrendo 7,3 chilometri con 797 metri di dislivello positivo. Classificato EEA — Escursionismo Esperto con Attrezzatura — l'itinerario richiede imbrago, piccozza e ramponi nelle sezioni glaciali o innevate che si incontrano nella parte alta del tracciato. Il terreno transita su morene, nevai persistenti e tratti di roccia attrezzata; la progressione è impegnativa e richiede esperienza alpinistica consolidata. L'ambiente è severo: il Valpelline alto è circondato da ghiacciai pensili e pareti di granito che mantengono condizioni alpinistiche anche in piena estate. È obbligatorio verificare le condizioni del tracciato prima della partenza. Sconsigliato ai non esperti.",
    description_en: "Linking Rifugio Prarayer at 2002 m to Rifugio Aosta at 2790 m in the upper Valpelline, this 7.3 km route gains 797 m and is rated EEA — Expert Hiking with Equipment. Harness, ice axe, and crampons are required for the glacial and snow sections in the upper portion. The terrain crosses moraines, persistent snowfields, and equipped rock passages. The high Valpelline remains under alpine conditions well into summer due to hanging glaciers and granite walls. Check route conditions before departure. Not suitable for inexperienced parties.",
    description_fr: "De 2002 m au Refuge Prarayer à 2790 m au Refuge Aoste dans le haut Valpelline, ce sentier de 7,3 km et 797 m de dénivelé est classé EEA — Randonneur Expert avec Équipement. Baudrier, piolet et crampons sont indispensables pour les sections glaciaires et enneigées en partie haute. Les conditions alpines persistent tout l'été dans ce secteur. Vérifier l'état du tracé avant le départ. Déconseillé aux non-initiés.",
    description_de: "Von der Hütte Prarayer auf 2002 m zur Hütte Aosta auf 2790 m im oberen Valpelline: 7,3 km, 797 Höhenmeter, Schwierigkeitsgrad EEA — Erfahrene Bergwanderer mit Ausrüstung. Gurt, Eispickel und Steigeisen sind für die Gletscher- und Schneepassagen im oberen Abschnitt erforderlich. Routenbedingungen vor Abfahrt prüfen. Nicht geeignet für unerfahrene Gruppen.",
    shortDescription_it: "Dal Rifugio Prarayer (2002 m) al Rifugio Aosta (2790 m) in Valpelline: percorso EEA con ghiacciai e nevai persistenti. Obbligatori imbrago, piccozza e ramponi.",
    shortDescription_en: "Rifugio Prarayer (2002 m) to Rifugio Aosta (2790 m), upper Valpelline. EEA route across glacial terrain; harness, ice axe and crampons required.",
    shortDescription_fr: "Refuge Prarayer (2002 m) → Refuge Aoste (2790 m), haut Valpelline. Classé EEA : terrain glaciaire, baudrier, piolet et crampons obligatoires.",
    shortDescription_de: "Hütte Prarayer (2002 m) → Hütte Aosta (2790 m), oberes Valpelline. EEA: Gletschergelände, Gurt, Eispickel und Steigeisen erforderlich.",
    warnings_it: ["EEA: attrezzatura glaciale obbligatoria (imbrago, piccozza, ramponi).", "Non adatto a non esperti. Verificare condizioni prima della partenza."],
    warnings_en: ["EEA: glacial equipment mandatory (harness, ice axe, crampons).", "Not suitable for non-experts. Check conditions before departure."],
    warnings_fr: ["EEA : équipement glaciaire obligatoire (baudrier, piolet, crampons).", "Non adapté aux non-initiés. Vérifier les conditions avant le départ."],
    warnings_de: ["EEA: Gletscherausrüstung obligatorisch (Gurt, Eispickel, Steigeisen).", "Nicht für Unerfahrene. Bedingungen vor Abfahrt prüfen."],
    updated_at: "2026-06-01"
  },
  "10-s6": {
    description_it: "Breve ma impegnativa salita da Chez-Chenoux a 1739 metri fino all'Alpe Luseney a 2478 metri, nel Valpelline: soli 3 chilometri di sviluppo per 775 metri di dislivello positivo, con una pendenza media molto accentuata. L'alpe si apre in un caratteristico anfiteatro glaciale, chiuso a monte da creste che portano tracce di modellamento quaternario. Il sentiero sale deciso attraverso pascoli e radure rocciose, senza tornanti lunghi, mantenendo una direzione pressoché diretta verso l'alpe. La brevità del tracciato non smorza l'impegno fisico: il passo deve essere costante e misurato. Classificato E, è accessibile a escursionisti allenati.",
    description_en: "A short but demanding climb from Chez-Chenoux at 1739 m to Alpe Luseney at 2478 m in the Valpelline: just 3 km covering 775 m of elevation gain at a sustained steep gradient. The alp sits in a distinctive glacial cirque enclosed by ridges bearing clear signs of Quaternary glacial shaping. The path ascends directly through pastures and rocky clearings with few long switchbacks, demanding a steady, measured pace throughout. Rated E, the route is accessible to fit hikers without alpine equipment.",
    description_fr: "Courte mais exigeante montée de Chez-Chenoux (1739 m) à l'Alpe Luseney (2478 m) dans le Valpelline : 3 km seulement pour 775 m de dénivelé à forte pente soutenue. L'alpe s'ouvre dans un cirque glaciaire caractéristique. Le sentier monte directement à travers pâturages et clairières rocheuses, exigeant un rythme régulier et mesuré. Coté E, accessible aux randonneurs entraînés.",
    description_de: "Kurzer, aber anspruchsvoller Aufstieg von Chez-Chenoux auf 1739 m zur Alpe Luseney auf 2478 m im Valpelline: nur 3 km für 775 Höhenmeter bei anhaltend steilem Gefälle. Die Alpe liegt in einem markanten glazialen Kar. Der Weg steigt direkt durch Weiden und felsige Lichtungen ohne lange Kehren, was ein gleichmäßiges, dosiertes Tempo erfordert. Als E eingestuft.",
    shortDescription_it: "Da Chez-Chenoux (1739 m) all'Alpe Luseney (2478 m) in Valpelline: salita breve e ripida in anfiteatro glaciale. 3 km, +775 m, E.",
    shortDescription_en: "Chez-Chenoux (1739 m) to Alpe Luseney (2478 m), Valpelline: short, steep ascent into a glacial cirque. 3 km, +775 m, E.",
    shortDescription_fr: "Chez-Chenoux (1739 m) → Alpe Luseney (2478 m), Valpelline : montée courte et raide dans un cirque glaciaire. 3 km, +775 m, E.",
    shortDescription_de: "Chez-Chenoux (1739 m) → Alpe Luseney (2478 m), Valpelline: kurzer, steiler Aufstieg in ein Gletscherkar. 3 km, +775 m, E.",
    updated_at: "2026-06-01"
  },
  "12-s12": {
    description_it: "Il sentiero parte da Estoul, a 1884 metri nel comune di Brusson in Val d'Ayas, e raggiunge il Col de Palasinaz a 2676 metri, valico che mette in comunicazione la media Val d'Ayas con Champoluc. Con 6,3 chilometri e 797 metri di dislivello, il percorso attraversa terreno prevalentemente erboso nella prima metà e più sassoso nella parte alta. Estoul è un piccolo centro d'alpeggio con servizi essenziali; la partenza avviene già in quota, il che rende la progressione più graduale. Classificato E, il percorso è adatto a escursionisti con buona preparazione fisica. Il Col de Palasinaz è un punto panoramico di rilievo sull'intera testata del Monte Rosa.",
    description_en: "Starting from Estoul at 1884 m in the municipality of Brusson, this 6.3 km trail climbs 797 m to the Col de Palasinaz at 2676 m, a pass connecting the middle Val d'Ayas with Champoluc. The terrain is largely grassy in the lower half, becoming stonier toward the col. Estoul is a small alpine hamlet with basic services, and the high starting elevation makes for a relatively gradual ascent. Rated E, suitable for hikers in good physical shape. The Col de Palasinaz offers wide views over the entire Monte Rosa head-wall.",
    description_fr: "Au départ d'Estoul (1884 m, commune de Brusson), ce sentier de 6,3 km monte 797 m jusqu'au Col de Palasinaz (2676 m), col reliant le Val d'Ayas moyen à Champoluc. Le terrain est herbeux dans la première moitié, puis plus pierreux à l'approche du col. Estoul est un hameau d'alpage avec services de base. Coté E, adapté aux randonneurs en bonne condition physique.",
    description_de: "Von Estoul auf 1884 m (Gemeinde Brusson) führt der 6,3 km lange Weg mit 797 Höhenmetern zum Col de Palasinaz auf 2676 m, einem Übergang, der das mittlere Val d'Ayas mit Champoluc verbindet. Das Gelände ist in der ersten Hälfte überwiegend grasig, wird zur Passhöhe hin steiniger. Estoul ist ein kleiner Alpweiler mit Grundversorgung. Als E eingestuft.",
    shortDescription_it: "Da Estoul (1884 m) al Col de Palasinaz (2676 m) in Val d'Ayas: valico panoramico verso Champoluc. 6,3 km, +797 m, E.",
    shortDescription_en: "Estoul (1884 m) to Col de Palasinaz (2676 m), Val d'Ayas: scenic pass linking the valley to Champoluc. 6.3 km, +797 m, E.",
    shortDescription_fr: "Estoul (1884 m) → Col de Palasinaz (2676 m), Val d'Ayas : col panoramique vers Champoluc. 6,3 km, +797 m, E.",
    shortDescription_de: "Estoul (1884 m) → Col de Palasinaz (2676 m), Val d'Ayas: panoramischer Übergang nach Champoluc. 6,3 km, +797 m, E.",
    updated_at: "2026-06-01"
  },
  "12-s38": {
    description_it: "Dal pianoro di La Manda, a 1493 metri sul versante meridionale della Val d'Ayas, il sentiero si inerpica con decisione verso il Col Palasina, valico secondario a quota 2676 metri. Il percorso guadagna 1186 metri di dislivello in meno di sette chilometri: una salita sostenuta, quasi ininterrotta, attraverso pascoli alti poi terreno detritico e aperto dell'alta quota. La segnaletica è ridotta ai minimi — quattro segnavia lungo l'intero tracciato — ed esige buona capacità di orientamento, specie nei tratti superiori dove il sentiero si perde sulla pietraia. La vista sul Monte Rosa ripaga lo sforzo. Itinerario per escursionisti esperti; portare acqua sufficiente e non avvicinarsi in caso di maltempo.",
    description_en: "From the alp of La Manda at 1493 m, on the southern slopes of Val d'Ayas, the trail climbs steeply to the Col Palasina at 2676 m. Nearly 1200 metres of ascent in under seven kilometres, with sparse waymarking — just four signs along the entire route — demands solid route-finding skills, especially on the upper scree. The views toward Monte Rosa reward the effort. No mountain huts en route; carry sufficient water.",
    description_fr: "Depuis l'alpage de La Manda (1493 m), sur le versant sud de la Val d'Ayas, le sentier monte sans relâche vers le Col Palasina (2676 m). Près de 1200 mètres de dénivelé en moins de sept kilomètres, avec une signalétique réduite à quatre panneaux. Au-dessus des alpages, le terrain devient rocheux. Aucun refuge sur le parcours ; prévoir suffisamment d'eau.",
    description_de: "Vom Almboden La Manda auf 1493 m am Südhang des Val d'Ayas steigt der Weg zielstrebig zum Col Palasina auf 2676 m an. Knapp 1200 Höhenmeter auf weniger als sieben Kilometern, dazu eine spärliche Beschilderung mit nur vier Wegweisern. Im oberen Abschnitt verliert sich der Pfad im Geröll; sichere Geländeorientierung ist Voraussetzung. Keine Hütten unterwegs; ausreichend Wasser mitführen.",
    shortDescription_it: "Lunga salita da La Manda (1493 m) al Col Palasina (2676 m) in Val d'Ayas. Segnaletica rada, terreno detritico in quota. Nessun rifugio intermedio.",
    shortDescription_en: "Long ascent from La Manda (1493 m) to Col Palasina (2676 m) in Val d'Ayas. Sparse waymarking and open scree above the treeline. No huts en route.",
    shortDescription_fr: "Longue montée de La Manda (1493 m) au Col Palasina (2676 m) en Val d'Ayas. Signalétique rare, éboulis en altitude. Aucun refuge sur le parcours.",
    shortDescription_de: "Langer Aufstieg von La Manda (1493 m) zum Col Palasina (2676 m) im Val d'Ayas. Wenige Wegweiser, Geröll in der Höhe. Keine Hütte unterwegs.",
    warnings_it: ["Segnaletica scarsa: portare cartografia o GPS.", "Dislivello importante (1186m), nessun rifugio intermedio."],
    warnings_en: ["Sparse waymarking: carry map or GPS.", "Significant elevation gain (1186m), no intermediate huts."],
    warnings_fr: ["Signalétique rare : emporter carte ou GPS.", "Dénivelé important (1186m), aucun refuge intermédiaire."],
    warnings_de: ["Spärliche Markierung: Karte oder GPS mitführen.", "Erheblicher Höhenunterschied (1186m), keine Zwischenhütten."],
    updated_at: "2026-06-01"
  },
  "13-s5": {
    description_it: "Partendo da Quinçod a soli 1030 metri di quota, questo itinerario EE accumula 1708 metri di dislivello positivo prima di raggiungere il Colle Chasten a 2549 metri: uno dei dislivelli più impegnativi dell'intero arco valdostano accessibile a piedi in giornata. Il tracciato risale l'intero fianco orografico della valle, attraversando fasce altitudinali molto differenti — bosco ceduo, alpeggi intermedi, creste aperte — senza una pausa tecnica significativa. La classificazione EE riflette la lunghezza, il dislivello elevato e tratti di sentiero con esposizione laterale. Adatto solo ad alpinisti ed escursionisti esperti con ottima preparazione fisica. La cresta del Colle Chasten offre una prospettiva ravvicinata sulle vette che separano la Val d'Ayas dalla conca di Gressoney.",
    description_en: "Starting from Quinçod at just 1030 m in the lower Val d'Ayas, this EE-rated route climbs 1708 metres to the Colle Chasten at 2549 m — one of the greatest single-day elevation gains in the Aosta Valley. The trail ascends the full orographic flank of the valley through coppice woodland, intermediate alps and exposed ridgeline terrain. Sections with lateral exposure and the sheer accumulated effort make this suitable only for experienced, well-conditioned mountain walkers.",
    description_fr: "Au départ de Quinçod (1030 m), dans la basse Val d'Ayas, cet itinéraire classé EE accumule 1708 mètres de dénivelé jusqu'au Colle Chasten (2549 m), l'un des gains d'altitude les plus importants réalisables en une journée dans la région valdôtaine. Le sentier remonte l'intégralité du versant de la vallée à travers taillis, alpages intermédiaires et arêtes dégagées. Réservé aux randonneurs expérimentés.",
    description_de: "Von Quinçod auf nur 1030 m im unteren Val d'Ayas steigt diese als EE eingestufte Route 1708 Höhenmeter bis zum Colle Chasten auf 2549 m — einer der größten Tagesanstiege im gesamten Aostatal. Der Weg durchquert den gesamten Seitenhang der Talschlucht durch Niederwald, Mittelalpen und offenes Kammgelände. Nur für erfahrene Berggänger.",
    shortDescription_it: "Itinerario EE da Quinçod (1030 m) al Colle Chasten (2549 m): 1708 m di dislivello dal fondovalle. Solo per esperti, partenza mattutina obbligatoria.",
    shortDescription_en: "EE route from Quinçod (1030 m) to Colle Chasten (2549 m): 1708 m gain from the valley floor. Experienced hikers only, early start mandatory.",
    shortDescription_fr: "Itinéraire EE de Quinçod (1030 m) au Colle Chasten (2549 m) : 1708 m de dénivelé depuis le fond de vallée. Randonneurs expérimentés, départ matinal.",
    shortDescription_de: "EE-Route von Quinçod (1030 m) zum Colle Chasten (2549 m): 1708 Hm vom Talgrund. Nur für Erfahrene, früher Start obligatorisch.",
    warnings_it: ["EE: dislivello eccezionale, partenza molto mattutina obbligatoria. Portare acqua."],
    warnings_en: ["EE: exceptional elevation gain, very early start mandatory. Carry water."],
    warnings_fr: ["EE : dénivelé exceptionnel, départ très matinal obligatoire. Emporter de l'eau."],
    warnings_de: ["EE: außergewöhnlicher Höhenunterschied, sehr früher Start obligatorisch. Wasser mitnehmen."],
    updated_at: "2026-06-01"
  },
  "15-s1": {
    description_it: "Brevissimo ma sorprendente, questo percorso parte dal Ponte sulla Dora Baltea a quota 500 metri — tra i punti più bassi dell'intera rete escursionistica valdostana — e risale con costanza il versante sinistro della Valtournenche fino al villaggio di Verthuy a 1058 metri. In soli 3,6 chilometri e 568 metri di dislivello il sentiero compie una rapida transizione altitudinale che porta da un paesaggio quasi mediterraneo, con vigneti e boschi di quercia, ai prati terrazzati della media quota sopra Châtillon. Il tracciato è classificato E e non presenta difficoltà tecniche, ma la pendenza è costante e nei mesi estivi il caldo del fondovalle può renderlo impegnativo nelle ore centrali della giornata.",
    description_en: "Short but striking, this trail leaves from the Dora Baltea bridge at only 500 m — among the lowest starting points in the Aosta Valley trail network — and climbs steadily up the left bank of the Valtournenche to the hamlet of Verthuy at 1058 m. In 3.6 km the path moves from an almost Mediterranean landscape of vines and oak woodland to the terraced meadows above Châtillon. No technical difficulties, but the gradient is constant; in summer the valley-floor heat makes midday departures inadvisable.",
    description_fr: "Court mais saisissant, ce sentier part du pont sur la Doire Baltée à seulement 500 m — l'un des points de départ les plus bas du réseau valdôtain — et remonte régulièrement le versant gauche de la Valtournenche jusqu'au hameau de Verthuy (1058 m). En 3,6 km, le paysage passe de vignobles et chênaies d'allure méditerranéenne aux prairies en terrasses au-dessus de Châtillon.",
    description_de: "Kurz, aber eindrucksvoll: Dieser Weg beginnt an der Dora-Baltea-Brücke auf nur 500 m — einem der tiefsten Ausgangspunkte im Wandernetz des Aostatals — und steigt gleichmäßig den linken Hang des Valtournenche bis zum Weiler Verthuy auf 1058 m an. Auf 3,6 km wechselt die Landschaft von Weinbergen und Eichenwäldern zu den Terrassenwiesen oberhalb von Châtillon.",
    shortDescription_it: "Dal Ponte Dora Baltea (500 m) a Verthuy (1058 m) sopra Châtillon: 568 m in 3,6 km. Passaggio rapido dal fondovalle ai prati terrazzati della Valtournenche.",
    shortDescription_en: "From the Dora Baltea bridge (500 m) to Verthuy (1058 m) above Châtillon: 568 m in 3.6 km. Quick transition from valley floor to terraced meadows.",
    shortDescription_fr: "Du pont de la Doire Baltée (500 m) à Verthuy (1058 m) au-dessus de Châtillon : 568 m en 3,6 km. Transition rapide du fond de vallée aux prairies en terrasses.",
    shortDescription_de: "Von der Dora-Baltea-Brücke (500 m) nach Verthuy (1058 m) oberhalb von Châtillon: 568 Hm auf 3,6 km. Rascher Wechsel vom Talgrund zu Terrassenwiesen.",
    updated_at: "2026-06-01"
  },
  "16-s4": {
    description_it: "Chamois è un caso unico nell'intera penisola italiana: comune accessibile unicamente a piedi o con la telecabina da Buisson, senza alcuna strada carrozzabile. Da questa quota già elevata di 1812 metri il sentiero sale ulteriormente verso i 2600 metri dell'innesto con il sentiero 4, guadagnando 779 metri di dislivello in 5,8 chilometri su un versante rivolto a ovest verso la Valle centrale. Il tracciato attraversa gli alpeggi di alta quota che caratterizzano il territorio di Chamois, con vedute progressive sul fondovalle della Dora Baltea e sulle montagne del Massiccio del Cervino. La classificazione E rispecchia un percorso tecnicamente regolare ma fisicamente sostenuto.",
    description_en: "Chamois holds a unique distinction in Italy: a municipality with no road access whatsoever, reachable only on foot or by cable car from Buisson. From this already-elevated starting point at 1812 m the trail gains a further 779 metres over 5.8 km to join trail no. 4 at 2600 m, climbing west-facing slopes above the central Aosta Valley. The route crosses the high pastures that define Chamois territory, with widening views toward the Dora Baltea and the Matterhorn massif. The car-free character of the departure village lends the itinerary a quietness rare in more frequented valleys.",
    description_fr: "Chamois est une singularité italienne : commune sans aucune route carrossable, accessible uniquement à pied ou par télécabine depuis Buisson. De ce point de départ déjà élevé (1812 m), le sentier monte encore 779 mètres sur 5,8 km pour rejoindre le sentier 4 à 2600 m. Le parcours traverse les alpages d'altitude qui font l'identité de Chamois, avec des vues progressives sur la Doire Baltée et le massif du Cervin.",
    description_de: "Chamois ist eine Besonderheit in ganz Italien: eine Gemeinde ohne jede Straßenanbindung, die nur zu Fuß oder per Gondelbahn von Buisson erreichbar ist. Von diesem bereits hoch gelegenen Ausgangspunkt auf 1812 m steigt der Weg weitere 779 Höhenmeter über 5,8 km bis zum Anschluss an Weg Nr. 4 auf 2600 m. Der Pfad quert die Hochalmen, die das Gebiet von Chamois prägen, mit weiten Blicken zur Dora Baltea und zum Matterhorn-Massiv.",
    shortDescription_it: "Da Chamois (1812 m) — unico comune italiano senza strade — all'innesto sentiero 4 a 2600 m. 779 m di dislivello sui pascoli d'alta quota sopra la Valle centrale.",
    shortDescription_en: "From Chamois (1812 m) — Italy's only road-free municipality — to trail junction 4 at 2600 m. 779 m ascent over high pastures above the central Aosta Valley.",
    shortDescription_fr: "De Chamois (1812 m) — seule commune italienne sans route — au carrefour du sentier 4 (2600 m). 779 m sur les alpages dominant la vallée centrale.",
    shortDescription_de: "Von Chamois (1812 m) — Italiens einzige Gemeinde ohne Straße — zur Weggabelung Weg 4 auf 2600 m. 779 Hm über Hochalmen im zentralen Aostatal.",
    updated_at: "2026-06-01"
  },
  "17-s12": {
    description_it: "Il Lac Gelé, a 2606 metri di quota nei pressi di Charvensod, porta già nel nome la sua natura: uno specchio d'acqua glaciale incastonato in un anfiteatro di rocce dove la neve permane a lungo durante l'anno. Il sentiero parte da Veulla a 1286 metri e guadagna 1311 metri in 6,1 chilometri, uno dei dislivelli più marcati dei percorsi E della Valle d'Aosta. La salita è continua: bosco di conifere nella parte bassa, poi alpeggi aperti, poi il terreno minerale e austero dell'alta quota nei pressi del lago. La classificazione E indica l'assenza di difficoltà tecniche, ma il dislivello richiede buona preparazione fisica. Charvensod è comune adiacente ad Aosta, il che rende questo itinerario facilmente raggiungibile dal capoluogo.",
    description_en: "Lac Gelé — Frozen Lake — at 2606 m near Charvensod earns its name: a glacial tarn set in a rocky cirque where snow lingers well into summer. The trail departs from Veulla at 1286 m and climbs 1311 metres in 6.1 km, one of the most sustained elevation gains among E-rated routes in the Aosta Valley. The ascent is unrelenting — conifer forest low down, open alp pastures in the middle section, then austere rock and scree near the lake. Charvensod borders the city of Aosta, making this one of the valley's most accessible high-mountain objectives.",
    description_fr: "Le Lac Gelé (2606 m), près de Charvensod, porte bien son nom : un lac glaciaire enchâssé dans un cirque rocheux où la neige tarde à fondre. Le sentier part de Veulla (1286 m) et gravit 1311 mètres en 6,1 km, l'un des dénivelés les plus importants parmi les itinéraires E de la Vallée d'Aoste. La montée est sans répit. Charvensod est limitrophe d'Aoste, ce qui rend cet objectif de haute montagne facilement accessible.",
    description_de: "Der Lac Gelé — der Gefrorene See — liegt auf 2606 m nahe Charvensod und verdient seinen Namen: ein Gletschersee in einem Felskar, in dem Schnee weit in den Sommer hinein liegen bleibt. Der Weg beginnt in Veulla auf 1286 m und überwindet 1311 Höhenmeter auf 6,1 km — eines der stärksten Gefälle unter den E-bewerteten Routen im Aostatal. Charvensod grenzt an die Stadt Aosta — dieses Hochgebirgsziel ist damit vom Hauptort der Region bequem erreichbar.",
    shortDescription_it: "Da Veulla (1286 m) al Lac Gelé (2606 m) sopra Charvensod: 1311 m di dislivello continuo. Lago glaciale d'alta quota, facilmente raggiungibile da Aosta.",
    shortDescription_en: "From Veulla (1286 m) to Lac Gelé (2606 m) above Charvensod: 1311 m of sustained ascent to a glacial tarn easily reached from the city of Aosta.",
    shortDescription_fr: "De Veulla (1286 m) au Lac Gelé (2606 m) au-dessus de Charvensod : 1311 m de montée continue vers un lac glaciaire accessible depuis Aoste.",
    shortDescription_de: "Von Veulla (1286 m) zum Lac Gelé (2606 m) über Charvensod: 1311 Hm kontinuierlicher Aufstieg zu einem Gletschersee, gut erreichbar von Aosta.",
    warnings_it: ["Dislivello elevato (+1311m) per categoria E: buona preparazione fisica necessaria."],
    warnings_en: ["High elevation gain (+1311m) for an E-rated trail: good physical fitness required."],
    warnings_fr: ["Dénivelé élevé (+1311m) pour un sentier E : bonne condition physique nécessaire."],
    warnings_de: ["Hoher Höhenunterschied (+1311m) für einen E-Weg: gute körperliche Fitness erforderlich."],
    updated_at: "2026-06-01"
  }
};

const sk = JSON.parse(fs.readFileSync(skPath, 'utf8'));
let changed = 0;
const merged = sk.map(t => {
  const p = patch[t.slug];
  if (!p) return t;
  const fixes = {};
  if (!t.duration_hours || t.duration_hours === null) fixes.duration_hours = cai(t.distance_km, t.elevation_gain_m, t.elevation_loss_m);
  if (!t.mobile_coverage || t.mobile_coverage === null) fixes.mobile_coverage = 'partial';
  if (!t.fitness_level || t.fitness_level === null) fixes.fitness_level = diffToFitness[t.difficulty] ?? 2;
  if (!t.name_en) fixes.name_en = t.name_it;
  if (!t.name_fr) fixes.name_fr = t.name_it;
  if (!t.name_de) fixes.name_de = t.name_it;
  changed++;
  return { ...t, ...fixes, ...p };
});
console.log('Patchati:', changed);
fs.writeFileSync(skPath, JSON.stringify(merged, null, 2), 'utf8');
console.log('OK');
