'use strict';
const fs = require('fs');
const path = require('path');

const patch = JSON.parse(`{
  "01-s1": {
    "description_it": "Dal Chef-lieu di Allein (1248 m), cuore del comune omonimo nella Valle del Gran San Bernardo, il sentiero n° 24 si inerpica deciso verso il Mont Saron (2682 m), montagna-simbolo di questo territorio di confine tra Valpelline e vallata del Gran San Bernardo. La partenza avviene dietro la chiesa del capoluogo, dove il tracciato sale dapprima ai frazionamenti di Ville e Bruson attraverso pascoli e boschi misti di abete e larice. Dai pianori di Bruson si risale su stradina poderale fino all'Alpe Bossolaz, poi il sentiero entra nel bosco che si fa via via più rado, lasciando spazio all'alpeggio di Fontaines e all'Alpe Parc. Superata la zona degli alpeggi, la prateria alpina prende il sopravvento: il percorso guadagna quota su versante erboso con una sorgente in località Fontanin, poi traversa obliquamente verso la cresta opposta. L'ultimo tratto segue la dorsale finale fino alla vetta. Il dislivello positivo di 1434 m in 7.5 km rende questa salita impegnativa, con una progressione continua che richiede buon allenamento e calzatura idonea.",
    "description_en": "From the Chef-lieu of Allein (1248 m), the heart of this village in the Gran San Bernardo valley, trail no. 24 climbs steadily toward Mont Saron (2682 m), the landmark mountain that divides the Valpelline to the east from the Gran San Bernardo valley to the west. The route leaves the village behind the church, rising first through the hamlets of Ville and Bruson across meadows and mixed fir and larch forest. From the Bruson plateau, a farm track leads to Alpe Bossolaz, where the path re-enters thinning woodland before reaching the Fontaines alp and Alpe Parc. Beyond the pastures, open alpine grassland dominates: the trail gains height on grassy slopes, passes a spring at Fontanin, then traverses obliquely toward the opposite ridge. The final section follows the summit ridge to the top. The 1434 m ascent over 7.5 km makes this a demanding outing, requiring good fitness and sturdy footwear.",
    "description_fr": "Depuis le Chef-lieu d'Allein (1248 m), coeur de la commune dans la vallée du Grand-Saint-Bernard, le sentier n° 24 monte résolument vers le Mont Saron (2682 m), montagne emblématique de ce territoire frontière. Le départ s'effectue derrière l'église ; le tracé monte d'abord aux hameaux de Ville et de Bruson à travers prés et forêts mixtes de sapins et de mélèzes. Depuis les replats de Bruson, une piste agricole conduit à l'Alpe Bossolaz, puis le sentier pénètre dans un bois de plus en plus clairsemé laissant place aux alpages de Fontaines et de Parc. Au-delà des alpages, la prairie alpine domine : le parcours prend de l'altitude sur un versant herbeux, dépasse une source à Fontanin, puis traverse obliquement vers l'arête opposée. Le tronçon final longe l'arête sommitale jusqu'au sommet.",
    "description_de": "Vom Chef-lieu von Allein (1248 m), dem Herz der gleichnamigen Gemeinde im Tal des Großen Sankt Bernhard, führt Weg Nr. 24 zielstrebig auf den Mont Saron (2682 m). Der Weg beginnt hinter der Dorfkirche, steigt zunächst durch die Weiler Ville und Bruson über Weiden und gemischte Tannen-Lärchen-Wälder an. Von den Hochflächen bei Bruson folgt man einem Feldweg bis zur Alpe Bossolaz, wo der Pfad wieder in lichter werdenden Wald eintaucht, bevor er die Alp Fontaines und die Alpe Parc erreicht. Oberhalb der Almen dominiert die alpine Graslandschaft: Der Weg gewinnt Höhe an einem Grashang, passiert eine Quelle bei Fontanin, quert dann schräg zur gegenüberliegenden Kante. Der Schlussabschnitt folgt dem Gipfelgrat bis zum höchsten Punkt.",
    "shortDescription_it": "Dal capoluogo di Allein la salita al Mont Saron percorre boschi, alpeggi e cresta sullo spartiacque tra Gran San Bernardo e Valpelline: 1434 m di dislivello per escursionisti allenati.",
    "shortDescription_en": "From Allein village, the climb to Mont Saron crosses forest, alpine pastures and a summit ridge on the watershed between Gran San Bernardo and Valpelline: 1434 m ascent for fit hikers.",
    "shortDescription_fr": "Depuis le chef-lieu d'Allein, la montée au Mont Saron traverse forêts, alpages et arête sommitale sur la ligne de partage entre Grand-Saint-Bernard et Valpelline : 1434 m de dénivelé.",
    "shortDescription_de": "Vom Ortskern Alleins führt der Aufstieg auf den Mont Saron durch Wald, Almen und einen Gipfelgrat auf der Wasserscheide zwischen Großem Sankt Bernhard und Valpelline: 1434 Hm.",
    "warnings_it": ["Tratto di cresta finale esposto: richiede piede fermo e condizioni di visibilità adeguate.", "Presenza di neve tardiva possibile sugli alpeggi superiori in giugno."],
    "warnings_en": ["The final ridge section is exposed: sure footing and good visibility required.", "Late snow may remain on upper pastures in June."],
    "warnings_fr": ["Le tronçon final sur crête est exposé : il faut être assuré du pied et avoir une bonne visibilité.", "Présence possible de neige tardive sur les alpages supérieurs en juin."],
    "warnings_de": ["Der abschließende Gipfelgrat ist exponiert: Trittsicherheit und gute Sicht erforderlich.", "Bis in den Juni hinein kann auf den oberen Almen Schnee liegen."],
    "updated_at": "2026-06-01"
  },
  "02-s8": {
    "description_it": "L'anello dei villaggi di Antey-Saint-André si sviluppa lungo i versanti soleggiati che dominano la Valtournenche, unendo in un unico percorso circolare numerose piccole frazioni e paesaggi di mezza montagna. La partenza e l'arrivo coincidono a Ruvère (1015 m). Il tracciato si snoda su sentieri e poderali ben segnalati, alternando boschi di conifere, vigneti e prati terrazzati con scorci sul fondovalle e sulle cime circostanti. Con 5.2 km e un dislivello di 456 m, l'itinerario tocca villaggi che conservano l'architettura rurale tradizionale della Valle d'Aosta: cappellette votive, mayen in pietra e fienili. La classificazione E segnala un percorso escursionistico regolare, adatto a camminatori con normale allenamento. Il carattere ad anello permette di tornare al punto di partenza senza ripercorrere i medesimi tratti.",
    "description_en": "The village loop of Antey-Saint-André unfolds across the sunny slopes overlooking the Valtournenche, linking a series of small hamlets in a single circular route across mid-mountain terrain. The walk starts and ends at Ruvère (1015 m). The trail follows well-marked paths and farm tracks through conifer woodland, vineyards and terraced meadows, with open views across the valley floor and surrounding peaks. At 5.2 km with 456 m of elevation gain, the route passes hamlets that preserve the traditional rural architecture of the Aosta Valley: votive chapels, stone mayens and hay barns. The E rating marks a straightforward hiking route suitable for walkers of average fitness.",
    "description_fr": "L'anneau des villages d'Antey-Saint-André se déroule sur les versants ensoleillés dominant la Valtournenche, reliant en un seul parcours circulaire de nombreux petits hameaux dans un paysage de moyenne montagne. Le départ et l'arrivée coïncident à Ruvère (1015 m). L'itinéraire suit des sentiers et des pistes agricoles bien balisés, alternant forêts de conifères, vignobles et prairies en terrasses avec des échappées sur le fond de vallée. Avec 5.2 km et un dénivelé de 456 m, le parcours touche des villages conservant l'architecture rurale traditionnelle valdôtaine. La cotation E signale un parcours régulier adapté aux marcheurs ordinaires.",
    "description_de": "Die Dorfrunde von Antey-Saint-André verläuft über die sonnenexponierten Hänge oberhalb des Valtournenche-Tals und verbindet mehrere kleine Weiler in einem einzigen Rundweg. Start und Ziel liegen in Ruvère (1015 m). Der Weg folgt gut markierten Pfaden und Feldwegen durch Nadelwälder, Weinberge und terrassierte Wiesen mit offenen Blicken ins Tal. Bei 5.2 km und 456 Hm Aufstieg berührt die Route Weiler mit traditioneller Walliser Bausubstanz: Votivkapellen, steinerne Mayens und Stadel. Die Bewertung E steht für einen regulären Wanderweg.",
    "shortDescription_it": "Anello tra i villaggi soleggiati di Antey e Torgnon: architettura rurale valdostana, vigneti e boschi in 5.2 km con partenza e arrivo a Ruvère.",
    "shortDescription_en": "A loop through the sunlit hamlets of Antey and Torgnon: traditional Aosta Valley architecture, vineyards and mid-mountain forest, 5.2 km from Ruvère.",
    "shortDescription_fr": "Une boucle à travers les hameaux ensoleillés d'Antey et Torgnon : architecture rurale valdôtaine, vignobles et forêts, 5.2 km depuis Ruvère.",
    "shortDescription_de": "Rundweg durch die besonnten Weiler von Antey und Torgnon: traditionelle Architektur, Weinberge und Wald, 5.2 km ab Ruvère.",
    "updated_at": "2026-06-01"
  },
  "05-s11": {
    "description_it": "Il sentiero da Grand Haury a Boregne si apre nella zona di transizione tra la bassa Valgrisenche e il comune di Arvier, risalendo un vallone laterale dall'ambiente forestato verso gli alpeggi alti. La partenza avviene da Grand Haury (1170 m). Il tracciato risale il versante con pendenze sostenute attraverso il bosco, che si assottiglia progressivamente cedendo spazio alle praterie d'alta quota. L'alpe di Boregne (circa 2000 m) costituisce il punto di arrivo: un ampio ripiano pascolivo ai piedi delle pareti della Becca Verconey, aperto sul versante e sulle vette della Valgrisenche. Il dislivello di 835 m in 5.8 km concentra la fatica nella prima metà del percorso. La classificazione E indica un sentiero escursionistico che richiede allenamento, senza difficoltà tecniche. L'ambiente rimane selvaggio e poco frequentato.",
    "description_en": "The path from Grand Haury to Boregne opens in the transitional zone between the lower Valgrisenche and the commune of Arvier, climbing a side valley from forested terrain toward the high pastures. The walk begins at Grand Haury (1170 m). The trail climbs the slope at a sustained gradient through woodland that gradually thins, giving way to high-altitude grassland. Alpe di Boregne (approx. 2000 m) marks the arrival point: a broad pastoral terrace at the foot of the Becca Verconey walls, open across the valley. The 835 m ascent over 5.8 km concentrates effort in the first half. The E rating indicates a hiking route requiring fitness but free of technical difficulty.",
    "description_fr": "Le sentier de Grand Haury à Boregne s'inscrit dans la zone de transition entre la basse Valgrisenche et la commune d'Arvier, remontant un vallon latéral depuis un environnement forestier vers les alpages supérieurs. Le départ s'effectue depuis Grand Haury (1170 m). Le tracé monte le versant à forte pente à travers un bois qui s'éclaircit progressivement pour laisser place aux pelouses d'altitude. L'alpe de Boregne (env. 2000 m) constitue le point d'arrivée : un vaste replat pastoral au pied des parois de la Becca Verconey.",
    "description_de": "Der Weg von Grand Haury nach Boregne führt durch eine Übergangszone zwischen dem unteren Valgrisenche und der Gemeinde Arvier, er steigt ein Seitental vom bewaldeten Gelände zu den Hochalmen hinauf. Start ist Grand Haury (1170 m). Der Pfad steigt in anhaltender Steigung durch Wald an, der sich nach und nach lichtet und in Hochgebirgsrasen übergeht. Die Alpe di Boregne (ca. 2000 m) ist der Endpunkt: ein breites Weideterrassem am Fuß der Wände der Becca Verconey.",
    "shortDescription_it": "Da Grand Haury l'itinerario sale attraverso il bosco e la prateria verso l'Alpe di Boregne, ripiano pascolivo ai piedi della Becca Verconey, in una laterale silenziosa della Valgrisenche.",
    "shortDescription_en": "From Grand Haury the route climbs through forest and alpine meadow to the Alpe di Boregne pasture plateau at the foot of Becca Verconey in a quiet Valgrisenche side valley.",
    "shortDescription_fr": "Depuis Grand Haury, l'itinéraire monte à travers forêt et pelouse vers l'alpe de Boregne, replat pastoral au pied de la Becca Verconey, dans un vallon calme de la Valgrisenche.",
    "shortDescription_de": "Von Grand Haury steigt der Weg durch Wald und Almwiesen zur Alpe di Boregne auf, einer Weide am Fuß der Becca Verconey in einem stillen Seitental der Valgrisenche.",
    "warnings_it": ["Sentiero meno frequentato: traccia non sempre evidente nel bosco fitto.", "Neve tardiva possibile all'arrivo sull'alpe fino a giugno."],
    "warnings_en": ["Lightly used trail: markings may be unclear in dense woodland.", "Late snow can linger on the alp until June."],
    "warnings_fr": ["Sentier peu fréquenté : le balisage peut être peu visible dans la forêt dense.", "Présence possible de neige tardive sur l'alpage jusqu'en juin."],
    "warnings_de": ["Wenig begangener Weg: Markierungen im dichten Wald nicht immer gut erkennbar.", "Bis in den Juni hinein kann auf der Alp Schnee liegen."],
    "updated_at": "2026-06-01"
  },
  "06-s11": {
    "description_it": "Il sentiero dai pressi del Bivio Jovençan ai Lacs de Dziule si sviluppa nel Vallone di Vertosan, laterale della Valdigne nel comune di La Salle, in un ambiente di alta montagna che alterna praterie, zone umide e rocce. La partenza avviene da una sterrata a quota 1855 m, già all'interno del vallone. Il percorso risale il vallone con dislivello regolare di 702 m in 6.9 km, mantenendosi su terreno aperto con ampi panorami. I Lacs de Dziule si trovano a circa 2553 m, immersi in un paesaggio glaciale residuale dove la roccia e l'acqua si alternano in un contesto severo e pulito. La stagione ottimale si colloca tra luglio e settembre, quando il vallone è libero da neve. La classificazione E richiede allenamento e calzatura adeguata, senza difficoltà tecniche particolari su terreno ben segnalato.",
    "description_en": "The trail from the Bivio Jovençan road junction to the Lacs de Dziule runs through the Vertosan valley, a side valley of the Valdigne in La Salle, in a high-mountain environment of grassland, wetland and rock. The walk begins from a gravel track at 1855 m, already within the valley. The route ascends the valley with a steady 702 m gain over 6.9 km, crossing open terrain with wide panoramas. The Lacs de Dziule lie at approximately 2553 m, set in a residual glacial landscape where rock and water alternate in a spare, clear setting. The optimal season runs from July to September.",
    "description_fr": "Le sentier du Bivio Jovençan aux Lacs de Dziule se déroule dans le Vallon de Vertosan, vallée latérale de la Valdigne dans la commune de La Salle, dans un environnement de haute montagne alternant pelouses, zones humides et roches. Le départ s'effectue depuis une piste à 1855 m, déjà à l'intérieur du vallon. Le parcours remonte le vallon avec un dénivelé régulier de 702 m sur 6.9 km sur terrain ouvert et panoramique. Les Lacs de Dziule se trouvent à environ 2553 m, dans un paysage glaciaire résiduel. La saison optimale va de juillet à septembre.",
    "description_de": "Der Weg vom Bivio Jovençan zu den Lacs de Dziule verläuft durch das Vallone di Vertosan, ein Seitental der Valdigne in La Salle, in einem Hochgebirgsumfeld aus Wiesen, Feuchtgebieten und Fels. Start ist ein Schotterweg auf 1855 m, bereits im Inneren des Tals. Der Weg steigt das Tal mit konstantem Anstieg von 702 Hm auf 6.9 km über offenes, panoramisches Gelände hinauf. Die Lacs de Dziule liegen auf etwa 2553 m in einer Restgletscherlandschaft. Optimale Saison: Juli bis September.",
    "shortDescription_it": "Nel Vallone di Vertosan il percorso risale fino ai Lacs de Dziule, specchi d'acqua glaciali a 2553 m immersi in un paesaggio severo di roccia e prateria alta in Valdigne.",
    "shortDescription_en": "Through the Vertosan valley, the trail climbs to the Lacs de Dziule, glacial lakes at 2553 m set in a stark landscape of rock and high meadow in the Valdigne.",
    "shortDescription_fr": "Dans le Vallon de Vertosan, l'itinéraire monte jusqu'aux Lacs de Dziule, miroirs glaciaires à 2553 m dans un paysage austère de roche et de pelouse d'altitude en Valdigne.",
    "shortDescription_de": "Durch das Vallone di Vertosan führt der Weg zu den Lacs de Dziule, Gletscherseen auf 2553 m in einer strengen Fels- und Hochalmlandschaft der Valdigne.",
    "warnings_it": ["Il vallone può trattenere neve fino a metà luglio: verificare le condizioni prima di partire.", "Assenza di punti di sosta attrezzati lungo il percorso."],
    "warnings_en": ["The valley can hold snow until mid-July: check conditions before setting out.", "No staffed shelters along the route."],
    "warnings_fr": ["Le vallon peut conserver de la neige jusqu'à mi-juillet : vérifier les conditions avant le départ.", "Absence d'abri gardé sur le parcours."],
    "warnings_de": ["Das Tal kann bis Mitte Juli Schnee aufweisen: Bedingungen vor dem Aufbruch prüfen.", "Keine bewirtschafteten Schutzhütten entlang der Route."],
    "updated_at": "2026-06-01"
  },
  "06-s28": {
    "description_it": "La salita da Runaz all'Alpage du Glacier è uno degli itinerari di maggior sviluppo altimetrico della Valdigne, con 1635 m di dislivello positivo in 8.7 km. La partenza avviene da Runaz (839 m), piccola frazione nel comune di La Salle. Il percorso guadagna quota rapidamente attraverso il bosco, risalendo il versante con una progressione che alterna tratti nel fitto della foresta e aperture sulle praterie. Man mano che si sale, il bosco lascia spazio agli alpeggi intermedi, poi alla prateria alpina sempre più aperta. L'Alpage du Glacier (2163 m) rappresenta la destinazione finale, un pianoro pascolivo nel contesto dell'alta Valle di La Salle. L'impegno fisico di questa salita è notevole per il dislivello accumulato; la classificazione E indica assenza di difficoltà tecniche ma richiede camminatori ben allenati.",
    "description_en": "The ascent from Runaz to the Alpage du Glacier is one of the most demanding routes in the Valdigne by vertical gain, with 1635 m of ascent over 8.7 km. The walk begins at Runaz (839 m), a small hamlet in La Salle. The path gains height rapidly through forest, climbing the slope with alternating dense woodland and open meadow sections. As altitude increases, the landscape transforms: the forest gives way to intermediate pastures, then to increasingly open alpine grassland. The Alpage du Glacier (2163 m) is the final destination, a pastoral plateau within the upper La Salle valley zone.",
    "description_fr": "La montée de Runaz à l'Alpage du Glacier est l'un des itinéraires à plus fort dénivelé de la Valdigne, avec 1635 m de montée sur 8.7 km. Le départ s'effectue depuis Runaz (839 m), un petit hameau de la commune de La Salle. Le sentier prend rapidement de l'altitude à travers la forêt, montant le versant en alternant tronçons boisés denses et ouvertures sur les prairies. L'Alpage du Glacier (2163 m) constitue la destination finale, un replat pastoral dans la zone haute de La Salle.",
    "description_de": "Der Aufstieg von Runaz zum Alpage du Glacier ist eine der höhenintensivsten Routen der Valdigne mit 1635 Hm auf 8.7 km. Start ist Runaz (839 m), ein kleiner Weiler der Gemeinde La Salle. Der Weg gewinnt rasch Höhe durch den Wald, steigt den Hang hinauf mit abwechselnd dichtem Waldgelände und offenen Wiesenflächen. Der Alpage du Glacier (2163 m) ist das Ziel, ein Weidehochplateau im oberen Bereich des La-Salle-Tals.",
    "shortDescription_it": "Da Runaz (839 m) fino all'Alpage du Glacier (2163 m): 1635 m di dislivello attraverso boschi, alpeggi e praterie aperte in uno degli itinerari più impegnativi della Valdigne.",
    "shortDescription_en": "From Runaz (839 m) to the Alpage du Glacier (2163 m): 1635 m of ascent through forest, pastures and open alpine grassland, one of the most demanding routes in the Valdigne.",
    "shortDescription_fr": "De Runaz (839 m) à l'Alpage du Glacier (2163 m) : 1635 m de dénivelé à travers forêts, alpages et prairies ouvertes, l'un des itinéraires les plus exigeants de la Valdigne.",
    "shortDescription_de": "Von Runaz (839 m) zum Alpage du Glacier (2163 m): 1635 Hm durch Wald, Almen und offene Hochalmwiesen — einer der anspruchsvollsten Aufstiege der Valdigne.",
    "warnings_it": ["Dislivello elevato: necessario partire nelle prime ore del mattino e portare acqua a sufficienza.", "Il versante è esposto al sole nel pomeriggio."],
    "warnings_en": ["High elevation gain: an early start and sufficient water are essential.", "The slope receives full afternoon sun."],
    "warnings_fr": ["Dénivelé élevé : départ tôt le matin et eau en quantité suffisante indispensables.", "Le versant est exposé au soleil l'après-midi."],
    "warnings_de": ["Großer Höhenunterschied: Frühzeitiger Start und ausreichend Wasser sind unerlässlich.", "Der Hang ist nachmittags voll der Sonne ausgesetzt."],
    "updated_at": "2026-06-01"
  },
  "07-s17": {
    "description_it": "La salita da Saint-Jacques al Mont Roisetta è uno degli itinerari più impegnativi della Val d'Ayas, con 1579 m di dislivello positivo per raggiungere la quota di 3269 m. La partenza avviene da Saint-Jacques (1700 m), frazione del comune di Ayas. Il tracciato risale progressivamente attraverso pascoli alpini, scavalca zone di detrito e macereto e guadagna quota con pendenza regolare prima di avvicinarsi alla fascia più alta, dove il terreno si fa più ripido. L'ambiente si trasforma con l'altitudine: dalla prateria verde di bassa quota si passa alle distese di pietraia e ghiaione d'alta montagna, con il panorama che si allarga progressivamente verso la catena del Monte Rosa. La classificazione EE è motivata dalla quota elevata, dalla lunghezza del percorso e dalla presenza di tratti su terreno impervio che richiedono adattamento alle condizioni d'alta montagna. Consigliato da luglio a settembre.",
    "description_en": "The ascent from Saint-Jacques to Mont Roisetta is one of the most demanding itineraries in the Val d'Ayas, gaining 1579 m to reach 3269 m. The walk starts from Saint-Jacques (1700 m), a hamlet of Ayas. The route climbs steadily through alpine pastures, crosses scree and boulder terrain and gains height at a consistent gradient before steepening in the upper section. The environment shifts with altitude: from green lowland meadow to the broad stony and rocky belts of high mountain, with the panorama progressively opening toward the Monte Rosa massif. The EE rating is justified by the elevation, route length and demanding terrain. Recommended from July to September.",
    "description_fr": "La montée de Saint-Jacques au Mont Roisetta est l'un des itinéraires les plus exigeants de la Val d'Ayas, avec 1579 m de dénivelé pour atteindre 3269 m. Le départ s'effectue depuis Saint-Jacques (1700 m), hameau d'Ayas. Le tracé monte progressivement à travers pâturages alpins, traversées d'éboulis et terrains rocheux. L'environnement se transforme avec l'altitude : des prairies vertes inférieures aux étendues de pierrailles de la haute montagne, avec un panorama s'ouvrant vers le massif du Mont-Rose. La cotation EE est justifiée par l'altitude, la longueur et le terrain. Recommandé de juillet à septembre.",
    "description_de": "Der Aufstieg von Saint-Jacques auf den Mont Roisetta ist einer der anspruchsvollsten Wege im Val d'Ayas mit 1579 Hm bis auf 3269 m. Start ist Saint-Jacques (1700 m), ein Weiler der Gemeinde Ayas. Die Route steigt stetig durch Almweiden, quert Schutt- und Blockfelder und gewinnt gleichmäßig Höhe, bevor sie im oberen Abschnitt steiler wird. Mit zunehmender Höhe wandelt sich die Landschaft, das Panorama öffnet sich zum Monte-Rosa-Massiv. Die Bewertung EE begründet sich durch Höhenlage, Streckenlänge und anspruchsvolles Gelände. Empfohlen Juli bis September.",
    "shortDescription_it": "Da Saint-Jacques il lungo itinerario EE al Mont Roisetta risale pascoli, macereti e versanti d'alta montagna della Val d'Ayas, con panorama sul Monte Rosa.",
    "shortDescription_en": "From Saint-Jacques, the demanding EE route to Mont Roisetta climbs pastures, scree and high-mountain terrain in the Val d'Ayas, with views toward Monte Rosa.",
    "shortDescription_fr": "Depuis Saint-Jacques, l'exigeant itinéraire EE au Mont Roisetta remonte pâturages, éboulis et versants de haute montagne, avec panorama sur le Mont-Rose.",
    "shortDescription_de": "Von Saint-Jacques führt der anspruchsvolle EE-Weg auf den Mont Roisetta über Almen, Geröll und Hochgebirgshänge mit Blick auf den Monte Rosa.",
    "warnings_it": ["Itinerario EE: richiede esperienza in alta montagna, orientamento e condizioni meteo stabili.", "Neve e ghiaccio residui possibili fino a luglio sulla sezione superiore."],
    "warnings_en": ["EE route: high-mountain experience, route-finding ability and stable weather are required.", "Residual snow and ice possible until July in the upper section."],
    "warnings_fr": ["Itinéraire EE : expérience en haute montagne, orientation et conditions météorologiques stables requis.", "Neige et glace résiduelles possibles jusqu'en juillet dans la section supérieure."],
    "warnings_de": ["EE-Route: Hochgebirgserfahrung, Orientierungssinn und stabile Wetterlage erforderlich.", "Restschnee und Eis im oberen Abschnitt bis Juli möglich."],
    "updated_at": "2026-06-01"
  },
  "07-s25": {
    "description_it": "Il percorso da Blanchard al Colle Inferiore delle Cime Bianche conduce nel cuore del Vallone delle Cime Bianche, uno degli ambienti di alta montagna più integri della Val d'Ayas. La partenza avviene da Blanchard (1731 m). Con 1167 m di dislivello in 8 km, la progressione è lunga e richiede allenamento. Il tracciato risale il vallone sul lato sinistro orografico, alternando tratti su prateria, zone umide, piccoli specchi d'acqua e terreno più roccioso in quota. Il Colle Inferiore delle Cime Bianche (2892 m) è un colletto incastonato tra le vette omonime che separano la Val d'Ayas dalla Valtournenche. L'area è inclusa nella rete Natura 2000 per il suo valore naturalistico e geologico. La classificazione EE riflette la quota elevata e la presenza di terreno impervio nella sezione finale.",
    "description_en": "The route from Blanchard to the Colle Inferiore delle Cime Bianche leads into the heart of the Vallone delle Cime Bianche, one of the most pristine high-mountain environments in Val d'Ayas. The walk starts at Blanchard (1731 m). With 1167 m of ascent over 8 km, the route is long and demands fitness. The path climbs the valley on the left orographic side, alternating meadow, wetland, small lakes and rockier terrain. The Colle Inferiore delle Cime Bianche (2892 m) separates Val d'Ayas from Valtournenche. The area is in the Natura 2000 network. The EE rating reflects the high altitude and demanding terrain in the final section.",
    "description_fr": "L'itinéraire de Blanchard au Colle Inferiore delle Cime Bianche mène au coeur du Vallone delle Cime Bianche, l'un des environnements de haute montagne les plus préservés de la Val d'Ayas. Au départ de Blanchard (1731 m), avec 1167 m de dénivelé sur 8 km, la progression est longue. Le tracé remonte le vallon sur la rive gauche, alternant prairies, zones humides, petits lacs et terrain rocheux. Le Colle Inferiore delle Cime Bianche (2892 m) sépare la Val d'Ayas de la Valtournenche. Zone Natura 2000. La cotation EE reflète l'altitude et le terrain délicat.",
    "description_de": "Der Weg von Blanchard zum Colle Inferiore delle Cime Bianche führt ins Herz des Vallone delle Cime Bianche, einer der unberührtesten Hochgebirgslandschaften des Val d'Ayas. Start ist Blanchard (1731 m). Mit 1167 Hm auf 8 km ist die Route lang und konditionell fordernd. Der Pfad steigt auf der linken Orographieseite auf, wechselt zwischen Wiesen, Feuchtgebieten, kleinen Seen und felsigem Gelände. Der Colle Inferiore delle Cime Bianche (2892 m) trennt Val d'Ayas und Valtournenche. Natura-2000-Gebiet. EE-Bewertung wegen Höhenlage und Terrain im Schlussabschnitt.",
    "shortDescription_it": "Da Blanchard il lungo itinerario EE risale il Vallone delle Cime Bianche fino al Colle Inferiore a 2892 m, valico fra Val d'Ayas e Valtournenche.",
    "shortDescription_en": "From Blanchard, the long EE route climbs the Vallone delle Cime Bianche to the Colle Inferiore at 2892 m, the pass between Val d'Ayas and Valtournenche.",
    "shortDescription_fr": "Depuis Blanchard, le long itinéraire EE remonte le Vallone delle Cime Bianche jusqu'au Colle Inferiore à 2892 m, col entre Val d'Ayas et Valtournenche.",
    "shortDescription_de": "Von Blanchard steigt der lange EE-Weg durch das Vallone delle Cime Bianche zum Colle Inferiore auf 2892 m, dem Pass zwischen Val d'Ayas und Valtournenche.",
    "warnings_it": ["Itinerario EE: richiede esperienza in alta montagna.", "Neve residua nel vallone fino a metà luglio."],
    "warnings_en": ["EE section: high-mountain experience required.", "Residual snow in the valley until mid-July."],
    "warnings_fr": ["Section EE : expérience en haute montagne requise.", "Neige résiduelle dans le vallon jusqu'à mi-juillet."],
    "warnings_de": ["EE-Abschnitt: Hochgebirgserfahrung erforderlich.", "Restschnee im Tal bis Mitte Juli."],
    "updated_at": "2026-06-01"
  },
  "07-s38": {
    "description_it": "Il breve itinerario da Crest al Lac Chercherioz percorre il versante soprastante la Valle d'Aosta centrale, nel comune di Avise, risalendo in poco più di 3.8 km un vallone laterale che porta a un lago di quota. La partenza avviene da Crest (1976 m), già in quota. Il dislivello di 428 m è contenuto rispetto alla quota di arrivo, consentendo una progressione regolare su terreno aperto. Il Lac Chercherioz (2354 m) è il traguardo: un lago alpino inserito in un contesto di praterie e rocce, con l'apertura panoramica tipica dei versanti esposti della Valle centrale. La classificazione E indica un itinerario adatto a escursionisti con normale preparazione, privo di difficoltà tecniche.",
    "description_en": "The short route from Crest to Lac Chercherioz climbs a side valley above the central Aosta Valley in the commune of Avise, covering just over 3.8 km to reach a high-altitude lake. The walk starts at Crest (1976 m), already at elevation. The 428 m elevation gain is modest relative to the arrival altitude, allowing a steady progression over open terrain. Lac Chercherioz (2354 m) is the objective: an alpine lake set among meadows and rock, with the panoramic openness typical of exposed slopes in the central valley. The E rating marks a route suited to hikers of average fitness.",
    "description_fr": "Le court itinéraire de Crest au Lac Chercherioz remonte un vallon latéral au-dessus de la vallée centrale d'Aoste dans la commune d'Avise, sur un peu plus de 3.8 km. Le départ s'effectue depuis Crest (1976 m), déjà en altitude. Le dénivelé de 428 m permet une progression régulière sur terrain ouvert. Le Lac Chercherioz (2354 m) est le but : un lac alpin niché entre prairies et roches. La cotation E signale un parcours adapté aux randonneurs ordinaires.",
    "description_de": "Der kurze Weg von Crest zum Lac Chercherioz steigt ein Seitental oberhalb des zentralen Aostatals in der Gemeinde Avise hinauf und legt auf gut 3.8 km den Weg zu einem Hochgebirgssee zurück. Start ist Crest (1976 m), bereits auf Höhe. Die 428 Hm erlauben eine gleichmäßige Wanderung über offenes Gelände. Der Lac Chercherioz (2354 m) ist das Ziel: ein Alpensee in einer Wiesen-Fels-Landschaft. Bewertung E: für Wanderer mit normaler Kondition.",
    "shortDescription_it": "Da Crest (1976 m) una salita breve e regolare conduce al Lac Chercherioz (2354 m), lago alpino tra praterie e rocce nel comune di Avise.",
    "shortDescription_en": "From Crest (1976 m) a short steady climb reaches Lac Chercherioz (2354 m), an alpine lake among meadows and rock in the commune of Avise.",
    "shortDescription_fr": "Depuis Crest (1976 m), une courte montée régulière mène au Lac Chercherioz (2354 m), lac alpin entre prairies et roches dans la commune d'Avise.",
    "shortDescription_de": "Von Crest (1976 m) führt ein kurzer, gleichmäßiger Aufstieg zum Lac Chercherioz (2354 m), einem Alpensee zwischen Wiesen und Fels in der Gemeinde Avise.",
    "updated_at": "2026-06-01"
  },
  "07-s6": {
    "description_it": "Il sentiero da Barmasc al Col Pillonnet risale uno dei passi che mettono in comunicazione la Val d'Ayas con la Valtournenche, toccando la quota di 2698 m in appena 3.7 km con un dislivello di 799 m. La partenza avviene da Barmasc (1898 m). Dal parcheggio si imbocca il sentiero 2A, segnalato con bolli gialli e neri, che risale il versante in maniera diretta. Il tracciato incrocia presto il Ru Courtod, poi procede verso la zona dell'Alpe Corneuil, guadagnando quota con pendenza sostenuta. La sezione finale porta al Col Pillonnet: una sella aperta sul versante di Chamois con un panorama che si allarga verso entrambe le vallate. La classificazione E rispecchia un percorso tecnicamente semplice, ma con tratti ripidi che richiedono attenzione. Consigliato dalla fine di maggio a ottobre.",
    "description_en": "The trail from Barmasc to Col Pillonnet climbs one of the passes linking the Val d'Ayas with the Valtournenche, reaching 2698 m in just 3.7 km with 799 m of elevation gain. The walk begins at Barmasc (1898 m). From the car park, trail 2A climbs the slope directly, soon crossing the Ru Courtod stream, then continues toward the Alpe Corneuil area, gaining height steadily. The final section leads to Col Pillonnet: an open saddle on the Chamois side offering views across both valleys. The E rating reflects a technically straightforward route with steep sections requiring care. Recommended from late May to October.",
    "description_fr": "Le sentier de Barmasc au Col Pillonnet remonte l'un des cols reliant la Val d'Ayas à la Valtournenche, atteignant 2698 m en seulement 3.7 km avec 799 m de dénivelé. Le départ s'effectue depuis Barmasc (1898 m). Le sentier 2A monte le versant directement, croise bientôt le Ru Courtod, puis continue vers la zone de l'Alpe Corneuil. La section finale mène au Col Pillonnet : une selle ouverte sur le versant de Chamois. La cotation E reflète un parcours techniquement simple avec des sections raides. Recommandé de fin mai à octobre.",
    "description_de": "Der Weg von Barmasc zum Col Pillonnet steigt einen der Übergänge zwischen Val d'Ayas und Valtournenche auf, erreicht 2698 m auf nur 3.7 km mit 799 Hm. Start ist Barmasc (1898 m). Der Weg 2A steigt direkt den Hang hinauf, kreuzt bald den Ru Courtod und geht weiter zur Alpe Corneuil. Der Schlussabschnitt führt zum Col Pillonnet, einer offenen Scharte zur Chamois-Seite mit Blick auf beide Täler. Bewertung E: technisch einfach, aber steile Passagen erfordern Aufmerksamkeit. Empfohlen von Ende Mai bis Oktober.",
    "shortDescription_it": "Da Barmasc il sentiero 2A scala in modo diretto il Col Pillonnet (2698 m), valico tra Val d'Ayas e Valtournenche, con 799 m di dislivello in 3.7 km.",
    "shortDescription_en": "From Barmasc, trail 2A climbs directly to Col Pillonnet (2698 m), the pass between Val d'Ayas and Valtournenche, with 799 m of ascent in 3.7 km.",
    "shortDescription_fr": "Depuis Barmasc, le sentier 2A monte directement au Col Pillonnet (2698 m), col entre Val d'Ayas et Valtournenche, avec 799 m de dénivelé en 3.7 km.",
    "shortDescription_de": "Von Barmasc steigt Weg 2A direkt auf den Col Pillonnet (2698 m), den Übergang zwischen Val d'Ayas und Valtournenche, mit 799 Hm auf 3.7 km.",
    "warnings_it": ["Alcuni tratti del tracciato sono poco evidenti: seguire con attenzione la segnaletica gialla.", "Neve residua possibile fino a fine maggio/inizio giugno."],
    "warnings_en": ["Some sections of the path are faint: follow yellow markings carefully.", "Residual snow possible until late May/early June."],
    "warnings_fr": ["Certains tronçons du tracé sont peu visibles : suivre attentivement le balisage jaune.", "Neige résiduelle possible jusqu'à fin mai/début juin."],
    "warnings_de": ["Einige Wegabschnitte sind schlecht erkennbar: gelbe Markierungen sorgfältig verfolgen.", "Restschnee bis Ende Mai/Anfang Juni möglich."],
    "updated_at": "2026-06-01"
  },
  "08-s13": {
    "description_it": "Il sentiero da Ozein alla Pointe de la Pierre è un itinerario classico del versante settentrionale della Val di Cogne, con partenza dalla frazione Ozein del comune di Aymavilles (1371 m) e arrivo in quota a 2642 m, per un dislivello di 1293 m in 7.5 km. Il sentiero risale dapprima attraverso la foresta, poi su strade forestali che conducono ai pascoli di Romperein, attraversa un pianoro erboso portandosi sul versante settentrionale, attraversa una seconda fascia boscata di conifere e tocca l'alpeggio di Champchenille prima di guadagnare la zona sommitale. La Pointe de la Pierre è un punto panoramico aperto sul bacino di Pila, sulla Valle d'Aosta centrale e sulle catene montuose circostanti. La classificazione E indica un percorso escursionistico regolare e frequentato, adatto a camminatori allenati. L'itinerario è frequentato anche in inverno con le racchette da neve.",
    "description_en": "The trail from Ozein to Pointe de la Pierre is a classic route on the northern flank of Val di Cogne, departing from Ozein in Aymavilles (1371 m) and arriving at 2642 m, covering 1293 m of ascent over 7.5 km. The path climbs first through forest, then along farm tracks to the Romperein pastures, crosses an open meadow to the northern face, passes through a second conifer forest belt and reaches the Champchenille alp before approaching the summit zone. Pointe de la Pierre offers open views across the Pila basin, the central Aosta Valley and surrounding mountain chains. The E rating marks a well-frequented hiking route for fit walkers. Also popular as a winter snowshoe route.",
    "description_fr": "Le sentier d'Ozein à la Pointe de la Pierre est un itinéraire classique du versant nord de la Val di Cogne, au départ d'Ozein dans la commune d'Aymavilles (1371 m), jusqu'à 2642 m, avec 1293 m de dénivelé sur 7.5 km. Le sentier monte d'abord en forêt, puis par des pistes forestières jusqu'aux pâturages de Romperein, traverse un replat herbeux, passe par une deuxième ceinture de conifères et atteint l'alpage de Champchenille avant la zone sommitale. La Pointe de la Pierre offre un panorama ouvert sur Pila, la Vallée d'Aoste centrale et les chaînes montagneuses. La cotation E signale un itinéraire bien fréquenté. Aussi fréquenté en raquettes l'hiver.",
    "description_de": "Der Weg von Ozein zur Pointe de la Pierre ist ein klassisches Itinerar am Nordhang des Val di Cogne, Ausgangspunkt ist der Weiler Ozein der Gemeinde Aymavilles (1371 m), Ziel 2642 m — 1293 Hm Aufstieg auf 7.5 km. Der Weg steigt zunächst durch den Wald, dann über Forstwege zu den Weiden von Romperein, quert einen offenen Grashang, durchquert einen zweiten Nadelwaldgürtel und erreicht die Alp Champchenille vor dem Gipfelbereich. Die Pointe de la Pierre bietet offene Sicht auf das Pila-Becken und das zentrale Aostatal. Im Winter auch als Schneeschuhroute beliebt.",
    "shortDescription_it": "Da Ozein la risalita alla Pointe de la Pierre attraversa foreste, alpeggi e praterie aperte fino a 2642 m, classico panoramico sul bacino di Pila e sulla Val di Cogne.",
    "shortDescription_en": "From Ozein, the ascent to Pointe de la Pierre climbs through forest, pastures and open alpine terrain to 2642 m, a classic viewpoint over the Pila basin and Val di Cogne.",
    "shortDescription_fr": "Depuis Ozein, la montée à la Pointe de la Pierre traverse forêts, alpages et pelouses ouvertes jusqu'à 2642 m, panoramique classique sur Pila et la Val di Cogne.",
    "shortDescription_de": "Von Ozein führt der Aufstieg zur Pointe de la Pierre durch Wald, Almen und offene Almwiesen auf 2642 m — klassischer Aussichtspunkt über das Pila-Becken und die Val di Cogne.",
    "updated_at": "2026-06-01"
  },
  "08-s26": {
    "description_it": "Il sentiero da Vieyes al Bivacco Gontier percorre il versante boscato sopra la Val di Cogne, nel comune di Aymavilles, raggiungendo il bivacco Mario Gontier situato all'alpeggio di Grand Nomenon. La partenza avviene da Vieyes (1149 m). Il sentiero n° 5 sale attraverso il bosco verso le case di Plan Pessey, prosegue lungo il torrente, supera alcuni edifici abbandonati e attraversa il corso d'acqua su una passerella in legno in direzione delle case di Petit Nomenon. Risalendo ancora si raggiunge il pianoro di Grand Nomenon e il Bivacco Mario Gontier (2302 m). Il bivacco, inaugurato nel 1985 e dedicato a Mario Gontier, alpinista di Aymavilles scomparso nel 1983, dispone di posti letto e dotazioni di base. Con 1167 m di dislivello in 6.9 km, la classificazione E riflette un itinerario regolare e ben frequentato. Il periodo consigliato va da giugno a ottobre.",
    "description_en": "The trail from Vieyes to Bivacco Gontier climbs the wooded hillside above the Val di Cogne in Aymavilles, reaching the Mario Gontier bivouac at the Grand Nomenon pasture. The walk starts at Vieyes (1149 m). Trail no. 5 rises through the forest toward Plan Pessey, continues along the stream, passes abandoned buildings and crosses the watercourse on a wooden footbridge toward Petit Nomenon. Continuing uphill leads to the Grand Nomenon plateau and Bivacco Mario Gontier (2302 m). The bivouac, inaugurated in 1985 and dedicated to Mario Gontier, an Aymavilles mountaineer who died in 1983, is equipped with bunks and basic provisions. With 1167 m of ascent over 6.9 km, the E rating reflects a regular, well-frequented itinerary. Recommended from June to October.",
    "description_fr": "Le sentier de Vieyes au Bivouac Gontier remonte le versant boisé au-dessus de la Val di Cogne à Aymavilles, pour atteindre le bivouac Mario Gontier à l'alpage de Grand Nomenon. Le départ s'effectue depuis Vieyes (1149 m). Le sentier n° 5 monte en forêt vers Plan Pessey, longe le torrent, dépasse des bâtiments abandonnés et traverse le cours d'eau sur une passerelle vers Petit Nomenon. En continuant on atteint le replat de Grand Nomenon et le Bivouac Mario Gontier (2302 m). Le bivouac, inauguré en 1985 et dédié à Mario Gontier, montagnard d'Aymavilles disparu en 1983, est équipé de couchettes. Recommandé de juin à octobre.",
    "description_de": "Der Weg von Vieyes zum Bivacco Gontier steigt den bewaldeten Hang oberhalb der Val di Cogne in Aymavilles hinauf und erreicht die Biwakschachtel Mario Gontier auf der Alm Grand Nomenon. Start ist Vieyes (1149 m). Weg Nr. 5 steigt durch den Wald zu Plan Pessey, folgt dem Bach, passiert verlassene Gebäude und überquert das Gewässer auf einer Holzbrücke Richtung Petit Nomenon. Weiter aufwärts erreicht man Grand Nomenon und den Bivacco Mario Gontier (2302 m). Das 1985 eingeweihte Biwak ist Mario Gontier gewidmet und bietet Liegeplätze. Empfohlen Juni bis Oktober.",
    "shortDescription_it": "Da Vieyes il sentiero n° 5 risale bosco e pascoli del Val di Cogne fino al Bivacco Mario Gontier (2302 m) sull'alpeggio di Grand Nomenon: 1167 m di dislivello in ambiente silenzioso.",
    "shortDescription_en": "From Vieyes, trail no. 5 climbs through Val di Cogne forest and pastures to the Bivacco Mario Gontier (2302 m) on the Grand Nomenon alp: 1167 m of ascent in quiet surroundings.",
    "shortDescription_fr": "Depuis Vieyes, le sentier n° 5 remonte forêt et alpages de la Val di Cogne jusqu'au Bivouac Mario Gontier (2302 m) à l'alpage de Grand Nomenon : 1167 m de dénivelé.",
    "shortDescription_de": "Von Vieyes steigt Weg Nr. 5 durch Wald und Almen der Val di Cogne zum Bivacco Mario Gontier (2302 m) auf der Alm Grand Nomenon: 1167 Hm in stiller Umgebung.",
    "updated_at": "2026-06-01"
  },
  "10-s16": {
    "description_it": "Il percorso da Place Moulin all'Alpe Tsa de Tsan si sviluppa nell'alta Valpelline, nel comune di Bionaz, in un paesaggio di altissima montagna dominato dalle grandi masse glaciali che incorniciano la testata del vallone. La partenza avviene dalla diga di Place Moulin (2011 m), opera ingegneristica tra le più imponenti della regione, che trattiene un bacino artificiale nel cuore di una conca glaciale. Il tracciato si snoda per 10.9 km con un dislivello di 650 m. Il percorso segue il fianco del bacino, poi risale verso il pianoro dell'Alpe Tsa de Tsan (2615 m), nei pressi del ghiacciaio omonimo. L'ambiente è quello dell'alta montagna glaciale, con torrenti di fusione, morene, rocce levigate e un senso di vastità che caratterizza i grandi valloni della Valpelline. La classificazione E riflette l'assenza di difficoltà tecniche, ma la quota richiede attenzione alle condizioni atmosferiche. Percorribile da luglio a settembre.",
    "description_en": "The route from Place Moulin to Alpe Tsa de Tsan unfolds in the upper Valpelline in Bionaz, in a high-mountain landscape dominated by the glacial masses framing the valley head. The walk starts from the Place Moulin dam (2011 m), one of the most imposing engineering works in the region, which impounds a reservoir at the heart of a glacial basin. The route covers 10.9 km with 650 m of ascent. The path follows the reservoir shore, then climbs toward the Alpe Tsa de Tsan plateau (2615 m), close to the glacier of the same name. The environment is that of high glacial mountain: meltwater streams, moraines, smoothed bedrock and vast open scenery. The E rating reflects no technical difficulty, though the altitude calls for attention to weather. Advisable from July to September.",
    "description_fr": "L'itinéraire de Place Moulin à l'Alpe Tsa de Tsan se déroule dans la haute Valpelline, commune de Bionaz, dans un paysage de haute montagne dominé par les grandes masses glaciaires. Le départ s'effectue depuis le barrage de Place Moulin (2011 m), l'un des ouvrages les plus imposants de la région. Le parcours couvre 10.9 km avec un dénivelé de 650 m. Le tracé longe le réservoir, puis monte vers l'Alpe Tsa de Tsan (2615 m), à proximité du glacier homonyme. L'environnement est celui de la haute montagne glaciaire. La cotation E reflète l'absence de difficulté technique. Praticable de juillet à septembre.",
    "description_de": "Der Weg von Place Moulin zur Alpe Tsa de Tsan verläuft im oberen Valpelline, Gemeinde Bionaz, in einer Hochgebirgslandschaft, die von den Gletschermassen am Talschluss beherrscht wird. Start ist die Staumauer von Place Moulin (2011 m). Die Route umfasst 10.9 km mit 650 Hm Aufstieg. Der Weg folgt dem Seeufer, steigt dann zum Plateau der Alpe Tsa de Tsan (2615 m) auf. Das Umfeld ist das der hochglazialen Bergwelt. Bewertung E: keine technischen Schwierigkeiten, aber in der Höhe auf das Wetter achten. Empfohlen Juli bis September.",
    "shortDescription_it": "Dalla diga di Place Moulin il sentiero risale l'alta Valpelline verso l'Alpe Tsa de Tsan (2615 m), nel cuore di un paesaggio glaciale tra le quote più alte della Valle d'Aosta.",
    "shortDescription_en": "From the Place Moulin dam, the trail climbs the upper Valpelline to the Alpe Tsa de Tsan (2615 m), deep within a glacial landscape among the highest terrain of the Aosta Valley.",
    "shortDescription_fr": "Depuis le barrage de Place Moulin, le sentier remonte la haute Valpelline vers l'Alpe Tsa de Tsan (2615 m), au coeur d'un paysage glaciaire parmi les plus hauts de la Vallée d'Aoste.",
    "shortDescription_de": "Von der Staumauer Place Moulin steigt der Weg ins obere Valpelline zur Alpe Tsa de Tsan (2615 m) auf — mitten in einer Gletscherlandschaft in einem der höchsten Bereiche Aostatals.",
    "warnings_it": ["Zona glaciale: verificare le condizioni prima di avvicinarsi.", "Meteo instabile può sopraggiungere rapidamente in alta quota."],
    "warnings_en": ["Glacial zone: check conditions before approaching.", "Rapidly changing weather is possible at this altitude."],
    "warnings_fr": ["Zone glaciaire : vérifier les conditions avant de s'en approcher.", "Le temps peut changer rapidement à cette altitude."],
    "warnings_de": ["Gletscherzone: Bedingungen vor dem Annähern prüfen.", "In dieser Höhe kann das Wetter schnell umschlagen."],
    "updated_at": "2026-06-01"
  },
  "10-s4": {
    "description_it": "Il sentiero da Chez-Chenoux all'Alpe Chardonney sale rapidamente attraverso il bosco che ricopre il basso versante della Valpelline, nel comune di Bionaz, per poi aprirsi sui pascoli del vasto bacino di Vertsan. La partenza avviene da Chez-Chenoux (1702 m). Il sentiero n° 5 sale deciso attraverso il bosco, con tornanti ripidi nella fascia forestata, prima di emergere su un terreno aperto di praterie ampie. Si attraversa il bacino della Comba di Vertsan, delimitato da vette tra cui Pic de Châtermontane, Monte Cervo e Mont de Crête Sèche, fino a raggiungere i ruderi dell'Alpe Chardonney (2519 m). Il dislivello di 810 m in 4.6 km concentra la fatica nella prima parte della salita nel bosco. La classificazione E riflette un percorso escursionistico senza difficoltà tecniche, adatto a chi è allenato.",
    "description_en": "The path from Chez-Chenoux to Alpe Chardonney climbs rapidly through the forest covering the lower Valpelline slope in Bionaz, before opening onto the pastures of the broad Vertsan basin. The walk starts at Chez-Chenoux (1702 m). Trail no. 5 climbs steeply through the woodland with tight switchbacks in the forested section, before emerging onto open pastoral terrain. The route crosses the Comba di Vertsan basin — bounded by summits including Pic de Châtermontane, Monte Cervo and Mont de Crête Sèche — to reach the ruins of Alpe Chardonney (2519 m). The 810 m ascent over 4.6 km concentrates effort in the early woodland section. The E rating indicates no technical difficulty for fit hikers.",
    "description_fr": "Le sentier de Chez-Chenoux à l'Alpe Chardonney monte rapidement à travers la forêt du bas versant de la Valpelline dans la commune de Bionaz, avant de s'ouvrir sur les pâturages du vaste bassin de Vertsan. Le départ s'effectue depuis Chez-Chenoux (1702 m). Le sentier n° 5 monte résolument en forêt avec des lacets serrés dans la zone boisée, avant de s'ouvrir sur un terrain pastoral plus ouvert. L'itinéraire traverse le bassin de la Comba di Vertsan jusqu'aux ruines de l'Alpe Chardonney (2519 m). Le dénivelé de 810 m sur 4.6 km concentre l'effort en début de montée. La cotation E indique l'absence de difficulté technique.",
    "description_de": "Der Weg von Chez-Chenoux zur Alpe Chardonney steigt rasch durch den Wald am Unterhang der Valpelline in der Gemeinde Bionaz auf, bevor er sich auf die Weiden des weiten Vertsan-Beckens öffnet. Start ist Chez-Chenoux (1702 m). Weg Nr. 5 steigt zügig durch den Wald mit engen Kehren auf, bevor er auf offenes Weideland austritt. Der Weg quert das Becken der Comba di Vertsan bis zu den Ruinen der Alpe Chardonney (2519 m). Die 810 Hm auf 4.6 km konzentrieren den Aufwand im frühen Waldabschnitt. Bewertung E: keine technischen Schwierigkeiten.",
    "shortDescription_it": "Da Chez-Chenoux il sentiero supera rapidamente la fascia boscata e sbuca sui pascoli della Comba di Vertsan fino ai ruderi dell'Alpe Chardonney (2519 m), nel silenzio dell'alta Valpelline.",
    "shortDescription_en": "From Chez-Chenoux the trail quickly clears the forest belt and opens onto the Comba di Vertsan pastures, climbing to the ruins of Alpe Chardonney (2519 m) in the quiet upper Valpelline.",
    "shortDescription_fr": "Depuis Chez-Chenoux, le sentier franchit rapidement la zone forestière et débouche sur les pâturages de la Comba di Vertsan jusqu'aux ruines de l'Alpe Chardonney (2519 m).",
    "shortDescription_de": "Von Chez-Chenoux überwindet der Weg rasch den Waldgürtel und öffnet sich auf die Weiden der Comba di Vertsan bis zu den Ruinen der Alpe Chardonney (2519 m) im stillen oberen Valpelline.",
    "updated_at": "2026-06-01"
  },
  "11-s7": {
    "description_it": "Il tratto dal Bivacco Menabreaz al Col d'Arbolle è la sezione alta di un itinerario che raggiunge uno dei passi più isolati del settore montuoso tra Brissogne e Charvensod, nel contesto del massiccio del Monte Emilius. Il Bivacco Mario Ernesto Ménabreaz (2546 m) sorge sulle rive del Lago Les Laures, ed è il punto di partenza di questa sezione. Dal bivacco, il sentiero risale verso il Col d'Arbolle (3154 m) con 604 m di dislivello in 4.5 km, attraversando un ambiente di alta montagna con pareti rocciose, ghiaioni e zona di crinale tra la Punta Rossa e il Monte Emilius. La classificazione EE rispecchia la quota elevata, la presenza di passaggi su terreno impervio e la difficoltà di orientamento nella sezione finale. Il Col d'Arbolle mette in comunicazione la Valle di Brissogne con i valloni verso Pila e Charvensod.",
    "description_en": "The section from Bivacco Menabreaz to Col d'Arbolle is the high section of a route reaching one of the most isolated passes in the Monte Emilius massif between Brissogne and Charvensod. The Bivacco Mario Ernesto Ménabreaz (2546 m) stands on the shores of Lago Les Laures and is the starting point. From the bivouac, the trail climbs to Col d'Arbolle (3154 m) with 604 m of ascent over 4.5 km, crossing a high-mountain environment of rocky walls, scree and ridgeline terrain between Punta Rossa and Monte Emilius. The EE rating reflects the high altitude, demanding terrain and difficulty of route-finding in the final section. Col d'Arbolle links the Brissogne valley with approaches to Pila and Charvensod.",
    "description_fr": "Le tronçon du Bivouac Menabreaz au Col d'Arbolle est la section supérieure d'un itinéraire atteignant l'un des cols les plus isolés du massif du Monte Emilius entre Brissogne et Charvensod. Le Bivouac Mario Ernesto Ménabreaz (2546 m) se trouve sur les rives du Lac Les Laures. Depuis le bivouac, le sentier monte au Col d'Arbolle (3154 m) avec 604 m de dénivelé sur 4.5 km, à travers un environnement de haute montagne avec parois rocheuses, éboulis et zone de crête. La cotation EE reflète l'altitude élevée et le terrain exigeant. Le Col d'Arbolle relie la vallée de Brissogne aux approches de Pila et Charvensod.",
    "description_de": "Der Abschnitt vom Bivacco Menabreaz zum Col d'Arbolle ist der Hochabschnitt einer Route, die einen der abgelegensten Pässe im Monte-Emilius-Massiv zwischen Brissogne und Charvensod erreicht. Der Bivacco Mario Ernesto Ménabreaz (2546 m) steht am Ufer des Lago Les Laures. Vom Biwak steigt der Weg zum Col d'Arbolle (3154 m) mit 604 Hm auf 4.5 km auf und durchquert eine Hochgebirgslandschaft aus Felswänden, Geröll und Gratkamm. Die Bewertung EE begründet sich durch die Höhenlage und anspruchsvolles Terrain. Der Col d'Arbolle verbindet die Brissogne-Seite mit den Zugängen zu Pila und Charvensod.",
    "shortDescription_it": "Dal Bivacco Menabreaz (2546 m) sulle rive del Lago Les Laures, l'itinerario EE risale verso il Col d'Arbolle (3154 m), valico remoto nel massiccio del Monte Emilius sopra Brissogne.",
    "shortDescription_en": "From Bivacco Menabreaz (2546 m) on the shores of Lago Les Laures, the EE route climbs to the Col d'Arbolle (3154 m), a remote pass in the Monte Emilius massif above Brissogne.",
    "shortDescription_fr": "Depuis le Bivouac Menabreaz (2546 m) sur les rives du Lac Les Laures, l'itinéraire EE monte au Col d'Arbolle (3154 m), col isolé dans le massif du Monte Emilius au-dessus de Brissogne.",
    "shortDescription_de": "Vom Bivacco Menabreaz (2546 m) am Ufer des Lago Les Laures führt der EE-Weg zum Col d'Arbolle (3154 m), einem abgelegenen Pass im Monte-Emilius-Massiv oberhalb von Brissogne.",
    "warnings_it": ["Tratto EE ad alta quota: obbligatorio avere esperienza in alta montagna.", "Neve e ghiaccio possibili fino ad estate inoltrata.", "Isolamento elevato: portare materiale d'emergenza."],
    "warnings_en": ["High-altitude EE section: high-mountain experience obligatory.", "Snow and ice possible until late summer.", "High remoteness: carry emergency equipment."],
    "warnings_fr": ["Section EE en haute altitude : expérience en haute montagne obligatoire.", "Neige et glace possibles jusqu'en été avancé.", "Isolement élevé : emporter le matériel d'urgence."],
    "warnings_de": ["Hochgelegener EE-Abschnitt: Hochgebirgserfahrung ist Pflicht.", "Schnee und Eis bis in den Spätsommer möglich.", "Große Abgelegenheit: Notfallausrüstung mitführen."],
    "updated_at": "2026-06-01"
  },
  "12-s2": {
    "description_it": "Il percorso da Arcésaz a Brusson è una passeggiata di fondovalle nella Val d'Ayas, classificata T (Turistico), ideale per chi cerca un itinerario semplice e accessibile. La partenza avviene da Arcésaz (1133 m), prima frazione che si incontra entrando nel comune di Brusson dalla strada regionale proveniente da Verrès. Il tracciato si svolge in discesa moderata su sentieri e stradine, seguendo in parte il canale irriguo ru d'Arlaz, immerso nella vegetazione di mezzacosta della valle con scorci sulle frazioni circostanti e sul paesaggio boscato. Si toccano le località di Ponteil e il piano di Plan de Servaz, passando per il percorso vita di Guillates, per arrivare alla strada regionale nei pressi di Brusson (1276 m). I 3.6 km e i soli 143 m di dislivello rendono questo itinerario adatto a ogni tipo di utente, incluse famiglie con bambini piccoli.",
    "description_en": "The walk from Arcésaz to Brusson is a valley-floor stroll in the Val d'Ayas, rated T (Tourist), ideal for those seeking a simple, accessible itinerary. The walk starts at Arcésaz (1133 m), the first hamlet encountered entering the Brusson commune from the regional road from Verrès. The route descends gently along paths and minor tracks, partly following the ru d'Arlaz irrigation canal, set within mid-slope vegetation with views of surrounding hamlets and woodland. The path passes through Ponteil and Plan de Servaz, through the Guillates fitness trail, arriving near Brusson (1276 m). The 3.6 km and modest 143 m make this suited to all users including families with young children.",
    "description_fr": "La promenade d'Arcésaz à Brusson est une balade de fond de vallée dans la Val d'Ayas, cotée T (Touristique), idéale pour un itinéraire simple et accessible. Le départ s'effectue depuis Arcésaz (1133 m). Le tracé descend doucement sur des sentiers, en partie le long du canal d'irrigation ru d'Arlaz, avec des vues sur les hameaux environnants. Le parcours passe par Ponteil et Plan de Servaz, à travers le parcours vita de Guillates, pour arriver près de Brusson (1276 m). Les 3.6 km et les 143 m de dénivelé font de cet itinéraire un parcours adapté à tous.",
    "description_de": "Die Wanderung von Arcésaz nach Brusson ist ein Talspaziergang im Val d'Ayas, bewertet T (Touristisch), ideal für einen einfachen, barrierefreien Weg. Start ist Arcésaz (1133 m). Der Weg verläuft in moderatem Abstieg auf Pfaden, teils entlang des Bewässerungskanals Ru d'Arlaz, mit Blicken auf umliegende Weiler. Der Weg berührt Ponteil und Plan de Servaz sowie den Fitnessparcours von Guillates und endet bei Brusson (1276 m). Die 3.6 km und bescheidenen 143 Hm machen diesen Weg für alle geeignet.",
    "shortDescription_it": "Passeggiata T da Arcésaz a Brusson lungo canali irrigui e sentieri di mezzacosta nella Val d'Ayas: 3.6 km senza difficoltà, adatta a famiglie e a ogni livello.",
    "shortDescription_en": "An easy T-rated stroll from Arcésaz to Brusson along irrigation canals and mid-slope paths in the Val d'Ayas: 3.6 km, no difficulty, suitable for families and all levels.",
    "shortDescription_fr": "Promenade T d'Arcésaz à Brusson le long des canaux d'irrigation et des sentiers de mi-versant : 3.6 km sans difficulté, adaptée à tous.",
    "shortDescription_de": "Leichter T-Spaziergang von Arcésaz nach Brusson entlang von Bewässerungskanälen und Hangwegen im Val d'Ayas: 3.6 km, keine Schwierigkeit, für alle geeignet.",
    "updated_at": "2026-06-01"
  }
}`);

function caiDuration(km, gain, loss) {
  const h = km / 4 + Math.max(gain, 0) / 400 + Math.max(loss, 0) / 600;
  return Math.max(0.5, Math.round(h * 2) / 2);
}
const diffToFitness = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };

const skPath = require('path').join(__dirname, '../src/data/trails-skeleton.json');
const sk = JSON.parse(require('fs').readFileSync(skPath, 'utf8'));
let changed = 0;

const merged = sk.map(t => {
  const p = patch[t.slug];
  if (!p) return t;
  changed++;
  const fixes = {};
  if (t.duration_hours === null || t.duration_hours === undefined)
    fixes.duration_hours = caiDuration(t.distance_km, t.elevation_gain_m, t.elevation_loss_m);
  if (t.mobile_coverage === null || t.mobile_coverage === undefined)
    fixes.mobile_coverage = 'partial';
  if (t.fitness_level === null || t.fitness_level === undefined)
    fixes.fitness_level = diffToFitness[t.difficulty] ?? 2;
  if (!t.name_en) fixes.name_en = t.name_it;
  if (!t.name_fr) fixes.name_fr = t.name_it;
  if (!t.name_de) fixes.name_de = t.name_it;
  return { ...t, ...fixes, ...p };
});

console.log('Patchati:', changed);
fs.writeFileSync(skPath, JSON.stringify(merged, null, 2), 'utf8');
console.log('OK');
