'use strict';
// Round 2 — blocco G (finale): BQ + BR (10 sentieri).
const fs = require('fs');
const path = require('path');
const skPath = path.join(__dirname, '../src/data/trails-skeleton.json');
function cai(km, gain, loss) { return Math.max(0.5, Math.round((km/4+Math.max(gain,0)/400+Math.max(loss,0)/600)*2)/2); }
const diffToFitness = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };

const patch = {
  "07-s61": {
    description_it: "Il sentiero sale deciso da Champoluc (1569 m) attraverso i pascoli alti della Val d'Ayas, seguendo in parte il tracciato dell'Alta Via della Valle d'Aosta n.1. Il percorso è impegnativo fin dai primi tratti: i boschi di larici lasciano rapidamente spazio agli alpi aperti, poi alle morene e infine alle pietraie d'alta quota. Il dislivello positivo di 1623 metri in soli 7,7 km impone un passo costante e attenzione al meteo, che in questa vallata può cambiare con rapidità. Il Bivacco Lateltin, a 3121 metri, è intitolato a Ulrich Lateltin, scomparso nel 1984, e rappresenta un punto di appoggio essenziale per gli alpinisti diretti alle cime circostanti. La struttura offre un riparo spartano ma sicuro, immersa in un paesaggio di rocce e ghiacciai che ripaga ampiamente la fatica della salita.",
    description_en: "The trail climbs steeply from Champoluc (1569 m) through the high pastures of Val d'Ayas, partly following the route of the Alta Via n.1. The 1623 m of elevation gain over 7.7 km demands a steady pace and careful weather awareness. Larch forests give way to open alp, then moraines and high-altitude scree. The Bivacco Lateltin at 3121 m, dedicated to Ulrich Lateltin who died in 1984, provides a basic but essential shelter for mountaineers tackling the surrounding summits, set in a landscape of rock and ice that amply rewards the effort.",
    description_fr: "Le sentier monte depuis Champoluc (1569 m) à travers les alpages de la Val d'Ayas, en suivant en partie le tracé de la Haute Route n.1. Le dénivelé de 1623 m en 7,7 km impose un rythme soutenu. Les forêts de mélèzes cèdent la place aux alpages, puis aux moraines et éboulis d'altitude. Le Bivouac Lateltin, à 3121 m, dédié à Ulrich Lateltin disparu en 1984, offre un refuge spartiate mais sûr dans un paysage de roches et de glaciers qui récompense largement l'effort.",
    description_de: "Der Weg steigt steil von Champoluc (1569 m) durch die Hochweiden des Val d'Ayas auf, teilweise entlang der Alta Via Nr. 1. Der Höhenunterschied von 1623 m auf 7,7 km verlangt ausdauerndes Gehen und Aufmerksamkeit für das Wetter. Lärchenwälder weichen offenen Almen, dann Moränen und Hochgebirgsschutt. Die Biwakschachtel Lateltin auf 3121 m, Ulrich Lateltin gewidmet (gest. 1984), bietet Bergsteigern einfache, aber verlässliche Unterkunft in einer Landschaft aus Fels und Eis, die die Mühe reichlich belohnt.",
    warnings_it: ["Itinerario EE: richiede esperienza alpinistica, orientamento oltre i 2800m, attrezzatura da alta montagna.", "Neve persistente fino a tarda stagione. Non adatto a escursionisti non esperti."],
    warnings_en: ["EE route: requires mountain experience, navigation above 2800 m, high-mountain equipment.", "Persistent snow into late season. Not suitable for inexperienced hikers."],
    warnings_fr: ["Itinéraire EE : expérience alpine, orientation au-delà de 2800 m, équipement de haute montagne requis.", "Neige persistante en fin de saison. Déconseillé aux randonneurs non expérimentés."],
    warnings_de: ["EE-Route: Bergerfahrung, Orientierung über 2800 m, Hochgebirgsausrüstung erforderlich.", "Anhaltender Schnee bis in die Spätsaison. Nicht für unerfahrene Wanderer."],
    updated_at: "2026-06-01"
  },
  "08-s19": {
    description_it: "Il percorso parte da Vieyes (1150 m), piccola borgata della Val di Cogne nel comune di Aymavilles, e risale con pendenza sostenuta verso gli alpeggi di Nomenon, protagonisti silenziosi di questa salita. Il sentiero non è mai banale: superata la fascia boscata iniziale, il tracciato si fa ripido in modo quasi ininterrotto per buona parte del percorso, rivelando panorami progressivamente più ampi sulla testata della valle. Gli alpeggi di Nomenon offrono uno spazio di respiro prima del tratto finale che porta al Bivacco Gontier, posizionato a 2302 metri in un ambiente aperto e ventoso. I 4,5 km di sviluppo con 1167 metri di dislivello si traducono in una pendenza media elevata che richiede gambe allenate e passo regolare. Un itinerario E adatto a escursionisti con buona preparazione fisica.",
    description_en: "Starting from Vieyes (1150 m) in the Val di Cogne, this short but steep route climbs 1167 m in just 4.5 km — one of the sharpest gradients in the valley. The path passes through the Nomenon alpine pastures before reaching the Bivacco Gontier at 2302 m. Wide views over the valley open progressively as the forest gives way to open meadows and high pasture. The near-continuous steepness demands strong legs and a steady rhythm.",
    description_fr: "Au départ de Vieyes (1150 m) dans la Val di Cogne, ce sentier court mais très raide gagne 1167 m en seulement 4,5 km. L'itinéraire traverse les alpages de Nomenon avant d'atteindre le Bivouac Gontier à 2302 m. La pente quasi ininterrompue exige des jambes solides et un rythme régulier ; la récompense est un panorama de plus en plus large sur la tête de vallée.",
    description_de: "Von Vieyes (1150 m) im Val di Cogne führt dieser kurze, aber sehr steile Weg auf 4,5 km 1167 Höhenmeter hinauf — einer der steilsten Anstiege im Tal. Der Pfad durchquert die Almen von Nomenon, bevor er das Biwak Gontier auf 2302 m erreicht. Die fast ununterbrochene Steigung verlangt kräftige Beine und gleichmäßiges Gehen, mit immer weiterem Blick auf den Talschluss.",
    updated_at: "2026-06-01"
  },
  "10-s12": {
    description_it: "Questo è uno dei rari percorsi di fondovalle della Valpelline che consente di apprezzare il paesaggio alpino senza impegni tecnici. Il tracciato si sviluppa per 4,6 km con un dislivello quasi nullo (soli 34 metri negativi), costeggiando le rive del bacino artificiale di Place Moulin, creato negli anni Sessanta del Novecento. L'acqua smeraldo del lago riflette le pareti rocciose circostanti e le cime innevate del fondo valle, regalando scorci fotografici di grande bellezza in ogni stagione. Partendo dalla diga di Place Moulin (2011 m) si percorre la sponda del bacino su sentiero comodo e ben segnato, raggiungendo il Rifugio Prarayer (2002 m), storico punto di sosta per chi si incammina verso il Colle del Gran San Bernardo o le mete alpinistiche della testata. Adatto a famiglie e a chi cerca una passeggiata tranquilla in ambiente d'alta quota.",
    description_en: "One of the few nearly flat valley-floor routes in Valpelline, this 4.6 km walk skirts the shores of the Place Moulin reservoir with a negligible elevation change of just 34 m. Built in the 1960s, the turquoise lake mirrors the surrounding rocky walls and snowy summits. The comfortable path links the dam at Place Moulin (2011 m) to the historic Rifugio Prarayer (2002 m), a base for ascents toward the head of the valley. Suitable for families and anyone seeking an easy walk in a high-altitude setting.",
    description_fr: "L'un des rares itinéraires quasi plats de la Valpelline, ce parcours de 4,6 km longe les rives du lac artificiel de Place Moulin avec un dénivelé négligeable de 34 m. Le lac turquoise, créé dans les années 1960, reflète les parois rocheuses et les sommets enneigés. Le sentier relie le barrage de Place Moulin (2011 m) au Refuge Prarayer (2002 m), point de départ historique vers la tête de vallée. Idéal pour les familles et les promenades tranquilles en altitude.",
    description_de: "Einer der wenigen nahezu flachen Talbodenwege im Valpelline: Auf 4,6 km mit kaum wahrnehmbarem Höhenunterschied (34 m) folgt der Weg dem Ufer des Stausees Place Moulin, der in den 1960er Jahren angelegt wurde. Das türkisfarbene Wasser spiegelt Felswände und Schneegipfel. Der bequeme Pfad verbindet den Staudamm Place Moulin (2011 m) mit der historischen Rifugio Prarayer (2002 m), einem Ausgangspunkt für Touren zum Talschluss. Ideal für Familien und ruhige Höhenspaziergänge.",
    updated_at: "2026-06-01"
  },
  "10-s5": {
    description_it: "L'itinerario percorre il fianco della Valpelline in un ampio traverso da Ru (1694 m) fino alla diga di Place Moulin (1990 m), coprendo 11,2 km con 535 metri di dislivello positivo. Nonostante il dato di quota contenuto, la classificazione EE è giustificata dalla natura del terreno: il sentiero attraversa versanti ripidi, tratti esposti e passaggi su traccia non sempre evidente, richiedendo buona esperienza escursionistica e piede fermo. Il percorso tocca diversi alpeggi tradizionali, testimoni di un sistema pastorale ancora vitale, e offre viste continue sui laghi artificiali che caratterizzano questa parte della valle. La vegetazione di versante — rododendri, ginepri e larici — incornicia il panorama verso le cime del Gran Combin e delle Alpi Pennine. Un itinerario che premia con ampiezza di vedute chi ha l'esperienza necessaria per affrontarlo.",
    description_en: "A long traverse across the flanks of Valpelline, covering 11.2 km from Ru (1694 m) to Place Moulin (1990 m) with 535 m of ascent. The EE rating reflects exposed sections and intermittently faint trail rather than sheer altitude. The route visits traditional alpine farms and overlooks the reservoir chain below, with sweeping views toward the Gran Combin and the Pennine Alps. Slope vegetation of rhododendron, juniper and larch frames the panorama throughout.",
    description_fr: "Une longue traversée sur les flancs de la Valpelline, de Ru (1694 m) à Place Moulin (1990 m) sur 11,2 km avec 535 m de dénivelé. La cotation EE reflète des passages exposés et un tracé parfois peu visible plutôt qu'une altitude extrême. Le sentier relie plusieurs alpages traditionnels et offre des vues sur les lacs artificiels et vers le Grand Combin et les Alpes Pennines.",
    description_de: "Eine lange Querung über die Hänge des Valpelline, von Ru (1694 m) nach Place Moulin (1990 m) über 11,2 km mit 535 Höhenmetern. Die EE-Einstufung widerspiegelt exponierte Abschnitte und einen stellenweise schwachen Pfad. Der Weg verbindet mehrere Bergalmen und bietet weite Blicke auf die Stauseen und zum Grand Combin und den Walliser Alpen.",
    warnings_it: ["Itinerario EE: tratti esposti e sentiero non sempre evidente. Esperienza e orientamento necessari.", "Percorso lungo (11,2 km): sconsigliato in caso di nebbia o terreno bagnato."],
    warnings_en: ["EE route: exposed sections and faint trail in places. Experience and navigation required.", "Long route (11.2 km): not advised in fog or wet ground."],
    warnings_fr: ["Itinéraire EE : passages exposés et tracé parfois peu visible. Expérience et orientation requises.", "Long parcours (11,2 km) : déconseillé par brouillard ou terrain mouillé."],
    warnings_de: ["EE-Route: ausgesetzte Stellen und stellenweise schwacher Pfad. Erfahrung und Orientierung nötig.", "Lange Strecke (11,2 km): bei Nebel oder Nässe nicht empfohlen."],
    updated_at: "2026-06-01"
  },
  "12-s11": {
    description_it: "Il Corno Boussolaz (3023 m) è una delle mete più ambite per gli escursionisti esperti della Val d'Ayas nel comprensorio di Brusson. Il percorso parte da Estoul (1884 m), graziosa frazione a quota elevata, e risale deciso attraverso pascoli e tracce d'alpeggio verso il Col de Palasinaz, valico che fa da cerniera tra la testata della valle e i versanti affacciati verso il Monterosa. Superato il colle, la traccia si fa più aerea e tecnica, con tratti su roccette e terreno instabile che giustificano pienamente la classificazione EE. Il panorama dalla cima — che tocca i 3023 metri — abbraccia la catena del Monte Rosa, le Grandes Murailles e, nelle giornate limpide, gran parte delle Alpi Pennine. I 1149 metri di dislivello positivo in 8,6 km impongono preparazione fisica e dotazione adeguata.",
    description_en: "The Corno Boussolaz (3023 m) is one of the most rewarding EE summits accessible from Brusson in Val d'Ayas. Starting at Estoul (1884 m), the route climbs 1149 m in 8.6 km via the Col de Palasinaz, a key pass linking the upper valley to the Monte Rosa slopes. The final section involves rock steps and unstable terrain before the panoramic summit, with views spanning the Monte Rosa massif, the Grandes Murailles and the Pennine Alps.",
    description_fr: "Le Corno Boussolaz (3023 m) est l'une des cibles EE les plus appréciées au départ de Brusson en Val d'Ayas. Partant d'Estoul (1884 m), l'itinéraire gagne 1149 m sur 8,6 km via le Col de Palasinaz. La section finale, sur rochers et terrain instable, précède un sommet panoramique sur le massif du Mont Rose, les Grandes Murailles et les Alpes Pennines.",
    description_de: "Das Corno Boussolaz (3023 m) ist eines der lohnendsten EE-Ziele ab Brusson im Val d'Ayas. Von Estoul (1884 m) steigt der Weg 1149 m auf 8,6 km über den Col de Palasinaz. Der Schlussabschnitt führt über Felsplatten und losen Untergrund, bevor sich das Panorama auf das Monte-Rosa-Massiv, die Grandes Murailles und die Walliser Alpen öffnet.",
    warnings_it: ["Itinerario EE: tratti su roccette e terreno franoso oltre il Col de Palasinaz.", "Quota oltre i 3000 m: rapidi cambiamenti meteo, neve possibile fino a luglio.", "Partenza nelle prime ore del mattino consigliata."],
    warnings_en: ["EE route: rock steps and loose terrain beyond Col de Palasinaz.", "Above 3000 m: rapid weather changes, snow possible until July.", "Early morning start recommended."],
    warnings_fr: ["Itinéraire EE : rochers et terrain instable au-delà du Col de Palasinaz.", "Au-delà de 3000 m : changements météo rapides, neige possible jusqu'en juillet.", "Départ matinal conseillé."],
    warnings_de: ["EE-Route: Felsplatten und loses Gelände jenseits des Col de Palasinaz.", "Über 3000 m: rasche Wetterwechsel, Schnee bis Juli möglich.", "Früher Start am Morgen empfohlen."],
    updated_at: "2026-06-01"
  },
  "12-s36": {
    description_it: "Il sentiero prende avvio dal cuore di Brusson, a 1277 metri di quota, e risale con continuità il versante orientale della Val d'Ayas fino alla Testa di Comagna, quota 2102 metri. In poco meno di cinque chilometri si guadagnano 820 metri di dislivello, percorrendo prima i margini del paese tra orti e frutteti, poi attraversando fasce boscate di larici e abeti che cedono gradualmente il passo agli alpeggi aperti. Il tracciato è ben segnalato e percorribile da escursionisti con buona preparazione fisica; la pendenza è sostenuta ma regolare. La Testa di Comagna offre un panorama ampio sull'intera vallata: si spazia dal fondovalle di Brusson fino ai ghiacciai del Monte Rosa a est, con la catena del Gran Paradiso visibile a ovest nelle giornate limpide. Un itinerario classico di mezza giornata, ideale in estate o nel primo autunno quando i colori del bosco aggiungono fascino al percorso.",
    description_en: "Starting from the centre of Brusson at 1277 m, this trail climbs steadily up the eastern flank of the Val d'Ayas to the summit of Testa di Comagna at 2102 m. Over five kilometres the path gains 820 metres in elevation, passing through orchards and village gardens before entering larch and fir woodland, then opening onto high-altitude pastures. Well marked throughout, the route suits hikers with a good level of fitness. The summit rewards with sweeping views over the valley, the Monte Rosa massif to the east and, on clear days, the Gran Paradiso chain to the west. A classic half-day outing, best enjoyed in summer or early autumn.",
    description_fr: "Depuis le centre de Brusson à 1277 m, le sentier remonte régulièrement le versant oriental du Val d'Ayas jusqu'à la Testa di Comagna à 2102 m. En moins de cinq kilomètres, on gagne 820 m de dénivelé en traversant vergers et jardins du village, puis une forêt de mélèzes et de sapins avant d'atteindre les alpages ouverts. Bien balisé et à pente soutenue mais régulière, l'itinéraire convient à des randonneurs en bonne condition physique. Au sommet, le panorama embrasse toute la vallée, le massif du Mont Rose à l'est et, par temps clair, la chaîne du Gran Paradiso à l'ouest. Une belle sortie de demi-journée.",
    description_de: "Der Weg beginnt im Ortskern von Brusson auf 1277 m und steigt gleichmäßig den östlichen Hang des Val d'Ayas bis zur Testa di Comagna auf 2102 m an. Auf knapp fünf Kilometern werden 820 Höhenmeter überwunden — zunächst durch Obstgärten und Dorfränder, dann durch Lärchen- und Tannenwald, schließlich über offene Hochweiden. Der gut markierte Pfad verlangt eine solide Grundkondition. Oben erwartet ein weites Panorama über das gesamte Tal, das Monte-Rosa-Massiv im Osten und — an klaren Tagen — die Gran-Paradiso-Kette im Westen. Ein klassischer Halbtagesausflug, besonders lohnend im Sommer und frühen Herbst.",
    updated_at: "2026-06-01"
  },
  "13-s32": {
    description_it: "Questo sentiero collega Arbaz, piccola frazione a 1499 metri sul versante meridionale della Val d'Ayas, alla vetta della Tete de Comagne posta a 2106 metri sul confine amministrativo tra i comuni di Brusson ed Etroubles. In soli 3,8 chilometri si affrontano 608 metri di dislivello positivo, il che rende il percorso più breve del contiguo itinerario verso la Testa di Comagna ma altrettanto impegnativo in termini di pendenza. Il versante è caratterizzato da pascoli aperti e rimboschimenti di conifere; la vegetazione si dirada man mano che si guadagna quota, lasciando spazio a rocce e arbusti nani. La posizione di confine tra le due vallate conferisce alla cima un vantaggio visivo eccezionale: a nord il circo glaciale del Monte Rosa, a sud i rilievi che digradano verso la Plaine di Aosta. Ottimo punto di partenza per chi alloggia nei rifugi o negli alpeggi della zona di Arbaz.",
    description_en: "Departing from the hamlet of Arbaz at 1499 m, this compact route ascends 608 metres over 3.8 kilometres to reach the Tete de Comagne at 2106 m, on the boundary between the municipalities of Brusson and Etroubles. The slope is consistent and demanding, crossing open pastures and sparse conifer stands before reaching the rocky upper section. The summit's position on the watershed divide delivers panoramic views towards the Monte Rosa cirque to the north and the Aosta plain to the south. A short but rewarding climb well suited to hikers based at the local alpeggi.",
    description_fr: "Depuis le hameau d'Arbaz à 1499 m, ce court itinéraire s'élève de 608 m sur 3,8 km jusqu'à la Tete de Comagne à 2106 m, sur la limite communale entre Brusson et Etroubles. La montée est franche et régulière, traversant des pâturages ouverts et des boisements de conifères clairsemés avant d'atteindre la partie rocheuse sommitale. Depuis ce point de partage des eaux, le panorama porte au nord vers le cirque glaciaire du Mont Rose et au sud vers la plaine d'Aoste. Une ascension brève mais exigeante.",
    description_de: "Von der kleinen Fraktion Arbaz auf 1499 m führt dieser kompakte Anstieg über 3,8 Kilometer und 608 Höhenmeter zur Tete de Comagne auf 2106 m, die auf der Gemeindegrenze zwischen Brusson und Etroubles liegt. Der Hang ist durchgehend steil und verläuft über offene Weiden und lichte Nadelwälder, bevor der felsige Gipfelbereich erreicht wird. Die Wasserscheidenlage verschafft einen freien Rundblick: im Norden das Gletscherkar des Monte Rosa, im Süden die Ebene von Aosta. Ein kurzer, aber konditionsfordernder Aufstieg.",
    updated_at: "2026-06-01"
  },
  "14-s5": {
    description_it: "Il sentiero per il Col Dondeuil è probabilmente l'itinerario escursionistico di maggiore impegno fisico dell'intero territorio di Challand-Saint-Victor. Si parte da Isollaz a soli 700 metri di quota — una delle quote di partenza più basse dei sentieri valdostani — e in nove chilometri si risale fino al valico a 2342 metri, accumulando un dislivello positivo di 1662 metri che è del tutto eccezionale per una classificazione E. Il tracciato attraversa nel suo sviluppo tutti gli ambienti tipici delle Alpi valdostane: i vigneti e i castagneti del fondovalle, le fasce boschive di roverelle e frassini, i rimboschimenti di larici nella fascia intermedia, gli alpeggi aperti e infine le rocce e i ghiaioni della zona del colle. Questa varietà di ecosistemi rende il percorso straordinariamente ricco dal punto di vista naturalistico. Il Col Dondeuil si apre su un panorama di grande ampiezza verso la testata della valle e verso i gruppi montuosi circostanti. Si raccomanda la partenza all'alba.",
    description_en: "The trail to Col Dondeuil is one of the most physically demanding hiking routes in the Challand-Saint-Victor area. Beginning at Isollaz, just 700 m above sea level — one of the lowest starting points in the Aosta Valley trail network — it climbs 1662 metres over nine kilometres to reach the col at 2342 m, an exceptional elevation gain for an E-grade route. The path crosses every typical Alpine environment in succession: valley-floor vineyards and chestnut groves, mixed oak and ash woodland, larch forest, open high pastures, and finally the rocky scree of the upper col. This ecological diversity makes the route outstanding for nature lovers. An early start is strongly recommended given the length and altitude gain.",
    description_fr: "Le sentier du Col Dondeuil est l'un des itinéraires de randonnée les plus physiquement exigeants de Challand-Saint-Victor. Il s'élance d'Isollaz à seulement 700 m d'altitude — l'un des points de départ les plus bas du réseau valdôtain — et grimpe sur neuf kilomètres jusqu'au col à 2342 m, accumulant 1662 m de dénivelé positif, un chiffre exceptionnel pour un classement E. Le tracé traverse successivement vignes et châtaigneraies, forêts de chênes et de frênes, mélézins, alpages et enfin les éboulis du col. Cette diversité écologique en fait un parcours d'une richesse naturaliste remarquable. Un départ à l'aube est fortement conseillé.",
    description_de: "Der Weg zum Col Dondeuil gehört zu den konditionell anspruchsvollsten Wanderungen im Gebiet von Challand-Saint-Victor. Er beginnt in Isollaz auf nur 700 m — einem der niedrigsten Ausgangspunkte im Wandernetz des Aostatals — und erklimmt über neun Kilometer bis zum Pass auf 2342 m insgesamt 1662 Höhenmeter, ein für eine E-Klassifikation außergewöhnlicher Wert. Der Pfad durchquert nacheinander Weinberge und Kastanienhaine, Eichen- und Eschenwälder, Lärchenwälder, offene Hochweiden sowie schließlich Geröllfelder unterhalb des Passes. Diese ökologische Vielfalt macht die Route naturkundlich außerordentlich wertvoll. Frühzeitiger Aufbruch wird dringend empfohlen.",
    warnings_it: ["Dislivello eccezionale di 1662 m: ottima preparazione fisica e partenza all'alba indispensabili.", "Verificare le condizioni meteo prima della partenza; abbigliamento a strati."],
    warnings_en: ["Exceptional 1662 m of ascent: excellent fitness and a dawn start essential.", "Check weather before departure; layered clothing."],
    warnings_fr: ["Dénivelé exceptionnel de 1662 m : excellente condition et départ à l'aube indispensables.", "Vérifier la météo avant le départ ; vêtements en couches."],
    warnings_de: ["Außergewöhnliche 1662 Höhenmeter: ausgezeichnete Kondition und Start im Morgengrauen erforderlich.", "Wetter vor dem Start prüfen; Schichtbekleidung."],
    updated_at: "2026-06-01"
  },
  "16-s3": {
    description_it: "Chamois è uno dei pochissimi comuni italiani completamente privo di strade carrozzabili: comune valdostano raggiungibile esclusivamente a piedi o con la funivia da Buisson. Da questo borgo sospeso a 1812 metri parte il sentiero verso il Col Pillonnet, valico a 2698 metri che mette in comunicazione la Valle Centrale con il versante di La Salle. In 4,3 chilometri si affrontano 915 metri di dislivello positivo su un tracciato che sale deciso attraverso i pascoli dell'alta conca di Chamois, supera le ultime baite degli alpeggi estivi e raggiunge la cresta spartiacque in ambiente alpino aperto. Il colle è un punto di passaggio storicamente frequentato dai pastori transumanti e offre un panorama di grande respiro verso la Valle d'Aosta centrale. L'assenza di accesso stradale a Chamois garantisce un silenzio e un'autenticità rari; si raccomanda di verificare gli orari della funivia per il rientro.",
    description_en: "Chamois holds a unique distinction in the Italian Alps: it is the only municipality in the Aosta Valley with no road access whatsoever, reachable only on foot or by cable car from Buisson. From this car-free village at 1812 m, the trail climbs 915 metres over 4.3 kilometres to the Col Pillonnet at 2698 m, a historic transhumance pass linking the central valley to the La Salle side. The route ascends through the broad high pastures above Chamois, passes the last summer alpeggi, and gains the open ridge with panoramic views over the central Aosta Valley. Check cable-car timetables for the return journey.",
    description_fr: "Chamois est une curiosité unique dans les Alpes italiennes : commune valdôtaine accessible uniquement à pied ou par téléphérique depuis Buisson, sans aucune route carrossable. Depuis ce village suspendu à 1812 m, le sentier monte 915 m sur 4,3 km jusqu'au Col Pillonnet à 2698 m, un col de transhumance historique reliant la vallée centrale au versant de La Salle. Le tracé traverse les vastes alpages au-dessus de Chamois, dépasse les derniers chalets d'estive et atteint la crête ouverte avec un panorama étendu sur la vallée centrale. Vérifier les horaires du téléphérique pour le retour.",
    description_de: "Chamois ist eine Besonderheit in den italienischen Alpen: die einzige Gemeinde im Aostatal ohne jede Straßenverbindung, erreichbar ausschließlich zu Fuß oder per Seilbahn von Buisson. Von diesem autofreien Dorf auf 1812 m steigt der Weg über 4,3 Kilometer und 915 Höhenmeter zum Col Pillonnet auf 2698 m an, einem historischen Hirtenpass, der das Haupttal mit dem Hang oberhalb von La Salle verbindet. Der Pfad durchquert die weiten Hochweiden über Chamois, passiert die letzten Sennhütten und erreicht den freien Kamm mit Weitblick über das mittlere Aostatal. Seilbahn-Abfahrtszeiten für die Rückkehr vorher prüfen.",
    updated_at: "2026-06-01"
  },
  "17-s11": {
    description_it: "L'itinerario da Veulla al Grand Lac è uno degli impegni alpinistici più seri della rete escursionistica di Charvensod e dell'intera area del comune di Aosta. Classificato EE per la combinazione di lunghezza, dislivello e caratteristiche del terreno, il percorso accumula 1861 metri di dislivello positivo in nove chilometri, una cifra che lo colloca tra gli itinerari più impegnativi dell'intero arco valdostano. La partenza da Veulla, a 1286 metri di quota sulle pendici orientali della conca di Aosta, introduce fin dalle prime battute in un ambiente selvaggio e poco frequentato. Il sentiero risale dapprima attraverso boschi misti e rimboschimenti, poi attraverso valloni erbosi e morene, fino a raggiungere il bacino glaciale dove è adagiato il Grand Lac a 2539 metri. Il lago, di origine glaciale, è uno dei più belli e isolati dell'area, con le sue acque di colore blu-verde riflesso dalle pareti rocciose circostanti. Il ritorno per lo stesso percorso richiede grande attenzione nella discesa.",
    description_en: "The route from Veulla to Grand Lac is one of the most serious hiking undertakings in the Charvensod area. Rated EE, it climbs 1861 metres over nine kilometres — among the highest elevation gains in the entire Aosta Valley trail network. Departing from Veulla at 1286 m on the eastern slopes above Aosta, the path ascends through mixed woodland, grassy couloirs and moraine terrain before reaching the glacially-formed Grand Lac at 2539 m, a remote and strikingly beautiful mountain lake set against steep rock walls. The descent demands equal care and attention. An extremely early start is essential.",
    description_fr: "L'itinéraire de Veulla au Grand Lac est l'une des sorties de randonnée les plus engagées du territoire de Charvensod. Classé EE, il cumule 1861 m de dénivelé positif sur neuf kilomètres, l'un des chiffres les plus élevés du réseau valdôtain. Depuis Veulla à 1286 m sur les pentes orientales du bassin d'Aoste, le sentier monte à travers forêts mixtes, couloirs herbeux et moraines jusqu'au Grand Lac glaciaire à 2539 m, un lac isolé et d'une beauté saisissante cerné de parois rocheuses. La descente exige une attention constante. Départ très matinal impératif.",
    description_de: "Die Route von Veulla zum Grand Lac zählt zu den anspruchsvollsten Wanderungen im Gebiet von Charvensod und ist als EE eingestuft. Auf neun Kilometern werden 1861 Höhenmeter überwunden — einer der höchsten Werte im gesamten Wandernetz des Aostatals. Von Veulla auf 1286 m an den Osthängen des Aosta-Beckens steigt der Pfad durch Mischwälder, Grasrinnen und Moränengelände an, bis er den glazialen Grand Lac auf 2539 m erreicht: ein abgelegener, von Felswänden umrahmter Bergsee von außergewöhnlicher Schönheit. Der Abstieg erfordert gleiche Sorgfalt. Aufbruch vor Tagesanbruch ist zwingend.",
    warnings_it: ["Classificazione EE, 1861 m di dislivello tra i più elevati della rete VdA: partenza prima dell'alba obbligatoria.", "Non adatto a principianti o in caso di cielo coperto; esperienza alpina ed equipaggiamento tecnico necessari."],
    warnings_en: ["EE rating, 1861 m of ascent among the highest in the VdA network: pre-dawn start mandatory.", "Not for beginners or in overcast conditions; alpine experience and technical gear required."],
    warnings_fr: ["Classification EE, 1861 m de dénivelé parmi les plus élevés du réseau valdôtain : départ avant l'aube obligatoire.", "Déconseillé aux débutants ou par ciel couvert ; expérience alpine et équipement technique requis."],
    warnings_de: ["EE-Einstufung, 1861 Höhenmeter — einer der höchsten Werte im VdA-Netz: Start vor Tagesanbruch zwingend.", "Nicht für Anfänger oder bei bedecktem Himmel; Alpinerfahrung und technische Ausrüstung erforderlich."],
    updated_at: "2026-06-01"
  }
};

const sk = JSON.parse(fs.readFileSync(skPath, 'utf8'));
let changed = 0;
const merged = sk.map(t => {
  const p = patch[t.slug];
  if (!p) return t;
  const fixes = {};
  if (!t.duration_hours) fixes.duration_hours = cai(t.distance_km, t.elevation_gain_m, t.elevation_loss_m);
  if (!t.mobile_coverage) fixes.mobile_coverage = 'partial';
  if (!t.fitness_level) fixes.fitness_level = diffToFitness[t.difficulty] ?? 2;
  if (!t.name_en) fixes.name_en = t.name_it;
  if (!t.name_fr) fixes.name_fr = t.name_it;
  if (!t.name_de) fixes.name_de = t.name_it;
  changed++;
  return { ...t, ...fixes, ...p };
});
console.log('Patchati (blocco G):', changed);
fs.writeFileSync(skPath, JSON.stringify(merged, null, 2), 'utf8');
console.log('OK');
