'use strict';
// Round 2 — blocco C: BF + BG + BJ (15 sentieri). Solo description_*/warnings_* 4 lingue.
const fs = require('fs');
const path = require('path');
const skPath = path.join(__dirname, '../src/data/trails-skeleton.json');
function cai(km, gain, loss) { return Math.max(0.5, Math.round((km/4+Math.max(gain,0)/400+Math.max(loss,0)/600)*2)/2); }
const diffToFitness = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };

const patch = {
  "12-s21": {
    description_it: "Il sentiero che sale da Estoul (1884 m) al Col Ranzola (2176 m) è uno dei più evocativi della Val d'Ayas, non tanto per la difficoltà tecnica — classificato T, adatto a camminatori di ogni livello — quanto per la stratificazione di storia e paesaggio che offre in soli 3,4 chilometri. Il percorso si snoda attraverso pascoli aperti e radure di larici, con il fondovalle di Brusson che si allarga progressivamente alle spalle. La salita, regolare e ben segnalata, guadagna 294 metri di dislivello in modo graduale, rendendola accessibile anche alle famiglie. Al colle, oltre al panorama che spazia verso la Valle del Lys e le cime del Rosa, una targa in metallo ricorda un ospite d'eccezione: nel giugno del 1857 Lev Tolstoy attraversò questo valico durante il suo viaggio europeo. Il Col Ranzola diventa così non solo un punto geografico ma un luogo della memoria letteraria europea.",
    description_en: "The trail from Estoul (1884 m) to Col Ranzola (2176 m) combines easy alpine walking with a remarkable piece of literary history. Covering 3.4 km with 294 m of ascent, the path climbs gently through larch meadows and open pastures above the Brusson valley. The gradient is steady and well-marked throughout, making it suitable for walkers of all abilities. At the col, a metal plaque commemorates the passage of Leo Tolstoy in June 1857, when the young Russian writer crossed this saddle during his European travels. The view from the top extends toward the Lys valley and the Monte Rosa massif, rewarding even the most modest effort with a genuinely alpine panorama.",
    description_fr: "Le sentier qui relie Estoul (1884 m) au Col Ranzola (2176 m) est une belle introduction à la haute Val d'Ayas, accessible à tous grâce à ses 294 m de dénivelé positif sur 3,4 km. La montée traverse des alpages ouverts et des forêts de mélèzes, avec le fond de vallée de Brusson visible en contrebas. Au col, une plaque rappelle le passage de Léon Tolstoï en juin 1857 : le jeune écrivain russe, alors en voyage à travers l'Europe, franchit ce col en laissant des traces dans ses carnets de voyage. Le panorama depuis le col s'étend vers la vallée du Lys et le massif du Mont Rose.",
    description_de: "Der Weg von Estoul (1884 m) zum Col Ranzola (2176 m) verbindet leichtes Alpenwandern mit einem besonderen Stück Literaturgeschichte. Auf 3,4 km und 294 Höhenmeter führt der Pfad durch Lärchenwälder und offene Weiden über dem Brusson-Tal. Die Steigung ist gleichmäßig und gut markiert, sodass der Weg für Wanderer jeden Alters geeignet ist. Am Pass erinnert eine Gedenktafel an den Durchzug Leo Tolstois im Juni 1857: Der damals dreißigjährige russische Schriftsteller überquerte diesen Sattel während seiner europäischen Reise. Der Blick vom Col Ranzola reicht bis ins Lystal und zur Monte-Rosa-Gruppe.",
    updated_at: "2026-06-01"
  },
  "13-s1": {
    description_it: "Questo breve itinerario della bassa Val d'Ayas collega Mayn (1058 m) a Curien (1224 m) su un tracciato di 3 chilometri con 259 metri di dislivello positivo, classificato E. È un percorso di carattere rurale che attraversa il paesaggio agrario tradizionale della media valle, dove i nuclei abitati si susseguono tra terrazzamenti, muretti a secco, castagneti e vigneti che testimoniano secoli di lavoro contadino. Il sentiero segue in buona parte i vecchi collegamenti pedonali che un tempo erano le uniche vie di comunicazione tra le frazioni. I borghi attraversati conservano architetture di pietra e legno tipiche della tradizione costruttiva valdostana: granges, raccards e abitazioni rurali addossate le une alle altre. Un itinerario adatto a chi cerca un contatto diretto con la cultura insediativa della Valle d'Aosta, lontano dalle vette e vicino alla vita quotidiana delle comunità montane.",
    description_en: "A short rural walk connecting the hamlets of Mayn (1058 m) and Curien (1224 m) in the lower Val d'Ayas, covering 3 km with 259 m of ascent. The path follows old inter-village tracks through a landscape of dry-stone terraces, chestnut groves and traditional Valdostan rural architecture. Stone and timber granges, raccards and farmhouses line the route, offering an insight into centuries of mountain agriculture. This is an ideal outing for those interested in the cultural and built heritage of the Aosta Valley rather than high-altitude scenery.",
    description_fr: "Court itinéraire de liaison entre les hameaux de Mayn (1058 m) et Curien (1224 m) dans la basse Val d'Ayas, soit 3 km pour 259 m de dénivelé. Le chemin emprunte d'anciens sentiers de desserte agricole à travers un paysage de terrasses en pierre sèche, de châtaigniers et d'architecture rurale valdôtaine traditionnelle. Granges, raccards et maisons de pierre jalonnent le parcours, témoignant d'une tradition pastorale et agricole pluriséculaire. Une promenade idéale pour découvrir le patrimoine bâti et culturel de la vallée.",
    description_de: "Ein kurzer Verbindungsweg zwischen den Weilern Mayn (1058 m) und Curien (1224 m) im unteren Val d'Ayas, 3 km lang mit 259 Höhenmetern. Der Pfad folgt alten Wirtschaftswegen durch Trockensteinterrassen, Kastanienwälder und traditionelle Valdostaner Dorfsiedlungen. Granges, Raccards und Steinhäuser prägen das Bild und zeugen von einer jahrhundertealten Berglandwirtschaft. Ideal für alle, die das kulturelle und bauliche Erbe des Aostatals abseits der Gipfel erkunden möchten.",
    updated_at: "2026-06-01"
  },
  "13-s9": {
    description_it: "Partendo da Quinçod (1030 m), nella fascia bassa della Val d'Ayas, questo sentiero di 4,7 chilometri e 742 metri di dislivello positivo rappresenta una delle salite più significative verso i pascoli di mezza quota della zona di Brusson. Classificato E, richiede un impegno fisico costante ma su sentiero sempre ben definito. I primi tratti attraversano la zona più antropizzata della valle, con vigneti e frutteti che cedono progressivamente il posto ai boschi misti di castagno e faggio. Man mano che si guadagna quota, la vegetazione si trasforma: compaiono i larici, e il fondovalle diventa una striscia sempre più lontana e silenziosa. L'arrivo agli alpeggi di Leuriaz (1592 m) segna il passaggio in un paesaggio radicalmente diverso: pascoli aperti, baite, il silenzio della montagna d'estate. La salita non presenta mai difficoltà tecniche, e il ritmo regolare la rende soddisfacente anche per escursionisti con buona preparazione fisica.",
    description_en: "Starting from Quinçod (1030 m) in the lower Val d'Ayas, this 4.7 km trail climbs 742 m to the mid-altitude pastures of Leuriaz (1592 m). Graded E, it demands sustained effort but follows a clear and well-maintained path throughout. The lower sections pass through vineyards and mixed woodland before the forest opens into larch stands and then alpine meadow. The ascent traces a classic vertical transect of the Aosta Valley landscape, from valley floor agriculture to summer grazing alp. A rewarding climb for fit hikers seeking genuine altitude gain without technical difficulty.",
    description_fr: "Au départ de Quinçod (1030 m) dans le bas de la Val d'Ayas, ce sentier de 4,7 km et 742 m de dénivelé monte vers les alpages de Leuriaz (1592 m). Classé E, il exige un effort soutenu mais suit un chemin toujours bien tracé. Les premiers tronçons traversent vignes et forêts mixtes, avant que la végétation ne s'ouvre sur des mélèzes puis sur des pâturages d'altitude. Une montée classique à travers les étages de végétation valdôtains, idéale pour les randonneurs en bonne forme physique.",
    description_de: "Von Quinçod (1030 m) im unteren Val d'Ayas führt dieser 4,7 km lange Weg mit 742 Höhenmetern hinauf zu den Almen von Leuriaz (1592 m). Als E eingestuft, verlangt er kontinuierliche Ausdauer, folgt aber stets einem gut markierten Pfad. Der untere Teil durchquert Weinberge und Mischwälder, bevor Lärchen und offene Weiden die Landschaft bestimmen. Ein klassischer Aufstieg durch die Vegetationsstufen des Aostatals für gut konditionierte Wanderer.",
    updated_at: "2026-06-01"
  },
  "15-s4": {
    description_it: "Il sentiero che da Lusey (1166 m) sale all'Alpe Ponton (2043 m) è uno dei percorsi più impegnativi in termini di dislivello dell'area di Châtillon, con 1137 metri di ascesa concentrati in soli 5,7 chilometri. Classificato E, si rivolge a escursionisti con buona preparazione fisica e familiarità con l'ambiente montano. Il tracciato affronta con decisione il fianco della Valtournenche, guadagnando quota in modo costante attraverso una successione di ambienti ben distinti: la fascia boschiva dei versanti bassi, con abeti e larici via via sempre più radi, i pianori erbosi di mezza quota dove il sentiero si fa più aereo, fino all'apertura finale verso i pascoli dell'alpeggio. L'Alpe Ponton offre un panorama ampio sulla Valtournenche e sulle cime che la circondano. Il dislivello elevato rende questo percorso fisicamente selettivo, ma il terreno non presenta mai difficoltà tecniche: è la resistenza muscolare e la gestione del ritmo a fare la differenza.",
    description_en: "The trail from Lusey (1166 m) to Alpe Ponton (2043 m) in the Valtournenche area climbs 1137 m over just 5.7 km, making it one of the most demanding ascents by elevation gain in the Châtillon sector. Graded E, it suits experienced hikers with good fitness. The path works steadily up through mixed forest, then sparse larch stands, before breaking into open pasture on the upper slopes. Alpe Ponton provides a wide view over the Valtournenche valley and surrounding peaks. No technical difficulty, but the relentless gain demands solid stamina and careful pacing.",
    description_fr: "Le sentier de Lusey (1166 m) à l'Alpe Ponton (2043 m) accumule 1137 m de dénivelé sur 5,7 km, ce qui en fait l'une des montées les plus exigeantes physiquement du secteur de Châtillon. Classé E, il s'adresse à des randonneurs entraînés. Le tracé traverse forêts de conifères et prairies d'altitude avant d'atteindre les pâturages de l'alpage. Depuis l'Alpe Ponton, le panorama sur la Valtournenche est remarquable. Pas de difficulté technique, mais un effort musculaire soutenu sur toute la durée.",
    description_de: "Der Weg von Lusey (1166 m) zur Alpe Ponton (2043 m) überwindet 1137 Höhenmeter auf nur 5,7 km und ist damit einer der anspruchsvollsten Anstiege im Gebiet von Châtillon. Als E eingestuft, richtet er sich an erfahrene und konditionsstarke Wanderer. Der Pfad durchquert Nadelwälder und lichte Lärchenhänge, bevor er in die offenen Alpweiden mündet. Von der Alpe Ponton bietet sich ein weiter Blick über das Valtournenche-Tal. Keine technischen Schwierigkeiten, aber anhaltende Ausdauer ist unbedingt erforderlich.",
    warnings_it: ["Dislivello elevato (1137 m): ottima preparazione fisica e gestione del ritmo indispensabili."],
    warnings_en: ["High elevation gain (1137 m): excellent fitness and pacing essential."],
    warnings_fr: ["Dénivelé important (1137 m) : excellente condition physique indispensable."],
    warnings_de: ["Hoher Höhenunterschied (1137 m): ausgezeichnete Kondition erforderlich."],
    updated_at: "2026-06-01"
  },
  "16-s8": {
    description_it: "Chamois è uno dei pochissimi comuni italiani completamente privi di strade carrabili: si raggiunge solo a piedi o con la funivia da Buisson. Questa particolarità conferisce al punto di partenza di questo itinerario (1823 m) un'aura di isolamento che il percorso verso il Col de Nannaz (2772 m) amplifica ulteriormente. In 6,9 chilometri con 960 metri di dislivello positivo, classificato E, il sentiero lascia il borgo e sale deciso verso i pascoli alti della Valle centrale di Champdepraz. La progressione è lineare e sostenuta: si attraversano prima i terreni di pascolo che circondano Chamois, poi la fascia degli alpeggi estivi, infine le pendici più impervie che portano al valico. Il Col de Nannaz a 2772 m è un punto panoramico eccezionale, con viste a 360° sulle vette della Valle d'Aosta centrale. Il ritorno su Chamois, con il fondovalle sempre lontano e inaccessibile in auto, chiude un'escursione che ha qualcosa di raro: la sensazione autentica di essere davvero in montagna.",
    description_en: "Chamois is one of the very few Italian municipalities with no road access — it is reached only on foot or by cable car from Buisson. This isolation sets the tone for the climb to Col de Nannaz (2772 m), a 6.9 km route with 960 m of ascent graded E. From the village at 1823 m the trail climbs steadily through summer pastures and alp zones before reaching the rocky upper slopes below the col. At 2772 m, the Col de Nannaz offers a sweeping 360-degree panorama over the central Aosta Valley peaks. The car-free context of Chamois gives this outing an unusual sense of genuine remoteness.",
    description_fr: "Chamois est l'une des rares communes italiennes sans route carrossable : on n'y accède qu'à pied ou par téléphérique depuis Buisson. Cet isolement donne à ce point de départ (1823 m) un caractère particulier, renforcé par la montée vers le Col de Nannaz (2772 m) sur 6,9 km et 960 m de dénivelé. Classé E, le sentier traverse alpages et pâturages d'estive avant d'atteindre les pentes rocheuses sous le col. Au Col de Nannaz, le panorama à 360° sur les sommets de la vallée centrale est exceptionnel. Une excursion qui offre une véritable sensation de montagne sauvage.",
    description_de: "Chamois ist eine der wenigen italienischen Gemeinden ohne Straßenanbindung — erreichbar nur zu Fuß oder per Seilbahn von Buisson. Dieser Ausgangsort (1823 m) verleiht dem Aufstieg zum Col de Nannaz (2772 m) auf 6,9 km mit 960 Höhenmetern einen besonderen Charakter. Als E eingestuft, führt der Weg durch Almweiden und Sommerweiden, bevor die steileren Hänge unterhalb des Passes beginnen. Vom Col de Nannaz bietet sich ein 360-Grad-Panorama über die Gipfel des zentralen Aostatals. Die autofreie Umgebung von Chamois verleiht dieser Tour ein echtes Gefühl von alpiner Abgeschiedenheit.",
    updated_at: "2026-06-01"
  },
  "02-s3": {
    description_it: "Il sentiero collega Bourg, frazione di Valtournenche a 1096 metri, con il villaggio di Messelod a 1600 metri, attraversando un paesaggio rurale che conserva intatta la fisionomia dei borghi alpini valdostani. In soli 3 chilometri e 560 metri di dislivello, il percorso si snoda tra case in pietra e legno con caratteristici tetti in lose, fontane in granito, cappelle votive e fienili tradizionali. L'itinerario tocca nuclei abitati legati storicamente alla transumanza e all'economia agro-pastorale della Valtournenche, offrendo scorci ravvicinati sull'architettura rurale di montagna. Man mano che si guadagna quota, si aprono vedute sul fondovalle e, nelle giornate limpide, sulla sagoma inconfondibile del Cervino verso nord. La vegetazione cambia progressivamente dal castagneto dei versanti bassi ai prati d'alta quota nei pressi di Messelod. Percorso adatto a escursionisti di buon passo, ideale come introduzione alla cultura materiale della Valtournenche.",
    description_en: "This route climbs 560 metres from Bourg (1096 m) to Messelod (1600 m), weaving through historic hamlets that showcase the rural heritage of the Valtournenche valley. Stone-and-timber houses, granite fountains, votive chapels and traditional hay barns line the path, painting a vivid picture of Alpine pastoral life. As height is gained, views open across the valley floor towards the unmistakable silhouette of the Matterhorn. The gradient is steady throughout, making this an accessible and rewarding half-day walk for anyone wishing to explore the historic built landscape of the Valle d'Aosta.",
    description_fr: "Ce sentier de 3 km relie Bourg (1096 m) à Messelod (1600 m) en traversant des hameaux historiques qui témoignent du patrimoine rural de la Valtournenche. Maisons en pierre et bois, fontaines en granit, chapelles votives et greniers traditionnels jalonnent le parcours, offrant une immersion dans l'architecture montagnarde valdôtaine. Au fil de la montée, le regard se pose sur le fond de vallée et, par temps clair, sur la silhouette caractéristique du Cervin. Un itinéraire idéal pour découvrir la culture matérielle alpine en une demi-journée.",
    description_de: "Dieser 3 km lange Weg verbindet Bourg (1096 m) mit Messelod (1600 m) und führt durch historische Weiler, die das ländliche Erbe des Valtournenche-Tals bewahren. Stein- und Holzhäuser, Granitbrunnen, Votivkapellen und traditionelle Heustadel prägen das Bild und vermitteln ein lebendiges Bild alpiner Pastoralkultur. Mit zunehmender Höhe öffnen sich Blicke ins Tal und bei klarem Wetter zur unverkennbaren Silhouette des Matterhorns. Ein lohnender Halbtagesausflug für alle, die die historische Baukultur des Aostatals erkunden möchten.",
    updated_at: "2026-06-01"
  },
  "05-s13": {
    description_it: "Partendo da Chamin, piccolo nucleo agricolo a 1417 metri nel comune di Arvier, il sentiero sale con regolarità verso l'alpeggio di Boregne a 2014 metri, sviluppandosi per 3,5 chilometri con un dislivello positivo di 585 metri. Il percorso attraversa una delle foreste di larici più suggestive della Valgrisenche: i tronchi rosati si stagliano contro il cielo nelle stagioni di transizione, mentre in autunno l'intera fascia boschiva si tinge di oro intenso. Man mano che il bosco si dirada, compaiono i pascoli aperti che anticipano l'arrivo all'alpeggio. Boregne è un insediamento estivo tradizionale dove la pratica casearia è ancora attiva; i baiti in pietra conservano le tecniche costruttive tipiche della Valgrisenche. L'ambiente è quieto e lontano dai grandi flussi turistici, con la Valgrisenche che mantiene un carattere autentico e poco antropizzato. Il sentiero è classificato E e non presenta difficoltà tecniche; la pendenza è costante ma gestibile, adatta a escursionisti allenati.",
    description_en: "Starting from the small farming hamlet of Chamin (1417 m) in the municipality of Arvier, this 3.5 km trail climbs 585 metres through ancient larch forest to the high-altitude alp of Boregne at 2014 m. The larch woodland is among the finest in the Valgrisenche valley, turning brilliant gold in autumn and casting long pink shadows in spring light. Above the treeline, open pastures lead to a traditional summer dairy settlement where stone barns reflect centuries of pastoral craftsmanship. The Valgrisenche remains one of the least-visited lateral valleys of the Aosta region, lending this walk an atmosphere of genuine Alpine solitude.",
    description_fr: "Au départ du hameau agricole de Chamin (1417 m) sur la commune d'Arvier, ce sentier de 3,5 km grimpe 585 mètres à travers une forêt de mélèzes séculaires jusqu'à l'alpage de Boregne (2014 m). La forêt de mélèzes est parmi les plus belles de la Valgrisenche, se parant d'or intense en automne. Au-delà de la limite des arbres, des pâturages ouverts mènent à un établissement d'estive traditionnel où les mazots en pierre témoignent d'un savoir-faire pastoral séculaire. La Valgrisenche conserve un caractère authentique et peu fréquenté, idéal pour une randonnée dans le silence alpin.",
    description_de: "Vom kleinen Weiler Chamin (1417 m) in der Gemeinde Arvier führt dieser 3,5 km lange Weg durch alten Lärchenwald 585 Höhenmeter hinauf zur Alm von Boregne (2014 m). Der Lärchenwald gehört zu den schönsten im Valgrisenche-Tal und leuchtet im Herbst in intensivem Gold. Oberhalb der Baumgrenze öffnen sich Weiden zu einer traditionellen Sennalm, deren Steinhütten das handwerkliche Erbe der Bergpastoral bewahren. Das Valgrisenche-Tal ist eines der ruhigsten Seitentäler des Aostatals — ideal für alle, die alpine Einsamkeit suchen.",
    updated_at: "2026-06-01"
  },
  "06-s2": {
    description_it: "La traversata da Vedun a Charvaz è uno dei percorsi in quota più equilibrati della Valdigne: 4,5 chilometri con soli 297 metri di dislivello positivo, svolti interamente tra i 1500 e i 1700 metri, con un andamento quasi orizzontale che permette di godere appieno del paesaggio senza affaticarsi eccessivamente. Il sentiero si sviluppa sui versanti che congiungono i territori comunali di La Salle e La Thuile, attraversando pascoli aperti, boschetti di conifere e piccoli pianori dove la flora alpina raggiunge la sua massima espressione tra giugno e luglio. La quota garantisce panorami stabili sul massiccio del Monte Bianco a ovest e sulle cime che delimitano la testata della valle verso il Piccolo San Bernardo. Il tratto centrale della traversata offre viste sul fondovalle della Dora Baltea. Percorso ideale per escursionisti di ogni livello che desiderino immergersi nel paesaggio aperto della Valdigne senza impegni tecnici. Particolarmente indicato nella stagione estiva e nei mesi di settembre-ottobre.",
    description_en: "This high-level traverse links Vedun (1519 m) to Charvaz (1700 m) across the slopes shared by La Salle and La Thuile in the Valdigne, covering 4.5 km with a modest 297 metres of ascent. Walking almost on the level between 1500 and 1700 metres, the route crosses open pastures, conifer groves and small alpine meadows rich in wildflowers from June through July. The elevation guarantees clear views west towards the Mont Blanc massif and east along the Dora Baltea valley floor. An ideal itinerary for walkers of all abilities who seek wide mountain scenery without technical demands.",
    description_fr: "Cette traversée relie Vedun (1519 m) à Charvaz (1700 m) sur les versants partagés entre La Salle et La Thuile en Valdigne, sur 4,5 km avec seulement 297 m de dénivelé. Le parcours se déroule presque à l'horizontale entre 1500 et 1700 m, traversant pâturages ouverts, bosquets de conifères et prairies alpines fleuries de juin à juillet. L'altitude garantit des panoramas sur le massif du Mont-Blanc à l'ouest et sur le fond de la vallée de la Doire Baltée. Un itinéraire accessible à tous les randonneurs cherchant de grands espaces sans difficulté technique.",
    description_de: "Diese Höhenwanderung verbindet Vedun (1519 m) mit Charvaz (1700 m) auf den Hängen zwischen La Salle und La Thuile in der Valdigne — 4,5 km mit nur 297 Höhenmetern. Der Weg verläuft nahezu waagerecht zwischen 1500 und 1700 m, überquert offene Weiden, Nadelwäldchen und alpine Blumenwiesen. Die Höhenlage garantiert freie Sicht auf das Mont-Blanc-Massiv im Westen und ins Dora-Baltea-Tal. Ein ideales Ausflugsziel für Wanderer aller Leistungsstufen.",
    updated_at: "2026-06-01"
  },
  "07-s11": {
    description_it: "Il Mont Facebelle (2619m) è una cima panoramica che domina il comune di Avise nella Valle centrale. L'itinerario parte da Amponey a 1550 metri e sviluppa 5,6 chilometri per 1077 metri di dislivello positivo, classificato EE — Escursionisti Esperti. Il percorso inizia in ambiente boschivo, risalendo versanti ripidi con sentiero ben tracciato ma che richiede passo sicuro e buon senso dell'orientamento. Superata la fascia forestale, il terreno si apre su dorsali erbose alternate a passaggi su roccia e detrito che esigono attenzione nella progressione. In prossimità della vetta il percorso può presentare tratti esposti dove è necessario l'uso delle mani. La cima offre un panorama a 360° di eccezionale ampiezza: dalla catena del Gran Paradiso alle Alpi Graie, dal Monte Rosa al Mont Blanc, con il fondovalle della Dora Baltea che si stende ben visibile verso est e ovest. Riservato a escursionisti con esperienza su terreno montano impegnativo.",
    description_en: "Mont Facebelle (2619m) dominates the skyline above Avise in the central Aosta Valley. This EE-rated route — for experienced mountain walkers only — climbs 1077 metres over 5.6km from the hamlet of Amponey (1550m). The ascent moves through dense forest before breaking onto open grassy ridges interspersed with rocky and scree sections demanding sure footing. Near the summit, exposed passages may require the use of hands. The reward is a 360-degree panorama taking in the Gran Paradiso chain, the Graian Alps, Monte Rosa and Mont Blanc, with the Dora Baltea valley stretching below. Not recommended in poor weather or when snow lingers at altitude.",
    description_fr: "Le Mont Facebelle (2619 m) domine la commune d'Avise dans la vallée centrale. Cet itinéraire côté EE — réservé aux randonneurs expérimentés — gravit 1077 m sur 5,6 km depuis le hameau d'Amponey (1550 m). La montée traverse la forêt avant de déboucher sur des arêtes herbeuses entrecoupées de passages rocheux et d'éboulis exigeant un pied sûr. Près du sommet, des passages exposés peuvent nécessiter l'usage des mains. Le panorama à 360° embrasse le Gran Paradiso, les Alpes Grées, le Mont Rose et le Mont-Blanc. Déconseillé par mauvais temps ou en présence de neige résiduelle.",
    description_de: "Der Mont Facebelle (2619 m) beherrscht die Silhouette über der Gemeinde Avise im zentralen Aostatal. Diese EE-bewertete Route — ausschließlich für erfahrene Bergwanderer — überwindet 1077 Höhenmeter auf 5,6 km ab dem Weiler Amponey (1550 m). Der Aufstieg führt durch dichten Wald, bevor er auf grasbewachsene Grate mit Fels- und Geröllpassagen wechselt, die Trittsicherheit erfordern. Gipfelnahe exponierte Stellen können den Einsatz der Hände verlangen. Das 360-Grad-Panorama umfasst Gran Paradiso, Grajische Alpen, Monte Rosa und Mont Blanc. Bei Schlechtwetter oder Restschnee nicht empfohlen.",
    warnings_it: ["Percorso EE: esperienza su terreno montano impegnativo, passo sicuro e orientamento richiesti.", "Tratti esposti in prossimità della vetta possono richiedere l'uso delle mani.", "Sconsigliato in caso di maltempo, nebbia o neve residua."],
    warnings_en: ["EE route: experience on demanding mountain terrain, sure footing and navigation required.", "Exposed passages near the summit may require use of hands.", "Not recommended in bad weather, fog or residual snow."],
    warnings_fr: ["Itinéraire EE : expérience en terrain de montagne, pas assuré et orientation requis.", "Passages exposés près du sommet pouvant nécessiter l'usage des mains.", "Déconseillé par mauvais temps, brouillard ou neige résiduelle."],
    warnings_de: ["EE-Route: Erfahrung im anspruchsvollen Berggelände, Trittsicherheit und Orientierung erforderlich.", "Ausgesetzte Stellen nahe dem Gipfel können den Einsatz der Hände erfordern.", "Bei Schlechtwetter, Nebel oder Restschnee nicht empfohlen."],
    updated_at: "2026-06-01"
  },
  "07-s27": {
    description_it: "L'itinerario da Blanchard al Bivacco Città di Mariano è uno dei percorsi più impegnativi del territorio di Avise nella Valle centrale, con 5,2 chilometri e 1128 metri di dislivello positivo che portano da 1731 a 2836 metri di quota. La classificazione EE riflette la natura selvaggia e tecnicamente esigente del tracciato. La salita si sviluppa inizialmente attraverso boschi misti e pascoli d'alta quota, poi su terreno sempre più aperto e rupestre. Il Gran Lago di Tzère, bacino naturale di grande bellezza situato nelle vicinanze del percorso, rappresenta uno dei momenti di maggior suggestione dell'itinerario: le sue acque ferme riflettono le creste circostanti in un ambiente di severa bellezza alpina. Sopra il lago il sentiero si fa più arduo, con tratti su roccia, ghiaioni e pendii ripidi che richiedono attenzione costante. Il Bivacco Città di Mariano, posto a 2836 metri, offre rifugio di emergenza in un contesto di alta montagna. L'esposizione al meteo è totale nella parte finale.",
    description_en: "The ascent from Blanchard (1731m) to the Bivacco Città di Mariano (2836m) is one of the most demanding routes in the Avise area of the central Aosta Valley: 5.2km and 1128 metres of climbing through progressively wilder Alpine terrain. Rated EE — experienced hikers only. The path climbs through mixed woodland and high pasture before entering a stark landscape of rock, scree and steep slopes. The nearby Gran Lago di Tzère is a highlight of the route: a natural lake whose still waters mirror the surrounding ridges in an atmosphere of raw Alpine grandeur. Above the lake, the trail grows steeper and more technical, demanding sure footwork throughout. The Bivacco Città di Mariano at 2836m provides emergency shelter. Full weather exposure on the upper section.",
    description_fr: "La montée de Blanchard (1731 m) au Bivouac Città di Mariano (2836 m) est l'un des itinéraires les plus exigeants du secteur d'Avise dans la vallée centrale : 5,2 km et 1128 m de dénivelé à travers un paysage alpin de plus en plus sauvage. Côté EE — randonneurs expérimentés uniquement. Le sentier traverse forêt mixte et hauts pâturages avant d'aborder un terrain de rochers, d'éboulis et de pentes raides. Le Grand Lac de Tzère, à proximité du tracé, est un joyau paysager : ses eaux calmes reflètent les crêtes environnantes dans un décor d'une beauté austère. Au-dessus du lac, le sentier devient plus technique et exige une progression attentive. Le bivouac à 2836 m offre un abri d'urgence.",
    description_de: "Der Aufstieg von Blanchard (1731 m) zum Bivacco Città di Mariano (2836 m) zählt zu den anspruchsvollsten Routen im Gebiet Avise im zentralen Aostatal: 5,2 km und 1128 Höhenmeter durch zunehmend wildes Alpingelände. Bewertung EE — nur für erfahrene Bergwanderer. Der Weg durchquert Mischwald und Hochweide, bevor er in eine karge Landschaft aus Fels, Geröll und steilen Hängen übergeht. Der nahe gelegene Gran Lago di Tzère ist ein landschaftlicher Höhepunkt: Sein stilles Wasser spiegelt die umliegenden Grate in strenger Alpinschönheit. Oberhalb des Sees wird das Gelände technisch anspruchsvoller. Das Biwak auf 2836 m bietet Notunterkunft. Vollständige Wetterexposition im oberen Abschnitt.",
    warnings_it: ["Percorso EE: esperienza alpina solida, terreno su roccia, ghiaione e pendii ripidi.", "Esposizione totale al meteo nella parte alta; sconsigliato con maltempo o neve.", "Scarponi tecnici, bastoncini e abbigliamento per condizioni alpine obbligatori."],
    warnings_en: ["EE route: solid alpine experience required; rock, scree and steep slopes.", "Full weather exposure on the upper section; not advised in bad weather or snow.", "Technical boots, poles and alpine clothing mandatory."],
    warnings_fr: ["Itinéraire EE : expérience alpine solide ; rochers, éboulis et pentes raides.", "Exposition totale en partie haute ; déconseillé par mauvais temps ou neige.", "Chaussures techniques, bâtons et vêtements alpins obligatoires."],
    warnings_de: ["EE-Route: solide Alpinerfahrung; Fels, Geröll und steile Hänge.", "Vollständige Wetterexposition im oberen Abschnitt; bei Schlechtwetter oder Schnee nicht empfohlen.", "Technische Bergstiefel, Stöcke und Alpinbekleidung erforderlich."],
    updated_at: "2026-06-01"
  },
  "02-s6": {
    description_it: "Il sentiero prende avvio a Grand Moulin (1022 m), piccola frazione immersa nel verde della bassa Valtournenche, e risale con passo costante il versante orientale fino all'alpeggio di Mognod (1522 m). In soli 3,1 km si guadagnano 504 metri di dislivello, percorrendo un itinerario che appartiene alla tradizione pastorale valdostana: il tracciato attraversa fasce di bosco misto di abeti e larici, supera alcuni rustici in pietra e sbocca infine su pianori erbosi dove d'estate il bestiame sale ancora agli alti pascoli. Il paesaggio cambia gradualmente con la quota, dal fondovalle raccolto e umido ai pianori aperti con le prime viste sulle creste di confine tra le due valli. Difficoltà E, adatto a escursionisti con un minimo di allenamento.",
    description_en: "Starting at Grand Moulin (1022 m) in lower Valtournenche, this 3.1 km trail climbs 504 metres to the pastoral hamlet of Mognod (1522 m). The path winds through mixed larch and fir forest, passes old stone farm buildings and opens onto grassy terraces that have been summer grazing land for generations. A quiet, traditional route connecting the Valtournenche and Valpelline valleys. Rated E, suitable for reasonably fit walkers.",
    description_fr: "Au départ de Grand Moulin (1022 m), dans la basse Valtournenche, ce sentier de 3,1 km monte 504 mètres jusqu'au hameau pastoral de Mognod (1522 m). Le tracé traverse des forêts mixtes de mélèzes et de sapins, longe de vieux bâtiments en pierre et débouche sur des alpages herbeux traditionnels. Un itinéraire calme et authentique reliant la Valtournenche à la Valpelline. Difficulté E, accessible aux randonneurs en bonne condition.",
    description_de: "Startpunkt ist Grand Moulin (1022 m) im unteren Valtournenche. Auf 3,1 km überwindet der Weg 504 Höhenmeter bis zum Weiler Mognod (1522 m). Der Pfad führt durch gemischten Lärchen- und Tannenwald, vorbei an alten Steingebäuden, und mündet in offene Wiesenhänge, die seit Generationen als Sommerweide genutzt werden. Eine stille, traditionelle Route zwischen Valtournenche und Valpelline. Schwierigkeit E, geeignet für geübte Wanderer.",
    updated_at: "2026-06-01"
  },
  "05-s3": {
    description_it: "Uno degli itinerari più impegnativi della Valgrisenche per il suo dislivello sostenuto: da Leverogne (767 m), piccolo nucleo del fondovalle tra Arvier e La Salle, il sentiero sviluppa 6,2 km di percorso per portarsi fino a Baulin (1763 m), guadagnando oltre 1000 metri di quota. La via passa per La Ravoire, frazione semidiroccata che testimonia il lento abbandono dei villaggi montani valdostani, con i rustici in pietra ancora in piedi tra la vegetazione. Salendo, il bosco di castagni e querce lascia progressivamente spazio a larici e pascoli, mentre si aprono le prime vedute sulla Valgrisenche. L'itinerario richiede buona resistenza fisica e un passo regolare; è classificato E. La partenza dal fondovalle rende il rientro particolarmente lungo in caso di stanchezza: meglio organizzarsi con punto di appoggio in quota.",
    description_en: "One of Valgrisenche's most demanding valley-floor-to-alp routes, this 6.2 km trail climbs over 1000 metres from Leverogne (767 m) to Baulin (1763 m). Passing through the partly abandoned hamlet of La Ravoire — with its stone ruins still standing among encroaching vegetation — the path ascends through chestnut and oak woodland before opening into larch forest and high pasture. Rated E; solid fitness required. The long descent back to the valley floor should be factored into planning.",
    description_fr: "L'un des itinéraires les plus exigeants de la Valgrisenche : 6,2 km et plus de 1000 mètres de dénivelé depuis Leverogne (767 m) jusqu'à Baulin (1763 m). Le sentier traverse le hameau semi-abandonné de La Ravoire, dont les bâtisses en pierre témoignent du dépeuplement progressif des villages de montagne valdôtains. La végétation évolue de la châtaigneraie aux mélèzes et aux alpages ouverts. Difficulté E ; bonne condition physique indispensable.",
    description_de: "Eine der anspruchsvollsten Talrouten der Valgrisenche: 6,2 km und über 1000 Höhenmeter von Leverogne (767 m) nach Baulin (1763 m). Der Weg führt durch den teilweise verlassenen Weiler La Ravoire mit seinen noch stehenden Steinruinen, dann durch Kastanien- und Eichenwälder hinauf in Lärchenwälder und offene Almwiesen. Schwierigkeit E; gute körperliche Kondition ist Voraussetzung. Der lange Rückweg ins Tal sollte bei der Planung berücksichtigt werden.",
    updated_at: "2026-06-01"
  },
  "06-s25": {
    description_it: "Questo sentiero della Valdigne è un concentrato di fatica e bellezza: da Runaz (839 m), nel comune di La Salle, si sale in soli 3,2 km fino a Mont-Colombo (1814 m), accumulando 978 metri di dislivello positivo. La pendenza media supera il 30%, con tratti che toccano valori ancora più ripidi — un dato che chiarisce immediatamente il carattere dell'itinerario, adatto esclusivamente a escursionisti allenati e con passo sicuro. Il sentiero risale il versante meridionale della Valdigne attraverso boschi di castagni nella parte bassa, poi larici e pascoli sempre più esposti. La ricompensa si materializza già a metà percorso: il Monte Bianco con il suo corteo di ghiacciai si svela progressivamente, dominando il panorama. In cima, la vista abbraccia l'intera testata della Valdigne fino al Gran San Bernardo. Difficoltà E; sconsigliato in caso di terreno bagnato o innevato.",
    description_en: "A punishing ascent in the Valdigne: 978 metres of climbing packed into just 3.2 km from Runaz (839 m) to Mont-Colombo (1814 m). Average gradients exceed 30%, demanding sure footing and good fitness throughout. The lower slopes pass through chestnut woodland before giving way to larch and open pasture. The reward is exceptional: Mont Blanc and its glacier complex reveal themselves progressively as height is gained, with a sweeping panorama at the summit over the entire upper Valdigne. Rated E; avoid in wet or icy conditions.",
    description_fr: "Une montée exigeante dans la Valdigne : 978 mètres de dénivelé en seulement 3,2 km de Runaz (839 m) à Mont-Colombo (1814 m). La pente moyenne dépasse 30 %, imposant une bonne condition physique et une allure assurée sur tout le parcours. Les pentes inférieures traversent une châtaigneraie avant de laisser place aux mélèzes et aux alpages. La récompense est à la hauteur de l'effort : le Mont-Blanc se dévoile progressivement, offrant un panorama exceptionnel depuis le sommet. Difficulté E ; à éviter par temps humide ou enneigé.",
    description_de: "Ein kraftraubender Aufstieg in der Valdigne: 978 Höhenmeter auf nur 3,2 km von Runaz (839 m) nach Mont-Colombo (1814 m). Die Durchschnittssteigung überschreitet 30 % und verlangt durchgängig sicheres Gehen und gute Kondition. Die unteren Hänge durchqueren Kastanienwälder, bevor Lärchen und offene Almwiesen folgen. Die Belohnung ist außergewöhnlich: Das Mont-Blanc-Massiv mit seinen Gletschern öffnet sich schrittweise, mit einem weiten Rundblick vom Gipfel. Schwierigkeit E; bei Nässe oder Schnee nicht empfehlenswert.",
    warnings_it: ["Pendenza media oltre il 30%: solo per escursionisti allenati con passo sicuro.", "Sconsigliato con terreno bagnato o innevato."],
    warnings_en: ["Average gradient over 30%: only for fit hikers with sure footing.", "Avoid in wet or snowy conditions."],
    warnings_fr: ["Pente moyenne supérieure à 30 % : réservé aux randonneurs entraînés.", "À éviter par terrain humide ou enneigé."],
    warnings_de: ["Durchschnittssteigung über 30 %: nur für trainierte, trittsichere Wanderer.", "Bei Nässe oder Schnee nicht empfohlen."],
    updated_at: "2026-06-01"
  },
  "07-s19": {
    description_it: "Itinerario per escursionisti esperti che dalla conca di Saint-Jacques (1700 m) raggiunge la vetta del Monte Croce (2895 m), affrontando 6,8 km e 1202 metri di dislivello su terreno che richiede esperienza alpina consolidata. Il tracciato si sviluppa lungo il fianco della Val d'Ayas, superando zone di pascolo, morene e tratti su roccia o terreno instabile che giustificano la classificazione EE. La progressione è sostenuta e la quota impone attenzione al meteo: i temporali pomeridiani estivi sono frequenti e possono trasformare rapidamente le condizioni. In giornata limpida la cima ripaga ogni sforzo: il Monte Rosa con la sua parete est, il Cervino dalla forma inconfondibile e l'intera corona di ghiacciai valdostani si dispiegano in uno dei panorami più completi della media valle. Obbligatori scarponi tecnici e solida esperienza su terreno d'alta quota. Non adatto a chi non abbia già percorso itinerari EE.",
    description_en: "A demanding EE-rated route rising from Saint-Jacques (1700 m) to Monte Croce (2895 m) in the Val d'Ayas. The 6.8 km, 1202-metre ascent crosses pasture, moraine and sections of loose or rocky ground that require confident movement in alpine terrain. Summer afternoon thunderstorms are common above 2500 m and conditions can change rapidly. On a clear day the summit delivers one of the finest panoramas in the central Aosta Valley: the east face of Monte Rosa, the unmistakable silhouette of the Matterhorn and the full chain of Valle d'Aosta glaciers. Technical boots and high-altitude experience are essential.",
    description_fr: "Itinéraire coté EE au départ de Saint-Jacques (1700 m) jusqu'au Monte Croce (2895 m) dans le Val d'Ayas. Les 6,8 km et 1202 mètres de dénivelé traversent alpages, moraines et sections rocheuses ou instables qui nécessitent une expérience solide en terrain alpin. Les orages estivaux d'après-midi sont fréquents au-dessus de 2500 m. Par temps clair, le sommet offre un panorama exceptionnel sur la face est du Mont Rose, la silhouette du Cervin et les glaciers valdôtains. Chaussures techniques et expérience en haute montagne indispensables.",
    description_de: "Eine anspruchsvolle EE-Route von Saint-Jacques (1700 m) zum Monte Croce (2895 m) im Val d'Ayas. Die 6,8 km und 1202 Höhenmeter führen über Weiden, Moränen und felsige oder instabile Abschnitte, die alpine Erfahrung voraussetzen. Sommerliche Nachmittagsgewitter sind oberhalb 2500 m häufig. Bei klarem Wetter bietet der Gipfel ein außergewöhnliches Panorama: Ostseite des Monte Rosa, die unverkennbare Silhouette des Matterhorns und die gesamte Gletscherkette des Aostatals. Bergstiefel und Hochgebirgserfahrung sind Pflicht.",
    warnings_it: ["Difficoltà EE: esperienza in alta montagna e orientamento su terreno sassoso richiesti.", "Cresta sommitale esposta al vento e a variazioni meteo rapide.", "Temporali pomeridiani estivi frequenti sopra i 2500 m."],
    warnings_en: ["EE difficulty: high-altitude experience and route-finding on rocky ground required.", "Summit ridge exposed to wind and rapid weather changes.", "Summer afternoon thunderstorms common above 2500 m."],
    warnings_fr: ["Difficulté EE : expérience en haute montagne et orientation requises.", "Arête sommitale exposée au vent et aux changements météo rapides.", "Orages d'après-midi fréquents au-dessus de 2500 m."],
    warnings_de: ["EE-Schwierigkeit: Hochgebirgserfahrung und Orientierung erforderlich.", "Gipfelgrat Wind und schnellen Wetteränderungen ausgesetzt.", "Sommerliche Nachmittagsgewitter über 2500 m häufig."],
    updated_at: "2026-06-01"
  },
  "07-s29": {
    description_it: "L'anello di Tzère è uno degli itinerari ad anello più soddisfacenti della Val d'Ayas: parte e ritorna a Blanchard (1731 m), sviluppando 6,2 km con 956 metri di dislivello totale su terreno classificato E. Il percorso sale rapidamente fuori dalla conca di partenza per immergersi negli ampi pascoli alti della zona di Tzère, dove in estate le mucche al pascolo e i fienili in pietra compongono un paesaggio alpino d'altri tempi. La logica dell'anello permette di variare il panorama in entrambe le direzioni di percorrenza e di godere viste aperte sulla media Val d'Ayas con le creste circostanti. Il terreno è in prevalenza erboso con qualche tratto su traccia più marcata. Adatto a escursionisti con discreta preparazione fisica; la quota di partenza relativamente elevata riduce lo sforzo complessivo rispetto ad altri itinerari della valle.",
    description_en: "The Tzère loop is one of Val d'Ayas's most rewarding circular walks, starting and finishing at Blanchard (1731 m) over 6.2 km with 956 metres of total ascent. The trail climbs quickly onto the broad high pastures of the Tzère area, where summer grazing herds and stone hay barns create a timeless alpine scene. Open views across the mid-valley and surrounding ridges reward the effort throughout. Mostly grassy terrain with some well-defined track sections. Rated E; sturdy walking boots recommended.",
    description_fr: "La boucle de Tzère est l'un des meilleurs circuits de la Val d'Ayas, au départ et retour à Blanchard (1731 m), sur 6,2 km avec 956 mètres de dénivelé cumulé. Le sentier monte rapidement sur les vastes alpages de Tzère, où troupeaux estivaux et granges en pierre composent un paysage alpin intemporel. Des vues ouvertes sur la moyenne vallée et les crêtes environnantes ponctuent tout l'itinéraire. Terrain majoritairement herbeux. Difficulté E ; chaussures de randonnée robustes recommandées.",
    description_de: "Die Tzère-Runde ist eine der schönsten Rundwanderungen im Val d'Ayas: Start und Ziel in Blanchard (1731 m), 6,2 km mit insgesamt 956 Höhenmetern. Der Weg steigt rasch auf die weiten Hochweiden von Tzère, wo Sommerherden und Steinheuschober eine zeitlose Alpenlandschaft bilden. Offene Aussichten über das mittlere Tal und die umliegenden Grate begleiten die gesamte Tour. Überwiegend grasbewachsenes Gelände. Schwierigkeit E; festes Schuhwerk empfohlen.",
    updated_at: "2026-06-01"
  }
};

const sk = JSON.parse(fs.readFileSync(skPath, 'utf8'));
let changed = 0;
const merged = sk.map(t => {
  const p = patch[t.slug];
  if (!p) return t;
  const fixes = {};
  if (!t.duration_hours) fixes.duration_hours = cai(t.distance_km, t.elevation_gain_m, t.elevation_loss_m);
  if (!t.mobile_coverage) fixes.mobile_coverage = 'partial';
  if (!t.fitness_level) fixes.fitness_level = diffToFitness[t.difficulty] ?? 2;
  if (!t.name_en) fixes.name_en = t.name_it;
  if (!t.name_fr) fixes.name_fr = t.name_it;
  if (!t.name_de) fixes.name_de = t.name_it;
  changed++;
  return { ...t, ...fixes, ...p };
});
console.log('Patchati (blocco C):', changed);
fs.writeFileSync(skPath, JSON.stringify(merged, null, 2), 'utf8');
console.log('OK');
