'use strict';
// Round 2 — blocco D: BE + BH (10 sentieri).
const fs = require('fs');
const path = require('path');
const skPath = path.join(__dirname, '../src/data/trails-skeleton.json');
function cai(km, gain, loss) { return Math.max(0.5, Math.round((km/4+Math.max(gain,0)/400+Math.max(loss,0)/600)*2)/2); }
const diffToFitness = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };

const patch = {
  "07-s45": {
    description_it: "Da Champoluc, cuore pulsante del comprensorio Monte Rosa Ski, il sentiero sale con dolcezza verso l'Alpe Résy attraverso pascoli aperti e boschi di larici. Il punto di partenza a 1925 metri offre già una vista ampia sulla testata della Val d'Ayas, con il Monte Rosa che chiude l'orizzonte a sud-ovest con i suoi ghiacciai inconfondibili. Il percorso, classificato T (turistico), è adatto a famiglie e a chi vuole avvicinarsi alla montagna senza difficoltà tecniche: il dislivello contenuto di 262 metri su 4,6 chilometri consente un'andatura rilassata. Résy, a 2067 metri, è un alpeggio tradizionale valdostano con il suo caratteristico paesaggio aperto, ideale per una sosta panoramica prima di rientrare a Champoluc. Il sentiero è percorribile dalla tarda primavera all'autunno inoltrato.",
    description_en: "Starting from Champoluc at 1925 metres, the gateway to the Monte Rosa Ski area, this easy tourist-grade trail winds gently up through open pastures and larch woodland to the Alpe Résy at 2067 metres. The modest elevation gain of 262 metres over 4.6 kilometres makes it ideal for families and walkers seeking an accessible mountain experience. Throughout the route, the Monte Rosa massif dominates the skyline to the south-west, its glaciers glinting above the Val d'Ayas valley floor. Résy is a traditional alpine pasture where the views open wide across the valley. The path is accessible from late spring through autumn.",
    description_fr: "Au départ de Champoluc, à 1925 mètres, cette randonnée de niveau touristique grimpe doucement à travers pâturages ouverts et mélézins vers l'Alpe Résy, à 2067 mètres. Le dénivelé de 262 mètres sur 4,6 kilomètres la rend accessible aux familles et aux promeneurs peu entraînés. Tout au long du parcours, le massif du Mont Rose ferme l'horizon au sud-ouest de ses glaciers imposants, offrant un arrière-plan spectaculaire à la verdure de la Val d'Ayas. Résy est un alpage traditionnel valdôtain, idéal pour une pause panoramique avant de redescendre à Champoluc.",
    description_de: "Von Champoluc auf 1925 Metern, dem Zentrum des Skigebiets Monte Rosa Ski, führt dieser leichte Wanderweg sanft durch offene Weiden und Lärchenwälder zur Alpe Résy auf 2067 Metern. Der geringe Höhenunterschied von 262 Metern auf 4,6 Kilometern macht die Tour ideal für Familien und Einsteiger. Das Monte-Rosa-Massiv mit seinen Gletschern beherrscht die Silhouette im Südwesten und bietet eine eindrucksvolle Kulisse. Résy ist ein traditioneller Walliser Alp-Weiler mit weitem Panoramablick über das Val d'Ayas. Der Weg ist von spätem Frühling bis Herbst begehbar.",
    shortDescription_it: "Passeggiata panoramica da Champoluc all'Alpe Résy nel cuore del comprensorio Monte Rosa, con vista sui ghiacciai e pascoli tipici della Val d'Ayas.",
    shortDescription_en: "A gentle walk from Champoluc to Alpe Résy with sweeping views of the Monte Rosa massif — perfect for families and easy-going mountain walkers.",
    shortDescription_fr: "Promenade panoramique de Champoluc à l'Alpe Résy, avec vue sur les glaciers du Mont Rose et les pâturages typiques de la Val d'Ayas.",
    shortDescription_de: "Gemütliche Wanderung von Champoluc zur Alpe Résy mit Panoramablick auf den Monte Rosa — ideal für Familien im Herzen des Val d'Ayas.",
    updated_at: "2026-06-01"
  },
  "07-s9": {
    description_it: "Uno degli itinerari più impegnativi dell'intera media Valle d'Aosta: da Amponey a 1550 metri la traccia risale senza sconti fino alla Becca Trecare a 3032 metri, guadagnando quasi 1500 metri di dislivello in 7,5 chilometri. La classificazione EE (Escursionisti Esperti) è pienamente meritata: il percorso affronta terreno ripido, tratti su erba e roccia instabile nella parte alta, e richiede orientamento autonomo fuori dai sentieri segnalati della bassa valle. Le condizioni cambiano rapidamente sopra i 2500 metri, dove il manto nevoso può persistere fino a giugno-luglio. La vetta della Becca Trecare offre un panorama eccezionale sulla Valle centrale e sulle catene alpine circostanti. Obbligatoria un'uscita nelle prime ore del mattino e la valutazione delle condizioni meteo prima della partenza.",
    description_en: "One of the most demanding routes in the central Aosta Valley: from Amponey at 1550 metres the trail climbs relentlessly to the Becca Trecare summit at 3032 metres, gaining nearly 1500 metres over 7.5 kilometres. The EE rating (Expert Hikers) is fully warranted — steep terrain, loose rock and grass in the upper section, and the need for autonomous navigation above 2500 metres. Snow may linger on the high flanks until June or July. The summit delivers a vast panorama over the central valley and the surrounding alpine chains. An early start and careful weather assessment are essential before attempting this route.",
    description_fr: "L'un des itinéraires les plus exigeants de la moyenne Vallée d'Aoste : depuis Amponey à 1550 mètres, le sentier remonte sans relâche jusqu'au sommet de la Becca Trecare à 3032 mètres, avec un dénivelé de près de 1500 mètres sur 7,5 kilomètres. La cotation EE est pleinement justifiée : pente soutenue, terrain mixte herbe-rocher dans la partie haute, orientation autonome au-delà de 2500 mètres. La neige peut persister jusqu'en juin-juillet. Le sommet offre un panorama exceptionnel sur la vallée centrale. Départ matinal et évaluation météo indispensables.",
    description_de: "Eine der anspruchsvollsten Routen im mittleren Aostatal: Von Amponey auf 1550 Metern steigt der Weg unerbittlich zur Becca Trecare auf 3032 Metern, mit fast 1500 Höhenmetern auf 7,5 Kilometern. Die EE-Bewertung ist vollauf gerechtfertigt — steiles Gelände, Fels- und Graspfade im oberen Abschnitt, eigenständige Navigation ab 2500 Metern erforderlich. Schneefelder können bis Juni-Juli bestehen bleiben. Vom Gipfel bietet sich ein weites Panorama über das Haupttal und die umliegenden Alpenketten. Frühzeitiger Aufbruch und sorgfältige Wetterbeurteilung sind Pflicht.",
    shortDescription_it: "Salita EE impegnativa da Amponey fino alla Becca Trecare a 3032m: quasi 1500m di dislivello su terreno vario, panorama alpino di grande respiro.",
    shortDescription_en: "A demanding EE ascent from Amponey to Becca Trecare at 3032m — nearly 1500m of gain on varied terrain with sweeping summit views.",
    shortDescription_fr: "Ascension EE depuis Amponey jusqu'à la Becca Trecare à 3032m — près de 1500m de dénivelé sur terrain varié et panorama alpin exceptionnel.",
    shortDescription_de: "Anspruchsvoller EE-Aufstieg von Amponey zur Becca Trecare auf 3032m — fast 1500 Hm auf abwechslungsreichem Gelände mit alpinem Gipfelpanorama.",
    warnings_it: ["Percorso EE: obbligatoria esperienza alpinistica e orientamento fuori sentiero", "Nevai possibili fino a luglio nella parte alta; portare ramponcini nella prima stagione", "Meteo instabile sopra i 2500m: partire presto e monitorare le previsioni"],
    warnings_en: ["EE-rated route: requires mountain experience and off-trail navigation skills", "Snow possible until July above 2500m; carry microspikes early in the season", "Weather deteriorates rapidly above 2500m: start early and check forecasts"],
    warnings_fr: ["Itinéraire EE : expérience montagne et sens de l'orientation hors sentier requis", "Névés possibles jusqu'en juillet au-delà de 2500m ; prévoir crampons légers en début de saison", "Météo instable au-dessus de 2500m : départ matinal et consultation météo indispensables"],
    warnings_de: ["EE-Route: Bergerfahrung und Orientierung im weglosen Gelände erforderlich", "Schneefelder bis Juli über 2500m möglich; Grödel zu Saisonbeginn empfohlen", "Wetter oberhalb 2500m schnell wechselhaft: früher Start und Wettercheck unbedingt notwendig"],
    updated_at: "2026-06-01"
  },
  "08-s3": {
    description_it: "Il punto di partenza è già una meraviglia storica: il Pont d'Ael, costruito nel 3 a.C., è uno dei ponti-acquedotto romani meglio conservati delle Alpi. La struttura in pietra porta ancora le iscrizioni dedicatorie dei costruttori e sovrasta la gola del torrente Grand Eyvia con eleganza millenaria. Da qui il sentiero inizia la sua risalita verso Petit Poignon a 1576 metri, guadagnando 883 metri di dislivello in 5,7 chilometri: una salita sostenuta, classificata E, attraverso la selvaggia Valle del Grand Eyvia nel Parco Nazionale del Gran Paradiso. Il percorso alterna tratti boscosi a zone più aperte, con scorci sulla profonda forra e sulla vegetazione tipica del fondovalle. L'arrivo a Petit Poignon regala un ambiente alpino quieto, lontano dai circuiti più frequentati della Valle di Cogne.",
    description_en: "The starting point alone is worth the journey: Pont d'Ael, built in 3 BC, is one of the best-preserved Roman aqueduct bridges in the Alps. Its stone structure still bears the dedicatory inscriptions of its builders and spans the Grand Eyvia gorge with timeless elegance. From here the trail climbs 883 metres over 5.7 kilometres to Petit Poignon at 1576 metres — a sustained E-rated ascent through the wild Grand Eyvia valley within the Gran Paradiso National Park. The route alternates forested stretches with open sections offering glimpses of the deep gorge below. The arrival at Petit Poignon offers a quiet alpine setting away from the more popular Cogne valley circuits.",
    description_fr: "Le point de départ est déjà un chef-d'œuvre : le Pont d'Ael, construit en 3 av. J.-C., est l'un des ponts-aqueducs romains les mieux conservés des Alpes. Sa structure en pierre porte encore les inscriptions dédicatoires de ses bâtisseurs et enjambe les gorges du Grand Eyvia avec une élégance millénaire. De là, le sentier monte 883 mètres sur 5,7 kilomètres jusqu'à Petit Poignon à 1576 mètres — une ascension soutenue, cotée E, à travers la sauvage vallée du Grand Eyvia dans le Parc National du Grand Paradis. L'itinéraire alterne tronçons forestiers et zones ouvertes avec des vues sur les gorges profondes.",
    description_de: "Der Ausgangspunkt ist bereits ein historisches Wunder: die Pont d'Ael, erbaut 3 v. Chr., gehört zu den am besten erhaltenen römischen Aquäduktbrücken der Alpen. Das Steinbauwerk trägt noch die Widmungsinschriften seiner Erbauer und überspannt die Schlucht des Grand Eyvia mit zeitloser Eleganz. Von hier steigt der Weg 883 Höhenmeter über 5,7 Kilometer bis Petit Poignon auf 1576 Metern — ein gleichmäßig anspruchsvoller E-Weg durch das wilde Grand-Eyvia-Tal im Nationalpark Gran Paradiso. Die Route wechselt zwischen Waldstrecken und offenen Abschnitten mit Blicken in die tiefe Schlucht.",
    shortDescription_it: "Da Pondel, con la meraviglia del Pont d'Ael romano (3 a.C.) come anticamera, fino a Petit Poignon nel cuore selvaggio della Valle del Grand Eyvia.",
    shortDescription_en: "From the Roman Pont d'Ael (3 BC) at Pondel, a sustained climb into the wild Grand Eyvia valley to the quiet alp of Petit Poignon.",
    shortDescription_fr: "Du Pont d'Ael romain (3 av. J.-C.) à Pondel, une montée soutenue dans la sauvage vallée du Grand Eyvia jusqu'à l'alpage de Petit Poignon.",
    shortDescription_de: "Von der römischen Pont d'Ael (3 v. Chr.) in Pondel hinauf ins wilde Grand-Eyvia-Tal zum stillen Alp Petit Poignon — Geschichte trifft Wildnis.",
    cultural_notes_it: "Il Pont d'Ael è un monumento nazionale. La struttura a doppio arco serviva contemporaneamente da acquedotto (livello superiore) e da via di transito (livello inferiore). Un must da visitare prima o dopo il percorso.",
    cultural_notes_en: "Pont d'Ael is a national monument. Its double-arch structure served simultaneously as an aqueduct (upper level) and a road bridge (lower level). Allow time to explore it before or after the hike.",
    cultural_notes_fr: "Le Pont d'Ael est un monument national. Sa structure à double arc servait à la fois d'aqueduc (niveau supérieur) et de voie de passage (niveau inférieur). À visiter avant ou après la randonnée.",
    cultural_notes_de: "Die Pont d'Ael ist ein nationales Denkmal. Ihr Doppelbogen diente gleichzeitig als Aquädukt (Oberebene) und Durchgangsweg (Unterebene). Vor oder nach der Wanderung unbedingt besichtigen.",
    updated_at: "2026-06-01"
  },
  "10-s21": {
    description_it: "L'alta Valpelline è una delle valli più selvagge e meno conosciute della Valle d'Aosta: un paesaggio di pascoli abbandonati, torrentelli e creste severe che culmina, verso sud, nel Cervino e nelle Grandes Murailles. Da Ferrère a 1704 metri il sentiero affronta subito un dislivello deciso di 992 metri in 5,5 chilometri, portando al Bivacco Chentre Bionaz a 2530 metri. Il percorso traversa ambienti alpini aperti con scorci progressivamente più ampi sulla valle sottostante e sui ghiacciai di confine con la Svizzera. Il bivacco è meta di alpinisti e escursionisti che intendono approfondire questo angolo remoto dell'alta Valpelline. La classificazione E riflette la lunghezza, il dislivello e il terreno a tratti impervio, ma non richiede attrezzatura tecnica. Fuori stagione la traccia può essere innevata.",
    description_en: "The upper Valpelline is one of the wildest and least-known valleys in the Aosta region, a landscape of abandoned pastures, rushing streams and severe ridgelines culminating southward in the Matterhorn and the Grandes Murailles. From Ferrère at 1704 metres the trail climbs 992 metres in 5.5 kilometres to the Bivacco Chentre Bionaz at 2530 metres. The route crosses open alpine terrain with progressively wider views over the valley below and the glaciers along the Swiss border. The bivouac is a base for alpinists and hikers exploring this remote corner of the high Valpelline. E-rated but without technical demands; the path may hold snow outside the main summer season.",
    description_fr: "La haute Valpelline est l'une des vallées les plus sauvages et les moins connues du Val d'Aoste, un paysage d'alpages abandonnés, de torrents et de crêtes sévères qui culminent au sud sur le Cervin et les Grandes Murailles. Depuis Ferrère à 1704 mètres, le sentier grimpe 992 mètres sur 5,5 kilomètres jusqu'au Bivouac Chentre Bionaz à 2530 mètres. L'itinéraire traverse des terrains alpins ouverts avec des vues progressivement plus larges sur la vallée et les glaciers frontaliers. Coté E, sans difficulté technique ; enneigement possible hors saison estivale.",
    description_de: "Das obere Valpelline gehört zu den wildesten und unbekanntesten Tälern des Aostatals — eine Landschaft aus verlassenen Alpen, Bächen und schroffen Kämmen, die im Süden zu Matterhorn und Grandes Murailles ansteigen. Von Ferrère auf 1704 Metern geht es mit 992 Höhenmetern auf 5,5 Kilometern hinauf zum Bivacco Chentre Bionaz auf 2530 Metern. Der Weg durchquert offenes Alpengelände mit zunehmend weitem Blick ins Tal und auf die Grenzgletscher zur Schweiz. E-Bewertung ohne technische Anforderungen; außerhalb der Hauptsaison kann Schnee liegen.",
    shortDescription_it: "Salita solitaria verso il Bivacco Chentre Bionaz nell'alta Valpelline selvaggia: quasi 1000m di dislivello tra pascoli abbandonati e panorami sui ghiacciai di confine.",
    shortDescription_en: "A solitary climb to Bivacco Chentre Bionaz deep in the wild upper Valpelline — nearly 1000m of gain among abandoned pastures and border glaciers.",
    shortDescription_fr: "Montée solitaire vers le Bivouac Chentre Bionaz dans la sauvage haute Valpelline — près de 1000m de dénivelé entre alpages abandonnés et glaciers frontaliers.",
    shortDescription_de: "Einsamer Aufstieg zum Bivacco Chentre Bionaz im wilden oberen Valpelline — fast 1000 Hm zwischen verlassenen Alpen und Grenzgletschern.",
    warnings_it: ["Sentiero isolato: scarsa frequentazione fuori dall'estate; portare navigazione offline", "Neve possibile fino a giugno e da ottobre in poi sulla parte alta", "Verificare l'agibilità del bivacco prima di programmare un pernottamento"],
    warnings_en: ["Isolated trail with little traffic outside summer; carry offline navigation", "Snow possible above 2000m until June and from October onwards", "Check bivouac availability before planning an overnight stay"],
    warnings_fr: ["Sentier isolé, peu fréquenté hors été ; navigation hors ligne recommandée", "Neige possible au-dessus de 2000m jusqu'en juin et dès octobre", "Vérifier la disponibilité du bivouac avant de prévoir un hébergement"],
    warnings_de: ["Abgelegener Weg mit wenig Verkehr außerhalb des Sommers; Offline-Navigation mitführen", "Schnee über 2000m möglich bis Juni und ab Oktober", "Verfügbarkeit des Biwaks vor einer Übernachtung überprüfen"],
    updated_at: "2026-06-01"
  },
  "11-s2": {
    description_it: "Un sentiero che non perdona i ritardi: da Grand Brissogne a 1042 metri la salita non concede mai tregua per 7,4 chilometri e 1567 metri di dislivello, fino al Bivacco Menabreaz a 2556 metri. Il versante sinistro orografico della Valle centrale è qui quasi sconosciuto al grande escursionismo, il che rende questo percorso una scoperta per chi cerca solitudine e ambienti alpini autentici. La classificazione E è severa ma giusta: il terreno è vario, la traccia non sempre evidente, e la lunghezza del percorso unita alla pendenza sostenuta richiede ottima preparazione fisica. I pascoli alti e le creste verso il bivacco aprono progressivamente su panorami di grande ampiezza verso la Valle centrale. Ideale per chi vuole immergersi in un angolo autentico della montagna valdostana lontano dai circuiti battuti.",
    description_en: "A trail that demands full commitment: from Grand Brissogne at 1042 metres the climb never relents across 7.4 kilometres and 1567 metres of elevation gain to the Bivacco Menabreaz at 2556 metres. This left orographic flank of the central Aosta Valley sees almost no visitor traffic, making it a genuine discovery for those seeking solitude and authentic alpine terrain. The E rating is well-earned — varied surfaces, an occasionally faint path, and the combined length and sustained gradient demand strong physical fitness. The upper pastures and ridgelines open onto sweeping panoramas of the main valley. A compelling choice for those who want to experience Valdostan mountain country away from the beaten track.",
    description_fr: "Un sentier qui n'admet pas les retards : depuis Grand Brissogne à 1042 mètres, la montée ne s'interrompt jamais sur 7,4 kilomètres et 1567 mètres de dénivelé, jusqu'au Bivouac Menabreaz à 2556 mètres. Ce versant gauche orographique de la vallée centrale est quasi inconnu des randonneurs, ce qui en fait une vraie découverte pour qui cherche la solitude et un terrain alpin authentique. La cotation E est méritée : surfaces variées, tracé parfois peu marqué, longueur et pente soutenues exigent une excellente forme physique. Les hauts alpages et les crêtes offrent des panoramas étendus sur la vallée principale.",
    description_de: "Ein Weg ohne Verschnaufpausen: Von Grand Brissogne auf 1042 Metern steigt die Route unablässig über 7,4 Kilometer und 1567 Höhenmeter bis zum Bivacco Menabreaz auf 2556 Metern. Dieser linke Talhang des Hauptaostatals ist dem Wandertourismus so gut wie unbekannt — eine echte Entdeckung für alle, die Einsamkeit und ursprüngliches Alpingelände suchen. Die E-Einstufung ist verdient: wechselndes Untergelände, gelegentlich undeutliche Wegführung und die Kombination aus Länge und Steigung verlangen eine hervorragende körperliche Verfassung. Die oberen Weiden und Kämme bieten weitreichende Panoramen über das Haupttal.",
    shortDescription_it: "Salita impegnativa da Grand Brissogne al Bivacco Menabreaz su un versante quasi sconosciuto della Valle centrale: 1567m di dislivello tra solitudine e panorami.",
    shortDescription_en: "A demanding climb from Grand Brissogne to Bivacco Menabreaz on a barely-visited flank of the central Aosta Valley — 1567m of gain and true solitude.",
    shortDescription_fr: "Montée exigeante de Grand Brissogne au Bivouac Menabreaz sur un versant presque inconnu de la vallée centrale — 1567m de dénivelé en pleine solitude.",
    shortDescription_de: "Anspruchsvoller Aufstieg von Grand Brissogne zum Bivacco Menabreaz an einem kaum bekannten Hang des Aostatals — 1567 Hm und echte Einsamkeit.",
    warnings_it: ["Sentiero poco frequentato: portare traccia GPS offline e comunicare il programma a terzi", "Dislivello elevato: valutare con onestà il livello di allenamento; non adatto a principianti", "Partenza bassa a 1042m: la giornata si allunga considerevolmente"],
    warnings_en: ["Low-traffic trail: carry an offline GPS track and leave your itinerary with someone", "High elevation gain: honestly assess your fitness level; not suitable for beginners", "Low starting elevation means a long day; plan time and energy accordingly"],
    warnings_fr: ["Sentier peu fréquenté : emporter une trace GPS hors ligne et informer un tiers", "Dénivelé important : évaluer honnêtement son niveau physique ; déconseillé aux débutants", "Départ bas à 1042m : la journée est longue, prévoir temps et énergie"],
    warnings_de: ["Wenig begangener Weg: Offline-GPS-Track mitführen und Tourplan hinterlassen", "Hoher Höhenunterschied: Fitness realistisch einschätzen; nicht für Anfänger", "Niedriger Startpunkt bedeutet einen langen Tag — Zeit und Energie einplanen"],
    updated_at: "2026-06-01"
  },
  "07-s47": {
    description_it: "Il sentiero che sale da Champoluc al Col Palasinaz è uno dei percorsi di valico più significativi della Val d'Ayas, nella zona del Monte Rosa. Si parte dal centro di Champoluc a 1560 metri di quota, nel cuore della rinomata stazione di Brusson-Champoluc, e si risale con costanza il fianco orientale della valle attraverso pascoli e boschi di larici. Il dislivello positivo di 1115 metri in 6,9 chilometri impone un passo regolare e allenamento adeguato. Man mano che si guadagna quota, il panorama si apre verso le cime del gruppo del Monte Rosa, con le loro pareti glaciali che dominano l'orizzonte a ovest. Il Col Palasinaz, a 2680 metri, è il punto d'incontro tra la Val d'Ayas e la vallata di Brusson: da questa soglia lo sguardo abbraccia entrambi i versanti, regalando una delle viste più complete sull'alta Valle d'Aosta orientale. La difficoltà E richiede buone scarpe da trekking e attenzione nella parte alta, dove il terreno può presentare tratti erbosi ripidi.",
    description_en: "The trail from Champoluc to Col Palasinaz is one of the most rewarding high passes in the Val d'Ayas, set against the spectacular backdrop of the Monte Rosa massif. Starting from Champoluc at 1560 m, the route climbs 1115 metres over 6.9 km through larch forests and alpine meadows. The gradient is sustained throughout, demanding a steady pace and good fitness. As altitude increases, the glaciated peaks of the Monte Rosa group come into full view to the west. The Col Palasinaz at 2680 m marks the watershed between Val d'Ayas and the Brusson valley, offering a sweeping panorama across both sides of this corner of eastern Aosta Valley. Rated E, the trail requires sturdy footwear and care on the steeper upper sections.",
    description_fr: "Le sentier qui relie Champoluc au Col Palasinaz est l'un des itinéraires de col les plus significatifs de la Val d'Ayas, dans la zone du Mont Rose. Au départ de Champoluc à 1560 m d'altitude, le parcours remonte le versant oriental de la vallée à travers forêts de mélèzes et alpages, avec un dénivelé positif de 1115 mètres sur 6,9 km. À mesure que l'on prend de l'altitude, le panorama s'ouvre sur les sommets et les glaciers du groupe du Mont Rose. Le Col Palasinaz, à 2680 m, constitue le point de rencontre entre la Val d'Ayas et la vallée de Brusson. La difficulté E exige de bonnes chaussures de randonnée et de la prudence sur les parties hautes.",
    description_de: "Der Weg von Champoluc zum Col Palasinaz ist einer der bedeutendsten Passübergänge im Val d'Ayas, im Bereich der Monte-Rosa-Gruppe. Ausgangspunkt ist Champoluc auf 1560 m; der Pfad steigt über 6,9 km mit 1115 Höhenmetern durch Lärchenwälder und Almwiesen an. Mit zunehmender Höhe öffnet sich der Blick auf die vergletscherten Gipfel der Monte-Rosa-Gruppe im Westen. Der Col Palasinaz auf 2680 m bildet die Wasserscheide zwischen dem Val d'Ayas und dem Brusson-Tal und bietet einen weiten Ausblick auf beide Talseiten. Schwierigkeitsgrad E erfordert festes Schuhwerk und Sorgfalt in den steileren Oberabschnitten.",
    shortDescription_it: "Dal cuore di Champoluc al Col Palasinaz (2680 m): un valico alpino tra Val d'Ayas e Brusson con vista sul gruppo del Monte Rosa.",
    shortDescription_en: "From Champoluc to Col Palasinaz (2680 m): a classic alpine pass linking Val d'Ayas and Brusson with sweeping Monte Rosa views.",
    shortDescription_fr: "De Champoluc au Col Palasinaz (2680 m) : un col alpin entre la Val d'Ayas et Brusson, avec vue sur le massif du Mont Rose.",
    shortDescription_de: "Von Champoluc zum Col Palasinaz (2680 m): ein alpiner Übergang zwischen Val d'Ayas und Brusson mit Blick auf die Monte-Rosa-Gruppe.",
    updated_at: "2026-06-01"
  },
  "08-s1": {
    description_it: "Un breve itinerario di straordinaria densità storica che unisce la frazione di Moulin, a 653 metri di quota presso Aymavilles, al sito del Pont d'Ael a 885 metri. Il Pont d'Ael è uno dei manufatti romani meglio conservati dell'arco alpino: un acquedotto-ponte del 3 avanti Cristo che convogliava le acque del torrente Grand Eyvia verso i fondovalle abitati. La struttura, alta una ventina di metri, integra un passaggio carraio sovrapposto al canale idrico, testimonianza dell'ingegneria romana che sapeva unire funzione idraulica e viabilità. Il percorso, con soli 238 metri di dislivello in 3,6 chilometri, è accessibile anche a escursionisti meno allenati e si sviluppa in un paesaggio di media collina dominato da vegetazione mediterranea e castagneti. La difficoltà E è contenuta, ma il tratto terminale richiede attenzione per il terreno irregolare vicino al ponte. Meta ideale per chi vuole unire escursionismo leggero e archeologia alpina.",
    description_en: "A short but historically exceptional walk linking the hamlet of Moulin (653 m) near Aymavilles to the ancient site of Pont d'Ael (885 m). Built around 3 BC, the Pont d'Ael is one of the best-preserved Roman aqueduct bridges in the Alps. The structure, roughly twenty metres high, combines a water channel with a roadway above it, showcasing Roman hydraulic and civil engineering at its most elegant. The route covers only 3.6 km with 238 metres of ascent, making it suitable for all fitness levels. The landscape is one of mid-valley hillsides, chestnut groves and Mediterranean scrub. Rated E, with some care needed on uneven ground near the bridge itself. An ideal destination for those combining light hiking with alpine archaeology.",
    description_fr: "Un court itinéraire d'une richesse historique exceptionnelle, reliant le hameau de Moulin (653 m) près d'Aymavilles au site du Pont d'Ael (885 m). Construit vers 3 av. J.-C., le Pont d'Ael est l'un des aqueducs romains les mieux conservés de l'arc alpin. La structure, haute d'une vingtaine de mètres, combine un canal hydraulique et un passage charretier superposé, témoignage remarquable du génie romain. Avec seulement 238 mètres de dénivelé sur 3,6 km, le parcours est accessible à tous. Le paysage se compose de collines de moyenne altitude, de châtaigneraies et de maquis méditerranéen. Difficulté E, avec prudence recommandée sur terrain irrégulier à l'approche du pont.",
    description_de: "Ein kurzer, aber historisch außergewöhnlicher Weg verbindet den Weiler Moulin (653 m) bei Aymavilles mit dem antiken Pont d'Ael (885 m). Das um 3 v. Chr. erbaute Aquäduktbauwerk gilt als eines der besterhaltenen römischen Brückenaquädukte der Alpen. Die rund zwanzig Meter hohe Konstruktion vereint einen Wasserkanal mit einem darüber liegenden Fahrweg — ein Meisterwerk römischer Hydraulik- und Straßenbaukunst. Mit nur 238 Höhenmetern auf 3,6 km ist die Route für alle Fitnessstufen geeignet. Die Landschaft besteht aus Mittelhanghügeln, Kastanienwäldern und mediterranem Gebüsch. Schwierigkeitsgrad E; in der Nähe des Brückenbauwerks auf unebenem Untergrund Vorsicht geboten.",
    shortDescription_it: "Da Moulin al Pont d'Ael (885 m): un breve cammino verso un acquedotto romano del 3 a.C., tra i meglio conservati delle Alpi.",
    shortDescription_en: "From Moulin to Pont d'Ael (885 m): a short walk to a 3 BC Roman aqueduct bridge, one of the finest preserved in the Alps.",
    shortDescription_fr: "De Moulin au Pont d'Ael (885 m) : courte randonnée vers un aqueduc romain du 3 av. J.-C., parmi les mieux conservés des Alpes.",
    shortDescription_de: "Von Moulin zum Pont d'Ael (885 m): ein kurzer Weg zu einem römischen Aquädukt aus dem 3. Jh. v. Chr., einem der besterhaltenen der Alpen.",
    cultural_notes_it: "Il Pont d'Ael (3 a.C.) è un acquedotto romano a doppio livello — canale idrico superiore e passaggio inferiore — visitabile e inserito nell'elenco dei beni culturali della Valle d'Aosta.",
    cultural_notes_en: "Pont d'Ael (3 BC) is a two-level Roman aqueduct — upper water channel, lower walkway — open to visitors and listed among the Aosta Valley's cultural heritage sites.",
    cultural_notes_fr: "Le Pont d'Ael (3 av. J.-C.) est un aqueduc romain à deux niveaux — canal d'eau supérieur, passage inférieur — visitable et classé parmi les biens culturels de la Vallée d'Aoste.",
    cultural_notes_de: "Die Pont d'Ael (3 v. Chr.) ist ein zweistöckiges römisches Aquädukt — oberer Wasserkanal, unterer Durchgang — besichtigbar und Teil des Kulturerbes des Aostatals.",
    updated_at: "2026-06-01"
  },
  "08-s8": {
    description_it: "Un itinerario che percorre il versante viticolo della Val di Cogne, risalendo da Champsolin a 762 metri fino alla borgata di Serignan a 1190 metri, con un dislivello di 770 metri in 4,5 chilometri. Questo settore della valle, esposto a sud e caratterizzato da suoli ben drenati, ospita vigneti terrazzati che producono vini tipici della tradizione valdostana. Il sentiero si sviluppa attraverso un paesaggio umano stratificato: muretti a secco, terrazzamenti antichi e piccole borgate rurali scandiscono la salita, rendendo questo percorso tanto un'escursione naturalistica quanto un viaggio nel paesaggio agrario tradizionale della Valle d'Aosta. La difficoltà E, con quasi ottocento metri di dislivello concentrati in poco più di quattro chilometri, impone un passo regolare. La progressione altimetrica consente di apprezzare il progressivo passaggio dalla zona viticola alle fasce più alte di pascolo e bosco rado, con le pareti rocciose della Val di Cogne che si stagliano all'orizzonte.",
    description_en: "This trail climbs the vineyard-covered slopes of the Val di Cogne, from Champsolin at 762 m to the hamlet of Serignan at 1190 m — 770 metres of ascent over 4.5 km. The south-facing hillside hosts terraced vineyards typical of the Aosta Valley winemaking tradition, supported by ancient dry-stone walls. The route is as much a journey through a traditional agricultural landscape as it is a nature hike: small rural hamlets, centuries-old terracing and the rocky walls of the Val di Cogne frame the climb. Rated E, the sustained gradient over a short distance demands a steady rhythm. The path transitions gradually from vine terraces to higher pastures and sparse woodland.",
    description_fr: "Ce sentier parcourt le versant viticole de la Val di Cogne, grimpant de Champsolin (762 m) jusqu'au hameau de Serignan (1190 m) — 770 mètres de dénivelé sur 4,5 km. Le versant exposé au sud accueille des vignes en terrasses caractéristiques de la tradition vitivinicole valdôtaine, soutenues par d'anciens murs en pierre sèche. L'itinéraire est autant un voyage dans un paysage agricole traditionnel qu'une randonnée naturaliste : petits hameaux ruraux, terrasses séculaires et parois rocheuses de la Val di Cogne rythment la montée. Difficulté E ; la pente soutenue sur une courte distance demande un rythme régulier.",
    description_de: "Dieser Weg erklimmt den weinbaugeprägten Hang des Val di Cogne von Champsolin (762 m) bis zum Weiler Serignan (1190 m) — 770 Höhenmeter auf 4,5 km. Der nach Süden ausgerichtete Hang trägt Terrassenreben, die für die valdostanische Weinbautradition charakteristisch sind und von alten Trockensteinmauern gestützt werden. Die Route ist ebenso eine Reise durch eine traditionelle Agrarlandschaft wie eine Naturwanderung: kleine Weiler, jahrhundertealte Terrassen und die Felswände des Val di Cogne begleiten den Aufstieg. Schwierigkeitsgrad E; das anhaltende Gefälle auf kurzer Distanz verlangt einen gleichmäßigen Schritt.",
    shortDescription_it: "Da Champsolin a Serignan (1190 m) tra vigneti terrazzati e borgate rurali: il sentiero che racconta il paesaggio viticolo della Val di Cogne.",
    shortDescription_en: "From Champsolin to Serignan (1190 m) through terraced vineyards and rural hamlets: the trail that tells the story of Val di Cogne's wine landscape.",
    shortDescription_fr: "De Champsolin à Serignan (1190 m) entre vignes en terrasses et hameaux ruraux : l'itinéraire du versant viticole de la Val di Cogne.",
    shortDescription_de: "Von Champsolin nach Serignan (1190 m) durch Terrassenreben und Weiler: der Weg durch die Weinbaulandschaft des Val di Cogne.",
    updated_at: "2026-06-01"
  },
  "10-s23": {
    description_it: "Dal pianoro di Pouillaye a 1626 metri, nel cuore della Valpelline presso Bionaz, il sentiero si inerpica deciso verso il Colle di Montagnaye a 2907 metri, toccando il confine italo-svizzero. Con 1282 metri di dislivello in 6,3 chilometri, si tratta di uno degli itinerari di valico più impegnativi della Valpelline. La progressione porta dapprima attraverso ampi pascoli d'alpeggio dove in estate stazionano le mandrie di vacche valdostane, poi su terreno sempre più aperto e roccioso, fino alle ultime balze che precedono la cresta di confine. Il Colle di Montagnaye, a quasi 2900 metri, segna la frontiera tra il Canton Vallese svizzero e la Valle d'Aosta italiana: da qui lo sguardo spazia su entrambi i versanti, con le creste della Valpelline e le vette del gruppo del Grand Combin che emergono a nord. La difficoltà E impone buon allenamento e attrezzatura adeguata; le condizioni del colle possono essere difficili fuori stagione.",
    description_en: "From the plateau of Pouillaye at 1626 m in the Valpelline near Bionaz, this demanding trail climbs to the Colle di Montagnaye at 2907 m — right on the Italian-Swiss border. With 1282 metres of ascent over 6.3 km, it is one of the most strenuous pass routes in the Valpelline. The path climbs through broad summer pastures where Valdostana cattle graze in season, then onto increasingly open, rocky terrain leading to the border ridge. From the col, views extend across both sides of the watershed, with the ridges of Valpelline and the Grand Combin group visible to the north. Rated E; good fitness, proper equipment and attention to seasonal conditions are essential.",
    description_fr: "Depuis le plateau de Pouillaye (1626 m) dans la Valpelline près de Bionaz, ce sentier exigeant monte au Colle di Montagnaye (2907 m), sur la frontière italo-suisse. Avec 1282 mètres de dénivelé sur 6,3 km, c'est l'un des itinéraires de col les plus ardus de la Valpelline. Le chemin traverse de larges alpages d'estive avant d'atteindre un terrain de plus en plus ouvert et rocheux menant à la crête frontière. Du col, le panorama s'étend sur les deux versants, avec les arêtes de la Valpelline et le massif du Grand Combin au nord. Difficulté E ; bonne forme physique, équipement adapté et attention aux conditions saisonnières indispensables.",
    description_de: "Vom Plateau Pouillaye (1626 m) in der Valpelline bei Bionaz führt dieser anspruchsvolle Weg zum Colle di Montagnaye (2907 m) — unmittelbar an der italienisch-schweizerischen Grenze. Mit 1282 Höhenmetern auf 6,3 km gehört er zu den kräftezehrendsten Passrouten der Valpelline. Der Pfad durchquert weitläufige Sommeralmen, auf denen im Sommer Valdostana-Rinder weiden, bevor er auf zunehmend offenes, felsiges Gelände trifft. Vom Col aus reicht der Blick über beide Talseiten, mit den Kämmen der Valpelline und der Grand-Combin-Gruppe im Norden. Schwierigkeitsgrad E; gute Kondition, angemessene Ausrüstung und Beachtung der Saisonbedingungen erforderlich.",
    shortDescription_it: "Da Pouillaye (1626 m) al Colle di Montagnaye (2907 m): un valico di frontiera tra la Valpelline e il Canton Vallese svizzero.",
    shortDescription_en: "From Pouillaye (1626 m) to Colle di Montagnaye (2907 m): a demanding border crossing between the Valpelline and the Swiss Canton of Valais.",
    shortDescription_fr: "De Pouillaye (1626 m) au Colle di Montagnaye (2907 m) : un col frontière entre la Valpelline et le Canton du Valais suisse.",
    shortDescription_de: "Von Pouillaye (1626 m) zum Colle di Montagnaye (2907 m): ein anspruchsvoller Grenzübergang zwischen der Valpelline und dem Schweizer Kanton Wallis.",
    warnings_it: ["Dislivello elevato (1282 m): buona preparazione fisica necessaria.", "Zona di confine d'alta quota: possibili nevai fino a luglio. Verificare le condizioni del colle."],
    warnings_en: ["High elevation gain (1282 m): good fitness required.", "High-altitude border area: snowfields possible until July. Check pass conditions."],
    warnings_fr: ["Dénivelé important (1282 m) : bonne condition physique nécessaire.", "Zone frontalière d'altitude : névés possibles jusqu'en juillet. Vérifier l'état du col."],
    warnings_de: ["Hoher Höhenunterschied (1282 m): gute Kondition erforderlich.", "Hochgelegenes Grenzgebiet: Firnfelder bis Juli möglich. Passbedingungen prüfen."],
    updated_at: "2026-06-01"
  },
  "11-s6": {
    description_it: "Un itinerario d'alta quota per escursionisti esperti che collega il Bivacco Menabreaz a 2546 metri al Col des Laures a 3035 metri, nel settore della Valle centrale presso Brissogne. Con 486 metri di dislivello in 4 chilometri, il percorso è tecnicamente breve ma impegnativo: la classificazione EE segnala terreno che richiede passo sicuro, assenza di vertigini e buona capacità di orientamento fuori dai sentieri battuti. A questa quota il paesaggio è quello dell'alta montagna valdostana: rocce nude, eventuali nevai residui, assenza di alberi e cielo aperto. Il Col des Laures a 3035 metri rappresenta un traguardo alpinistico significativo, con panorami sull'alta Valle centrale e sulle creste circostanti. Le condizioni meteo possono mutare rapidamente: la finestra stagionale è ristretta, generalmente da luglio a settembre inoltrato.",
    description_en: "A high-altitude route for experienced hikers, linking Bivacco Menabreaz (2546 m) to Col des Laures (3035 m) in the Valle centrale area near Brissogne. The route covers 4 km with 486 metres of ascent, but its EE rating reflects the nature of the terrain rather than the distance: sure-footedness, a head for heights and solid mountain orientation skills are all required. Above 2500 m the landscape is bare rock, possible late snow patches and open sky. Col des Laures at 3035 m commands wide views over the upper Valle centrale and surrounding ridges. Weather can change rapidly at this altitude; the viable season is typically July to late September.",
    description_fr: "Un itinéraire de haute altitude pour randonneurs expérimentés reliant le Bivouac Menabreaz (2546 m) au Col des Laures (3035 m), dans le secteur de la Vallée centrale près de Brissogne. Le parcours couvre 4 km avec 486 mètres de dénivelé, mais la cotation EE reflète la nature du terrain plutôt que la distance : terrain stable, absence de vertige et bonne orientation en montagne sont indispensables. Au-dessus de 2500 m, le paysage est celui de la haute montagne valdôtaine. Le Col des Laures (3035 m) offre un panorama étendu sur la haute Vallée centrale. La saison praticable va généralement de juillet à fin septembre.",
    description_de: "Eine Hochgebirgstour für erfahrene Wanderer, die die Biwakschachtel Menabreaz (2546 m) mit dem Col des Laures (3035 m) im Valle-centrale-Gebiet bei Brissogne verbindet. Die Route umfasst 4 km mit 486 Höhenmetern; die EE-Bewertung spiegelt die Beschaffenheit des Geländes wider: Trittsicherheit, Schwindelfreiheit und gutes Orientierungsvermögen im Hochgebirge sind Voraussetzung. Oberhalb von 2500 m prägen blanker Fels, eventuelle Altschneefelder und weiter Himmel das Bild. Der Col des Laures (3035 m) bietet einen weiten Ausblick über das obere Valle centrale. Das Wetter kann sich rasch ändern; die begehbare Saison reicht in der Regel von Juli bis Ende September.",
    shortDescription_it: "Dal Bivacco Menabreaz (2546 m) al Col des Laures (3035 m): alta quota, terreno EE e panorami sull'alta Valle centrale valdostana.",
    shortDescription_en: "From Bivacco Menabreaz (2546 m) to Col des Laures (3035 m): high altitude, EE terrain and sweeping views over the upper Valle centrale.",
    shortDescription_fr: "Du Bivouac Menabreaz (2546 m) au Col des Laures (3035 m) : haute altitude, terrain EE et panoramas sur la haute Vallée centrale.",
    shortDescription_de: "Von der Biwakschachtel Menabreaz (2546 m) zum Col des Laures (3035 m): Hochgebirge, EE-Gelände und weite Aussichten über das obere Valle centrale.",
    warnings_it: ["Percorso EE: richiede passo sicuro, assenza di vertigini e buona capacità di orientamento.", "Finestra stagionale ristretta: luglio–settembre. Verificare la presenza di nevai residui.", "Dotazione obbligatoria: abbigliamento a strati, mappa, bussola. Il meteo può cambiare rapidamente oltre i 3000 m."],
    warnings_en: ["EE route: sure-footedness, no fear of heights and good mountain navigation skills required.", "Narrow seasonal window: July–September. Check for late snow before setting out.", "Mandatory equipment: layered clothing, map, compass. Weather can change rapidly above 3000 m."],
    warnings_fr: ["Itinéraire EE : terrain stable, absence de vertige et bonne orientation indispensables.", "Fenêtre saisonnière restreinte : juillet–septembre. Vérifier la présence de neige résiduelle.", "Équipement obligatoire : vêtements en couches, carte, boussole. La météo peut changer rapidement au-dessus de 3000 m."],
    warnings_de: ["EE-Route: Trittsicherheit, Schwindelfreiheit und gutes Orientierungsvermögen erforderlich.", "Enge Saisonzeit: Juli–September. Auf Altschneefelder prüfen.", "Pflichtausrüstung: Mehrlagenbekleidung, Karte, Kompass. Oberhalb 3000 m kann das Wetter schnell umschlagen."],
    updated_at: "2026-06-01"
  }
};

const sk = JSON.parse(fs.readFileSync(skPath, 'utf8'));
let changed = 0;
const merged = sk.map(t => {
  const p = patch[t.slug];
  if (!p) return t;
  const fixes = {};
  if (!t.duration_hours) fixes.duration_hours = cai(t.distance_km, t.elevation_gain_m, t.elevation_loss_m);
  if (!t.mobile_coverage) fixes.mobile_coverage = 'partial';
  if (!t.fitness_level) fixes.fitness_level = diffToFitness[t.difficulty] ?? 2;
  if (!t.name_en) fixes.name_en = t.name_it;
  if (!t.name_fr) fixes.name_fr = t.name_it;
  if (!t.name_de) fixes.name_de = t.name_it;
  changed++;
  return { ...t, ...fixes, ...p };
});
console.log('Patchati (blocco D):', changed);
fs.writeFileSync(skPath, JSON.stringify(merged, null, 2), 'utf8');
console.log('OK');
