'use strict';
// Round 2 — blocco E: BI + BL + BK (15 sentieri). description_* 4 lingue.
const fs = require('fs');
const path = require('path');
const skPath = path.join(__dirname, '../src/data/trails-skeleton.json');
function cai(km, gain, loss) { return Math.max(0.5, Math.round((km/4+Math.max(gain,0)/400+Math.max(loss,0)/600)*2)/2); }
const diffToFitness = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };

const patch = {
  "12-s22": {
    description_it: "Il sentiero prende il via da Estoul (1884 m), graziosa frazione di Brusson immersa nei larici, e risale con pendenza regolare verso nord-est attraverso pascoli aperti che d'estate ospitano greggi al pascolo. Superata la zona dei prati bassi, il tracciato aggira le propaggini meridionali della Punta Regina, dove la vegetazione si dirada e il panorama si apre progressivamente sulle creste che dividono la Val d'Ayas dalla Valle di Gressoney. Il terreno è erboso e ben segnalato, con qualche breve tratto su roccia affiorante vicino alle quote più alte. Si raggiunge infine il Col de Garda (2289 m), valico panoramico che offre una vista ampia verso il massiccio del Monte Rosa a est e il fondovalle di Brusson a ovest. Il dislivello contenuto e il percorso su sentiero ben tracciato rendono questa escursione adatta a escursionisti con minima esperienza. Consigliabile nella stagione estiva da giugno a settembre.",
    description_en: "Starting from Estoul (1884 m), a charming hamlet of Brusson nestled among larch trees, the trail climbs steadily north-east across open pastures that host grazing flocks in summer. Rounding the southern flanks of Punta Regina, the vegetation thins and broad views open toward the ridgeline separating Val d'Ayas from the Gressoney valley. The path is grassy and well-marked, with occasional rocky sections near the higher reaches. The Col de Garda (2289 m) rewards hikers with a sweeping panorama over the Monte Rosa massif to the east and the Brusson valley floor to the west. A manageable ascent suitable for moderately fit walkers from June through September.",
    description_fr: "Au départ d'Estoul (1884 m), charmant hameau de Brusson niché parmi les mélèzes, le sentier monte régulièrement vers le nord-est à travers des alpages ouverts où paissent les troupeaux en été. En contournant les flancs sud de la Punta Regina, la végétation se raréfie et le panorama s'élargit vers la crête séparant le val d'Ayas de la vallée de Gressoney. Le terrain est herbeux et bien balisé, avec quelques passages rocheux près du point culminant. Le Col de Garda (2289 m) offre une vue dégagée sur le massif du Mont Rose à l'est et sur le fond de vallée de Brusson à l'ouest. Une randonnée accessible, praticable de juin à septembre.",
    description_de: "Der Weg beginnt in Estoul (1884 m), einem malerischen Weiler von Brusson inmitten von Lärchenwäldern, und steigt gleichmäßig nach Nordosten über offene Almwiesen an, auf denen im Sommer Herden weiden. Beim Umrunden der Südflanken der Punta Regina lichtet sich die Vegetation, und der Blick öffnet sich zur Kammlinie zwischen dem Val d'Ayas und dem Gressoney-Tal. Das Gelände ist grasbewachsen und gut markiert, mit vereinzelten Felsabschnitten in den oberen Bereichen. Der Col de Garda (2289 m) belohnt mit einem weiten Panorama über das Monte-Rosa-Massiv im Osten und das Brusson-Tal im Westen. Eine lohnende Tagestour von Juni bis September.",
    updated_at: "2026-06-01"
  },
  "13-s12": {
    description_it: "Questo sentiero di raccordo collega i due borghi di Tilly (964 m) e Mayn (1058 m) nella bassa Val d'Ayas, nel comune di Brusson. Il percorso, breve ma ricco di carattere, si snoda su mulattiera acciottolata attraverso castagneti secolari e lembi di vigneto terrazzato, tipici del paesaggio culturale di questa porzione di valle. Il dislivello modesto e la lunghezza contenuta lo rendono adatto a tutti, compresi famiglie con bambini e anziani. Lungo il cammino si incontrano antiche fontane in pietra e qualche edificio rurale restaurato, testimonianze di un'economia agropastorale oggi in parte sopravvissuta nei masi. Le viste sul fondovalle e sulle pendici boscose di fronte completano un'escursione indicata come passeggiata culturale o come anello di connessione con altri itinerari della zona. Percorribile in tutte le stagioni.",
    description_en: "A short but characterful link trail connecting the hamlets of Tilly (964 m) and Mayn (1058 m) in the lower Val d'Ayas. The cobbled mule track winds through ancient chestnut groves and terraced vineyards typical of this lower stretch of the valley. The gentle gradient makes it suitable for all ages and abilities, including families with young children. Stone fountains and restored rural buildings dot the route, bearing witness to a long agropastoral tradition. Fine views over the valley floor and wooded slopes opposite round off what is an ideal cultural stroll or connecting leg for longer itineraries. Walkable in all seasons.",
    description_fr: "Ce court sentier de liaison relie les hameaux de Tilly (964 m) et Mayn (1058 m) dans le bas val d'Ayas. L'ancienne mulatière pavée serpente à travers des châtaigneraies séculaires et des vignes en terrasses, typiques du paysage cultural de cette portion de vallée. La faible dénivelée et la courte distance en font une promenade accessible à tous, y compris aux familles avec enfants. On croise quelques fontaines en pierre et des bâtiments ruraux restaurés, témoins d'une longue tradition agropastorale. Les vues sur le fond de vallée et les versants boisés d'en face complètent agréablement cette balade culturelle, praticable en toutes saisons.",
    description_de: "Ein kurzer, aber reizvoller Verbindungsweg zwischen den Weilern Tilly (964 m) und Mayn (1058 m) im unteren Val d'Ayas. Der gepflasterte Saumpfad schlängelt sich durch jahrhundertealte Kastanienwälder und terrassierte Weinberge, die typisch für diesen Teil des Tals sind. Das geringe Gefälle macht ihn für alle Alters- und Fitnessgruppen geeignet, einschließlich Familien mit Kindern. Steinerne Brunnen und restaurierte Bauernhäuser zeugen von einer langen agropastoralen Tradition. Schöne Aussichten über den Talboden und die bewaldeten Hänge gegenüber runden diesen kulturellen Spaziergang ab, der in allen Jahreszeiten begehbar ist.",
    updated_at: "2026-06-01"
  },
  "14-s11": {
    description_it: "Anello straordinariamente selvaggio che parte e ritorna a Isollaz (700 m), nel comune di Challand-Saint-Victor. Il sentiero penetra nelle gole scavate dal torrente Roesaz, uno degli ambienti naturali più spettacolari e meno frequentati della bassa Valle d'Aosta. Le pareti di roccia metamorfica si stringono in canyon stretti dove la luce filtra a fatica, il terreno è bagnato e irregolare, e il rumore dell'acqua accompagna costantemente il cammino. Dopo le gole, il tracciato guadagna quota rapidamente su versanti boscosi e poi aperti, raggiungendo pascoli alti prima di rientrare sul versante opposto. Con 9,4 km e 1238 metri di dislivello, la classificazione EE riflette i passaggi esposti, gli attraversamenti di torrenti su massi e i tratti di sentiero poco evidenti che richiedono attenzione e orientamento. Percorribile da giugno a ottobre con condizioni stabili.",
    description_en: "A wild and spectacular loop starting and finishing at Isollaz (700 m) in the municipality of Challand-Saint-Victor. The route plunges into the gorges carved by the Roesaz torrent — one of the most dramatic and least-visited natural environments in the lower Aosta Valley. Narrow metamorphic rock walls close in to form genuine canyons where light barely penetrates, the ground is wet and uneven, and the sound of rushing water is constant. Above the gorges the trail gains height rapidly through forested and then open slopes before descending on the opposite flank. At 9.4 km and 1238 m of ascent, the EE rating reflects exposed passages, boulder stream crossings and faint sections requiring confident navigation. Suitable from June to October in stable conditions.",
    description_fr: "Un circuit sauvage et spectaculaire au départ et à l'arrivée d'Isollaz (700 m), commune de Challand-Saint-Victor. L'itinéraire plonge dans les gorges creusées par le torrent Roesaz, l'un des milieux naturels les plus dramatiques et les moins fréquentés de la basse Vallée d'Aoste. Les parois de roche métamorphique se resserrent en véritables canyons où la lumière pénètre à peine, le sol est humide et irrégulier, le bruit de l'eau omniprésent. Au-dessus des gorges, le sentier monte rapidement à travers forêt puis alpages avant de redescendre par le versant opposé. Passages exposés, traversées de torrents sur blocs et tronçons peu marqués exigent une navigation sûre. Praticable de juin à octobre par temps stable.",
    description_de: "Eine wildromantische Rundtour, die in Isollaz (700 m), Gemeinde Challand-Saint-Victor, beginnt und endet. Der Weg taucht in die vom Torrente Roesaz geschaffenen Schluchten ein — eine der dramatischsten und am wenigsten besuchten Naturlandschaften im unteren Aostatal. Enge Wände aus Metamorphitgestein formen echte Canyons, in denen kaum Licht eindringt, der Boden feucht und uneben ist und das Rauschen des Wassers nie verstummt. Oberhalb der Schluchten gewinnt der Pfad rasch an Höhe über bewaldete, dann offene Hänge, bevor er auf der Gegenseite absteigt. Mit 9,4 km und 1238 Höhenmetern: ausgesetzte Stellen, Bachüberquerungen auf Felsbrocken und schwach markierte Abschnitte. Begehbar von Juni bis Oktober bei stabilen Verhältnissen.",
    warnings_it: ["Percorso EE con 1238 m di dislivello: ottima preparazione, esperienza e attrezzatura adeguata.", "Gole umide e irregolari, attraversamenti di torrenti su massi: terreno scivoloso.", "Tratti esposti e sentiero poco evidente: orientamento necessario."],
    warnings_en: ["EE route with 1238 m of ascent: excellent fitness, experience and proper equipment required.", "Wet, uneven gorges and boulder stream crossings: slippery ground.", "Exposed passages and faint trail: navigation skills needed."],
    warnings_fr: ["Itinéraire EE avec 1238 m de dénivelé : excellente condition, expérience et équipement requis.", "Gorges humides et irrégulières, traversées sur blocs : terrain glissant.", "Passages exposés et sentier peu marqué : orientation nécessaire."],
    warnings_de: ["EE-Route mit 1238 Höhenmetern: ausgezeichnete Kondition, Erfahrung und Ausrüstung erforderlich.", "Feuchte, unebene Schluchten und Bachquerungen auf Felsblöcken: rutschig.", "Ausgesetzte Stellen und schwacher Pfad: Orientierungsvermögen nötig."],
    updated_at: "2026-06-01"
  },
  "15-s8": {
    description_it: "Il sentiero parte da Gouilles (628 m), piccola frazione nel comune di Châtillon, e risale il ripido versante soleggiato che domina la confluenza tra la Valtournenche e la Valle centrale della Valle d'Aosta. Il percorso si sviluppa principalmente su sentiero di campagna e mulattiera, attraversando prima vigneti e frutteti ben curati, poi macchie di roverella e pino silvestre caratteristiche di questo versante caldo e asciutto. Il dislivello di 623 m in soli 3,5 km rende la salita sostenuta, con pendenze che si mantengono moderate ma costanti per tutta la durata. A mano a mano che si guadagna quota, il panorama si allarga verso Châtillon, il castello di Ussel e le vette che chiudono la Valtournenche verso nord. Si giunge infine a Del (1251 m), modesto insediamento montano immerso in una vegetazione più fresca. Itinerario consigliato nella mezza stagione e in estate.",
    description_en: "Setting off from Gouilles (628 m) in the municipality of Châtillon, the trail climbs the sun-drenched south-facing slope overlooking the confluence of Valtournenche and the central Aosta Valley. The route follows country paths and old mule tracks through well-tended vineyards and orchards before entering the warm, dry scrubland of downy oak and Scots pine typical of this sheltered aspect. The 623 m gain over just 3.5 km gives the ascent a consistent, sustained character. Views broaden steadily toward Châtillon, the Ussel castle and the peaks closing the Valtournenche to the north. The trail ends at Del (1251 m), a quiet mountain hamlet shaded by fresher mixed woodland. Best walked in spring, autumn or early summer.",
    description_fr: "Au départ de Gouilles (628 m), commune de Châtillon, le sentier grimpe sur le versant ensoleillé qui domine la confluence de la Valtournenche et de la vallée centrale d'Aoste. L'itinéraire emprunte des chemins de campagne et d'anciennes mulatières à travers vignes et vergers soignés, puis pénètre dans les garrigues de chênes pubescents et de pins sylvestres typiques de ce versant chaud et sec. Le dénivelé de 623 m en seulement 3,5 km confère à la montée un caractère soutenu et régulier. Le panorama s'élargit progressivement vers Châtillon, le château d'Ussel et les sommets fermant la Valtournenche au nord. On arrive à Del (1251 m), hameau tranquille aux bois plus frais.",
    description_de: "Der Weg startet in Gouilles (628 m) in der Gemeinde Châtillon und erklimmt den sonnigen Südhang, der die Mündung des Valtournenche-Tals in das zentrale Aostatal überblickt. Der Pfad führt über Feldwege und alte Saumpfade durch gepflegte Weinberge und Obstgärten, bevor er in das warme, trockene Buschland aus Flaumeichen und Waldkiefern eintaucht. Das Höhengefälle von 623 m auf nur 3,5 km verleiht dem Aufstieg einen gleichmäßig anspruchsvollen Charakter. Der Blick weitet sich schrittweise auf Châtillon, die Burg Ussel und die das Valtournenche im Norden abschließenden Gipfel. Ziel ist Del (1251 m), ein stiller Bergweiler im kühlen Mischwald.",
    updated_at: "2026-06-01"
  },
  "17-s1": {
    description_it: "Percorso impegnativo che sale dal fondovalle della Valle centrale, nei comuni di Charvensod e Jovençan, fino al pianoro di Arvueil (1707 m), guadagnando 1544 m di dislivello positivo in 7,6 km. La partenza da Lo Pian (551 m) avviene su sentiero che attraversa subito un mosaico di prati e vigneti alle porte di Aosta, risalendo poi attraverso boschi di castagno e frassino che coprono le pendici medio-basse del versante sinistro orografico della valle. Con il guadagno di quota la vegetazione cambia: i boschi di latifoglie lasciano il posto al faggio e poi al larice, aprendo squarci panoramici sull'intera conca di Aosta, sul Gran Combin e sui 4000 m del Cervino e del Monte Rosa all'orizzonte. Il dislivello sostenuto e la lunghezza del percorso richiedono buona preparazione fisica. Consigliate partenza mattutina e abbigliamento a strati. Escursione praticabile da maggio a ottobre.",
    description_en: "A demanding ascent from the valley floor of the central Aosta Valley, rising through the municipalities of Charvensod and Jovençan to the high plateau of Arvueil (1707 m). The 1544 m of total ascent over 7.6 km makes this a full-day commitment requiring solid fitness. From Lo Pian (551 m) the path crosses a mosaic of meadows and vineyards on the outskirts of Aosta, then climbs through chestnut and ash woodland on the left orographic flank of the valley. Higher up, deciduous trees give way to beech and larch, revealing sweeping views over the Aosta basin, the Gran Combin and the distant 4000 m summits of the Matterhorn and Monte Rosa. An early start and layered clothing are strongly recommended. Open from May to October.",
    description_fr: "Une montée exigeante depuis le fond de la vallée centrale d'Aoste, traversant les communes de Charvensod et Jovençan jusqu'au plateau d'Arvueil (1707 m). Le dénivelé de 1544 m sur 7,6 km en fait une randonnée de pleine journée nécessitant une bonne condition physique. Depuis Lo Pian (551 m), le sentier traverse un patchwork de prairies et vignes en périphérie d'Aoste, puis grimpe à travers châtaigneraies et frênaies sur le versant gauche de la vallée. Plus haut, les feuillus cèdent la place au hêtre puis au mélèze, dégageant de larges panoramas sur le bassin d'Aoste, le Grand Combin et les 4000 m du Cervin et du Mont Rose à l'horizon. Départ matinal et vêtements en couches fortement conseillés.",
    description_de: "Ein anspruchsvoller Aufstieg vom Talboden des zentralen Aostatals durch die Gemeinden Charvensod und Jovençan hinauf zum Hochplateau von Arvueil (1707 m). Die 1544 Höhenmeter auf 7,6 km machen dies zu einer ganztägigen Tour, die gute körperliche Verfassung voraussetzt. Von Lo Pian (551 m) quert der Weg ein Mosaik aus Wiesen und Weinbergen am Stadtrand von Aosta, bevor er durch Kastanien- und Eschenwälder am linken Hang des Tals aufsteigt. Weiter oben weichen Laubbäume der Buche und dann der Lärche, und weite Panoramen über das Aosta-Becken, den Gran Combin sowie die fernen 4000er Matterhorn und Monte Rosa tun sich auf. Früher Aufbruch und Kleidung in Schichten dringend empfohlen.",
    warnings_it: ["Dislivello elevato (1544 m) e percorso lungo: partenza mattutina e buona preparazione fisica necessarie."],
    warnings_en: ["High elevation gain (1544 m) and long route: early start and good fitness required."],
    warnings_fr: ["Dénivelé important (1544 m) et long parcours : départ matinal et bonne condition nécessaires."],
    warnings_de: ["Hoher Höhenunterschied (1544 m) und lange Strecke: früher Start und gute Kondition nötig."],
    updated_at: "2026-06-01"
  },
  "12-s26": {
    description_it: "Il sentiero prende avvio dall'abitato di Graines, a 1420 metri di quota, dominato dall'imponente castello medievale che sovrasta la valle come una sentinella di pietra. Già dai primi passi il tracciato offre scorci sul maniero, uno dei meglio conservati della Valle d'Aosta, prima di addentrarsi in un bosco misto di conifere e latifoglie. La salita, costante e mai banale, guadagna quota con regolarità attraverso radure erbose e alpeggi dove il bestiame pascola durante la stagione estiva. Man mano che si sale, la vegetazione si fa più rada e lo sguardo si allarga sulla testata della Val d'Ayas con le sue vette innevate. Si raggiunge infine il Col de Garda a 2268 metri, un pianoro aperto che regala una visuale ampia e silenziosa sul paesaggio alpino circostante. Dislivello impegnativo di 880 metri su 6,6 km, adatto a escursionisti allenati.",
    description_en: "The trail starts at Graines (1420 m), watched over by one of the finest medieval castles in the Aosta Valley. The path climbs steadily through mixed forest and open alpine pastures, offering expanding views of the Val d'Ayas peaks. After gaining 880 metres over 6.6 km, the route reaches Col de Garda at 2268 m — a broad, quiet upland terrace with sweeping mountain panoramas toward the Monte Rosa massif and, on the far side, the Valle del Lys. A demanding but rewarding itinerary for fit hikers, best from June to October.",
    description_fr: "Le sentier part de Graines (1420 m), au pied du château médiéval qui domine la vallée. La montée traverse forêts mixtes et alpages ouverts, avec des vues de plus en plus larges sur la Val d'Ayas. Après 880 m de dénivelé sur 6,6 km, on atteint le Col de Garda à 2268 m, un belvédère naturel offrant un panorama alpin remarquable vers le massif du Mont Rose. Randonnée exigeante, réservée aux marcheurs en bonne condition physique, de juin à octobre.",
    description_de: "Der Weg beginnt in Graines (1420 m), wo eine der besterhaltenen mittelalterlichen Burgen des Aostatals die Landschaft überragt. Über gemischte Wälder und alpine Weiden führt der Pfad stetig aufwärts, mit immer weiteren Blicken ins Val d'Ayas. Nach 880 Höhenmetern auf 6,6 km erreicht man den Col de Garda auf 2268 m — ein offenes Hochplateau mit beeindruckendem Bergpanorama Richtung Monte-Rosa-Massiv. Anspruchsvolle Tour für gut trainierte Wanderer, von Juni bis Oktober.",
    updated_at: "2026-06-01"
  },
  "13-s25": {
    description_it: "Partendo da Orbeillaz (1119 m), piccola frazione immersa nel fondovalle della Val d'Ayas, il sentiero sale con decisione per 3 km e 493 m di dislivello fino al Col Tzecore (1612 m). Nonostante la brevità, la pendenza sostenuta rende l'itinerario impegnativo nella sua semplicità: i primi tratti si snodano tra prati e piccoli nuclei rurali, per poi addentrarsi in un bosco misto che accompagna l'escursionista fino alle soglie del valico. Il Col Tzecore, discreto e poco frequentato, regala la soddisfazione di un orizzonte allargato senza le folle dei percorsi più celebri. Ottimo allenamento per gambe e polmoni, adatto a escursionisti di esperienza intermedia. La brevità del percorso lo rende percorribile anche nelle mezze stagioni con buone condizioni meteo.",
    description_en: "From Orbeillaz (1119 m) in Val d'Ayas, this short but steep route covers 3 km with 493 m of ascent to Col Tzecore (1612 m). The trail moves quickly from valley-floor meadows and rural hamlets into mixed woodland before reaching the quiet col. Despite its modest length, the sustained gradient makes it a genuine workout. The pass itself is unhurried and off the beaten track, offering rewarding views without the crowds. Suitable for hikers with some experience; accessible in good conditions from late spring to autumn.",
    description_fr: "Depuis Orbeillaz (1119 m), ce court itinéraire de 3 km grimpe de 493 m jusqu'au Col Tzecore (1612 m) en Val d'Ayas. Le sentier quitte rapidement les prairies de fond de vallée pour traverser une forêt mixte avant d'atteindre le col. Malgré sa brièveté, la pente soutenue en fait un exercice physique sérieux. Le Col Tzecore, peu fréquenté, offre une belle ouverture sur le paysage environnant dans un cadre tranquille. Convient aux randonneurs ayant une expérience intermédiaire, praticable du printemps tardif à l'automne.",
    description_de: "Von Orbeillaz (1119 m) im Val d'Ayas führt diese kurze, aber steile Route über 3 km und 493 Höhenmeter zum Col Tzecore (1612 m). Der Pfad verlässt rasch die Talwiesen, durchquert Mischwald und erreicht den stillen Pass. Trotz der geringen Streckenlänge fordert die anhaltende Steigung Kondition. Der Col Tzecore ist wenig begangen und bietet in ruhiger Atmosphäre einen offenen Ausblick. Geeignet für erfahrene Wanderer; bei guten Bedingungen von Spätfrühling bis Herbst begehbar.",
    updated_at: "2026-06-01"
  },
  "14-s2": {
    description_it: "Il percorso ha inizio nei pressi dei Ponti Romani (764 m), zona di Challand-Saint-Victor dove antichi manufatti romani testimoniano la frequentazione millenaria di questo versante della Val d'Ayas. Il tracciato sale per 3,3 km e 600 m di dislivello fino alla località di Tron damon (1285 m), attraversando un versante fortemente termofilo, caratterizzato da vegetazione di impronta quasi mediterranea: querce, ornielli, cisti e aromatiche convivono con la roccia calcarea ben esposta al sole. La natura del terreno e l'insolazione intensa rendono questo itinerario particolarmente interessante per i naturalisti e per chi vuole scoprire una Val d'Aosta insolita, lontana dagli stereotipi alpini. Il sentiero, impegnativo per la pendenza, è percorribile anche nella tarda primavera quando le quote più alte sono ancora innevate.",
    description_en: "Beginning near the Ponti Romani (764 m) in Challand-Saint-Victor — where Roman-era bridges attest to centuries of human passage — this 3.3 km route climbs 600 m to Tron damon (1285 m) along a sun-drenched, thermophilous slope. Oak, manna ash, rock rose and aromatic herbs lend the hillside a near-Mediterranean character rare in the Alpine environment. The sustained gradient makes it a stiff climb, but the botanical interest and historical echoes reward the effort. A fine option in late spring when higher elevations are still snowbound.",
    description_fr: "Au départ des Ponti Romani (764 m), à Challand-Saint-Victor, où de vieux ouvrages romains témoignent d'une fréquentation ancienne, ce sentier de 3,3 km monte 600 m jusqu'à Tron damon (1285 m) sur un versant thermophile remarquable. Chênes, frênes à fleurs, cistes et plantes aromatiques confèrent à ce flanc un caractère quasi méditerranéen, rare dans le contexte alpin valdôtain. La pente est soutenue, mais le contexte botanique et historique en fait un itinéraire singulier. Idéal au printemps tardif lorsque les hauts alpages sont encore enneigés.",
    description_de: "Nahe den Ponti Romani (764 m) in Challand-Saint-Victor, wo römerzeitliche Brücken von einer jahrtausendealten Begehung zeugen, startet diese 3,3 km lange Route mit 600 Höhenmetern bis Tron damon (1285 m). Der stark sonnenexponierte, thermophile Hang trägt eine fast mediterrane Vegetation: Eichen, Blumenesche, Zistrose und Kräuter gedeihen auf dem gut besonnten Kalkfels. Für Botanik- und Geschichtsinteressierte besonders lohnend. Schon im Spätfrühling begehbar, wenn höhere Lagen noch eingeschneit sind.",
    updated_at: "2026-06-01"
  },
  "16-s1": {
    description_it: "Chamois (1812 m) è un'unicità assoluta nel panorama italiano: il solo comune dello stivale privo di strade carrozzabili, raggiungibile esclusivamente a piedi o con la funivia da Buisson. Da questo villaggio sospeso nel tempo parte il sentiero verso il Col Pilaz (1966 m), un percorso di 3,1 km con soli 220 m di dislivello classificato come turistico. L'itinerario scorre tra pascoli aperti e radure, con una panoramica progressiva che abbraccia la Valle centrale, il gruppo del Gran Paradiso e, nelle giornate limpide, le cime del Monte Bianco. La difficoltà contenuta lo rende adatto a famiglie con bambini e a escursionisti alle prime armi. Il valico, comodo e ben segnalato, è un ottimo punto di sosta per godere del silenzio e del paesaggio senza affollamento eccessivo.",
    description_en: "Chamois (1812 m) is Italy's only car-free municipality, reachable solely on foot or by cable car from Buisson — a village genuinely apart from modern infrastructure. From here a gentle 3.1 km trail gains just 220 m to Col Pilaz (1966 m), rated T (tourist). The path traverses open pastures and clearings, gradually revealing sweeping views over the central Aosta Valley, the Gran Paradiso group and, on clear days, the Mont Blanc massif. The easy gradient makes it ideal for families with children or first-time Alpine walkers. Well-signed throughout.",
    description_fr: "Chamois (1812 m) est la seule commune italienne sans routes carrossables, accessible uniquement à pied ou par téléphérique depuis Buisson. De ce village hors du temps part un sentier de 3,1 km et seulement 220 m de dénivelé jusqu'au Col Pilaz (1966 m), classé T (touristique). Le parcours traverse pâturages et clairières en dévoilant progressivement un panorama généreux sur la vallée centrale, le massif du Grand Paradis et, par temps clair, le Mont Blanc. Sa faible difficulté le rend idéal pour les familles et les randonneurs débutants.",
    description_de: "Chamois (1812 m) ist die einzige autofreie Gemeinde Italiens — erreichbar nur zu Fuß oder per Seilbahn von Buisson. Von diesem zeitlos wirkenden Dorf führt ein 3,1 km langer Weg mit nur 220 Höhenmetern zum Col Pilaz (1966 m), eingestuft als T (touristisch). Der Pfad zieht durch offene Weiden und Lichtungen; der Blick weitet sich schrittweise über das zentrale Aostatal, die Gran-Paradiso-Gruppe und bei klarem Wetter bis zum Mont Blanc. Geringe Anforderungen machen die Route ideal für Familien und Einsteiger.",
    updated_at: "2026-06-01"
  },
  "17-s10": {
    description_it: "Il punto di partenza è il Rifugio Barbustel (2200 m), struttura ben nota agli escursionisti che frequentano i monti sopra Charvensod, alle porte di Aosta. Da qui il sentiero si sviluppa per 5,2 km con 468 m di dislivello positivo fino al Col de Mézove (2613 m), muovendosi interamente in ambiente di alta quota. Il paesaggio è quello tipico dell'orizzonte aperto alpino: praterie a nardeto, macchie di rododendro e mirtillo, rocce levigate dai ghiacciai quaternari. L'assenza di copertura arborea offre visibilità costante su Aosta, sulla Valle centrale e sulle catene montuose circostanti, dal Monte Emilius al gruppo del Gran Combin. La difficoltà escursionistica richiede equipaggiamento adeguato e attenzione alle condizioni meteorologiche, frequentemente variabili a questa quota. Percorribile da luglio a settembre.",
    description_en: "Setting out from Rifugio Barbustel (2200 m) above Charvensod near Aosta, this 5.2 km trail climbs 468 m to Col de Mézove (2613 m). The entire route unfolds above the treeline in a high-alpine landscape of nardus grassland, rhododendron and bilberry heath, and glacier-polished bedrock. Unobstructed views extend over Aosta, the central valley and the surrounding ridgelines from Monte Emilius to the Gran Combin group. Graded E, the route calls for proper mountain gear and awareness of rapidly changing weather at altitude. Season: July to September.",
    description_fr: "Au départ du Refuge Barbustel (2200 m), au-dessus de Charvensod près d'Aoste, ce sentier de 5,2 km s'élève de 468 m jusqu'au Col de Mézove (2613 m). L'itinéraire se déroule entièrement en haute montagne, dans un paysage de pelouses à nard, landes à rhododendrons et myrtilles, et roches polies par les anciens glaciers. La vue, dégagée en permanence, embrasse Aoste, la vallée centrale et les crêtes environnantes du Monte Emilius au Grand Combin. Coté E, il exige un équipement adapté. Praticable de juillet à septembre.",
    description_de: "Vom Rifugio Barbustel (2200 m) oberhalb von Charvensod nahe Aosta führt dieser 5,2 km lange Weg mit 468 Höhenmetern zum Col de Mézove (2613 m). Die gesamte Route verläuft oberhalb der Waldgrenze in einer offenen Hochgebirgslandschaft aus Borstgrasmatten, Almrausch- und Heidelbeerheide sowie glazial geschliffenem Fels. Der ständig freie Blick erfasst Aosta, das zentrale Aostatal und die umliegenden Gipfel von Monte Emilius bis Gran Combin. Einstufung E; angemessene Ausrüstung und Wetterbewusstsein sind erforderlich. Begehbar von Juli bis September.",
    updated_at: "2026-06-01"
  },
  "07-s5": {
    description_it: "Il Mont Zerbion è uno dei belvedere più completi dell'intera Valle d'Aosta. Il sentiero parte da Barmasc, piccola frazione a 1898 m, e risale con costanza lungo versanti aperti e pascoli d'alta quota fino alla vetta a 2722 m. Gli 810 m di dislivello si sviluppano in 3,9 km di tracciato ben segnalato, con pendenze sostenute ma mai tecniche, adatto a escursionisti allenati. La quota finale regala un panorama raro: a ovest si staglia il massiccio del Monte Bianco, a nord il Cervino e il Rosa, a sud-est la catena del Gran Paradiso con le sue nevi perenni. Il percorso attraversa ambienti di alpeggio ancora frequentati in estate, dove non è raro incontrare mandrie di bovine di razza Valdostana. L'assenza di vegetazione arborea dalla metà del tracciato in poi garantisce vedute continue e un senso di spazio tipico delle creste valdostane. Consigliata la partenza mattutina.",
    description_en: "Mont Zerbion is one of the most rewarding viewpoints in the Aosta Valley. Starting from the hamlet of Barmasc (1898 m), the trail climbs steadily across open pastures and high-altitude meadows to the summit at 2722 m. The 810 m of elevation gain over 3.9 km are demanding but never technical, making this a classic hike for fit walkers. From the top, the panorama spans 360 degrees: Mont Blanc to the west, the Matterhorn and Monte Rosa to the north, and the Gran Paradiso massif to the south-east. Summer grazing is still active along the route, and encounters with Valdostan cattle herds are common. An early start is advisable to maximise visibility and avoid afternoon thunderstorms.",
    description_fr: "Le Mont Zerbion est l'un des belvédères les plus complets de la Vallée d'Aoste. Au départ du hameau de Barmasc (1898 m), le sentier monte régulièrement à travers alpages ouverts et pelouses d'altitude jusqu'au sommet à 2722 m. Les 810 m de dénivelé sur 3,9 km sont exigeants mais jamais techniques. Du sommet, le panorama à 360° embrasse le massif du Mont-Blanc à l'ouest, le Cervin et le Mont Rose au nord, et le Grand Paradis au sud-est. Les alpages sont encore fréquentés en été par les troupeaux de vaches valdôtaines. Départ matinal conseillé pour profiter de la meilleure visibilité.",
    description_de: "Der Mont Zerbion ist einer der umfassendsten Aussichtspunkte im gesamten Aostatal. Der Weg beginnt im Weiler Barmasc (1898 m) und steigt gleichmäßig über offene Weiden und Hochgebirgswiesen bis zum Gipfel auf 2722 m. Die 810 Höhenmeter auf 3,9 km sind fordernd, aber nie technisch anspruchsvoll. Vom Gipfel bietet sich ein 360°-Panorama: Mont Blanc im Westen, Matterhorn und Monte Rosa im Norden, Gran-Paradiso-Massiv im Südosten. Im Sommer grasen auf dem Weg noch Herden der Valdostaner Rinderrasse. Früher Aufbruch empfohlen für beste Fernsicht und zur Vermeidung nachmittäglicher Gewitter.",
    updated_at: "2026-06-01"
  },
  "08-s16": {
    description_it: "Questo itinerario nella Val di Cogne collega il fondovalle di Aymavilles, a 770 m, agli ampi pascoli di Torlin a 1622 m, con un dislivello di 848 m in soli 4 km. Il tracciato segue un percorso di antica frequentazione: per secoli contadini e pastori hanno percorso questi stessi sentieri per raggiungere i maggenghi e gli alpeggi estivi. La prima parte attraversa boschi misti di castagni, querce e betulle, con tratti ombreggiati particolarmente piacevoli nelle giornate calde. Man mano che si guadagna quota, la vegetazione lascia spazio a prati aperti con vedute sempre più ampie sulla bassa Val di Cogne e sul massiccio del Gran Paradiso. Aymavilles è nota per il suo castello medievale a quattro torri, visibile dal basso durante la salita. Il sentiero, ben segnalato e mantenuto, è percorribile dalla tarda primavera all'autunno inoltrato. Adatto a escursionisti con buona preparazione fisica.",
    description_en: "This route in the Val di Cogne links the valley floor at Aymavilles (770 m) to the broad pastures of Torlin (1622 m), gaining 848 m over 4 km. The path follows an ancient track used for centuries by farmers and shepherds moving livestock to summer grazing grounds. The lower section winds through mixed woodland of chestnut, oak and birch before opening onto meadows with widening views of the lower Val di Cogne and the Gran Paradiso massif. Aymavilles is known for its four-towered medieval castle, visible from below during the ascent. The trail is well marked and can be walked from late spring through autumn.",
    description_fr: "Cet itinéraire en Val di Cogne relie le fond de vallée d'Aymavilles (770 m) aux vastes alpages de Torlin (1622 m), avec 848 m de dénivelé en 4 km. Le sentier emprunte un tracé historique utilisé depuis des siècles par les paysans et bergers pour rejoindre leurs estives. La partie basse traverse une forêt mixte de châtaigniers, chênes et bouleaux, tandis que la partie haute s'ouvre sur des prairies avec des vues dégagées sur le bas Val di Cogne et le massif du Grand Paradis. Aymavilles est connue pour son château médiéval à quatre tours, visible depuis le bas. Sentier bien balisé, praticable du printemps tardif à l'automne.",
    description_de: "Diese Route im Val di Cogne verbindet das Tal von Aymavilles (770 m) mit den weiten Weiden von Torlin (1622 m) und überwindet 848 Höhenmeter auf 4 km. Der Weg folgt einem alten Pfad, den Bauern und Hirten seit Jahrhunderten zur Erreichung der Sommerweiden nutzten. Der untere Abschnitt führt durch Mischwald aus Kastanien, Eichen und Birken, bevor er sich zu Wiesen mit weitem Blick auf das untere Val di Cogne und das Gran-Paradiso-Massiv öffnet. Aymavilles ist für sein vierturmiges mittelalterliches Schloss bekannt, das vom Weg aus sichtbar ist. Gut markierter Weg, begehbar von Spätfrühling bis Herbst.",
    updated_at: "2026-06-01"
  },
  "09-s1": {
    description_it: "Bard è il comune più basso della Valle d'Aosta, con il suo fondovalle a soli 364 m. Dominato dall'imponente Forte di Bard — fortezza napoleonica ricostruita nell'Ottocento e oggi museo di fama internazionale — il paese è punto di partenza di questo impegnativo sentiero che guadagna 1044 m in 5,2 km fino alla Tête de Cou a 1410 m. Il percorso si sviluppa nel territorio della Valle del Lys, risalendo versanti boscosi con tratti a gradiente sostenuto. La copertura forestale è fitta nella parte bassa, con faggete e castagneti che lasciano progressivamente spazio a vegetazione montana. La Tête de Cou offre vedute sull'imbocco della Valle del Lys e sulla Dora Baltea. Il forte di Bard, visibile durante la salita, ricorda la posizione strategica di questo angolo di Valle d'Aosta, già presidio romano sulla via delle Gallie. Sentiero adatto a escursionisti con buon allenamento e passo sicuro, date le pendenze costanti.",
    description_en: "Bard is the lowest municipality in the Aosta Valley, its valley floor sitting at just 364 m. Dominated by the imposing Forte di Bard — a Napoleonic fortress rebuilt in the nineteenth century and now an internationally renowned museum — the village is the starting point for this demanding trail, which gains 1044 m over 5.2 km to reach the Tête de Cou at 1410 m. The route climbs wooded slopes in the Valle del Lys area, passing through dense beech and chestnut forest in the lower section before transitioning to mountain scrub higher up. The Tête de Cou offers views over the lower Valle del Lys and the Dora Baltea. Suitable for fit hikers comfortable with sustained steep gradients.",
    description_fr: "Bard est la commune la plus basse de la Vallée d'Aoste, avec un fond de vallée à seulement 364 m. Dominée par l'imposant Fort de Bard — forteresse napoléonienne reconstruite au XIXe siècle et aujourd'hui musée de renommée internationale — le village est le point de départ de ce sentier exigeant, qui gagne 1044 m en 5,2 km jusqu'à la Tête de Cou à 1410 m. Le parcours monte à travers les versants boisés de la Valle del Lys, traversant hêtraies et châtaigneraies denses en bas avant de rejoindre une végétation montagnarde. La Tête de Cou offre des vues sur la basse Valle del Lys et la Doire Baltée. Recommandé aux randonneurs entraînés.",
    description_de: "Bard ist die tiefstgelegene Gemeinde des Aostatals, mit einem Talboden auf nur 364 m. Das vom imposanten Forte di Bard — einer napoleonischen, im 19. Jahrhundert wiederaufgebauten und heute international bekannten Museumsfestung — beherrschte Dorf ist Ausgangspunkt dieses anspruchsvollen Weges, der auf 5,2 km 1044 Höhenmeter bis zur Tête de Cou (1410 m) überwindet. Der Weg steigt durch bewaldete Hänge im Valle del Lys auf, zunächst durch dichte Buchen- und Kastanienwälder, dann durch Bergvegetation. Die Tête de Cou bietet Ausblicke auf das untere Valle del Lys und die Dora Baltea. Für fitte Wanderer mit Trittsicherheit geeignet.",
    updated_at: "2026-06-01"
  },
  "10-s24": {
    description_it: "L'alta Valpelline è una delle valli laterali più selvagge e meno frequentate della Valle d'Aosta, e questo lungo itinerario da Bionaz a Place Moulin ne percorre il cuore lungo le rive del torrente Buthier. Gli 11 km con 698 m di dislivello si sviluppano su un tracciato prevalentemente in quota, senza difficoltà tecniche, ideale per chi cerca un'escursione lunga e immersiva piuttosto che un'ascesa ripida. Bionaz (1495 m) è l'ultimo centro abitato della valle; da qui il sentiero risale il fondovalle passando per alpeggi ancora attivi, fienili in pietra e ambienti di pascolo aperti che d'estate si colorano di fioriture alpine. L'arrivo a Place Moulin (2011 m) è segnato dal grande lago artificiale omonimo, creato dallo sbarramento della Diga di Place Moulin, una delle opere idroelettriche più imponenti della regione. Il contesto paesaggistico è dominato dalle cime del massiccio del Monte Vélan. Sentiero E adatto a escursionisti con buona autonomia.",
    description_en: "The upper Valpelline is one of the wildest and least-visited lateral valleys of the Aosta Valley, and this long itinerary from Bionaz to Place Moulin runs through its heart along the banks of the Buthier torrent. The 11 km with 698 m of ascent follow a mostly mid-altitude route without technical difficulties, ideal for those seeking a long, immersive walk rather than a steep climb. Bionaz (1495 m) is the last inhabited centre of the valley; from here the path climbs through still-active summer farms, stone barns and open pastures bright with alpine flowers in summer. The destination, Place Moulin (2011 m), is marked by the large reservoir created by the Place Moulin Dam, one of the most significant hydroelectric works in the region. The landscape is framed by the peaks of the Monte Vélan massif.",
    description_fr: "La haute Valpelline est l'une des vallées latérales les plus sauvages de la Vallée d'Aoste, et cet itinéraire de Bionaz à Place Moulin en parcourt le cœur le long du torrent Buthier. Les 11 km avec 698 m de dénivelé suivent un tracé en altitude sans difficultés techniques, idéal pour une longue randonnée immersive. Bionaz (1495 m) est le dernier village habité de la vallée ; de là, le sentier remonte le fond de vallée à travers alpages encore actifs, granges en pierre et prairies fleuries en été. L'arrivée à Place Moulin (2011 m) est marquée par le grand lac artificiel créé par le barrage de Place Moulin, l'un des ouvrages hydroélectriques les plus importants de la région, encadré par les sommets du massif du Monte Vélan.",
    description_de: "Das obere Valpelline ist eines der wildesten und am wenigsten besuchten Seitentäler des Aostatals. Diese lange Route von Bionaz nach Place Moulin führt entlang des Buthier-Baches durch sein Herzstück. Die 11 km mit 698 Höhenmetern verlaufen auf einem überwiegend mittelhoch gelegenen Weg ohne technische Schwierigkeiten — ideal für eine lange, eindrucksvolle Wanderung. Bionaz (1495 m) ist das letzte bewohnte Dorf des Tals; von dort steigt der Weg durch noch aktive Sennereien, Steinhütten und sommers blühende Almwiesen. Das Ziel Place Moulin (2011 m) wird durch den großen Stausee markiert, den der gleichnamige Staudamm — eines der bedeutendsten Wasserkraftwerke der Region — aufgestaut hat. Der Hintergrund wird von den Gipfeln des Monte-Vélan-Massivs beherrscht.",
    updated_at: "2026-06-01"
  },
  "11-s8": {
    description_it: "Questo itinerario di alta montagna nella zona di Brissogne, Valle centrale, è riservato a escursionisti esperti (EE). Parte dal Bivacco Menabreaz a 2546 m e raggiunge il Col de Leppe a 3110 m, con 557 m di dislivello concentrati su soli 3,2 km: un'ascesa ripida e continua su terreno di alta quota, dove la segnaletica si fa ridotta e il percorso richiede esperienza di orientamento in ambiente alpino. Oltre i 2800 m il paesaggio si trasforma radicalmente: la vegetazione scompare lasciando posto a pietraie, nevai persistenti anche in estate e rocce compatte. Il Col de Leppe, quota 3110 m, è un valico severo con vedute ampie sul versante opposto e sulle cime circostanti della Valle centrale. Le condizioni meteorologiche a queste quote possono cambiare rapidamente: è indispensabile partire con previsioni favorevoli, equipaggiamento adeguato (piccozza e ramponi in caso di neve) e ottime capacità di lettura del terreno.",
    description_en: "This high-mountain route in the Brissogne area is graded EE (expert hikers only). Starting from the Bivacco Menabreaz at 2546 m, it climbs to the Col de Leppe at 3110 m, gaining 557 m over just 3.2 km — a steep, unrelenting ascent on high-altitude terrain where waymarking is sparse and route-finding skills are essential. Above 2800 m the landscape changes dramatically: vegetation gives way to scree, persistent snowfields and bare rock. The Col de Leppe offers wide views over the opposite slopes and surrounding peaks of the central Aosta Valley. Weather at this altitude can deteriorate rapidly. Crampons and ice axe may be required when snow is present. Strictly for experienced mountain hikers with solid alpine skills.",
    description_fr: "Cet itinéraire de haute montagne dans la zone de Brissogne est classé EE (randonneurs expérimentés). Au départ du Bivouac Menabreaz (2546 m), il monte au Col de Leppe (3110 m), gagnant 557 m en seulement 3,2 km — une montée raide et continue sur terrain de haute altitude où le balisage est rare et l'orientation exige de l'expérience. Au-dessus de 2800 m, la végétation cède la place aux pierriers, aux névés persistants et à la roche nue. Le Col de Leppe offre de larges panoramas sur les versants opposés et les sommets de la vallée centrale. Les conditions météo peuvent changer rapidement. Crampons et piolet nécessaires en présence de neige. Réservé aux randonneurs alpins confirmés.",
    description_de: "Diese Hochgebirgsroute im Gebiet von Brissogne trägt die Bewertung EE (nur für erfahrene Bergwanderer). Startpunkt ist das Bivacco Menabreaz auf 2546 m; das Ziel ist der Col de Leppe auf 3110 m, mit 557 Höhenmetern auf nur 3,2 km — ein steiler, anhaltender Aufstieg auf Hochgebirgsterrain, wo die Beschilderung spärlich ist und Orientierungserfahrung im Alpingelände unbedingt erforderlich ist. Über 2800 m weicht die Vegetation Geröll, anhaltenden Schneefeldern und blankem Fels. Der Col de Leppe bietet weite Aussichten auf die gegenüberliegenden Hänge und Gipfel des zentralen Aostatals. Das Wetter kann sich in diesen Höhen rasch ändern. Steigeisen und Eispickel bei Schnee erforderlich. Ausschließlich für erfahrene Alpinwanderer.",
    warnings_it: ["Percorso EE, interamente sopra i 2500 m. Segnaletica ridotta: necessari cartografia dettagliata e GPS.", "Nevai persistenti anche in estate; piccozza e ramponi in caso di neve."],
    warnings_en: ["EE route, entirely above 2500 m. Sparse waymarking: detailed map and GPS required.", "Persistent snowfields even in summer; crampons and ice axe if snow present."],
    warnings_fr: ["Itinéraire EE, entièrement au-dessus de 2500 m. Balisage rare : carte détaillée et GPS requis.", "Névés persistants même en été ; crampons et piolet si neige."],
    warnings_de: ["EE-Route, vollständig über 2500 m. Spärliche Markierung: detaillierte Karte und GPS nötig.", "Anhaltende Firnfelder auch im Sommer; Steigeisen und Eispickel bei Schnee."],
    updated_at: "2026-06-01"
  }
};

const sk = JSON.parse(fs.readFileSync(skPath, 'utf8'));
let changed = 0;
const merged = sk.map(t => {
  const p = patch[t.slug];
  if (!p) return t;
  const fixes = {};
  if (!t.duration_hours) fixes.duration_hours = cai(t.distance_km, t.elevation_gain_m, t.elevation_loss_m);
  if (!t.mobile_coverage) fixes.mobile_coverage = 'partial';
  if (!t.fitness_level) fixes.fitness_level = diffToFitness[t.difficulty] ?? 2;
  if (!t.name_en) fixes.name_en = t.name_it;
  if (!t.name_fr) fixes.name_fr = t.name_it;
  if (!t.name_de) fixes.name_de = t.name_it;
  changed++;
  return { ...t, ...fixes, ...p };
});
console.log('Patchati (blocco E):', changed);
fs.writeFileSync(skPath, JSON.stringify(merged, null, 2), 'utf8');
console.log('OK');
