'use strict';
// Round 2 — blocco F: BO + BM + BP (15 sentieri).
const fs = require('fs');
const path = require('path');
const skPath = path.join(__dirname, '../src/data/trails-skeleton.json');
function cai(km, gain, loss) { return Math.max(0.5, Math.round((km/4+Math.max(gain,0)/400+Math.max(loss,0)/600)*2)/2); }
const diffToFitness = { T: 1, E: 2, EE: 3, EEA: 4, A: 5 };

const patch = {
  "12-s27": {
    description_it: "Il sentiero prende avvio dall'abitato di Graines, a 1420 metri di quota, dominato dall'imponente castello medievale che sovrasta la valle come una sentinella di pietra. Già dai primi passi il tracciato offre scorci sul maniero, uno dei meglio conservati della Valle d'Aosta, prima di addentrarsi in un bosco misto di conifere e latifoglie. La salita, costante e mai banale, guadagna quota con regolarità attraverso radure erbose e alpeggi dove il bestiame pascola durante la stagione estiva. Man mano che si sale, la vegetazione si fa più rada e lo sguardo si allarga sulla testata della Val d'Ayas con le sue vette innevate. Si raggiunge infine la Cleva de Moulaz a 2235 metri, un pianoro aperto che regala una visuale ampia e silenziosa sul paesaggio alpino circostante. Dislivello impegnativo di 814 metri su 5,1 km, adatto a escursionisti allenati.",
    description_en: "The trail starts at Graines (1420 m), where a well-preserved medieval castle stands guard over the valley. The path climbs steadily through mixed forest and open alpine pastures, offering expanding views of the Val d'Ayas peaks. After gaining 814 metres over 5.1 km, the route reaches Cleva de Moulaz at 2235 m — a broad, quiet upland terrace with sweeping mountain panoramas. A demanding but rewarding itinerary for fit hikers.",
    description_fr: "Le sentier part de Graines (1420 m), au pied du château médiéval qui domine la vallée. La montée traverse forêts mixtes et alpages ouverts, avec des vues de plus en plus larges sur la Val d'Ayas. Après 814 m de dénivelé sur 5,1 km, on atteint la Cleva de Moulaz à 2235 m, un belvédère naturel offrant un panorama alpin remarquable. Randonnée exigeante, réservée aux marcheurs en bonne condition physique.",
    description_de: "Der Weg beginnt in Graines (1420 m), wo eine der besterhaltenen mittelalterlichen Burgen des Aostatals die Landschaft überragt. Über gemischte Wälder und alpine Weiden führt der Pfad stetig aufwärts, mit immer weiteren Blicken ins Val d'Ayas. Nach 814 Höhenmetern auf 5,1 km erreicht man die Cleva de Moulaz auf 2235 m — ein offenes Hochplateau mit beeindruckendem Bergpanorama. Anspruchsvolle Tour für gut trainierte Wanderer.",
    updated_at: "2026-06-01"
  },
  "13-s27": {
    description_it: "Partendo da Paysan a 1079 metri, il sentiero conduce alle Miniere di Bechaz attraverso un percorso ricco di interesse storico e naturalistico. La Val d'Ayas ha una lunga tradizione mineraria e le miniere di Bechaz ne sono una delle testimonianze più significative: gallerie, discariche e manufatti industriali abbandonati raccontano secoli di faticoso lavoro sotterraneo alla ricerca di minerali ferrosi e altri materiali. Il tracciato, di soli 3,1 km con un dislivello di 425 metri, sale con pendenza sostenuta attraverso boschi di castagni e betulle, aprendo a tratti su scorci della media valle. L'arrivo a 1505 metri permette di esplorare i resti degli impianti estrattivi, oggi inseriti in un paesaggio semi-abbandonato di grande fascino. Percorso adatto a escursionisti di media preparazione, con particolare appeal per chi ama la storia industriale alpina.",
    description_en: "From Paysan at 1079 m, this 3.1 km trail climbs 425 metres to the historic Bechaz Mines at 1505 m. The Val d'Ayas has a centuries-long mining tradition, and Bechaz preserves some of its most evocative remains: shafts, spoil heaps and ruined structures half-reclaimed by forest. A moderately demanding ascent through chestnut and birch woodland, rewarding hikers interested in alpine industrial heritage.",
    description_fr: "Depuis Paysan à 1079 m, ce sentier de 3,1 km monte de 425 m jusqu'aux Mines de Bechaz à 1505 m. La Val d'Ayas possède une longue tradition minière, et Bechaz en conserve de précieux témoignages : galeries, terrils et structures abandonnées aujourd'hui partiellement recouvertes par la forêt. Montée modérément exigeante à travers châtaigniers et bouleaux, idéale pour les amateurs de patrimoine industriel alpin.",
    description_de: "Von Paysan auf 1079 m führt dieser 3,1 km lange Weg mit 425 Höhenmetern Aufstieg zu den historischen Bergwerken von Bechaz auf 1505 m. Das Val d'Ayas blickt auf eine jahrhundertelange Bergbautradition zurück, und in Bechaz sind Stollen, Halden und verfallene Anlagen noch gut erhalten. Mäßig anspruchsvoller Aufstieg durch Kastanien- und Birkenwald — besonders reizvoll für Liebhaber alpiner Industriegeschichte.",
    updated_at: "2026-06-01"
  },
  "14-s26": {
    description_it: "Questo percorso ad anello di 3,6 km nella zona di Challand-Saint-Victor unisce due dei luoghi più suggestivi della bassa Val d'Ayas: il Lago di Villa e il Castello di Ville. Il lago, piccolo specchio d'acqua inserito in una riserva naturale, è circondato da vegetazione ripariale e ospita una fauna acquatica di notevole interesse, rendendo il percorso ricco di opportunità per l'osservazione naturalistica. Il tracciato si snoda attraverso boschi di querce e castagni tipici della fascia collinare valdostana, con passaggi panoramici sulla valle sottostante. Il castello di Ville, medievale e ben conservato, si staglia imponente sul terrazzo soprastante il lago e aggiunge un valore storico-culturale di prim'ordine all'escursione. Con soli 312 metri di dislivello distribuiti su 3,6 km, è un itinerario accessibile, adatto anche a famiglie con ragazzi.",
    description_en: "A 3.6 km loop at Challand-Saint-Victor combining two outstanding highlights: the Lago di Villa nature reserve and the medieval Castello di Ville. The trail winds through oak and chestnut woodland typical of the lower Aosta Valley hillsides, with open views across the valley. The protected lake offers excellent wildlife watching, while the castle adds strong historical interest. With only 312 m of elevation gain, this is an accessible route suitable for families.",
    description_fr: "Une boucle de 3,6 km à Challand-Saint-Victor reliant deux sites remarquables : le Lago di Villa, réserve naturelle aux eaux limpides, et le Château de Ville, forteresse médiévale bien conservée. Le sentier traverse des bois de chênes et de châtaigniers caractéristiques du piémont valdôtain, avec des vues ouvertes sur la vallée. Seulement 312 m de dénivelé — accessible aux familles et aux randonneurs de tous niveaux.",
    description_de: "Eine 3,6 km lange Rundtour bei Challand-Saint-Victor verbindet zwei Höhepunkte: das Naturschutzgebiet Lago di Villa und das mittelalterliche Castello di Ville. Der Weg führt durch Eichen- und Kastanienwälder der unteren Aostatal-Hügel mit freien Blicken ins Tal. Der geschützte See bietet reichlich Möglichkeiten zur Tierbeobachtung, das Schloss ergänzt den Ausflug mit historischem Charme. Nur 312 Höhenmeter — ideal für Familien.",
    updated_at: "2026-06-01"
  },
  "16-s2": {
    description_it: "Il sentiero parte da Chamois a 1812 metri, villaggio raggiungibile solo a piedi o in funivia, e sale fino al Col de Nannaz a 2772 metri seguendo la variante per Cleyva Bella, un itinerario che non incrocia mai una strada carrabile e regala quindi una delle esperienze più autentiche e selvagge dell'alta valle centrale. Il dislivello di 982 metri su 6,6 km richiede un buon allenamento e un equipaggiamento adeguato. Il percorso attraversa alpeggi aperti e pascoli d'alta quota, dove il silenzio è interrotto solo dal vento e dal suono delle campanelle del bestiame. La Cleyva Bella è un punto panoramico straordinario, con vedute sui ghiacciai del Monte Rosa e sulle creste che separano la Valle d'Aosta dal Piemonte. Il Col de Nannaz, meta finale, è un valico solitario che apre su scenari di alta montagna di rara grandiosità. Itinerario per escursionisti esperti.",
    description_en: "Starting from Chamois at 1812 m — a village accessible only on foot or by cable car — this 6.6 km route climbs 982 metres to the Col de Nannaz at 2772 m via the Cleyva Bella variant. The entire ascent avoids paved roads entirely, offering one of the most authentic wilderness experiences in the central Aosta Valley. High alpine pastures, sweeping views of the Monte Rosa massif and a remote, lonely pass reward experienced hikers willing to earn the altitude.",
    description_fr: "Depuis Chamois à 1812 m — village accessible uniquement à pied ou par téléphérique — ce sentier de 6,6 km monte de 982 m jusqu'au Col de Nannaz à 2772 m par la variante Cleyva Bella. Aucune route carrossable sur l'ensemble du parcours : une immersion totale dans la haute montagne valdôtaine. Alpages ouverts, vues sur le massif du Mont Rose et col solitaire récompensent les randonneurs expérimentés.",
    description_de: "Von Chamois auf 1812 m — einem Dorf, das nur zu Fuß oder per Seilbahn erreichbar ist — steigt dieser 6,6 km lange Weg über die Cleyva-Bella-Variante 982 Höhenmeter zum Col de Nannaz auf 2772 m. Der gesamte Aufstieg verläuft ohne Berührung von Fahrstraßen und bietet ein ursprüngliches Hochgebirgserlebnis. Weite Almen, Blicke auf das Monte-Rosa-Massiv und ein einsamer Pass erwarten erfahrene Bergwanderer.",
    warnings_it: ["Dislivello 982 m su terreno d'alta quota: buon allenamento ed equipaggiamento adeguato necessari.", "Chamois raggiungibile solo a piedi o in funivia: verificare gli orari per il rientro."],
    warnings_en: ["982 m of ascent on high-altitude terrain: good fitness and proper equipment required.", "Chamois reachable only on foot or by cable car: check timetables for the return."],
    warnings_fr: ["982 m de dénivelé en haute altitude : bonne condition et équipement adapté nécessaires.", "Chamois accessible uniquement à pied ou en téléphérique : vérifier les horaires du retour."],
    warnings_de: ["982 Höhenmeter im Hochgebirge: gute Kondition und geeignete Ausrüstung nötig.", "Chamois nur zu Fuß oder per Seilbahn erreichbar: Rückfahrzeiten prüfen."],
    updated_at: "2026-06-01"
  },
  "17-s102": {
    description_it: "Uno degli itinerari più lunghi e appaganti del territorio di Charvensod, questo percorso di 11,1 km con 1272 metri di dislivello positivo parte da Veulla a 1286 metri e conduce fino al Gran Lago a 2539 metri, toccando lungo il cammino il Lago Serva. Il tracciato si sviluppa su fasce di quota molto diverse: si parte da un ambiente ancora in parte boscoso e si sale progressivamente verso la fascia degli alpeggi, poi verso le zone rocciose d'alta quota dove i larici cedono il passo alle distese di rododendri e alle pietraie. Il Lago Serva è una prima tappa lacustre di grande bellezza, immersa in un anfiteatro naturale, ma è il Gran Lago la destinazione finale a colpire per le dimensioni e per il colore intenso delle acque. Il panorama dal Gran Lago abbraccia gran parte della Valle centrale e delle creste che la delimitano. Itinerario di una giornata intera, adatto a escursionisti esperti e allenati.",
    description_en: "An 11.1 km full-day route from Veulla at 1286 m to Gran Lago at 2539 m, passing the beautiful Lago Serva on the way. Starting in partially wooded terrain, the path climbs through summer pastures and rocky high-altitude zones, with larches giving way to rhododendron heath and scree. The Gran Lago rewards the 1272 m of total elevation gain with striking blue waters and a sweeping panorama over the central Aosta Valley. Suitable for experienced, fit hikers only.",
    description_fr: "Un itinéraire de journée entière de 11,1 km depuis Veulla à 1286 m jusqu'au Gran Lago à 2539 m, en passant par le Lago Serva. Le chemin traverse successivement forêts, alpages et zones rocheuses d'altitude, les mélèzes laissant place aux rhododendrons et aux éboulis. Le Gran Lago, avec ses eaux d'un bleu intense, récompense les 1272 m de dénivelé et offre un panorama exceptionnel sur la vallée centrale. Randonnée pour marcheurs expérimentés.",
    description_de: "Eine ganztägige Tour von 11,1 km von Veulla auf 1286 m zum Gran Lago auf 2539 m, mit Zwischenstopp am schönen Lago Serva. Der Weg führt durch Wald, Almen und felsige Hochlagen, wo Lärchen Rhododendronheiden und Geröllfeldern weichen. Der Gran Lago belohnt die 1272 Höhenmeter mit intensiv blauem Wasser und einem weiten Blick über das zentrale Aostatal. Nur für erfahrene und gut trainierte Bergwanderer geeignet.",
    warnings_it: ["Percorso lungo (11,1 km) con 1272 m di dislivello: giornata intera, solo per escursionisti allenati.", "Tratti rocciosi d'alta quota: attenzione al meteo e alle nevai residui a inizio stagione."],
    warnings_en: ["Long route (11.1 km) with 1272 m of ascent: full day, fit hikers only.", "Rocky high-altitude sections: mind the weather and early-season snowfields."],
    warnings_fr: ["Long parcours (11,1 km) avec 1272 m de dénivelé : journée entière, randonneurs entraînés.", "Tronçons rocheux d'altitude : attention à la météo et aux névés de début de saison."],
    warnings_de: ["Lange Strecke (11,1 km) mit 1272 Höhenmetern: ganztägig, nur für trainierte Wanderer.", "Felsige Hochlagen: Wetter und Restschnee zu Saisonbeginn beachten."],
    updated_at: "2026-06-01"
  },
  "03-s3": {
    description_it: "Un percorso breve ma significativo che collega il fondovalle della Val d'Ayas al pianoro di Arpuilles, attraversando un paesaggio di rara bellezza naturalistica e storica. Si parte da Via delle Betulle a quota 619 metri, nel territorio di Challand-Saint-Victor, immersi subito in una vegetazione rigogliosa dominata da betulle e castagni secolari. Il sentiero sale con pendenza regolare, offrendo scorci progressivi sul fondovalle e sulle prime propaggini delle Alpi Pennine. Avvicinandosi alla quota di arrivo, il bosco si apre sulla zona del Lago di Villa, inclusa in una riserva naturale che tutela un fragile ecosistema lacustre con flora e fauna acquatica di pregio. Nei pressi sorge il Castello di Villa, antica residenza della famiglia Challant, una delle casate nobiliari più influenti della storia valdostana. Il contrasto tra la quiete naturale del lago e la severità architettonica del castello è il punto di forza emotivo di questo itinerario.",
    description_en: "A short but rewarding climb through birch and chestnut woods leading to the Arpuilles plateau in the Val d'Ayas. Starting from Via delle Betulle at 619 metres, the path rises steadily through lush vegetation before opening onto the natural reserve of Lago di Villa, a protected wetland of ecological significance. Nearby stands the Castello di Villa, historic seat of the Challant family, one of the most powerful noble dynasties of the Aosta Valley throughout the Middle Ages. The combination of natural reserve and medieval heritage makes this short trail an ideal introduction to the cultural and environmental richness of the area.",
    description_fr: "Un court mais agréable itinéraire qui relie le fond de la Vallée d'Ayas au plateau d'Arpuilles, à travers des bois de bouleaux et de châtaigniers. Au départ de Via delle Betulle (619 m), le sentier monte régulièrement jusqu'à la zone du Lac de Villa, incluse dans une réserve naturelle protégée abritant une faune et une flore aquatiques remarquables. À proximité se dresse le Château de Villa, ancienne résidence de la famille Challant, l'une des dynasties nobles les plus influentes de la Vallée d'Aoste médiévale. Un itinéraire idéal pour conjuguer nature et patrimoine historique.",
    description_de: "Ein kurzer, aber lohnender Aufstieg durch Birken- und Kastanienwälder zum Plateau von Arpuilles im Val d'Ayas. Ausgangspunkt ist die Via delle Betulle auf 619 Metern; der Weg steigt gleichmäßig an und erreicht das Naturschutzgebiet des Lago di Villa, ein geschütztes Feuchtgebiet mit wertvoller Tier- und Pflanzenwelt. In der Nähe erhebt sich das Castello di Villa, einstige Residenz der Familie Challant, einer der bedeutendsten Adelsdynastien des mittelalterlichen Aostatals. Natur und Geschichte verbinden sich auf diesem kurzen Weg zu einem eindrucksvollen Erlebnis.",
    updated_at: "2026-06-01"
  },
  "05-s8": {
    description_it: "Questo sentiero rappresenta uno dei classici accessi alla Valgrisenche partendo dal fondovalle principale. Si muove da Leverogne a quota 737 metri, nel comune di Arvier, un piccolo borgo arroccato affacciato sulla Dora Baltea, e risale con costanza verso Grand Haury a 1171 metri. Il percorso attraversa la fascia boschiva che separa il piano dalla montagna, con alternanza di boschi di latifoglie nei tratti bassi e di conifere man mano che si acquista quota. La vegetazione lascia progressivamente spazio a praterie aperte con panorami via via più ampi sulla Valle Centrale e sulle creste che separano la Valgrisenche dalle valli laterali. L'itinerario è frequentato da chi vuole raggiungere la Valgrisenche senza percorrere la strada asfaltata, privilegiando il contatto diretto con il territorio. Un sentiero di raccordo fondamentale che conserva il sapore autentico dei tracciati storici di collegamento tra comunità montane.",
    description_en: "One of the traditional access routes to the Valgrisenche, this path departs from the small village of Leverogne at 737 metres in the municipality of Arvier, climbing steadily to Grand Haury at 1171 metres. The trail crosses alternating woodland zones, transitioning from deciduous forest at lower elevations to conifers higher up, before opening onto open pastures with wide views over the main valley and surrounding ridges. A valued alternative to the road for those wishing to enter the Valgrisenche on foot, this route preserves the character of historic mountain paths linking valley communities.",
    description_fr: "L'un des accès traditionnels à la Valgrisenche, ce sentier part du village de Leverogne (737 m), dans la commune d'Arvier, et monte régulièrement jusqu'à Grand Haury (1 171 m). Le parcours traverse des zones forestières variées, des feuillus en bas vers les conifères en altitude, avant de déboucher sur des alpages ouverts offrant de larges panoramas sur la vallée principale. Apprécié comme alternative pédestre à la route asphaltée, ce chemin conserve le caractère authentique des anciens tracés de liaison entre communautés de montagne.",
    description_de: "Einer der traditionellen Zugänge zur Valgrisenche: Der Weg startet im Dorf Leverogne (737 m), Gemeinde Arvier, und steigt gleichmäßig nach Grand Haury (1.171 m) an. Er durchquert wechselnde Waldgürtel — unten Laubwald, höher Nadelbäume — bevor er auf offene Weiden mit weiten Ausblicken ins Haupttal übergeht. Als fußläufige Alternative zur Asphaltstraße ist dieser Pfad bei Wanderern geschätzt, die das ursprüngliche Berggelände dem Straßenverkehr vorziehen.",
    updated_at: "2026-06-01"
  },
  "06-s26": {
    description_it: "Tra gli itinerari più impegnativi della Valdigne per puro dislivello, questo percorso di 6,9 chilometri porta da Runaz, a quota 839 metri nel comune di La Salle, fino all'alpeggio di Baulin a 1865 metri, guadagnando oltre 1130 metri di quota. Il sentiero sale con determinazione attraverso il villaggio di Milliery, un insediamento tradizionale valdostano che conserva architetture rurali di notevole interesse etnografico, con i caratteristici torchi e i fienili in pietra locale. Superato l'abitato, il percorso entra in un ambiente più selvatico, con boschi misti che cedono il passo ai pascoli d'alta quota. La progressiva conquista del dislivello regala punti panoramici sempre più estesi sul Mont Blanc e sulle cime della Valdigne. Baulin è un alpeggio ancora attivo in estate, dove è possibile incontrare il bestiame e i pastori della tradizione zootecnica valdostana. La discesa richiede attenzione per la lunghezza complessiva del tracciato.",
    description_en: "One of the most demanding trails in the Valdigne purely in terms of elevation gain, this 6.9-kilometre route climbs from Runaz at 839 metres to the high-altitude pasture of Baulin at 1865 metres, gaining over 1130 metres. The path passes through Milliery, a traditional Aosta Valley hamlet with notable rural architecture — stone barns, wine presses, and ancient storage buildings of ethnographic interest. Beyond the village, the trail enters wilder terrain, moving through mixed woodland before reaching open mountain pastures. The reward is sweeping views of Mont Blanc and the peaks of the Valdigne. Baulin remains an active summer alp where livestock and shepherds continue a centuries-old pastoral tradition.",
    description_fr: "L'un des itinéraires les plus exigeants de la Valdigne en termes de dénivelé, ce parcours de 6,9 km monte de Runaz (839 m) jusqu'à l'alpage de Baulin (1 865 m), soit plus de 1 130 mètres de dénivelé positif. Le sentier traverse le hameau de Milliery, village traditionnel valdôtain aux bâtisses rurales remarquables — greniers, pressoirs et granges en pierre locale — avant de s'enfoncer dans des bois mixtes puis de déboucher sur de grands alpages. Les panoramas sur le Mont-Blanc et les sommets de la Valdigne sont la récompense d'un effort soutenu. Baulin est un alpage encore actif en été.",
    description_de: "Einer der anspruchsvollsten Wege der Valdigne nach reinem Höhenunterschied: 6,9 Kilometer von Runaz (839 m) zum Hochalp Baulin (1.865 m) mit über 1.130 Höhenmetern. Der Pfad führt durch das Weiler Milliery, ein traditionelles Valdostaner Dorf mit eindrucksvoller Bauernarchitektur aus Stein. Jenseits der Siedlung durchquert man gemischten Wald, bevor weite Almwiesen mit Panoramablick auf den Mont Blanc und die Gipfel der Valdigne folgen. Baulin ist im Sommer noch aktiv bewirtschaftet. Der lange Abstieg verlangt gute Kondition und Trittsicherheit.",
    warnings_it: ["Dislivello oltre 1130 m: buona resistenza fisica necessaria; calcolare i tempi di rientro."],
    warnings_en: ["Over 1130 m of ascent: good stamina required; factor in return time."],
    warnings_fr: ["Plus de 1130 m de dénivelé : bonne endurance nécessaire ; prévoir le temps de retour."],
    warnings_de: ["Über 1130 Höhenmeter: gute Ausdauer nötig; Rückkehrzeit einplanen."],
    updated_at: "2026-06-01"
  },
  "07-s2": {
    description_it: "Un percorso di carattere quasi pianeggiante — con un modesto dislivello negativo di soli 137 metri — che attraversa il tessuto rurale del comune di Avise, nella Valle Centrale. Si parte da Lignod a quota 1617 metri e si scende dolcemente verso Praz Charbon a 1531 metri, collegando due nuclei abitati storici immersi in un paesaggio agrario di grande integrità. Il sentiero scorre tra prati stabili, muretti a secco, fontane e fienili che compongono il paesaggio culturale valdostano nei suoi tratti più autentici. È un itinerario adatto a tutti, privo di difficoltà tecniche, che permette di apprezzare con calma l'architettura rurale tradizionale — le case in pietra, i rascard, i mulini — e la vita agricola ancora presente in queste contrade. La breve distanza e il profilo dolce lo rendono particolarmente indicato per famiglie, anziani e chi cerca un contatto tranquillo con la montagna senza impegno fisico rilevante.",
    description_en: "A gently descending traverse connecting the rural hamlets of Lignod (1617 m) and Praz Charbon (1531 m) in the municipality of Avise, in the Valle Centrale. With a modest negative elevation of just 137 metres over 3.3 kilometres, this path requires no technical ability and suits walkers of all ages. The route winds between stable meadows, dry-stone walls, fountains, and traditional stone buildings — rascard, barns, and small mills — offering an authentic glimpse into the agricultural heritage of the Aosta Valley. A quiet, reflective walk through centuries of mountain rural culture.",
    description_fr: "Une douce traversée descendante reliant les hameaux ruraux de Lignod (1 617 m) et Praz Charbon (1 531 m), dans la commune d'Avise, en Vallée Centrale. Avec seulement 137 mètres de dénivelé négatif sur 3,3 km, cet itinéraire ne présente aucune difficulté technique et convient à tous les publics. Le sentier longe des prairies permanentes, des murets en pierre sèche, des fontaines et des bâtiments ruraux traditionnels — rascard, granges, moulins — témoignant de siècles d'occupation humaine à ces altitudes. Une promenade sereine au cœur du patrimoine agropastoral valdôtain.",
    description_de: "Ein sanft absteigender Querweg zwischen den Weilern Lignod (1.617 m) und Praz Charbon (1.531 m) in der Gemeinde Avise, im zentralen Aostatal. Mit nur 137 Höhenmetern Gefälle auf 3,3 Kilometern ist der Weg technisch anspruchslos und für alle Altersgruppen geeignet. Der Pfad führt durch Dauerwiesen, Trockenmauern, Brunnen und traditionelle Steinbauten — Rascard, Scheunen, Mühlen — und vermittelt ein authentisches Bild der jahrhundertealten Berglandwirtschaft des Aostatals. Ein ruhiger Spaziergang mit kulturhistorischem Tiefgang.",
    updated_at: "2026-06-01"
  },
  "07-s30": {
    description_it: "Uno degli itinerari più impegnativi dell'intera rete sentieristica valdostana, questo percorso di 9,4 chilometri con quasi 1869 metri di dislivello positivo conduce da Blanchard a quota 1731 metri fino al Rifugio Quintino Sella a 3593 metri, nel cuore dell'ambiente glaciale del Monte Rosa. Il tracciato, classificato EE, richiede ottima preparazione fisica, equipaggiamento alpinistico idoneo e capacità di orientamento in alta quota. Dopo una prima fase boschiva e di alpeggio, il sentiero abbandona progressivamente la vegetazione per entrare in un paesaggio di roccia, nevai residui e ghiaioni. Nelle ore tarde della stagione estiva o in caso di condizioni instabili, alcuni tratti possono presentare neve residua scivolosa o ghiaccio mattutino che richiedono l'uso di ramponcini o ramponi leggeri. Il Rifugio Quintino Sella, intitolato al fondatore del Club Alpino Italiano, è una base storica per le ascensioni al Castore e alle cime del gruppo del Monte Rosa. L'ambiente d'alta quota è grandioso ma severo.",
    description_en: "One of the most demanding trails in the entire Aosta Valley network, this 9.4-kilometre route ascends nearly 1869 metres from Blanchard (1731 m) to the Rifugio Quintino Sella at 3593 metres, in the high glacial environment of the Monte Rosa massif. Classified EE, the route demands excellent physical fitness, appropriate mountaineering equipment, and solid high-altitude navigation skills. The lower section passes through woodland and alpine pastures before the terrain becomes rocky and barren, with residual snowfields and scree. The Quintino Sella hut is a historic base for ascents of Castore and other Monte Rosa summits. Rapid weather changes at this altitude are common and must be taken seriously.",
    description_fr: "L'un des itinéraires les plus exigeants du réseau valdôtain, ce parcours de 9,4 km cumule près de 1 869 m de dénivelé positif depuis Blanchard (1 731 m) jusqu'au Rifugio Quintino Sella (3 593 m), en plein environnement glaciaire du massif du Mont Rose. Classé EE, il exige une excellente condition physique, un équipement alpinistique adapté et de solides capacités d'orientation en haute montagne. La partie supérieure est dominée par la roche, les névés résiduels et les éboulis. Le refuge Quintino Sella, du nom du fondateur du Club Alpin Italien, est une base historique pour les ascensions du Castore. Les conditions météo peuvent changer très rapidement à cette altitude.",
    description_de: "Einer der anspruchsvollsten Wege des gesamten Valdostaner Wegenetzes: 9,4 Kilometer und knapp 1.869 Höhenmeter von Blanchard (1.731 m) bis zur Rifugio Quintino Sella auf 3.593 Metern, mitten im Gletscherumfeld des Monte-Rosa-Massivs. Als EE klassifiziert, erfordert dieser Weg ausgezeichnete körperliche Kondition, geeignete Ausrüstung und sichere Orientierungsfähigkeit im Hochgebirge. Ab der Waldgrenze dominieren Fels, Altschneefelder und Geröll das Bild. Die Hütte Quintino Sella, benannt nach dem Gründer des Club Alpino Italiano, ist Ausgangspunkt für Besteigungen des Castore. Wetterwechsel sind in dieser Höhe abrupt — Vorsicht ist unbedingt geboten.",
    warnings_it: ["Itinerario EE riservato a escursionisti con solida esperienza in alta montagna.", "Equipaggiamento obbligatorio: ramponcini/ramponi, piccozza in caso di neve, abbigliamento a strati.", "Rapidi cambiamenti meteo sopra i 3000 m: non intraprendere con previsioni instabili.", "Neve residua e ghiaccio mattutino possibili anche in piena estate."],
    warnings_en: ["EE route for hikers with solid high-mountain experience only.", "Mandatory equipment: microspikes/crampons, ice axe if snow, layered clothing.", "Rapid weather changes above 3000 m: do not attempt with unstable forecasts.", "Residual snow and morning ice possible even in midsummer."],
    warnings_fr: ["Itinéraire EE réservé aux randonneurs très expérimentés en haute montagne.", "Équipement obligatoire : crampons légers/crampons, piolet si neige, vêtements en couches.", "Changements météo rapides au-dessus de 3000 m : ne pas s'engager par temps instable.", "Neige résiduelle et glace matinale possibles même en plein été."],
    warnings_de: ["EE-Route nur für Wanderer mit solider Hochgebirgserfahrung.", "Pflichtausrüstung: Grödel/Steigeisen, Eispickel bei Schnee, Schichtbekleidung.", "Rasche Wetterwechsel über 3000 m: bei instabiler Prognose nicht aufbrechen.", "Restschnee und Morgeneis auch im Hochsommer möglich."],
    updated_at: "2026-06-01"
  },
  "03-s7": {
    description_it: "Il sentiero attraversa uno dei versanti più soleggiati della Val d'Ayas, caratterizzato da un microclima termofilo che favorisce la coltivazione della vite fin dalla bassa quota. La partenza da Regione Consolata, a 675 metri, avviene in un paesaggio di vigneti terrazzati e muretti a secco, testimonianze di una viticoltura secolare che resiste ancora oggi. Salendo con pendenza regolare lungo i 3,3 chilometri del percorso, il bosco si infittisce gradualmente, offrendo ombra e frescura nelle ore più calde. Il guadagno altimetrico di 450 metri si compie senza strappi eccessivi, rendendolo adatto a escursionisti con discreta preparazione. L'arrivo a Excenex, a 1036 metri, regala una visuale aperta sulla media valle e sulle cime circostanti. Classificazione E.",
    description_en: "The trail climbs the sun-drenched, thermophilic slope of Challand-Saint-Victor, starting at 675 m in Regione Consolata among ancient terraced vineyards and dry-stone walls. The 3.3 km route gains 450 m of elevation at a steady pace, transitioning from vine-covered terraces to shaded woodland as height increases. The destination, Excenex at 1036 m, offers open views across the mid-valley. Rated E, the trail suits fit walkers with basic mountain experience.",
    description_fr: "Le sentier gravit le versant thermophile de Challand-Saint-Victor, en partant de la Région Consolata (675 m) au milieu des vignes en terrasses et des murets de pierres sèches. Sur 3,3 km et 450 m de dénivelé positif, le paysage évolue progressivement vers une forêt ombragée, avant d'atteindre Excenex (1036 m) et son panorama ouvert sur la vallée. Difficulté E, convient aux randonneurs entraînés.",
    description_de: "Der Weg führt den thermophilen Hang von Challand-Saint-Victor hinauf, beginnend in der Regione Consolata auf 675 m inmitten von Terrassenweinbergen und Trockenmauern. Auf 3,3 km und 450 Höhenmetern wechselt die Landschaft von Rebflächen zu schattigem Mischwald, bevor Excenex auf 1036 m mit weitem Blick ins Tal erreicht wird. Schwierigkeit E, geeignet für geübte Wanderer.",
    updated_at: "2026-06-01"
  },
  "06-s1": {
    description_it: "Il sentiero è un percorso in discesa che attraversa la Valdigne collegando i comuni di La Salle e La Thuile, con partenza da Vedun a 1519 metri e arrivo a Echarlod a 1013 metri. I 5,2 chilometri di cammino sviluppano un dislivello negativo di 578 metri, scendendo attraverso pascoli e boschi misti di larici e abeti che vestono il versante valdostano in tonalità diverse a seconda della stagione. Il tracciato presenta una pendenza costante ma mai eccessiva, percorribile con buona agilità nelle discese più ripide. La Valdigne, incuneata tra il massiccio del Monte Bianco e le Alpi Graie, offre lungo il percorso scorci sulle cime innevate e sui villaggi rurali aggrappati ai versanti. Classificazione E.",
    description_en: "A descending route through the Valdigne, linking La Salle and La Thuile from Vedun (1519 m) down to Echarlod (1013 m). Over 5.2 km the route loses 578 m through larch and fir forests and open pastures, with views toward the Mont Blanc massif and the surrounding peaks. The gradient is sustained but manageable, making this a pleasant descent for walkers comfortable on mountain terrain. Rated E.",
    description_fr: "Le sentier descend à travers la Valdigne en reliant La Salle et La Thuile, de Vedun (1519 m) à Echarlod (1013 m). Sur 5,2 km et 578 m de dénivelé négatif, le chemin traverse forêts de mélèzes et alpages ouverts, avec des vues sur le massif du Mont-Blanc. La pente est soutenue mais régulière, idéale pour les randonneurs à l'aise en descente. Difficulté E.",
    description_de: "Der Weg führt durch die Valdigne hinunter und verbindet La Salle mit La Thuile, von Vedun (1519 m) nach Echarlod (1013 m). Auf 5,2 km und 578 negativen Höhenmetern durchquert der Pfad Lärchen-Tannenwälder und offene Weiden, mit Blicken auf das Mont-Blanc-Massiv. Die Neigung ist gleichmäßig und gut beherrschbar. Schwierigkeit E.",
    updated_at: "2026-06-01"
  },
  "06-s29": {
    description_it: "Il sentiero porta rapidamente nel cuore dell'alta montagna valdostana, partendo da Baulin a 1771 metri e raggiungendo l'Alpe du Glacier a 2163 metri, con un guadagno altimetrico di 700 metri in soli 3,8 chilometri. La partenza avviene già in ambiente alpino, dove il bosco lascia presto spazio ai pascoli d'alta quota e alle rocce modellate dai ghiacciai. Il territorio di La Salle, nel cuore della Valdigne, offre in questo settore paesaggi di rara austerità: guglie granitiche, nevai residui, e il profilo del ghiacciaio che domina lo sfondo. Il dislivello concentrato in poca distanza rende il percorso impegnativo, adatto a escursionisti allenati. Classificazione E.",
    description_en: "The trail rises steeply from Baulin (1771 m) to the Alpe du Glacier (2163 m) in the high-alpine sector of La Salle, gaining 700 m over just 3.8 km. From the very start the landscape is already alpine: sparse vegetation gives way to high pastures and glacier-carved rock as altitude increases. The proximity of the glacier makes the upper section particularly dramatic. A strenuous but rewarding climb for experienced hikers. Rated E.",
    description_fr: "Le sentier grimpe rapidement de Baulin (1771 m) à l'Alpe du Glacier (2163 m), dénivelé de 700 m en 3,8 km dans le secteur de haute montagne de La Salle. Dès le départ, l'environnement est déjà alpin : pâturages d'altitude et roches façonnées par les glaciers se succèdent jusqu'au pied du glacier qui domine le cirque. Itinéraire exigeant, réservé aux randonneurs entraînés. Difficulté E.",
    description_de: "Der Weg steigt steil von Baulin (1771 m) zur Alpe du Glacier (2163 m) auf — 700 Höhenmeter auf nur 3,8 km im hochalpinen Bereich von La Salle. Schon am Start ist die Landschaft alpin geprägt: Hochalmen und glazial geformte Felsen führen hinauf zum Gletscherrand. Die komprimierte Steigung macht den Weg anspruchsvoll und ist erfahrenen Bergwanderern vorbehalten. Schwierigkeit E.",
    updated_at: "2026-06-01"
  },
  "07-s21": {
    description_it: "Uno dei rari itinerari quasi pianeggianti dell'alta Valle d'Aosta, classificato T (turistico), che segue il tracciato del Ru Courtaud, un antico canale d'irrigazione scavato per portare l'acqua ai villaggi del comune di Avise. Il percorso si sviluppa per 5,9 chilometri tra Barmasc (1898 m) e l'inizio pista (1893 m), con un dislivello negativo di soli 5 metri che lo rende accessibile a famiglie e a chi cerca una camminata rilassante in quota. Il ru accompagna il cammino come un filo d'acqua silenzioso, scorrendo tra prati fioriti e boschi di conifere. L'opera idraulica, risalente a secoli addietro, è essa stessa un monumento dell'ingegno rurale valdostano e merita attenzione lungo l'intero percorso.",
    description_en: "Trail following the Ru Courtaud, a historic irrigation channel cut centuries ago to bring water to the villages of Avise, at around 1900 m altitude. The 5.9 km route between Barmasc (1898 m) and the track start (1893 m) is nearly flat — just 5 m of descent — making it one of the few genuinely easy high-altitude walks in the Aosta Valley. Rated T (tourist), it is suitable for families and all fitness levels. The channel itself, threading through flower meadows and conifer forest, is a testament to traditional mountain engineering.",
    description_fr: "L'un des rares itinéraires quasi plats de la haute Vallée d'Aoste, classé T (touristique), longeant le Ru Courtaud, canal d'irrigation historique qui alimente depuis des siècles les villages d'Avise. Les 5,9 km entre Barmasc (1898 m) et le début de la piste (1893 m) sont quasi plats — seulement 5 m de dénivelé négatif. Convient aux familles et aux marcheurs de tout niveau. Le canal, qui serpente entre prairies fleuries et forêt de conifères, témoigne du génie hydraulique montagnard traditionnel.",
    description_de: "Einer der wenigen nahezu flachen Höhenwege im Aostatal, eingestuft als T (touristisch), folgt dem Ru Courtaud, einem jahrhundertealten Bewässerungskanal, der die Dörfer von Avise auf rund 1900 m Höhe mit Wasser versorgte. Die 5,9 km zwischen Barmasc (1898 m) und dem Pistenstart (1893 m) sind nahezu eben — nur 5 Höhenmeter Abstieg. Geeignet für Familien und alle Fitnessstufen. Der Kanal, der sich durch Blumenwiesen und Nadelwald zieht, ist ein Zeugnis traditioneller Bergwasserbaukunst.",
    updated_at: "2026-06-01"
  },
  "07-s36": {
    description_it: "Uno degli itinerari più impegnativi e spettacolari dell'intera Valle d'Ayas, classificato EEA (Escursionismo per Esperti con Attrezzatura), che conduce da Saint-Jacques (1719 m) fino al Rifugio Quintino Sella a 3602 metri sul ghiacciaio di Felik. Il dislivello di 1907 metri su 9,5 chilometri è già di per sé una sfida, ma è il terreno glaciale nella parte finale a rendere obbligatoria la dotazione alpinistica: piccozza, ramponi e imbragatura sono indispensabili. Il percorso attraversa dapprima i pascoli alti della testata della valle, poi sale tra morene e rocce levigate, fino ad affacciarsi sul mare di ghiaccio che circonda il rifugio. La vista dal Quintino Sella abbraccia le più alte cime del Monte Rosa. Solo per alpinisti esperti; valutare sempre le condizioni nivologiche prima della partenza.",
    description_en: "A serious mountaineering route rated EEA (expert hikers with equipment), climbing from Saint-Jacques (1719 m) to the Rifugio Quintino Sella at 3602 m on the Felik Glacier — 1907 m of gain over 9.5 km. The lower sections cross high pastures and moraines, but the final approach involves glacier travel requiring crampons, ice axe, and harness. The Quintino Sella hut commands sweeping views of the Monte Rosa massif. Assess snow and glacier conditions before departure; this route is strictly for experienced alpinists.",
    description_fr: "Un itinéraire d'alpinisme classé EEA (randonneurs experts avec équipement), reliant Saint-Jacques (1719 m) au Refuge Quintino Sella (3602 m) sur le glacier de Felik. Le dénivelé de 1907 m en 9,5 km est soutenu, mais c'est le glacier en altitude qui impose l'équipement complet : crampons, piolet et baudrier sont indispensables. Les vues sur le massif du Mont-Rose depuis le refuge sont exceptionnelles. Réservé aux alpinistes expérimentés ; vérifier les conditions nivologiques avant le départ.",
    description_de: "Eine ernste Bergsteigerroute der Kategorie EEA (erfahrene Bergwanderer mit Ausrüstung), die von Saint-Jacques (1719 m) zum Rifugio Quintino Sella auf 3602 m am Felik-Gletscher führt — 1907 Höhenmeter auf 9,5 km. Die unteren Abschnitte verlaufen über Hochweiden und Moränen, der Gletscheranstieg erfordert jedoch Steigeisen, Eispickel und Gurt. Die Aussicht vom Quintino Sella auf das Monte-Rosa-Massiv ist außergewöhnlich. Nur für erfahrene Alpinisten; Schnee- und Gletscherbedingungen vor Abfahrt prüfen.",
    warnings_it: ["Terreno glaciale nella sezione finale: piccozza, ramponi e imbragatura obbligatori.", "Valutare le condizioni nivologiche e meteorologiche prima della partenza.", "Classificazione EEA: riservato ad alpinisti con esperienza su ghiacciaio.", "Dislivello elevato (1907 m): partire nelle prime ore del mattino."],
    warnings_en: ["Glacial terrain in the final section: ice axe, crampons and harness mandatory.", "Assess snow and weather conditions before departure.", "EEA rating: for alpinists with glacier experience only.", "High elevation gain (1907 m): start in the early morning."],
    warnings_fr: ["Terrain glaciaire dans la section finale : piolet, crampons et baudrier obligatoires.", "Évaluer les conditions nivologiques et météo avant le départ.", "Classification EEA : réservé aux alpinistes expérimentés sur glacier.", "Dénivelé élevé (1907 m) : partir tôt le matin."],
    warnings_de: ["Gletschergelände im Schlussabschnitt: Eispickel, Steigeisen und Gurt obligatorisch.", "Schnee- und Wetterbedingungen vor der Abfahrt prüfen.", "EEA-Einstufung: nur für Alpinisten mit Gletschererfahrung.", "Hoher Höhenunterschied (1907 m): früh am Morgen starten."],
    updated_at: "2026-06-01"
  }
};

const sk = JSON.parse(fs.readFileSync(skPath, 'utf8'));
let changed = 0;
const merged = sk.map(t => {
  const p = patch[t.slug];
  if (!p) return t;
  const fixes = {};
  if (!t.duration_hours) fixes.duration_hours = cai(t.distance_km, t.elevation_gain_m, t.elevation_loss_m);
  if (!t.mobile_coverage) fixes.mobile_coverage = 'partial';
  if (!t.fitness_level) fixes.fitness_level = diffToFitness[t.difficulty] ?? 2;
  if (!t.name_en) fixes.name_en = t.name_it;
  if (!t.name_fr) fixes.name_fr = t.name_it;
  if (!t.name_de) fixes.name_de = t.name_it;
  changed++;
  return { ...t, ...fixes, ...p };
});
console.log('Patchati (blocco F):', changed);
fs.writeFileSync(skPath, JSON.stringify(merged, null, 2), 'utf8');
console.log('OK');
